### ISSUE TITLE
Removing the series using `removeIndex` doesn't remove the series from chart

### ISSUE THREAD

**Issue by mkdudeja** [amcharts/amcharts5#10]
Hi Team,

I had a requirement of dynamically adding and removing multiple series  and I have implemented the same. However, when I am removing the series, the series continues to remain visible on the chart.

Below is the codepen forked from the demos to replicate the behavior:
https://codepen.io/mkdudeja/pen/qBjxEXO

Try clicking on Delete Series, though series is deleted from internal data structures yet displayed on the chart. Also, legends and tooltips not updating on series delete.

Looking forward to your response on this.

Thanks,
Manish Kumar

**Comment by martynasma** [comment]
Fixed in [5.0.0-beta.18](https://github.com/amcharts/amcharts5/releases/tag/5.0.0-beta.18).

## [5.0.0-beta.18] - 2021-09-17

### Added
- `areLinked()` method added to `LinkedHierarchy`.
- `unlinkDataItems()` method added to `LinkedHierarchy`.
- Global function `am5.disposeAllRootElements()` added. Disposes all charts.
- `am5.registry.rootElements` added which holds an array with instances of all active `Root` elements.
- `seriesGraphics` property added to `PictorialStackedSeries`. It's a `Graphics` which shows `svgPath` shape under all slices. Useful when `startLocation`/`endLocation` is used to make slices not occupy whole shape area.

### Changed
- `maxPanOut` of `MapChart` is temporarily disabled until we figure out proper behavior for it.

### Fixed
- Linking nodes with `linkDataItems` of `LinkedHierarchy` was not working if called after the data was set.
- `Micro` theme was not removing padding from charts.
- Adding in `@types/geojson` as a dependency.
- Map could jump to unpredictable position after the chart's container size changed and user zoomed or panned the map.
- In some cases `Label` with `oversizedBehavior = "fit"` could be incorrectly positioned.
- Removing series and axes from a serial chart was not working properly.

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by mkdudeja** [comment]
@martynasma Thanks for the quick fixes.

However, I am not sure, if this is the right time to use amChart5 considering it has bugs in many basic scenarios and has comparatively lesser options as compared to amChart4 for XY charts.

I am considering amChart4 for our use case now.

Thanks,
Manish

**Comment by martynasma** [comment]
Fair enough. I'm pretty sure we're going to have most of the issues worked out within couple of months, tho.
