### ISSUE TITLE
In Bollinger Bands i cant see Text-box to change Deviations in settings!!!

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#1005]
i am taking about 3rd parameter (which is 2 in this case),

see below image for the text box not available to edit it.
![image](https://github.com/amcharts/amcharts5/assets/32473209/a59363f2-9100-4137-ab72-11a64dcda2f6)

see below image for the parameter
![image](https://github.com/amcharts/amcharts5/assets/32473209/733ec679-8036-4cfc-b278-d791ad53fa32)

**Comment by martynasma** [comment]
Fixed in [5.4.1](https://github.com/amcharts/amcharts5/releases/tag/5.4.1).

## [5.4.1] - 2023-07-18

### Added
- All Flow (Sankey, Chord and Arc) nodes can be toggled (on by default). [More info](https://www.amcharts.com/docs/v5/charts/flow-charts/#Node_toggling).
- New `Flow` settings added: `hiddenSize` and `minHiddenValue`. [More info](https://www.amcharts.com/docs/v5/charts/flow-charts/#Node_toggling).
- Deviation added to editable `BolingerBand` settings (`StockChart`).

### Changed
- `Chord`'s default value of `"sort"` changed from `"descending"` to `"none"`.  This change was necessary for the new feature of [toggling nodes](https://www.amcharts.com/docs/v5/charts/flow-charts/#Node_toggling).

### Fixed
- `Label` with wrapping/truncation, containing only symbols like question mark could make the whole chart break in a dead loop.
- `exclude`/`include` settings on `MapSeries` was being ignored when new data was set for the series.
- `LineSeries` was not being included in the caluclation of min/max of the vertical `ValueAxis` if it did not have any data points in current zoom scope of the horizontal `DateAxis`.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
