### ISSUE TITLE
Disable the tooltip stroke in amChart5

### ISSUE THREAD

**Issue by enjoywithouthey** [amcharts/amcharts5#1012]
How do I disable or set the tooltip stroke to transparent?  I've tried everything in the docs.

https://www.amcharts.com/docs/v5/reference/tooltip/

**Comment by xorspark** [comment]
You can modify the stroke and strokeOpacity on the tooltip's background: https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/#Outline

**Comment by enjoywithouthey** [comment]
@xorspark thank you for your response.

I'm setting a tooltip in my series and then using labelHTML to create a complex tooltip

```js
let series = chart.series.push(
am5xy.CandlestickSeries.new(root, {
...,
tooltip: am5.Tooltip.new(root, {
       labelHTML: 'myHTML'
   })
})
```

The solution you provided in the docs does remove the tooltip stroke, however it does so globally and overwirtes my custom labelHTML. No matter where I declare a global tooltip (before or after my series) it overwrites my custom tooltip.

I've tried setting `strokeOpacity: 0` in my series.tooltip object, but that doesn't seem to work.

Any other ideas?

**Comment by xorspark** [comment]
As I mentioned in my previous comment, you have to set it on the tooltip's *background*, not on the tooltip itself. It's also shown in the documentation link.

```
let tooltip = series.get('tooltip')
tooltip.get('background').set('strokeOpacity', 0)
```

**Comment by xorspark** [comment]
To add, if you're referring to the additional fill around the tooltip when using labelHTML, you'll also need to set the padding to 0 on the toolip:

```
tooltip.setAll({
      paddingTop: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      paddingRight: 0, 
})
```

`strokeOpacity` on the background will take care of the outline and arrow.

**Comment by enjoywithouthey** [comment]
These solutions do not work.  The only work around I can come up with is too "disguise" the stroke by setting it's color the same to the fill.  Not ideal but it works in my situation.

```
getStrokeFromSprite: true,
getFillFromSprite: true,
```

**Comment by xorspark** [comment]
> The solution you highlight in the documentation overwrites all of my custom HTML
> I have custom HTML for each data point using labelHTML

I'm struggling to understand what makes your setup different. The above solutions work for me using labelHTML so  I'm confused as to why it does not work for you. If you can provide a codepen of your exact implementation I can troubleshoot why it does not exactly work.

> I'm also trying to remove the pointer from the tooltip but I see no way to remove it in the reference section. Any pointers? No pun intended.

The background is a [PointedRectangle object](https://www.amcharts.com/docs/v5/reference/pointedrectangle/), so setting `pointerLength` to zero normally does the trick:

Codepen: https://codepen.io/team/amcharts/pen/KKroqer/e2613f663eaab52977d3b6bdc1455d16?editors=0010

However since my prior suggestions of modifying the background seems to break your implementation, I'm going to insist on a codepen of your setup if this one doesn't work for you either.

**Comment by enjoywithouthey** [comment]
@xorspark that codePen solves the issue. thank you so much.
