### ISSUE TITLE
External data load problem >v11

### ISSUE THREAD

**Issue by olneyMatt** [amcharts/amcharts5#104]
Hi,

There's seems to have been a problem introduced with loading external data (am5.net.load) from Version 12 onwards.

When I try to load an external JSON using the latest version of am5 on the CDN (v13?), I only get the first two data points drawn of the curve.

It can be fixed either by:

- setting the data from a copy/paste version of the JSON into the code, or

- forcing the code to use v11 from the CDN

I've attached a screenshot and a standalone demonstration of the issue with the code for the pasted JSON and the v11 commented.

Hope that helps

[dataLoadIssue.zip](https://github.com/amcharts/amcharts5/files/7624063/dataLoadIssue.zip)
![Screenshot 2021-11-30 at 08 21 31](https://user-images.githubusercontent.com/94979269/144010941-1303c422-7aed-4c6f-97fd-7c17100d3a2d.png)

.

**Comment by martynasma** [comment]
Thanks for the heads up.

The issue does not seem to be related to net.load but rather to delayed setting of scatter data.

We'll need to fix this.

Simplified demo:
https://codepen.io/team/amcharts/pen/e30e98d08002669620191469c0aead67?editors=0010

**Comment by martynasma** [comment]
Fixed in [5.0.14](https://github.com/amcharts/amcharts5/releases/tag/5.0.14).

## [5.0.14] - 2021-12-01

### Changed
- When setting `markerState` on `Annotator` it will now automatically render annotations without the need to open annotation mode.

### Fixed
- Updating data dynamically on series in all-`ValueAxis` setups.
- Rmoving axis range was not working properly.
- Closing annotation mode would not make chart regain its interactivity.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
