### ISSUE TITLE
Annotator crashing data graphs in the codepen demo

### ISSUE THREAD

**Issue by alienbuild** [amcharts/amcharts5#108]
Started to implement the annotator and noticed on the codepen when you toggle the annotator on and then off it'll prevent you from zooming and interacting with the graph. Fully aware that it's documented that toggling on will disable interaction but expect interaction to resume once it has been closed. This issue persists even after you close (X) or accept (Tick) the annotator to toggle it off. 

Ref
https://codepen.io/team/amcharts/pen/qBXOeBg

Can confirm this is also the case when implementing a custom button that uses the `annotator.toggle()` or `annotator.open()` functions

**Comment by martynasma** [comment]
Fixed in [5.0.14](https://github.com/amcharts/amcharts5/releases/tag/5.0.14).

## [5.0.14] - 2021-12-01

### Changed
- When setting `markerState` on `Annotator` it will now automatically render annotations without the need to open annotation mode.

### Fixed
- Updating data dynamically on series in all-`ValueAxis` setups.
- Rmoving axis range was not working properly.
- Closing annotation mode would not make chart regain its interactivity.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
