### ISSUE TITLE
Global pointermove event

### ISSUE THREAD

**Issue by nizhnikovskiy** [amcharts/amcharts5#11]
When you hover over any bullet through the central block, the map hover event is also triggered. The pointermove event works throughout the document, not just the map.

![image](https://user-images.githubusercontent.com/74915221/133800780-4c88c5a5-e1c7-4928-9273-3c4d1db275f6.png)

![image](https://user-images.githubusercontent.com/74915221/133792148-15366152-9ba6-456b-9cf7-e669dd2536d7.png)

Demo: https://codepen.io/nizhnikovskiy/pen/KKqQgGJ

**Comment by martynasma** [comment]
Fixed in [5.0.0-beta.20](https://github.com/amcharts/amcharts5/releases/tag/5.0.0-beta.20).

## [5.0.0-beta.20] - 2021-09-21

### Added
- `toFront()` and `toBack()` methods added to `Sprite`.
- `"above"` setting added to `AxisDataItem`. Allows putting `AxisRange` grid and fill elements above the series.
- New setting `ignoreFormatting` for `Label` added. If set to `true`, it will ignore square-bracketed style blocks and will display text as it is.

### Fixed
- Elements in chart will not generate hover events if they are obstructed by some other DOM element anymore.
- `XYSeries` with a vertical axis range was fully visible, even the part covered by an axis range.
- Axis bullets were not being hidden when axis data item was hidden.
- Labels in `BreadcrumbBar` were sometimes misaligned in Safari browser.
- Legend item of an initially-hidden series/slices/columns was being shown as enabled.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download-v5/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
