### ISSUE TITLE
lose the fill color in the legend when using stroke in the templateField

### ISSUE THREAD

**Issue by Campergue** [amcharts/amcharts5#110]
I defined my Series Fill and Stroke using a TemplateField and passed the series.dataItems to the Legend.
The fill color is only used in the legend if I do not specify a stroke value.
I would expect that I can set both via the TemplateField reference and that this also works for the Legend.

https://codepen.io/Campergue/pen/ZEXYWK
![144144134-fcd16e79-4f6f-405f-9f2f-e062559ca9f9](https://user-images.githubusercontent.com/6292190/144200891-53953e8a-f2ec-4f1d-bfaa-005386c620a0.png)

**Environment (if applicable)**
amCharts version : @amcharts/amcharts5 => 5.0.13
Browser and its version : all browers/versions
Related frameworks and their versions: Angular 12 and NativeJS

**Comment by martynasma** [comment]
Indeed, looks like something's off. `stroke` and `fill` alone produce correct result, whereas both seem to knock off the colors.

Your CodePen URL returns 404, so I made another test case:
https://codepen.io/team/amcharts/pen/167eef49f8429973bc3cc494d3179a0a?editors=0010

**Comment by Campergue** [comment]
Sorry was my mistake have not copied the url completely ;-( 
https://codepen.io/Campergue/pen/ZEXYWKj

**Comment by martynasma** [comment]
Fixed in [5.0.16](https://github.com/amcharts/amcharts5/releases/tag/5.0.16).

## [5.0.16] - 2021-12-10

### Added
- `tooltipPositionX` and `tooltipPositionY` added to `XYSeries` (possible values: `"value"`, `"open"`, `"low"`, and `"high"`). Indicates which data item value tooltip should be anchored to.
- New settings added to `Exporting` for formatting durations: `durationFields`, `durationFormat`, and `durationUnit`.
- `showTooltipOn` (default: `"hover"`) added to `Sprite`. Another option is `"always"` which will show tooltip without any interaction with the element. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/#Sticky_tooltips).

### Changed
- `Hierarchy` will now set bottom-level node's `cursorOverStyle: "default"` via theme, instead of hardocding it, so that it can be overridden via node templates.

### Fixed
- Stacked `XYSeries` with missing values and `valueYShow` set to `"valueYTotalPercent"` or `valueXShow` set to `"valueXTotalPercent"` were not showing columns/lines.
- Changing legend position from bottom/top to right/left was not arranging elements properly.
- If `Slice` of a `PieSeries` had a `templateField` set, legend marker was not using all the settings of that slice properly.
- Bullets were causing performance issues when data grouping was turned on.
- `Label` underline was not inheriting label's color properly.
- `Label` underline was not beign placed properly on center/right-aligned labels.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
