### ISSUE TITLE
tooltips using a custom html format

### ISSUE THREAD

**Issue by alabanu** [amcharts/amcharts5#1101]
Hello,
I am attempting to add tooltips using a custom html format, but it appears that each tooltip returns the same result.

Here is an example to reproduce the issue:
codepen: https://codepen.io/alavanu/pen/bGOojWg

In the above example the expected result should be:
132 # of cars
45 # of bicycles
etc

**Comment by xorspark** [comment]
Your code isn't checking the key associated with the series, it just stops on cars because the dataContext contains the entire object with all keys. Changing your code to look at the series' `valueYField` fixes it.

```
        for (const swithColor of enabledSensorsWithColors) {
          const sValue = swithColor.sensor;
          const keyToCheck = series.get('valueYField'); // changed
```

Your switch statement also needs to be updated to just look at the key in the dataContext as there is no `value` property:

```
                se.value = target.dataItem.dataContext[sValue.type];
```

Once you make those changes and add a sensor for motorcycles, you should be all set.
