### ISSUE TITLE
Fixed bullet position within a series

### ISSUE THREAD

**Issue by Mitwoc** [amcharts/amcharts5#1102]
Hi, I have a Gantt chart where I am trying to place a bullet for each segment of the chart. The bullet should be exactly in the middle of the segment, regardless of the current zoom. Currently, when I zoom the chart, the bullet position is adjusted according to the visible part of the segment.

No zoom applied:
![Screenshot from 2023-09-18 14-24-36](https://github.com/amcharts/amcharts5/assets/10099661/18c4e31e-f4de-48e4-8b57-b8df348314f1)

After zoom (bullets are centered according to the visible part of segments):
![Screenshot from 2023-09-18 14-24-53](https://github.com/amcharts/amcharts5/assets/10099661/c352cfd0-02b9-40de-9a13-b661db487b1f)

Is it possible to make bullets position fixed in the middle of the segments, regardless of the current zoom?

Codepen: https://codepen.io/Mitwoc/pen/KKbXGGg

**Comment by martynasma** [comment]
Well, the bullet is positioned according to the actual visible part of the bar. It's by design.

If you need a bullet to fixed at the actual middle value of the bar, you may need to create a separate series for bullet (e.g. LineSeries) and use it only for bullets, hiding actual lines.

Does that make sense?

**Comment by Mitwoc** [comment]
Sure, that makes sense. Thanks for the suggestion.
