### ISSUE TITLE
Zoom causes the XY chart to freeze

### ISSUE THREAD

**Issue by rookhive** [amcharts/amcharts5#1103]
Hello!

**Bug description**

If start zooming the XY chart (with the cursor behavior set to 'zoomX'), move the cursor far to the left out of the chart bounds, then release the mouse button, the chart goes into an infinite loop.

jsFiddle link:
https://jsfiddle.net/cu3tdeb9/ (the chart is from the demo https://www.amcharts.com/demos/data-grouping-50k-points/ without any modifications)

**Environment**
amcharts5 since `v5.3.16`
Chrome 116.0.5845.188, Mozilla 117.0, Edge 117.0.2045.31, Opera 102.0.4880.56

**Comment by martynasma** [comment]
Fixed in [5.4.8](https://github.com/amcharts/amcharts5/releases/tag/5.4.8).

## [5.4.8] - 2023-09-22

### Added
- Momentum indicator added to `StockChart`.

### Fixed
- `"z"` date formatting codes were not respecting the `Root.timezone` setting.
- If a new data was loaded and `groupData` of `DateAxis` was changed from `true` to `false`, the chart was not displaying the newly-loaded data properly.
- Accessibility: togglable elements like legend items were not being toggled by ENTER and SPACE keys with some screen reaaders (JAWS, Narrator) active.
- RST indicator of `StockChart` was always using "close" value even if a different value was selected in the settings.
- In some case chart could freeze when selecting with an `XYCursor` and releasing outside plot area.
- If a new animation of the same setting was created right after previous animation finished (on `Animation`'s `"stopped"` event) the animation would not play.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
