### ISSUE TITLE
Disable interacting with drawings on Stock Chart

### ISSUE THREAD

**Issue by Afellman** [amcharts/amcharts5#1109]
Hi,

I would like the ability to disable all user interactions with drawings, specifically on the stock chart. 

**Use Case**
User enters draw mode, draws many things, leaves draw mode (toggle drawingControl "active" setting), then we don't want the user to be able to interact with these created drawings while they are navigating the chart.
We also have a click event on our candle series and drawing anything over a candle disables the click event.

I am imagining a simple setting on the drawingControl
`drawingControl.set("userInteraction", false);`
or something equivalent.

**Comment by zeroin** [comment]
It's a reasonable request, we will add a method in next release and will let you know.

**Comment by Afellman** [comment]
@zeroin Great, thank you!

**Comment by martynasma** [comment]
Implemented in [5.4.9](https://github.com/amcharts/amcharts5/releases/tag/5.4.9).

## [5.4.9] - 2023-10-06

### Added
- `drawingsInteractive(value: bool)` method added to `StockChart`. `false` will make current annotations (drawings) to be fully static (non-editable).

### Fixed
- Zoom out button on `XYChart` was not focusable.
- Pulled out slices of a `PieSeries` could overlap with other slices if some slices were hidden.
- Pinch-zooming was not working properly in `XYChart`.
- Candlesticks on a `StockChart` were being colored based on previous period close value instead of current period open value.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
Editing is disabled, albeit hover and drag is still active. We'll fix it. Thanks for letting us know.

**Comment by martynasma** [comment]
Fixed in [5.4.11](https://github.com/amcharts/amcharts5/releases/tag/5.4.11).

## [5.4.11] - 2023-10-10

### Fixed
- `SliceGrouper` would use first color in series for a "group" slice if series was using a color set with custom list of colors.
- Fixed a problem where no series was displayed after data with all 0 values was set (since `5.4.10`).
- `forceInactive` was not working on `Container`.
- `drawingsInteractive(value: bool)` method in `StockChart` was not working properly.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
