### ISSUE TITLE
How to fix overlapped sectors in the pie chart?

### ISSUE THREAD

**Issue by dmytro-kuz** [amcharts/amcharts5#1112]
Hello. I noticed the behavior shown in the video. Is it possible to fix it somehow?
That is, the sectors that are visible, after some sectors are hidden due to the legend, are overlapped on each other, if I made one of them active. Labels are also overlapped on ticks.

https://github.com/amcharts/amcharts5/assets/92852665/5bc1a25e-a211-4b4f-a77e-e62cee378c91

**Comment by martynasma** [comment]
Fixed in [5.4.9](https://github.com/amcharts/amcharts5/releases/tag/5.4.9).

## [5.4.9] - 2023-10-06

### Added
- `drawingsInteractive(value: bool)` method added to `StockChart`. `false` will make current annotations (drawings) to be fully static (non-editable).

### Fixed
- Zoom out button on `XYChart` was not focusable.
- Pulled out slices of a `PieSeries` could overlap with other slices if some slices were hidden.
- Pinch-zooming was not working properly in `XYChart`.
- Candlesticks on a `StockChart` were being colored based on previous period close value instead of current period open value.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
