### ISSUE TITLE
Pinch zoom not working since 5.4.2

### ISSUE THREAD

**Issue by jyrimatti** [amcharts/amcharts5#1117]
**Bug description**

Pinch zooming at least on iOS Safari has not been working since 5.4.2.

5.4.1 (working): https://codepen.io/jyri-matti/pen/XWoPjop
5.4.2 (not working): https://codepen.io/jyri-matti/pen/poqOEYg

Please let me know if you have problems reproducing this and I can try to figure out why the problem is present on my phone.

Thanks!

**Comment by martynasma** [comment]
Fixed in [5.4.9](https://github.com/amcharts/amcharts5/releases/tag/5.4.9).

## [5.4.9] - 2023-10-06

### Added
- `drawingsInteractive(value: bool)` method added to `StockChart`. `false` will make current annotations (drawings) to be fully static (non-editable).

### Fixed
- Zoom out button on `XYChart` was not focusable.
- Pulled out slices of a `PieSeries` could overlap with other slices if some slices were hidden.
- Pinch-zooming was not working properly in `XYChart`.
- Candlesticks on a `StockChart` were being colored based on previous period close value instead of current period open value.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
