### ISSUE TITLE
How to set a tooltip for Pie Chart's labels

### ISSUE THREAD

**Issue by SDVII** [amcharts/amcharts5#1122]
**Question**

Is there a way to add a tooltip to a Pie Chart's label? I've tried using adapter, but it didn't work
Here is the [fiddle](https://jsfiddle.net/SDVII/z2guedL3/8/)

**Environment (if applicable)**

OS: Windows 11
Browser: Edge Version 117.0.2045.47

**Comment by xorspark** [comment]
You have to set a [background on the label in order to trigger a tooltip](https://www.amcharts.com/docs/v5/concepts/common-elements/labels/#label-templates) and also set a tooltipText on the label template itself.

```
series.labels.template.setup = function(target) {
  target.set("background", am5.Rectangle.new(root, {
    fill: am5.color(0x000000),
    fillOpacity: 0
  }))
}
series.labels.template.setAll({
  paddingTop: 1,
  paddingLeft: 1,
  paddingRight: 1,
  paddingBottom: 1,
  maxWidth: 100,
  oversizedBehavior: "truncate",
  tooltipText: "{category}",
})
```

Also note that data should be set [after your settings are applied](https://www.amcharts.com/docs/v5/concepts/data/#Setting_data), not before, or they won't carry over.

[Updated fiddle](https://jsfiddle.net/1h6kuvnq/)

**Comment by SDVII** [comment]
You are brilliant, thank you!
