### ISSUE TITLE
Disabling drawing interactions still allows some user interaction

### ISSUE THREAD

**Issue by ti-martins** [amcharts/amcharts5#1140]
**Bug description**

The `drawingsInteractive` method seems to be working for almost all of the drawing options, except for Horizontal Line, Horizontal Ray and Vertical Line, which are still interactive, even if not in draw mode.

Steps to reproduce:
 - Load amcharts stock chart and enter draw mode
 - Draw a circle or doodle, for example
 - Exit draw mode, drawing should not be interactive
 - Enter draw mode again
 - Draw Horizontal Line, Horizontal Ray or Vertical Line.
 - Exit draw mode, any of these specific drawings are still interactive

**Environment** 
 - amcharts 5.4.11
 - Google Chrome Version 116.0.5845.187 (Official Build) (arm64)
 - Typescript/React

**Comment by martynasma** [comment]
Fixed in [5.5.1](https://github.com/amcharts/amcharts5/releases/tag/5.5.1).

## [5.5.1] - 2023-10-19

### Fixed
- Not all visual settings from columns were being copied to their legend markers.
- Data items with identical timestamps in data could sometimes be ignored when plotting series.
- `drawingsInteractive(false)` was not having an effect on some drawing tools (Vertical/Horizontal/Ray Line).
- `CategoryAxis`' elements (e.g. labels and grid) were ignoring `forceHidden` setting.
- Some line elements (e.g. grid) were being drawn somewhat blurry since `5.4.9`.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
