### ISSUE TITLE
Blurry lines after v5.4.9

### ISSUE THREAD

**Issue by usamausman** [amcharts/amcharts5#1141]
**Bug description**

Hello, thanks for working on this library, it has been very useful for our charts :) We noticed a slight issue in one of the recent releases.

Some lines (grid lines, cursors, etc) with a `strokeWidth: 1` are drawn 2px wide, which makes them look slightly blurry. I'm not sure why this is affecting these lines specifically. Trying to set `crisp: false/true` or changing the `strokeWidth` on those lines doesn't seem to change how they are rendered. 

This is noticable when the device pixel ratio is 1, but I don't think it is as visible when it is >1.

v5.4.8: https://jsfiddle.net/bygLjnt6/0/
v5.4.9: https://jsfiddle.net/bygLjnt6/1/

|     | 5.4.8 | 5.4.9 |
|---|--------|--------|
| DPR = 1 | ![old](https://github.com/amcharts/amcharts5/assets/34593665/1ab06384-4c8b-453a-870f-183b58ac786e) | ![new](https://github.com/amcharts/amcharts5/assets/34593665/3aff3a69-18ab-415e-b639-ea31c967f379) |
| DPR > 1 | <img width="193" alt="5 4 8big" src="https://github.com/amcharts/amcharts5/assets/34593665/357da9b8-4613-4508-8637-cf8204291424"> | <img width="211" alt="5 4 9big" src="https://github.com/amcharts/amcharts5/assets/34593665/e6e7c3e0-059f-4305-8d86-18ad120de319"> |

I think this change was introduced in v5.4.9, possibly from this change: https://github.com/amcharts/amcharts5/compare/5.4.8...5.4.9#diff-34e1fccc0afac23ebdaff62118486fabf52d0cf4ca4a2d1e3d95bd84d788b3d3R492. I tried reverting this change locally, and it seems to fix the issue.

**Comment by martynasma** [comment]
Fixed in [5.5.1](https://github.com/amcharts/amcharts5/releases/tag/5.5.1).

## [5.5.1] - 2023-10-19

### Fixed
- Not all visual settings from columns were being copied to their legend markers.
- Data items with identical timestamps in data could sometimes be ignored when plotting series.
- `drawingsInteractive(false)` was not having an effect on some drawing tools (Vertical/Horizontal/Ray Line).
- `CategoryAxis`' elements (e.g. labels and grid) were ignoring `forceHidden` setting.
- Some line elements (e.g. grid) were being drawn somewhat blurry since `5.4.9`.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
