### ISSUE TITLE
Invisible bars when adding a series axis range after rendering

### ISSUE THREAD

**Issue by lindapaiste** [amcharts/amcharts5#1142]
**Bug description**

I am trying to change the color of some bars in a bar chart based on an axis range.  This only works if the axis range is added at the same time as the chart.  When I try to add an axis range later on it causes the bars inside of the range disappear instead of getting recolored.

For a quick reproduction, you can change the line
```
createRange(series1, 125, 275, am5.color(0xff621f));
```

```
setTimeout(() => {
  createRange(series1, 125, 275, am5.color(0xff621f));
}, 2000);
```

in the [Axis ranges with series demo](https://codepen.io/team/amcharts/pen/eYWbjPv?editors=1111) and you'll see this
![image](https://github.com/amcharts/amcharts5/assets/28965286/dbbf08a1-b94b-4abd-bd93-4c4af9c0e4a5)

It seems odd that the 2 second delay would make a difference, since this function is already called after the data is set.  But it does.

**Additional context**

What I am actually trying to do is more akin to this, where the range is added dynamically through an event.

[CodePen](https://codepen.io/linda-paiste/pen/rNPBMWB?editors=1111)

![image](https://github.com/amcharts/amcharts5/assets/28965286/4f98f297-2d66-47ca-9bfe-e4925ae0bd22)

I can see from console logging that there are 14 columns in the series `ListTemplate`, but 0 columns in the `ListTermplate` for the range.

**Environment (if applicable)**
 - amCharts version 5
 - Windows
 - Chrome
 - React is used in the app, but the bug can be reproduced in Vanilla JS

**Comment by martynasma** [comment]
Fixed in [5.5.2](https://github.com/amcharts/amcharts5/releases/tag/5.5.2).

## [5.5.2] - 2023-10-27

### Added
- `customValue` added to `ISeriesDataItem` and `customValueField` to `Series`. Allows storing additional numeric information which could be used for heat rules and other purposes.
- A middle line between oversold and overbought added to `StockChart`'s RSI indicator.
- While drawing polygon in a `StockChart`, a line is drawn from the previous point to mouse pointer.
- New setting `scrollable` (default: `false`) added to `StockChart`'s `DropdownList` and `DropdownListControl` (as well as other controls that extend those, e.g. `ComparisonControl`). If set to `true`, will autoamtically limit dropdown height to fit into chart, and will show scrollbar if the contents do not fit.
- Measure tool added to `StockChart` (as a drawing item).
- `toolSettings` setting added to `DrawingControl`. Allows passing in default settings for each drawing tool. [More info](https://www.amcharts.com/docs/v5/charts/stock/toolbar/drawing-control/#Tool_settings).

### Changed
- Printing via `ExportingMenu` print functionality using "CSS" print method will now temporarily remove all margins and padding on `body` so that images that do not fit into single page do not produce a blank page.
- `StockChart`'s Fibonacci drawing tool now draws from initial click point to the mouse pointer instead of to the right of the plot area.
- `StockChart`'s Fibonacci drawing tool's click point is now at 1 value (was at 0).
- Most of drawing tools of `StockChart` now support snapping to data items.
- Snapping to data items in `StockChart` drawing tools is now turned off by default.

### Fixed
- If an axis range was created for a `ColumnSeries` after series was inited, columns for the range were not being created.
- `GaplessDateAxis` valueToPosition method was returning wrong position if value was less than min value of the axis.
- Unserializing indicators and drawings that create separate panel in a `StockChart` would not restore drawings in indicator's panel.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
