### ISSUE TITLE
XYChart: Disabling all series from Legend results in errors when hovering chart (Consolidated Tooltip)

### ISSUE THREAD

**Issue by matteoc99** [amcharts/amcharts5#1145]
**Bug description**

if i disable all series from the legend below the chart, moving the mouse over the chart results in an endless amount of errors

see the official amChart demo on codepen: https://codepen.io/team/amcharts/pen/jOwzwXB

**Environment**

 - amCharts 5
 - Browser: tested on both Firefox 118.0.2 and Chrome  118.0.5993.88 

**Trace**

Uncaught TypeError: h is undefined
    arrangeTooltips https://cdn.amcharts.com/lib/5/xy.js:1

**Comment by martynasma** [comment]
Fixed in [5.5.2](https://github.com/amcharts/amcharts5/releases/tag/5.5.2).

## [5.5.2] - 2023-10-27

### Added
- `customValue` added to `ISeriesDataItem` and `customValueField` to `Series`. Allows storing additional numeric information which could be used for heat rules and other purposes.
- A middle line between oversold and overbought added to `StockChart`'s RSI indicator.
- While drawing polygon in a `StockChart`, a line is drawn from the previous point to mouse pointer.
- New setting `scrollable` (default: `false`) added to `StockChart`'s `DropdownList` and `DropdownListControl` (as well as other controls that extend those, e.g. `ComparisonControl`). If set to `true`, will autoamtically limit dropdown height to fit into chart, and will show scrollbar if the contents do not fit.
- Measure tool added to `StockChart` (as a drawing item).
- `toolSettings` setting added to `DrawingControl`. Allows passing in default settings for each drawing tool. [More info](https://www.amcharts.com/docs/v5/charts/stock/toolbar/drawing-control/#Tool_settings).

### Changed
- Printing via `ExportingMenu` print functionality using "CSS" print method will now temporarily remove all margins and padding on `body` so that images that do not fit into single page do not produce a blank page.
- `StockChart`'s Fibonacci drawing tool now draws from initial click point to the mouse pointer instead of to the right of the plot area.
- `StockChart`'s Fibonacci drawing tool's click point is now at 1 value (was at 0).
- Most of drawing tools of `StockChart` now support snapping to data items.
- Snapping to data items in `StockChart` drawing tools is now turned off by default.

### Fixed
- If an axis range was created for a `ColumnSeries` after series was inited, columns for the range were not being created.
- `GaplessDateAxis` valueToPosition method was returning wrong position if value was less than min value of the axis.
- Unserializing indicators and drawings that create separate panel in a `StockChart` would not restore drawings in indicator's panel.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by matteoc99** [comment]
@martynasma Really appreciate the quick response, Thanks
