### ISSUE TITLE
Scatter Chart example plot keeps re-rendering on specific viewport size

### ISSUE THREAD

**Issue by davidjb** [amcharts/amcharts5#1154]
**Bug description**

With a viewport size smaller than 1136px (e.g. under the `@media (max-width: 1136px)` media query limit), the Scatter Chart example at https://www.amcharts.com/demos/scatter-chart/ continuously re-renders the plot, seemingly flicking between two variations of renderings:

![Example flickering rendering](https://github.com/amcharts/amcharts5/assets/1002811/3793a6ec-33d9-434f-9c91-9111dc6862aa)

Here the viewport is larger than 1136px, and then the window size is reduced, triggering the issue. The problem goes away when the viewport is increased to >1136px again.

Note that the example has dropped the framerate to save space; the refresh rate is a lot faster in reality.

**Environment (if applicable)**

- amCharts version: CDN (5.5.2)
- Browser: tested in and affects Firefox 119 and Safari 17. Doesn't affect Chrome 118.

**Additional context**

This doesn't appear to happen to affect resizing the example in JSFiddle.

**Comment by martynasma** [comment]
Fixed in [5.5.3](https://github.com/amcharts/amcharts5/releases/tag/5.5.3).

## [5.5.3] - 2023-11-01

### Added
- New indicator "Stochastic Momentum Index" added.
- All `StockChart` indicators with OverBought/Oversold ranges (Commodity Channel Index, Relative Strength Index, Stochastic Momentum Index, Stochastic Oscilator and Williams R) have now middle line between oversold/overbought. Also a draggable grip added to oversold/overbought ranges which allows user to change values by dragging these grips.
- New `StockChart` toolbar control: `DropdownControl`. Can use to add any content to be displayed in a dropdown when clicked. [More info](https://www.amcharts.com/docs/v5/charts/stock/toolbar/dropdown-control/).

### Changed
- Changed defaults on a `StockPanel`: `wheelY: "zoomX"`, `panX: true`, `panY: true`. Previously, those were hardcoded in `ChartIndicator`, which prevented a possibility to change them via a theme.
- Changed defaults on an `AxisRendererY`: `pan:"zoom"`. This adds zoom possibility for all Y axes of a `StockChart` (previously indicator Y axes where not zoomable).
- `IndicatorControl` now extends `DropdownListControl` for consistency.
- `IndicatorControl` has now `scrollable: true` set by default.
- Tweaked number formats for indicator legend items.
- Default ordering of indicators in `IndicatorControl` changed.

### Fixed
- Returning empty string from `labelHTML` adapter on a `Tooltip` in some cases could result to an error.
- Timezone formatting with "z" codes in `DateFormatter` was not always correct.
- `XYChart` could flicker on Safari browser in some rare responsive CSS setups.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
