### ISSUE TITLE
Scrollbar without Animated theme is bugged after a while

### ISSUE THREAD

**Issue by mlomb** [amcharts/amcharts5#116]
It seems that after a while the "selected" area of the scrollbar is not updated correctly. Thumbs and scroll works as expected tough, but when dragging the whole scrollbar it resets to the previous location. (Video will be more clear)
I  was able to replicate this without the Animated theme, maybe it happens with it too, I don't know.

Demo: [https://jsfiddle.net/mlomb/qtup6a9w/8](https://jsfiddle.net/mlomb/qtup6a9w/8)
The demo is the [Line Chart with Scroll and Zoom demo](https://www.amcharts.com/demos/line-chart-with-scroll-and-zoom/) but without the Animated theme and Dark mode enabled.

Video where I do random stuff until it breaks:

https://user-images.githubusercontent.com/5845105/144528899-3a06475f-7c35-498c-84ec-33d8dcc9c330.mp4

In the video I notice it a bit late, but you can see the issue.

**Comment by martynasma** [comment]
Fixed in [5.0.17](https://github.com/amcharts/amcharts5/releases/tag/5.0.17).

## [5.0.17] - 2021-12-15

### Fixed
- `WordCloud` was not coloring words even if colors ColorSet was set or data with colors was used.
- `WordCloud` was not showing anything if all words had the same weight.
- Adding `type` and `main` fields to `package.json`.
- Fixed scrollbar issue with non-animated theme where clicking on a background of a scrollbar would not move to target position.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
