### ISSUE TITLE
Stock Chart Set Percent Control Setting Issue

### ISSUE THREAD

**Issue by Suleman12** [amcharts/amcharts5#1178]
I am facing this issue in Am Charts 5 that I have set my default settings of graph to show Regular like this. stockChart.setPercentScale(false); .Because I want the Graphs to be plotted on their Values and not Change Percent.Issue I face is when I apply this property it works fine when graph initially loads but when I try to Disable and then enable the graph back  the graph is not drawn on correct values. I am Attaching Screenshots for Refrence.
![Screenshot 2023-11-10 210536](https://github.com/amcharts/amcharts5/assets/24837687/f6afd2db-5a6d-4082-b838-446283a7cf5d)
![Screenshot 2023-11-10 210631](https://github.com/amcharts/amcharts5/assets/24837687/8fb92c49-4308-4f13-a275-b74752690791)
![Screenshot 2023-11-10 210704](https://github.com/amcharts/amcharts5/assets/24837687/d399719e-ec7d-43b4-bfc5-aa638c6e2ac9)
 I am also Attaching the Code pen Code https://codepen.io/Suleman12-the-vuer/pen/abXWQoJ

**Comment by martynasma** [comment]
Fixed in [5.5.7](https://github.com/amcharts/amcharts5/releases/tag/5.5.7).

## [5.5.7] - 2023-11-17

### Added
- Two new settings on a `ClusteredPointSeries`: `scatterDistance` and `scatterRadius`. Allow exploding clusters of very close points when further zoom-in is no longer possible. [More info](https://www.amcharts.com/docs/v5/charts/map-chart/clustered-point-series/#Scatter_settings).

### Fixed
- `PieSeries` was not issuing proper colors for its slices with some JSON config setups.
- In `StockChart` when percent mode was being switched off and related series toggled via legend, it would revert to percent mode.
- When updating data on a `PieSeries` its ticks could be displayed going all the way to the center briefly.
- Changing data on a main series in a `StockChart` was not updating related indicators properly.
- Legend marker for a `LineSeries` with bullets could display incorrectly if the whole chart was created before adding it to the `Root` container.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
