### ISSUE TITLE
XY chart with category axes

### ISSUE THREAD

**Issue by RavidAtiasAxonius** [amcharts/amcharts5#1190]
Hi
I'm using XYChart with CategoryAxis as yAxes.
This is the basic config:

```
  const nameAxis = chart.yAxes.push(
    CategoryAxis.new(root, {
      categoryField: "name",
      renderer: AxisRendererY.new(root, {
      }),
    })
```

I want to be able to hide some of the labels by their index, for example only odd indexes label should be shown.
How can I go over the labels and hide only some of them?

Thanks!

**Comment by xorspark** [comment]
There isn't a way to hide a label by its index. Your best bet is to disable the generated labels and create your own using axis ranges: https://www.amcharts.com/docs/v5/tutorials/using-axis-ranges-to-place-labels-at-arbitrary-values-or-dates/. While the tutorial uses value and date axes, the concept works the same in a category axis, the only difference is that you have to use `category` as the range data item value instead: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/#range-start-and-end

**Comment by RavidAtiasAxonius** [comment]
@xorspark I tried to do so, but as I understood it "cuts" from start  and from end, not from the middle.
I mean how can I use it to show only odd? or every 5 labels?

Is there a way to set another field called let's say "label" and I will set some of the items as empty string, and it will hold the displayed value in addition to categoryField?

**Comment by xorspark** [comment]
>  I understood it "cuts" from start and from end, not from the middle.

I'm sorry, I don't understand what you mean by this. You can place labels at any point by specifying the category values. In your case, since you know your category values from your data, just iterate through them by odd indicies and create the range, e.g.

```
for (let i = 1; i < data.length; i += 2) {
  // code to create range using data[i]
}
```

[Example](https://codepen.io/team/amcharts/pen/OJdvxxG/852fd2d98e2bcc2a0b6a7a991938e44a?editors=0010). Does that make sense?

> Is there a way to set another field called let's say "label" and I will set some of the items as empty string, and it will hold the displayed value in addition to categoryField?

Yes, but then you have to fiddle with [`minGridDistance`](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#grid-density) as the chart may hide those labels anyway. 

```
categoryAxis.get('renderer').labels.template.set('text', '{nameOfYourLabelField}')
```

A range is more consistent.
