### ISSUE TITLE
Indicator Control

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1202]
There are some Indicators which require volume data, but some products might not have the volume data( like the codepen link), so that case that whole website/chart gets freeze. That should not happen!

Instead of freezing, either there should be some pop-up denoting that volume data is missing or anything.

How can we handle this case?

Use indicators like Chaikin Money FLow, Chaikin  Oscillator
Link: https://codepen.io/Ansh-m-the-reactor/pen/QWYBNvZ

**Comment by martynasma** [comment]
> Instead of freezing, either there should be some pop-up denoting that volume data is missing or anything.
> How can we handle this case?

We should probably handle it in chart.

I think we should just hide indicators that rely on volume, if there is no volume series set.

**Comment by workingbuddy10** [comment]
Did the same !
@martynasma

**Comment by martynasma** [comment]
Fixed in [5.6.1](https://github.com/amcharts/amcharts5/releases/tag/5.6.1).

## [5.6.1] - 2023-11-27

### Changed
- New default rule added to `ResponsiveTheme` that will hide minor axis labels below `XXL` (1000px) breakpoint.
- `IndicatorControl` will not list Indicators that rely on volume if chart's `volumeSeries` is not set.

### Fixed
- Fixed stacking of bullets with varying `centerY`.
- `role` setting for `Root` element was being ignored.
- Setting `name` for a Series would not right away update labels of its related legend item.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
