### ISSUE TITLE
Chart flickers when using groupData: true and groupCount

### ISSUE THREAD

**Issue by lbonco** [amcharts/amcharts5#1206]
**Bug description**
Chart flickers when using groupData: true and groupCount.

Here is the link to codepen:
 
[https://codepen.io/luca-boncompagni/pen/wvNxZdG](https://codepen.io/luca-boncompagni/pen/wvNxZdG)

If I change the startDate from 2022-01-01, to  2022-01-02 stop flickering.

**Comment by martynasma** [comment]
Fixed in [5.6.2](https://github.com/amcharts/amcharts5/releases/tag/5.6.2).

## [5.6.2] - 2023-11-30

### Added
- Middle handles added to Parallel channel drawings so that the drawing could be resized vertically.

### Changed
- Clicking on a last or any other bullet when drawing a polyline on a `StockChart` will terminate current polyline. The next click will start a new polyline.
- `extraMax` and `extraMin` settings now work on `GaplessDateAxis`. This allows adding extra space in front (or back) of your data. We recommend setting `maxDeviation` to `0` if you use `extraMax`.

### Fixed
- In some rare cases (with a specific data count and `groupData` set to `true`) the chart was continously switching from monthly to weekly group interval causing the chart to flicker.
- Tick position was not always correct with `minorGridEnabled` set to `true`.
- On a `DateAxis` when `gridInterval` was set to `week`, it still showed minor grid lines even when `baseInterval` was also `week`.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
