### ISSUE TITLE
Date Range Selector Margin Being Set but Then Removed on Alternate Clicks on Direction RTL For Arabic

### ISSUE THREAD

**Issue by Suleman12** [amcharts/amcharts5#1214]
I am Facing an Issue in the Date Range Selector when It is Opened in Arabic/Direction RTL View in HTML. There is this margin-left:-.. px Property Being Applied to it on Alternate Clicks But is Removed on Alternate Clicks Also. For Example First Time I click the Date Range Selector Icon it Shows Fine and Margin left property is applied. If I close and open it Again it gets removed now the range selector moves out of the view of the page. Now I close and Open it again it works fine.
 Steps To Reproduce:
 1.Open any Working Code pen For Example https://codepen.io/team/amcharts/pen/popQjbv.
 2.Just Apply 
html{
  direction:rtl;
}  
 Property in the Css File of the Code Pen like this.
3.Now If you Open the date range selector alternatively you would notice this issue .Thanks.

**Comment by Suleman12** [comment]
I Am Attaching Loom Video For Reference so that it can Clarify the issue more.Thanks. https://www.loom.com/share/886085e0e8e74968863f17d12e6f0ea1

**Comment by workingbuddy10** [comment]
Earlier I was also facing the similar kind of issue with series switcher but later I fixed it via manipulating CSS properties.

**Comment by martynasma** [comment]
This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by martynasma** [comment]
Fixed in [5.7.0](https://github.com/amcharts/amcharts5/releases/tag/5.7.0).

## [5.7.0] - 2023-12-17

### Added
- New `Serializer` setting: `fullSettings`. Will ignore depth settings for keys listed in `fullSettings`.
- New `StockAxis` toolbar control: `DataSaveControl`. Allows to automatically or manually save all drawings and indicators to browser's local storage, as well as restore them across sessions. [More info](https://www.amcharts.com/docs/v5/charts/stock/toolbar/data-save-control/).
- Added additional item in `SettingsControl`: Auto-save drawings and indicators.
- New setting in `SettingsControl`: `autoSave`. Enables user to toggle auto-saving of indicators/drawings via Settings dropdown.
- New setting in `DropdownList` and `DropdownListControl`: `exclude`. Can be set to an array of item IDs that should not appear in the list. Can be used to disable default list items.
- New property in `StockChart`: `spriteResizer`. Holdes an instance of `SpriteResizer` which is used among drawing tools.
- `zoomable` setting added to Axis. If set to false, calling axis.zoom() won't do anything, meaning that the axis won't be zoomed with scrollbars, wheel, cursor etc.

## Changed
- `StockChart` will only sync zoom between X axes that are of the same type as the main axis.
- All drawing tools that allow selecting and resizing them (Label, Callout, Icons) will now use shared instance of `SpriteResizer`.
- `IndictorControl` is now searchable by default (`searchable: true`).

### Fixed
- `PeriodSelector`'s buttons were not being reset when chart was zoomed manually.
- Dropdowns in `StockChart`'s control were not being positioned correctly in all cases on a page with RTL direction enabled.
- Drawings loaded from serialized data were not being deleted with eraser or clear tools.
- Elinated multiple calls to preparing data of `StockChart` indicators.
- On `StockChart`, indicator's panel X-axis was out of sync with the main panel's X-axis if the latter's scale was longer to some other series on the main panel.
- Italic toggle was being ignored in `StockChart` label drawing tools.
- `GaplessDateAxis` was not always including the first date when using `axis.zoomToDates(startDate, endDate)` method.
- When swiching to percent scale `StovkChart's main panel was showing wrong Y-axis numbers until first zoom.


[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
