### ISSUE TITLE
Tooltip glitch incorrect between nodes/series

### ISSUE THREAD

**Issue by omar2205** [amcharts/amcharts5#1215]
When moving the mouse there is this white tooltip that appears until the mouse enters a correct node?

How do I remove it?

https://github.com/amcharts/amcharts5/assets/1373867/b30054d0-a0ac-4980-ace5-d9dc971c6109

Here is the Codepen where I recorded this glitch

https://codepen.io/omar2205/pen/ExrGPLm

**Comment by xorspark** [comment]
[Per the documentation](https://www.amcharts.com/docs/v5/charts/hierarchy/#Pre_selected_branch), you have to pre-select the node dataItem in order for it to respect your initial tree depths and for the chart to function properly:

```
  top_series.data.setAll([data[0]])
  top_series.set("selectedDataItem", top_series.dataItems[0]);

  mid_series.data.setAll([data[1]])
  mid_series.set("selectedDataItem", mid_series.dataItems[0]);
```

This will remove the tooltip popup that you're seeing. Note that for some reason you need to clone your series and rectangle configurations since reusing them seems to cause an issue when setting the selected dataItems:

```
  const top_series = container.children.push(
    am5hierarchy.Treemap.new(root, JSON.parse(JSON.stringify(series_opts))),
  )
  // ...
  top_series.rectangles.template.setAll(JSON.parse(JSON.stringify(series_rectangles_template_opts)))
```

Updated codepen: https://codepen.io/team/amcharts/pen/vYbvKvZ/3a432453dd1ddcda43c8a8cd914e9859?editors=0010

**Comment by omar2205** [comment]
Thanks, that fixed the issue (I used the spread operator instead of JSON-clone)
```js
am5hierarchy.Treemap.new(root, {...series_opts})
```

Quick question, is there a way to reset the colors in the heatrules? I want them (top & mid-series) to start and end with the same color.
