### ISSUE TITLE
Change tooltip text direction

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts5#122]
How change text direction ('rtl') in tooltip line series or column series?
I test direction tag in tooltipText but not work.
https://www.amcharts.com/docs/v5/reference/itextstyle/#direction_property
example: https://codepen.io/hassandl/pen/KKXdEYr

**Comment by martynasma** [comment]
Can you help us out? How would those tooltips should correctly look like?

![image](https://user-images.githubusercontent.com/1458520/144741776-ccbcdb09-bb37-439b-8dd7-e7217bf6ca30.png)

**Comment by HASSANDL** [comment]
A must after "القسم"
![image](https://user-images.githubusercontent.com/22093903/144742560-92490dfd-6598-4817-b07c-53d3ce765387.png)

**Comment by martynasma** [comment]
The following fixes the text:

```JavaScript
tooltip.label.set("direction", "rtl");
```

But it gets misplaced in comparison to tooltip itself right. We'll fix it in the next version.

Could you just confirm this looks right?

![image](https://user-images.githubusercontent.com/1458520/144753680-caad5023-a438-4478-adff-46550ba4d913.png)

**Comment by HASSANDL** [comment]
yes, it`s ok. but this version show:
![image](https://user-images.githubusercontent.com/22093903/144815083-4be5b754-0c30-4507-acdf-69e20e4cd62b.png)

**Comment by martynasma** [comment]
Yes, I know. It will be fixed in the next version. We'll let you know when it's out.

Thanks for confirming!

**Comment by martynasma** [comment]
Fixed in [5.0.15](https://github.com/amcharts/amcharts5/releases/tag/5.0.15).

## [5.0.15] - 2021-12-07

### Added
- Experimental support for underlined text added. Can be enabled via `Label` setting `fontDecoration: "underline"`, or via in-line style block (`[underline]`).
- Three new accessibility settings added: `ariaControls`, `ariaValueMin`, and `ariaValueMax`.

### Changed
- Focus elements used for accessibility are now enclosed in a container with `role="application"` which helps avoid "scan mode" in some screen readers.
- Tapping outside chart will now hide `XYCursor`.

### Fixed
- Sometimes `XYCursor` would stay on pointer moved out of chart area quickly.
- Fixed memory leak.
- Arabic text (and possibly other RTL languages) was not being displayed right on circular labels, even with `direction = "rtl"` set.
- Arabic text (`direction = "rtl"`) was being misplaced in tooltips.
- New line was resetting current in-line text style.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
`tooltip.label.set("direction", "rtl")` should function correctly now.
