### ISSUE TITLE
Arabic text in label not show correct

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts5#123]
Arabic text in label not show correct.
example: https://codepen.io/hassandl/pen/yLzYwRQ

**Comment by martynasma** [comment]
We will add some enhancements in the next version to better handle Arabic text on circular labels.

Before we do that, can you verify that this looks right?

![image](https://user-images.githubusercontent.com/1458520/144741658-43662ca5-3d98-4cde-8886-2c9321cf55e8.png)

**Comment by HASSANDL** [comment]
very good.
thanks.

**Comment by martynasma** [comment]
Thanks!

Currently `orientation: "rtl"` is not supported in circular labels, but will be from the next version. We will notify you here when the new version is out.

One thing though. Canvas text does not support putting it on a curve, so we need to simulate by drawing each single character, each ad a different angle and rotation. This does not work with Arabic text, unfortunately, so the labels will not be curved, but rather straight, as in the above image.

It's better, than completely wrong labels, though, I suppose.

**Comment by martynasma** [comment]
Fixed in [5.0.15](https://github.com/amcharts/amcharts5/releases/tag/5.0.15).

## [5.0.15] - 2021-12-07

### Added
- Experimental support for underlined text added. Can be enabled via `Label` setting `fontDecoration: "underline"`, or via in-line style block (`[underline]`).
- Three new accessibility settings added: `ariaControls`, `ariaValueMin`, and `ariaValueMax`.

### Changed
- Focus elements used for accessibility are now enclosed in a container with `role="application"` which helps avoid "scan mode" in some screen readers.
- Tapping outside chart will now hide `XYCursor`.

### Fixed
- Sometimes `XYCursor` would stay on pointer moved out of chart area quickly.
- Fixed memory leak.
- Arabic text (and possibly other RTL languages) was not being displayed right on circular labels, even with `direction = "rtl"` set.
- Arabic text (`direction = "rtl"`) was being misplaced in tooltips.
- New line was resetting current in-line text style.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
