### ISSUE TITLE
Data Save Control Issue

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1233]
I wanted to integrate the Data Save control feature in my app but there is an issue while restoring the drawings/indicators.

Though properties are getting saved in the local storage but when I re-open the app tab after closing it, I am not getting the option of restoring the drawings/indicators.

Image 1:
![image](https://github.com/amcharts/amcharts5/assets/137867461/92e50846-950a-4920-b416-bfc40ba8cc4f)

Image 2 ( rectangle series is there & saved in local storage) :
![image](https://github.com/amcharts/amcharts5/assets/137867461/089a46db-8b29-4821-af05-8d137172c76e)

Image 3 (After re-opening the app tab again, I am not getting the option) :
![image](https://github.com/amcharts/amcharts5/assets/137867461/08eec889-0431-437a-b0dd-b1a564047c6f)

And even though there are Two drawings in the local storage but when I re-stored it. It displayed only the last one.
- I made the triangle series earlier, then I close the tab and again re-open it. After that I have drawn the Fibonacci series.

![image](https://github.com/amcharts/amcharts5/assets/137867461/c0fb8876-8b77-465a-9963-56c0fe448029)

**Comment by workingbuddy10** [comment]
So the main issue is when I re-open the tab I am unable to re-store the drawings/indicators even though details/data is stored in the local storage.
![image](https://github.com/amcharts/amcharts5/assets/137867461/2312eeaa-911a-4806-bb90-7e87da0b559c)

**Comment by workingbuddy10** [comment]
Lastly you can see in the images, the pop-up of opening data save control is opening below the indicator control.
![image](https://github.com/amcharts/amcharts5/assets/137867461/de83ccba-b7b5-4889-b061-7515cbe6f1d9)

**Comment by martynasma** [comment]
Does this happen in all amCharts demos, or just locally?

I just tried the workflow you described here:
https://codepen.io/team/amcharts/pen/BaMXwQZ/f0883e6dd0d9cb1f1e56aba39443e0d7

Works fine.

Finally, which browser are you testing with?

**Comment by workingbuddy10** [comment]
I am using Chrome browser.

So the main use of storing the data of the drawing/indicators is that we can retrieve the data again after re-opening the tab or re-loading the tab.
But it is not happening.

View this video : https://www.loom.com/share/48f6d4577d5b43a2b76ab6a2cfb2d7bf?sid=558774fb-ac8b-4532-a7f5-7ba002cbd2d6

@martynasma

**Comment by martynasma** [comment]
Thanks!

This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by martynasma** [comment]
> Secondly there is should be mapping with the product name too!

There is: https://www.amcharts.com/docs/v5/charts/stock/toolbar/data-save-control/#Storage_scope

**Comment by workingbuddy10** [comment]
Nice it worked! Thank you for your assistance.

> Thanks!
> 
> This issue was fixed in dev version, and will be released soon.
> 
> We'll notify you here when that happens.

Will be waiting for this!!
@martynasma

**Comment by martynasma** [comment]
Fixed in [5.7.1](https://github.com/amcharts/amcharts5/releases/tag/5.7.1).

## [5.7.1] - 2023-12-18

### Fixed
- `DataSaveControl` was always clearing manually-saved drawings/indicators unless auto-save was enabled.
- Drawing tools eraser and clear would not always clear drawings loeaded by a `DataSaveControl`.
- `VolumeProfileIndicator` was not working if added via API.
- `VolumeProfileIndicator` was drawn detached from the Y-axis in some cases.
- Fixed `VWAP` indicator with data that contained zero-volume items.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
