### ISSUE TITLE
Volume Profile Indicator Issue

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1234]
There are Two issue in volume profile indicator: 
- The volume profile indicator axis is not fixed with the Y-axis and it shifts which isn't nice:

![image](https://github.com/amcharts/amcharts5/assets/137867461/6ce4f719-b251-4ec9-9dd9-a8ad3488ce7c)
 
- And when I choose the option of ticks per row, the app hangs and looks way too much laggy:

![image](https://github.com/amcharts/amcharts5/assets/137867461/d6e4a9c1-98de-44a0-b3ec-c8c0ebc3abae)

**Comment by martynasma** [comment]
We'll fix the first issue in the next version.

The other one is not so straightforward. If you'd like to pursue it, please post a separate issue.

**Comment by martynasma** [comment]
Fixed in [5.7.1](https://github.com/amcharts/amcharts5/releases/tag/5.7.1).

## [5.7.1] - 2023-12-18

### Fixed
- `DataSaveControl` was always clearing manually-saved drawings/indicators unless auto-save was enabled.
- Drawing tools eraser and clear would not always clear drawings loeaded by a `DataSaveControl`.
- `VolumeProfileIndicator` was not working if added via API.
- `VolumeProfileIndicator` was drawn detached from the Y-axis in some cases.
- Fixed `VWAP` indicator with data that contained zero-volume items.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
