### ISSUE TITLE
New line in text style reset font size

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts5#124]
New line in text style reset font size.
```tooltipText: '[fontSize: 40px]Line 1\nLine 2[/]'```

![image](https://user-images.githubusercontent.com/22093903/144810418-0ec3336a-b9f4-4108-986c-c0626826493c.png)

**Comment by martynasma** [comment]
Fixed in [5.0.15](https://github.com/amcharts/amcharts5/releases/tag/5.0.15).

## [5.0.15] - 2021-12-07

### Added
- Experimental support for underlined text added. Can be enabled via `Label` setting `fontDecoration: "underline"`, or via in-line style block (`[underline]`).
- Three new accessibility settings added: `ariaControls`, `ariaValueMin`, and `ariaValueMax`.

### Changed
- Focus elements used for accessibility are now enclosed in a container with `role="application"` which helps avoid "scan mode" in some screen readers.
- Tapping outside chart will now hide `XYCursor`.

### Fixed
- Sometimes `XYCursor` would stay on pointer moved out of chart area quickly.
- Fixed memory leak.
- Arabic text (and possibly other RTL languages) was not being displayed right on circular labels, even with `direction = "rtl"` set.
- Arabic text (`direction = "rtl"`) was being misplaced in tooltips.
- New line was resetting current in-line text style.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
