### ISSUE TITLE
Line is not centered on axis Y

### ISSUE THREAD

**Issue by roshaxo** [amcharts/amcharts5#1244]
Hello!
Y-axis has `strictMinMaxSelection: true` and if you leave only one line visible by clicking on the legend items, it will not be centered.
Is there any way to fix this?

![Screenshot 2023-12-20 at 19 18 12](https://github.com/amcharts/amcharts5/assets/108542985/b142df7c-587c-458a-90f7-a2173aae20e4)

Codepen:
https://codepen.io/flexinclique/pen/rNRBrza

Thanks in advance for your answer!

**Comment by martynasma** [comment]
Fixed in [5.7.2](https://github.com/amcharts/amcharts5/releases/tag/5.7.2).

## [5.7.2] - 2023-12-22

### Added
- New setting on `Label`: `maxChars`. If set to a number, will truncate text to X characters with ellipsis, obeying `breakWords` and `ellipsis` settings.
- "Bull Bear Power" indicator added to `StockChart`.
- "Acceleration Bands" indicator added to `StockChart`.
- Standalone `registerClass(name, classRef)` added to Stock Chart package (global: `am5stock.registerClass()`). Allows registering own indicator class so that it gets properly serialized and restored.

### Changed
- Improved min/max calculation of the `ValueAxis` when all the values of a series are the same.

### Fixed
- "Volume Profile" was showing up in the `IndicatorControl`'s dropdown, even if `volumeSeries` was not set on the `StockChart`.
- Left-side `ValueAxis` on a `StockChart` (`opposite: false`) it was impossible to right-align axis labels to plot area. Scrollbar's width was also not adjusted to the width of the plot area.
- Some drawing tools in `StockChart` where not working when chart was in comparison mode.
- Drawings created when `StockChart` was in comparinson mode were not carried over correctly when switching to regular value mode.
- Some drawing tools ceized working when main `StockChart` series was updated.
- Searchable dropdown controls in `StockChart` were not clearing up the list of found items when the search field was cleared.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
