### ISSUE TITLE
Drawings not working when switch to different series via Series Switcher.

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1252]
When I switch to line series or any other series via series switcher, my drawing tools stop working. Even when I come back to candlestick series again. 
Initially it works fine, without using series switcher when I am on candlestick series ( default case).

The drawings are forming just behind the series like this, I tried to draw vertical line & Fibonacci series :
![image](https://github.com/amcharts/amcharts5/assets/137867461/59f3a285-cccd-40a1-96ba-c4a88c08192f)

What are the possible corner cases I should look for, why it can happen. Though I am not able to re-produce it on a codepen.

Code for the series switcher I wrote:
```
    var seriesSwitcher = am5stock.SeriesTypeControl.new(root, {
      stockChart: stockChart,
      name: "",
      description: "Series Switcher",
    });
    seriesSwitcher.events.on("selected", function (ev) {
      seriesType(ev.item.id);
    });
    seriesSwitcher.get("items").push({
      id: "heikinashi",
      label: "Heikinashi",
      icon: am5stock.StockIcons.getIcon("Default"),
    });

    function getNewSettings(series) {
      var newSettings = [];
      am5.array.each(
        [
          "name",
          "valueYField",
          "highValueYField",
          "lowValueYField",
          "openValueYField",
          "calculateAggregates",
          "valueXField",
          "xAxis",
          "yAxis",
          "legendValueText",
          "stroke",
          "fill",
        ],
        function (setting) {
          newSettings[setting] = series.get(setting);
        }
      );
      return newSettings;
    }
    function calculateHeikinAshi(data) {
      const haData = [];
      for (let i = 0; i < data.length; i++) {
        const haClose =
          (data[i].Open + data[i].High + data[i].Low + data[i].Close) / 4;
        const haOpen =
          i === 0
            ? (data[i].Open + data[i].Close) / 2
            : (haData[i - 1].Open + haData[i - 1].Close) / 2;
        const haHigh = Math.max(data[i].High, haOpen, haClose);
        const haLow = Math.min(data[i].Low, haOpen, haClose);

        haData.push({
          Date: data[i].Date, // Preserve the date
          Open: haOpen,
          High: haHigh,
          Low: haLow,
          Close: haClose,
        });
      }
      return haData;
    }
    function seriesType(seriesType) {
      // Get current series and its settings
      var currentSeries = stockChart.get("stockSeries");
      var newSettings = getNewSettings(currentSeries);
      var data =
        seriesType === "candlestick"
          ? originalDataRef.current
          : currentSeries.data._values;
      mainPanel.series.removeValue(currentSeries);

      // Create new series
      var series;
      let heikinashiData = calculateHeikinAshi(data);
      switch (seriesType) {
        case "line":
          series = mainPanel.series.push(
            am5xy.LineSeries.new(root, newSettings)
          );
          break;
        case "candlestick":
        case "procandlestick":
          newSettings.clustered = false;
          series = mainPanel.series.push(
            am5xy.CandlestickSeries.new(root, newSettings)
          );
          if (seriesType === "procandlestick") {
            series.columns.template.get("themeTags").push("pro");
          }
          break;
        case "ohlc":
          newSettings.clustered = false;
          series = mainPanel.series.push(
            am5xy.OHLCSeries.new(root, newSettings)
          );
          break;
        case "heikinashi":
          newSettings.clustered = false;
          series = mainPanel.series.push(
            am5xy.CandlestickSeries.new(root, newSettings)
          );
          break;
        default:
          break;
      }

      // Set new series as stockSeries
      if (series) {
        valueLegend.data.removeValue(currentSeries);
        if (seriesType === "heikinashi") {
          series.data.setAll(heikinashiData);
        } else {
          series.data.setAll(originalDataRef.current);
          console.log(series.data); 
        }
        // series.data.setAll(data);
        stockChart.set("stockSeries", series);
        var cursor = mainPanel.get("cursor");
        if (cursor) {
          cursor.set("snapToSeries", [series]);
        }
        valueLegend.data.insertIndex(0, series);
      }
    }

```

**Comment by martynasma** [comment]
Fixed in [5.7.2](https://github.com/amcharts/amcharts5/releases/tag/5.7.2).

## [5.7.2] - 2023-12-22

### Added
- New setting on `Label`: `maxChars`. If set to a number, will truncate text to X characters with ellipsis, obeying `breakWords` and `ellipsis` settings.
- "Bull Bear Power" indicator added to `StockChart`.
- "Acceleration Bands" indicator added to `StockChart`.
- Standalone `registerClass(name, classRef)` added to Stock Chart package (global: `am5stock.registerClass()`). Allows registering own indicator class so that it gets properly serialized and restored.

### Changed
- Improved min/max calculation of the `ValueAxis` when all the values of a series are the same.

### Fixed
- "Volume Profile" was showing up in the `IndicatorControl`'s dropdown, even if `volumeSeries` was not set on the `StockChart`.
- Left-side `ValueAxis` on a `StockChart` (`opposite: false`) it was impossible to right-align axis labels to plot area. Scrollbar's width was also not adjusted to the width of the plot area.
- Some drawing tools in `StockChart` where not working when chart was in comparison mode.
- Drawings created when `StockChart` was in comparinson mode were not carried over correctly when switching to regular value mode.
- Some drawing tools ceized working when main `StockChart` series was updated.
- Searchable dropdown controls in `StockChart` were not clearing up the list of found items when the search field was cleared.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
