### ISSUE TITLE
Scrollbar bug in new version

### ISSUE THREAD

**Issue by canesen7** [amcharts/amcharts5#1253]
Hi. I'm using amcharts 5 in my side project. When I deploy project with 5.7.2 chart scrollbar background moved left.

![image](https://github.com/amcharts/amcharts5/assets/67913330/5d4c33ee-f9fd-49b5-9322-5066f5a47610)

In 5.3.6 version there is no problem you can see the bottom image 

![image](https://github.com/amcharts/amcharts5/assets/67913330/1b7e5439-629d-4042-a8d0-9834638c4f86)

**Comment by martynasma** [comment]
Fixed in [5.7.3](https://github.com/amcharts/amcharts5/releases/tag/5.7.3).

## [5.7.3] - 2023-12-26

### Fixed
- `Scrollbar` background was being drawn shifted since `5.7.2`.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by canesen7** [comment]
Thanks
