### ISSUE TITLE
ChartLine, line should be zero but instead it looks like a negative value

### ISSUE THREAD

**Issue by gabi04** [amcharts/amcharts5#1257]
Between may and june value is 0 but in the chart it looks like a negative value

**Example 1:**
data: [
  { date: 1672549200000, value1: 0 },
  { date: 1675227600000, value1: 0 },
  { date: 1677646800000, value1: 0 },
  { date: 1680325200000, value1: 0 },
  { date: 1682917200000, value1: 0 },
  { date: 1685595600000, value1: 0 },
  { date: 1688187600000, value1: 0 },
  { date: 1690866000000, value1: 0 },
  { date: 1693544400000, value1: 0 },
  { date: 1696136400000, value1: 0 },
  { date: 1698814800000, value1: 0 },
  { date: 1701406800000, value1: 0 },
],
chart:
![image](https://github.com/amcharts/amcharts5/assets/23067070/e8ccc59e-289b-4603-8b7f-b1511497b712)

**Example 2:**
data: [
  { date: 1672549200000, value1: 0 },
  { date: 1675227600000, value1: 0 },
  { date: 1677646800000, value1: 0 },
  { date: 1680325200000, value1: 0 },
  { date: 1682917200000, value1: 0 },
  { date: 1685595600000, value1: 0 },
  { date: 1688187600000, value1: 173038870.59 },
  { date: 1690866000000, value1: 173038870.59 },
  { date: 1693544400000, value1: 173038870.59 },
  { date: 1696136400000, value1: 173038870.59 },
  { date: 1698814800000, value1: 173038870.59 },
  { date: 1701406800000, value1: 173038870.59 },
]
chart:
![image](https://github.com/amcharts/amcharts5/assets/23067070/6ce5e58a-dfb2-4f56-a2d1-e40deaa2c80e)

**Problem:**
![image](https://github.com/amcharts/amcharts5/assets/23067070/89edbe18-9e18-48eb-93c4-dd5a07e20667)

**Comment by xorspark** [comment]
It looks like you're using a smoothed line, which typically has a small curved dip before climbing up. You can try [increasing the tension](https://www.amcharts.com/docs/v5/charts/xy-chart/series/smoothed-series/#Line_tension), use one of the [d3 smoothing algorithms](https://www.amcharts.com/docs/v5/charts/xy-chart/series/smoothed-series/#Using_D3_smoothing), set [extraMin](extraMin) to a small number to account for the dip so that it is visible or use a non-smoothed line.
