### ISSUE TITLE
Auto Retrieval in Data save control

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1270]
I want to add/enable the auto enable the auto retrieval in my app. 

Like if user have saved any drawings/indicator and re-opens the same product again then it automatically retrieve all the drawings/indicator info . Currently user have click in the drop-down option for the retrieval. 

I have given the storageId for saving the info with respect to products.

**Comment by martynasma** [comment]
You can use `SettingsControl`'s setting `autoSave` to auto-enable auto-save:

```
am5stock.SettingsControl.new(root, {
  stockChart: stockChart,
  autoSave: true
})
```

**Comment by workingbuddy10** [comment]
I tried using that but it is not working as expected.

Like the auto save is enabled and I used rectangle drawing, later I again open the chart of the same product it didn't appeared. 

Whereas when I manually save and retrieve the drawing data it comes.

```
        am5stock.DataSaveControl.new(root, {
          stockChart: stockChart,
          storageId: props.product,
          autoSave:true,
        }),
```
@martynasma

**Comment by workingbuddy10** [comment]
Can you try & test something like this in your local? Whether its working or not.
@martynasma

**Comment by martynasma** [comment]
Fixed in [5.7.6](https://github.com/amcharts/amcharts5/releases/tag/5.7.6).

## [5.7.6] - 2024-01-05

### Fixed
- One of the underlying series was not being removed when disposing MACross indicator.
- Some of the newer indicators were not being restored.
- `autoSave: true` set on `DataSaveControl` was not working.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by workingbuddy10** [comment]
And lastly I only want to Retrieve automatically, like I don't want to save automatically.

To avoid ambiguity, I only  only want to Retrieve drawings/indicators automatically but save when on the click of the user only.

Though currently to retrieve automatically we have to enable auto save, so it's kind of dependency.
@martynasma

**Comment by martynasma** [comment]
There's currently no such functionality available.
