### ISSUE TITLE
Moving Average Cross indicator issue

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1272]
Moving Average Cross indicator is not removing properly.

You can test it out on demo : https://www.amcharts.com/demos/stock-chart/

1) Added "Moving Average Cross indicator : 

![image](https://github.com/amcharts/amcharts5/assets/137867461/f86bc891-bde8-4781-8608-8ca0ff54e23d)

2) On removing it is not going properly : 

![image](https://github.com/amcharts/amcharts5/assets/137867461/433ac719-6def-46fa-93d9-a003d20e81bc)

**Comment by martynasma** [comment]
Fixed in [5.7.6](https://github.com/amcharts/amcharts5/releases/tag/5.7.6).

## [5.7.6] - 2024-01-05

### Fixed
- One of the underlying series was not being removed when disposing MACross indicator.
- Some of the newer indicators were not being restored.
- `autoSave: true` set on `DataSaveControl` was not working.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
