### ISSUE TITLE
Bug Report: Unnecessary One-Day Extension in AmCharts Time Period [additional dates to the selected period][wrong calendar periods][wrong first date]

### ISSUE THREAD

**Issue by ivannrs** [amcharts/amcharts5#1292]
Amcharts 5 is adding additional dates to the selected period. One in the beginning(in the chart) and one in the end(in the calendar), which is not expected behavior for a stockchart. The newly added first date affect the performance and it is presented in the line chart, while the one at the end of the period is just in the calendar input. This causes a lot of issues when you’re trying to compare values for a specific time frame.

**Here’s my code pen:** 
https://codepen.io/kris-a/pen/jOJBjax?editors=0010  

As you can see the last available date we’re setting in the data object is 1040947200000 
which converts to: 
Fri Dec 27 2002 00:00:00 GMT+0000 or  
Fri Dec 27 2002 02:00:00 GMT+0200 (Eastern European Standard Time). 
Yet the calendar is showing one additional day, 28.12.2002. 

### Steps to reproduce:

** Issue 1: additional date in the beginning of the period **
1. Open my code pen 
2. Select and apply any date in the calendar, this way you will be able to see the date input (not sure why the calendar input can not be presented since the initialization, we workaround this with js events)
3. Then select "1 month" from the interval menu, the dates you will have should be “2002-11-29 -- 2002-12-28” 
4. The first point should be on 29th of November and I would expect this to be the first visible and selectable point in my chart with value 0,00 %, which is not the case. For some reason I am also able to see the history of the line going in a direction close to 0, 00 % but not exactly. 
![1_1](https://github.com/amcharts/amcharts5/assets/16203829/8a8d8815-fa60-49cf-bcdc-6dbdec10ec9c)

** Issue 2: Calendar input is showing one more day **
1. Continue the steps from the previous issue
2. In this case I would expect to have Fri Dec 27 as end date in my calendar input, but instead it is showing 28th of Dec.

** Issue 3: The last day of the period is not presented (related to Issue 2) **
1. Open the codepen demo
2. Select "1 month" from the period menu
3. Change the end date via the calendar to 2002-12-24, so you should see the following string in the input: "2002-11-29 -- 2002-12-24"
4. Now I am not able to hover and select 24th of Dec. even it is included in my period, I also can not see what's the closing value on this date. I can see that the line is going in some direction, but looks like cut to me. I would expect the end of the line to be 24th of Dec. and I would be able to select it via hovering.

###  Environment

-  amCharts version: check the HTML tab
-  Browser and its version: Edge and Chrome
- Licensed version (the demo is of course not)

**Comment by ivannrs** [comment]
_Just cutting off the line there would misrepresent the data in a way that would make user think there's no data before 29th._

Oh, that's smart actually. I would really agree it makes sense, the only problem then with **Issue 1** is that the expected percent value for the date should be 0.00% since its the first price and we have "-0,27 %". Might be that its is using as a start date 28th (or the previous available date).

**Comment by martynasma** [comment]
> Oh, that's smart actually. I would really agree it makes sense, the only problem then with Issue 1 is that the expected percent value for the date should be 0.00% since its the first price and we have "-0,27 %". Might be that its is using as a start date 28th (or the previous available date).

We'll fix that in the next version, too.

**Comment by martynasma** [comment]
Fixed in [5.8.0](https://github.com/amcharts/amcharts5/releases/tag/5.8.0).

## [5.8.0] - 2024-02-01

### Added
- New container type `ZoomableContainer` added, which allows adding zoom capabilities to virtually any chart. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/containers/#Zoomable_container).
- New class `ZoomTools` added. Can be used to quickly add zoom support for elements compatible with `IZoomable` interface, e.g. `ZoomableContainer`.
- New read-only property of `DrawingControl`: `drawingSeries`. Contains an object where key is a drawing tool name and values are array with references to actual drawing series.

### Changed
- Default value for `strokeOpacity` for the grid line of a `StockChart` changed from `0` to `0.4` so that it would differ from regular grid lines.

### Fixed
- Resizing stock chart's panels after moving them up/down was not working properly.
- `Hierarchy.addChildData` was duplicating node's children which were added before.
- If `topDepth` was set to `1` on `Partition`, initially the chart was showing not all levels of nodes.
- When clicking on particular partitions of a `Partion` chart, zoom animation was not playing.
- `DateRangeSelector` was showing extra day in automatically-calculated end date.
- `DateRangeSelector` was zooming to the start of the selected day, instead of end.
- Tooltip background color passed to `HeatLegend.showValue(value, text, color)` was being ignored.
- `ClusteredPointSeries` was not showing charts if they were added to clustered bullets.
- Fixed issue with `DrawingControl` which was unnecessarily duplicating drawing series with each tool selection / API call.
- Using "1M" button in `PeriodSelector` was not always selecting full month.
- Restoring drawings with `DrawingControl.unserializeDrawings()` will now correctly update indexes of the restored drawings based on current drawing counter.
- In some cases `StockChart` was taking a data item which was just outside of zoom range when calculating aggregate values for its series, affecting percent change values and some other aggregates.
- Legend value was not being updated when series axis' range changed. This caused `legendRangeLabelText` to not being updated (if set) when chart was being zoomed-in/out.
- If a type of `StockChart` series was changed with data grouping enabled, some duplicate candlesticks or ohlc sticks were displayed until first zoom.
- In some rare cases chart would show incorrect last segment of a `LineSeries` when in percent mode.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
