### ISSUE TITLE
Stock chart is not showing closing percent value in the legend [missing legendRangeValueText]

### ISSUE THREAD

**Issue by ivannrs** [amcharts/amcharts5#1293]
I am trying to show the closing value (in %) of a line stock chart series for a selected period, whenever the mouse is not hovering the chart.
To achieve this I've tried this setting “legendRangeValueText” parameter with “valueYChangeSelectionPercent” as described in the documentation, but with no success. The same setting appears to show a value if I set it “valueYsum”, but it does not fulfill our requirements mentioned above. 

**Here’s my code pen:**
https://codepen.io/kris-a/pen/jOJBjax?editors=0010

### Steps to reproduce:

1. Please use the provided code pen, the “legendRangeValueText” is already set for you in the settings and you can check the legend value is missing.

###  Environment

- amCharts version: check the HTML tab
- Browser and its version: Edge and Chrome
- Licensed version (the demo is of course not)

###  Additional context

Have in mind that I am also reporting issue #1292 which is basically not presenting the last value (Issue 3), so please excuse me if “legendRangeValueText” is working, but the periods are messed.

**Comment by zeroin** [comment]
Hi,

last item of a series is not set as a data item of a legend, so legendRangeValueText will not work. You can solve this by adding an adapter for the legendRangeValueText:

```
valueSeries.adapters.add("legendRangeValueText", (legendRangeValueText) => {
  // take last index of a series
  var lastIndex = valueSeries.endIndex() - 1;
  var lastDataItem = valueSeries.dataItems[lastIndex];
  if (lastDataItem) {
    return valueSeries.getNumberFormatter().format(lastDataItem.get("valueYChangeSelectionPercent"), "0.00") + "%";
  }
  return legendRangeValueText
})
```

However sometimes last index of a series might be not visible in the selection, so you might want to do some adjustments based on your confing an date's axis max selection: `dateAxis.getPrivate("maxSelection")`

**Comment by zeroin** [comment]
An alternative version would be to set `alwaysShow:true` for the cursor and position it to the very end when plot area is unhovered:

```
mainPanel.events.on("pointerout", ()=>{
  cursor.set("positionX", 0.9999);  
})

mainPanel.events.on("pointerover", ()=>{  
  cursor.set("positionX", undefined)
})
```

(should work with 1, but I found some bug while doing the example, it will work properly with 1 in next release).

https://codepen.io/team/amcharts/pen/mdowaMw/756f8bd8d68a1e8075dccfda0e8a3d0a?editors=0010

**Comment by ivannrs** [comment]
Hey @zeroin 
Thanks for all the updates. We have tested your suggestions and here is what we have found out so far:
**Approach 1** https://github.com/amcharts/amcharts5/issues/1293#issuecomment-1903591375
Not sure what exactly you mean by :
_However sometimes last index of a series might be not visible in the selection, so you might want to do some adjustments based on your config an date's axis max selection: dateAxis.getPrivate("maxSelection")_
However we have tested the rest and the result is not bad at all. The only negative point here is that whenever a user do not hover the chart and just click on the preset periods, the legend value does not get updated.
Steps to reproduce: 
1. Open the code pen https://codepen.io/kris-a/pen/qBvxdLO?editors=1010
2. Select periods without hovering the chart

**Approach 2** https://github.com/amcharts/amcharts5/issues/1293#issuecomment-1903654030
Also not bad at all, but then whenever we have more than one series with different availability you will get no value in the legend. Lets say you have 2 series, the first that ends on 20th and the second that ends on 22nd, then on no hover the pointer will select 22nd which will result in no value for the first item.
Steps to reproduce:
1. Open this codepen: https://codepen.io/kris-a/pen/xxBYVJx
1. Check the legend. You can also select 1 month to see the obvious difference in the lines.

Honestly, I have the feeling that the first approach is more logically close to the expectations, we should only check if we can trigger the correct show, what's your opinion on these.

**Comment by zeroin** [comment]
Hi,

The first issue is a bug, we will fix it - thanks for the heads up. 

You can fix it for now by adding:

```
  series.onPrivate("startIndex", function(){    
    series.updateLegendValue();
  })
  
  series.onPrivate("endIndex", function(){    
    series.updateLegendValue();
  })
```

As for the second one, then you are right, it's not a very good one with missing data.

**Comment by martynasma** [comment]
Fixed in [5.8.0](https://github.com/amcharts/amcharts5/releases/tag/5.8.0).

## [5.8.0] - 2024-02-01

### Added
- New container type `ZoomableContainer` added, which allows adding zoom capabilities to virtually any chart. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/containers/#Zoomable_container).
- New class `ZoomTools` added. Can be used to quickly add zoom support for elements compatible with `IZoomable` interface, e.g. `ZoomableContainer`.
- New read-only property of `DrawingControl`: `drawingSeries`. Contains an object where key is a drawing tool name and values are array with references to actual drawing series.

### Changed
- Default value for `strokeOpacity` for the grid line of a `StockChart` changed from `0` to `0.4` so that it would differ from regular grid lines.

### Fixed
- Resizing stock chart's panels after moving them up/down was not working properly.
- `Hierarchy.addChildData` was duplicating node's children which were added before.
- If `topDepth` was set to `1` on `Partition`, initially the chart was showing not all levels of nodes.
- When clicking on particular partitions of a `Partion` chart, zoom animation was not playing.
- `DateRangeSelector` was showing extra day in automatically-calculated end date.
- `DateRangeSelector` was zooming to the start of the selected day, instead of end.
- Tooltip background color passed to `HeatLegend.showValue(value, text, color)` was being ignored.
- `ClusteredPointSeries` was not showing charts if they were added to clustered bullets.
- Fixed issue with `DrawingControl` which was unnecessarily duplicating drawing series with each tool selection / API call.
- Using "1M" button in `PeriodSelector` was not always selecting full month.
- Restoring drawings with `DrawingControl.unserializeDrawings()` will now correctly update indexes of the restored drawings based on current drawing counter.
- In some cases `StockChart` was taking a data item which was just outside of zoom range when calculating aggregate values for its series, affecting percent change values and some other aggregates.
- Legend value was not being updated when series axis' range changed. This caused `legendRangeLabelText` to not being updated (if set) when chart was being zoomed-in/out.
- If a type of `StockChart` series was changed with data grouping enabled, some duplicate candlesticks or ohlc sticks were displayed until first zoom.
- In some rare cases chart would show incorrect last segment of a `LineSeries` when in percent mode.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by ivannrs** [comment]
Thanks a lot @martynasma, this release was really fast response.
Unfortunately we have found another small issue now and I would like to report it to you. To reproduce it please check this codepen: https://codepen.io/kris-a/pen/qBvxdLO
Try not to hover the chart and click on the predefined periods at the top, lets say 1 year, you will see percent in the legend like -19.01 and -35.45, which is actually relevant for the previous selected period. If you hover the chart the labels will bet updated. Now click on 3 years then (without hovering the chart) on 5 years. On 3 years it did not updated anything, but kept the values from 1 year, then on 5 years it shows the values from 3 years. I assume it did not trigger the update on the right event and it always shows the values from the previous selection, unless you hover the chart, but some users are using entirely the keyboard.

**Comment by martynasma** [comment]
Would you be able to post it as a new ticket as this one has already been closed?

**Comment by ivannrs** [comment]
Sure, it makes more sense. Sorry about that.
