### ISSUE TITLE
Protruding lines at the beginning and at the end of a chart

### ISSUE THREAD

**Issue by ivannrs** [amcharts/amcharts5#1306]
Amcharts 5 is showing unexpected lines in the beginning and in the end of a chart.

Here’s my code pen:
https://codepen.io/kris-a/pen/jOJBjax

Steps to reproduce:
** Issue **

1. Open my code pen
2. Select and apply the following dates in the calendar: 2000-02-16 -- 2002-02-21
3. Observe the lines in the beginning and in the end. On the client's side they are even more obvious.

![image](https://github.com/amcharts/amcharts5/assets/16203829/e69ed557-4585-4007-981a-29a155240e7e)
one more example: 
![image](https://github.com/amcharts/amcharts5/assets/16203829/4d3903bf-7328-4fdb-9504-a59fba2c57ca)

Also if we do the line a bit wider its more obvious.

### Environment

- amCharts version: check the HTML tab
- Browser and its version: Edge and Chrome
- Licensed version (the demo is of course not)

**Comment by martynasma** [comment]
Lines are masked to the dimensions of the plot container.

If you have a thick line which goes almost in parallel with the edge then you'll get the effect of the line being cut off down the middle of it.

There's no way to work around it.

**Comment by ivannrs** [comment]
Thanks for your explanation @martynasma.

I have checked the next few entry points in the series and non of them is as high as the line is, actually the next one is supposed to be even in the other direction. One more interesting fact I have observed is that it looks like the chart doesn't know the next index, if you follow my steps then switch the end date to 2002-02-22 and then back to 2002-02-21 you will see the chart renders correctly. 
Such a line is leaving a feeling of significate drop or rise in the clients the way it looks like.

**Comment by martynasma** [comment]
Hm, indeed. Thanks for more details!

We're fixing this in the next version.

**Comment by martynasma** [comment]
Fixed in [5.8.0](https://github.com/amcharts/amcharts5/releases/tag/5.8.0).

## [5.8.0] - 2024-02-01

### Added
- New container type `ZoomableContainer` added, which allows adding zoom capabilities to virtually any chart. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/containers/#Zoomable_container).
- New class `ZoomTools` added. Can be used to quickly add zoom support for elements compatible with `IZoomable` interface, e.g. `ZoomableContainer`.
- New read-only property of `DrawingControl`: `drawingSeries`. Contains an object where key is a drawing tool name and values are array with references to actual drawing series.

### Changed
- Default value for `strokeOpacity` for the grid line of a `StockChart` changed from `0` to `0.4` so that it would differ from regular grid lines.

### Fixed
- Resizing stock chart's panels after moving them up/down was not working properly.
- `Hierarchy.addChildData` was duplicating node's children which were added before.
- If `topDepth` was set to `1` on `Partition`, initially the chart was showing not all levels of nodes.
- When clicking on particular partitions of a `Partion` chart, zoom animation was not playing.
- `DateRangeSelector` was showing extra day in automatically-calculated end date.
- `DateRangeSelector` was zooming to the start of the selected day, instead of end.
- Tooltip background color passed to `HeatLegend.showValue(value, text, color)` was being ignored.
- `ClusteredPointSeries` was not showing charts if they were added to clustered bullets.
- Fixed issue with `DrawingControl` which was unnecessarily duplicating drawing series with each tool selection / API call.
- Using "1M" button in `PeriodSelector` was not always selecting full month.
- Restoring drawings with `DrawingControl.unserializeDrawings()` will now correctly update indexes of the restored drawings based on current drawing counter.
- In some cases `StockChart` was taking a data item which was just outside of zoom range when calculating aggregate values for its series, affecting percent change values and some other aggregates.
- Legend value was not being updated when series axis' range changed. This caused `legendRangeLabelText` to not being updated (if set) when chart was being zoomed-in/out.
- If a type of `StockChart` series was changed with data grouping enabled, some duplicate candlesticks or ohlc sticks were displayed until first zoom.
- In some rare cases chart would show incorrect last segment of a `LineSeries` when in percent mode.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
