### ISSUE TITLE
Drawing Index issue 

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1307]
What will happen in the case of Data Save Control?

For example I have an file which contains un-serialize drawings of product X.

Now user have 3 options related to drawings :

Can draw using drawing tools.
Can retrieve drawings from local storage which he had saved once.
Can choose the option to view the drawings of the file ( which contains un-serialize drawing set of data).
Let's see a sample real-life case:

X product un-serialize File content: It will have Template of horizontal ray which has 3 horizontal ray's with the indexes 0,1,2. This file I have generated from a script as I already know what template unserializeDrawings accepts.

Now user came and draw a horizontal ray ( which will have an index as 0), and then he saved it in local storage using DataSaveControl feature.
Now he removed the ray from the chart ( Note: it is already saved in local storage).
Again he used the drawing tools to draw a horizontal ray. Let's Assume the index is 1 of the ray.
Question 1: what will be the index of the ray which user made at step 3?
Now he Retrieved the horizontal ray which is stored in local storage via DataSaveControl feature.
And Lastly he also unserializeDrawings of the file too which contains 3 horizontal ray's with the indexes 0,1,2.
Question 2:
Now you can see there are total 5 Horizontal ray's on the mainpanel/chart.

One the user which he had made. (with index 1). (step 3)
One which he retrieved from local storage. ( with index 0). (step 1)
And 3 other's from unserializeDrawings. ( with index 0,1,2). ( step 5)
You can see there are horizontal ray's which has same index.

How the index of drawings will behave and change. As I can Only pass index to delete the drawings ( disposeIndex method)?
As passing index 0 might delete multiple horizontal ray, due to common index.

More reference present in #1297

**Comment by workingbuddy10** [comment]
@martynasma  That's I why I was suggesting to add a parameter/method in the drawings template to differentiate between unserialize Drawings & others. 

Currently I have solved the issue using a hack, by giving the large index to the  un-serialize Drawings (1000+).

**Comment by martynasma** [comment]
Fixed in [5.8.0](https://github.com/amcharts/amcharts5/releases/tag/5.8.0).

## [5.8.0] - 2024-02-01

### Added
- New container type `ZoomableContainer` added, which allows adding zoom capabilities to virtually any chart. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/containers/#Zoomable_container).
- New class `ZoomTools` added. Can be used to quickly add zoom support for elements compatible with `IZoomable` interface, e.g. `ZoomableContainer`.
- New read-only property of `DrawingControl`: `drawingSeries`. Contains an object where key is a drawing tool name and values are array with references to actual drawing series.

### Changed
- Default value for `strokeOpacity` for the grid line of a `StockChart` changed from `0` to `0.4` so that it would differ from regular grid lines.

### Fixed
- Resizing stock chart's panels after moving them up/down was not working properly.
- `Hierarchy.addChildData` was duplicating node's children which were added before.
- If `topDepth` was set to `1` on `Partition`, initially the chart was showing not all levels of nodes.
- When clicking on particular partitions of a `Partion` chart, zoom animation was not playing.
- `DateRangeSelector` was showing extra day in automatically-calculated end date.
- `DateRangeSelector` was zooming to the start of the selected day, instead of end.
- Tooltip background color passed to `HeatLegend.showValue(value, text, color)` was being ignored.
- `ClusteredPointSeries` was not showing charts if they were added to clustered bullets.
- Fixed issue with `DrawingControl` which was unnecessarily duplicating drawing series with each tool selection / API call.
- Using "1M" button in `PeriodSelector` was not always selecting full month.
- Restoring drawings with `DrawingControl.unserializeDrawings()` will now correctly update indexes of the restored drawings based on current drawing counter.
- In some cases `StockChart` was taking a data item which was just outside of zoom range when calculating aggregate values for its series, affecting percent change values and some other aggregates.
- Legend value was not being updated when series axis' range changed. This caused `legendRangeLabelText` to not being updated (if set) when chart was being zoomed-in/out.
- If a type of `StockChart` series was changed with data grouping enabled, some duplicate candlesticks or ohlc sticks were displayed until first zoom.
- In some rare cases chart would show incorrect last segment of a `LineSeries` when in percent mode.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by workingbuddy10** [comment]
The example is not working which is present in the docs 
https://www.amcharts.com/docs/v5/concepts/common-elements/containers/#Example

@martynasma

**Comment by martynasma** [comment]
Try clearing your browser cache.
