### ISSUE TITLE
Legend values get updated too late

### ISSUE THREAD

**Issue by ivannrs** [amcharts/amcharts5#1319]
Thank you for your last release which fixed a lot of points, here is something we have just found in the new version and it might be considered as a follow of this ticket:
https://github.com/amcharts/amcharts5/issues/1293

**Issue**
The values in the legend shows the closing percent from the previous selected period.

- Open this codepen: https://codepen.io/kris-a/pen/qBvxdLO
- Try not to hover the chart and click on the predefined periods at the top, lets say 1 year, you will see percent in the legend like -19.01 and -35.45, which is actually relevant for the previous selected period. If you hover the chart the labels will bet updated.
-  Now click on 3 years then (without hovering the chart) on 5 years. 
On 3 years it did not updated anything, but kept the values from 1 year, then on 5 years it shows the values from 3 years. I assume it did not trigger the update on the right event and it always shows the values from the previous selection, unless you hover the chart, but some users are using entirely the keyboard.

### Environment

amCharts version: check the HTML tab
Browser and its version: Edge and Chrome
Licensed version (the demo is of course not)

**Comment by martynasma** [comment]
Fixed in [5.8.1](https://github.com/amcharts/amcharts5/releases/tag/5.8.1).

## [5.8.1] - 2024-02-14

### Changed
- `VolumeProfile` indicator will now not let select an unreasonably small value for its "ticks per row" setting.

### Fixed
- Using `DrawingControl` in standalone mode was resulting in error when trying to enable drawing tool from API.
- Volume profile indicator was taking one extra date which was out of selection in some cases.
- If `snapToSeries` was set on `XYCursor`, `tooltipDataItem` was set one extra time with incorrect value on `XYSeries`.
- `XYSeries` was not updating legend if `legendRangeValueText` text was set on series and range was changed from outside without animated theme enabled.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
