### ISSUE TITLE
Issue related to Extra Max in valueAxis property  

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1339]
I have added extraMin in valueAxis & extraMax  in dateAxis, and when I click on 5d period selector it shows me the blank/zoom-in, out of the scope/beyond the candles present.

And even when I change the product it remains zoom-in to the blank. It should have synced or taken the data date which is present rather than taking extra date added by extraMax.

ExtraMax is working perfectly, it's the period selector taking the date range.

https://github.com/amcharts/amcharts5/assets/137867461/b36a333f-8c5b-4aee-96ab-495e9666fd59

https://www.amcharts.com/demos/stock-chart-comparing-prices/

**Comment by martynasma** [comment]
Fixed in [5.8.4](https://github.com/amcharts/amcharts5/releases/tag/5.8.4).

## [5.8.4] - 2024-02-22

### Added
- New `DrawingSeries` method: `getIndex(drawingId)`. Will return index of a drawing corresponding to a unique id, or `null` if not found.

### Changed
- `PeriodSelector` will now zoom to last/first data items if `stockSeries` is set on `StockChart`. Previously it used to zoom to X-axis scale end/start, regardless of data.
- All `DrawingSeries` will now add a unique `drawingId` to all drawing data.
- Stock indicatos adjusted so that they could handle data with negative values, `0` volume values and all OHLC values being equal.

### Fixed
- Scale of a `ValueAxis` was not adjusting properly if its height/width changed during zoom.
- Standalone `DrawingControl` (one that was not added to a toolbar) was erroring out when parent `Root` was disposed.
- HTML content in a `Label` (with `html` set) was not inheriting labels actual color (`fill`).
- Setting a `selectedDataItem` to a data item without children on a `Hierarchy` series was resulting in error.
- Heat rules were setting "neutral" color on the default state of a target even if it was undefined, resulting in some issues when value was not set.
- Heat rules were ignoring `customFunction` if value was not set.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
