### ISSUE TITLE
root.dispose() throws error after adding drawing controls to chart

### ISSUE THREAD

**Issue by marciammart** [amcharts/amcharts5#1346]
**Bug description**

After adding drawing controls to a stock chart using `am5stock.DrawingControl.new(root, { stockChart })`, the `root.dispose()` function stops working and I get the following error:

<img width="676" alt="Screenshot 2024-02-21 at 14 49 16" src="https://github.com/amcharts/amcharts5/assets/53227495/b46c79e8-6cf5-4633-86e8-260da3f5cb2b">

I'm not using the built in drawing controls menu, and instead using a custom made one.

**Environment (if applicable)**
version 5.8.3 in React/Typescript

**Comment by martynasma** [comment]
Fixed in [5.8.4](https://github.com/amcharts/amcharts5/releases/tag/5.8.4).

## [5.8.4] - 2024-02-22

### Added
- New `DrawingSeries` method: `getIndex(drawingId)`. Will return index of a drawing corresponding to a unique id, or `null` if not found.

### Changed
- `PeriodSelector` will now zoom to last/first data items if `stockSeries` is set on `StockChart`. Previously it used to zoom to X-axis scale end/start, regardless of data.
- All `DrawingSeries` will now add a unique `drawingId` to all drawing data.
- Stock indicatos adjusted so that they could handle data with negative values, `0` volume values and all OHLC values being equal.

### Fixed
- Scale of a `ValueAxis` was not adjusting properly if its height/width changed during zoom.
- Standalone `DrawingControl` (one that was not added to a toolbar) was erroring out when parent `Root` was disposed.
- HTML content in a `Label` (with `html` set) was not inheriting labels actual color (`fill`).
- Setting a `selectedDataItem` to a data item without children on a `Hierarchy` series was resulting in error.
- Heat rules were setting "neutral" color on the default state of a target even if it was undefined, resulting in some issues when value was not set.
- Heat rules were ignoring `customFunction` if value was not set.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
