### ISSUE TITLE
DateRangeSelector does not inherit timezone from root

### ISSUE THREAD

**Issue by theoturner** [amcharts/amcharts5#1362]
If a chart is set up with `root.utc = true` as directed [here](https://www.amcharts.com/docs/v5/concepts/formatters/formatting-dates/#utc-and-time-zones) e.g.

```js
const root = am5.Root.new("my-div");
root.utc = true;
const chart = root.container.children.push(
  am5stock.StockChart.new(root, {})
);
```

The axes and date-related elements now stay in UTC rather than local timezone, except `DateRangeSelector`, which remains in the local timezone. This leads to a difference in the date the user input and that selected:
![Screenshot 2024-02-29 at 15 32 16](https://github.com/amcharts/amcharts5/assets/10600558/94bd8821-6937-40eb-b639-960aa83d82ec)

Example stock toolbar on chart for this behaviour:
```js
am5stock.StockToolbar.new(root, {
  container: document.getElementById("my-control-div")!,
  stockChart: chart,
  controls: [
    am5stock.DateRangeSelector.new(root, {
      stockChart: chart,
    }),
  ],
});
```

Removing `root.utc = true` prevents the behaviour (though then axes also become localized).

**Comment by martynasma** [comment]
Fixed in [5.8.5](https://github.com/amcharts/amcharts5/releases/tag/5.8.5).

## [5.8.5] - 2024-03-15

### Added
- `forceHidden` (default: `false`) setting added to `StockControl`. Enables forcing some `StockChart` controls to be always hidden.
- New `DateRangeSelector` event added: `"rangeselected"`.
- New `PriodSelector` event added: `"periodselected"`.

### Fixed
- A JavaScript error was being triggered if a `Picture` was disposed before external image was finished loading (since 5.8.3).
- Inputs in `DateRangeSelector` were ignoring `Root`'s `timezone` and `utc` settings.
- Thicker stroke (`strokeWidth > 1`) was being ignored as a hit target for interactive elements.
- `Scrollbar` grips would not update their position according to `maxZoomCount`/`minZoomCount` setting in some cases.
- Hovering over the border of a `Treemap` node could result tooltip of some other node to appear.
- In some cases pointer over tooltip of a hovered `Treemap` node would remain on the same node, even if pointer would move to some other node.
- If a `{ timeUnit: "week", count: 2 }` (count > 1) was added to a `DateAxis`, labels were flickering while scrolling.
- Calling `zoomToDates()`/`zoomToValues()` on a `DateAxis` was resulting not exact dates when data grouping was enabled and grouping period would changed during zoom.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
