### ISSUE TITLE
Rapidly clicking through a Treemap crashes the chart with EventDispatcher is disposed

### ISSUE THREAD

**Issue by c-ody** [amcharts/amcharts5#1388]
**Bug description**

Rapidly clicking through the levels of a Treemap will sometimes throw an error, `EventDispatcher is disposed`, and crash the chart.

It seems to only happen when there's enough data in the Treemap to cause a bit of lag. I think it may have to do with the BreadcrumbBar, since it doesn't happen when that's removed.

For a minimal example, I took your demo Treemap (https://www.amcharts.com/demos/drill-down-treemap/), added another level to it, and added enough extra junk data to cause it to lag a little: https://jsfiddle.net/ocra8hp4/. It doesn't happen all the time, it may take several attempts before you get the error.

**Comment by martynasma** [comment]
Fixed in [5.8.5](https://github.com/amcharts/amcharts5/releases/tag/5.8.5).

## [5.8.5] - 2024-03-15

### Added
- `forceHidden` (default: `false`) setting added to `StockControl`. Enables forcing some `StockChart` controls to be always hidden.
- New `DateRangeSelector` event added: `"rangeselected"`.
- New `PriodSelector` event added: `"periodselected"`.

### Fixed
- A JavaScript error was being triggered if a `Picture` was disposed before external image was finished loading (since 5.8.3).
- Inputs in `DateRangeSelector` were ignoring `Root`'s `timezone` and `utc` settings.
- Thicker stroke (`strokeWidth > 1`) was being ignored as a hit target for interactive elements.
- `Scrollbar` grips would not update their position according to `maxZoomCount`/`minZoomCount` setting in some cases.
- Hovering over the border of a `Treemap` node could result tooltip of some other node to appear.
- In some cases pointer over tooltip of a hovered `Treemap` node would remain on the same node, even if pointer would move to some other node.
- If a `{ timeUnit: "week", count: 2 }` (count > 1) was added to a `DateAxis`, labels were flickering while scrolling.
- Calling `zoomToDates()`/`zoomToValues()` on a `DateAxis` was resulting not exact dates when data grouping was enabled and grouping period would changed during zoom.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
