### ISSUE TITLE
Load Data on pan

### ISSUE THREAD

**Issue by p3777dev** [amcharts/amcharts5#1408]
I am trying to load the data on panning on stock chart. Though it loads the data on panning but if I click any where on the chart then too it loads data and it considers the click as panning.

I have also added the wheelended event for loading the data which is working fine.

```
    let wheelTimeout;
 
    const handleOnDemandDataLoading = (e) => {
      if (this.dateAxis.get("start") > 0) return;
      if (wheelTimeout) {
        wheelTimeout.dispose();
      }
      wheelTimeout = this.dateAxis.setTimeout(function () {
        $this.root.dataStore.requestMoreData($this);
      }, 50);
    };

    mainPanel.events.on("wheelended", handleOnDemandDataLoading);

    mainPanel.events.on("panended",handleOnDemandDataLoading);   // this line is causing issue.
```

**Comment by martynasma** [comment]
We won't be able to change the behavior of `panended` since it would be a breaking change.

However, there's another event `pancancelled` which kicks in before `panended`, so you can use it as an indicator to skip your next `panended` event.

**Comment by p3777dev** [comment]
Okay @martynasma 


I tried this, yet it didn't worked.
```

    let wheelTimeout;
    let skipNextPanEnded = false; // Flag to indicate whether to skip the next panended event
   
    const $this = this;
   
    const handleOnDemandDataLoading = () => {
      if (this.dateAxis.get("start") > 0) return;

      if (wheelTimeout) {
        wheelTimeout.dispose();
      }
     
      wheelTimeout = this.dateAxis.setTimeout(function () {
        $this.root.dataStore.requestMoreData($this);
      }, 50);
    };
   
    mainPanel.events.on("panended", function() {
      if (!skipNextPanEnded) { // Check if we should skip the next panended event
        handleOnDemandDataLoading();
      }
      skipNextPanEnded = false; // Reset the flag
    });
   
    mainPanel.events.on("pancancelled", function() {
      // Set the flag to skip the next panended event
      skipNextPanEnded = true;
    });
```

**Comment by martynasma** [comment]
Hm, seems like a bug. We'll fix it in the next version.

**Comment by martynasma** [comment]
Fixed in [5.8.6](https://github.com/amcharts/amcharts5/releases/tag/5.8.6).

## [5.8.6] - 2024-03-20

### Fixed
- `pancancelled` event of an `XYChart` was not being fired in some cases.
- When old series were removed from an `XYChart` and a new added, related `ValueAxis` was not zooming out to new data if Animated theme was not used.
- `Series.on("tooltipDataItem")` was not working in some setups since `5.8.3`.
- If a `ValueAxis` width `extraMin` and/or `extraMax` set was being synced with another axis (via `syncWith`) chart could go into an SO in some setups/cases.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by workingbuddy10** [comment]
Tried doing by the above approach but now my chart jumps like this whenever we load the data via panning :

https://github.com/amcharts/amcharts5/assets/137867461/4c32c4a1-a232-45b4-b975-0d4add8c5966


my valueAxis is set to autoZoom True.

@martynasma

**Comment by workingbuddy10** [comment]
> 
>     let wheelTimeout;
>     let skipNextPanEnded = false; // Flag to indicate whether to skip the next panended event

Issue 2:

After adding the panning via the above approach, when we zoom-in/out the it shows blank space or sometimes candlesticks/ volume candles looks like covered by something:

 

https://github.com/amcharts/amcharts5/assets/137867461/62a668a7-94ae-4316-ab3e-8add0909da4d

![image](https://github.com/amcharts/amcharts5/assets/137867461/8e27bef3-1700-41d4-bbf1-95d214cc799d)

![image](https://github.com/amcharts/amcharts5/assets/137867461/b908d191-4844-416f-a9f8-f33ebe1ce259)

@martynasma
