### ISSUE TITLE
Label background still shows even if label text has been hidden

### ISSUE THREAD

**Issue by c-ody** [amcharts/amcharts5#1418]
**Bug description**

This might be a feature, not a bug (or I might be doing something wrong), but I noticed that, in a Treemap, when a label is too small and the text is hidden, the label's background is still shown, which results in an empty rectangle.

If it's not a bug, is there a way to hide the label's background rectangle when the label's text is not displayed due to it not having enough space?

For a minimal example, I took your demo Treemap (https://www.amcharts.com/demos/drill-down-treemap/), removed the logos and made the text visible again, made the chart smaller, added padding to the labels, and gave the labels a background rectangle: https://jsfiddle.net/fjgke5c7/

**Comment by martynasma** [comment]
Fixed in [5.8.7](https://github.com/amcharts/amcharts5/releases/tag/5.8.7).

## [5.8.7] - 2024-03-25

### Fixed
- If a `Label` with background was hidden due to `oversizedBehavior` rule, the background was still visible.
- Moving `XYCursor` with keyboard were not always properly updating adapter-populated tooltips.
- HTML-based tooltips were not being updated properly in some cases.
- Labels of a zero-value slices on a `Venn` diagram will not be displayed anymore.
- `Sankey` links were ignoring `dx` and `dy` settings set on nodes.
- A JS error could occur when loading on-demand data in some specific cases.
- Series range affected by an axis range was not using settings from its `tempalteField`.
- When data grouping was enabled on `DateAxis`, calling `zoomToDates()` (and `zoomToValues()`) could result zooming to slightly different dates.


[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
