### ISSUE TITLE
5.8.6 version causing issue in stock chart

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1421]
The issue is the dataItems is getting undefined value at last.

How to reproduce : 
- Load chart/data.
- Load more using on-demand loading.
- Then zoom-in to the recent candles. **[IF YOU DON'T ZOOM-in then & change the product you won't get any error]**
- Then switch/change the next product.
- And whole app will freeze with this error.

Whereas when switch back to previous version then everything is working fine.

https://github.com/amcharts/amcharts5/assets/137867461/9b626734-44c8-4166-9e81-78947904f368

Like mentioned in #1416 Getting the exact same error

**Comment by zeroin** [comment]
We'll try to understand why this error might happen, thanks.

**Comment by workingbuddy10** [comment]
Sure

**Comment by workingbuddy10** [comment]
@zeroin Can you please tell me what was the exact issue? Very keen to know that.

**Comment by martynasma** [comment]
Fixed in [5.8.7](https://github.com/amcharts/amcharts5/releases/tag/5.8.7).

## [5.8.7] - 2024-03-25

### Fixed
- If a `Label` with background was hidden due to `oversizedBehavior` rule, the background was still visible.
- Moving `XYCursor` with keyboard were not always properly updating adapter-populated tooltips.
- HTML-based tooltips were not being updated properly in some cases.
- Labels of a zero-value slices on a `Venn` diagram will not be displayed anymore.
- `Sankey` links were ignoring `dx` and `dy` settings set on nodes.
- A JS error could occur when loading on-demand data in some specific cases.
- Series range affected by an axis range was not using settings from its `tempalteField`.
- When data grouping was enabled on `DateAxis`, calling `zoomToDates()` (and `zoomToValues()`) could result zooming to slightly different dates.


[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
