### ISSUE TITLE
Sankey node template adapter dy doesn't adjust link positions

### ISSUE THREAD

**Issue by vg-stan** [amcharts/amcharts5#1423]
I'm attempting to modify the vertical position of sankey nodes using an adapter on dy, the eventual goal is to have different dy settings per group of nodes based on business rules.  For now I'm just testing using a fixed value:
`
chart.nodes.nodes.template.adapters.add("dy", function(dy, target) {
    return 50
})
`

This however is only shifting the nodes and not the connecting links.
Before adapter:
<img width="981" alt="Screenshot 2024-03-22 at 2 43 25 PM" src="https://github.com/amcharts/amcharts5/assets/27689461/eaee1e55-ae40-4eb9-8d60-50721c343624">

After adapter:
<img width="1010" alt="Screenshot 2024-03-22 at 2 43 11 PM" src="https://github.com/amcharts/amcharts5/assets/27689461/726f6c79-133c-4851-9f59-17c7839b3529">

This isn't the same behavior from the amcharts 4 tutorial:
https://www.amcharts.com/docs/v4/tutorials/sankey-diagram-with-custom-node-widths-and-positions/

I can shift the the links using a similar adapter, however once I start having different dy values for different nodes, the links won't change their "shape" and connect properly.   

Did I miss anything in the documentation or Is there a better way to achieve what I'm trying to do?

I forked one the demo sandboxes and updated it with the above:

https://codepen.io/vg-schen/pen/ExMzrxm?editors=0110

**Comment by zeroin** [comment]
Indeed, Sankey links ignored dx and dy settings. We will fix this in next release.

**Comment by vg-stan** [comment]
Thanks @zeroin !  What is the expected date for the next release?

**Comment by martynasma** [comment]
Fixed in [5.8.7](https://github.com/amcharts/amcharts5/releases/tag/5.8.7).

## [5.8.7] - 2024-03-25

### Fixed
- If a `Label` with background was hidden due to `oversizedBehavior` rule, the background was still visible.
- Moving `XYCursor` with keyboard were not always properly updating adapter-populated tooltips.
- HTML-based tooltips were not being updated properly in some cases.
- Labels of a zero-value slices on a `Venn` diagram will not be displayed anymore.
- `Sankey` links were ignoring `dx` and `dy` settings set on nodes.
- A JS error could occur when loading on-demand data in some specific cases.
- Series range affected by an axis range was not using settings from its `tempalteField`.
- When data grouping was enabled on `DateAxis`, calling `zoomToDates()` (and `zoomToValues()`) could result zooming to slightly different dates.


[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
