### ISSUE TITLE
Strange rendering of certain Venn diagrams

### ISSUE THREAD

**Issue by stla** [amcharts/amcharts5#1424]
Hello,

In the Venn diagram below, all intersections are empty. Then their labels are superimposed:

![avenn1](https://github.com/amcharts/amcharts5/assets/4466543/3f0e1bfb-8c39-497b-9cff-acc70fd1cada)

In the one below, `A=B=AinterB`:

![avenn2](https://github.com/amcharts/amcharts5/assets/4466543/351b2049-3065-420d-bb54-944e84bdb35b)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by stla** [comment]
No problem. [Here is the fiddle](https://jsfiddle.net/stla/ndmhk612/5/). It contains the data of the nine possible Venn diagrams with cardinalities (2, 2, 1).

**Comment by martynasma** [comment]
Fixed in [5.8.7](https://github.com/amcharts/amcharts5/releases/tag/5.8.7).

## [5.8.7] - 2024-03-25

### Fixed
- If a `Label` with background was hidden due to `oversizedBehavior` rule, the background was still visible.
- Moving `XYCursor` with keyboard were not always properly updating adapter-populated tooltips.
- HTML-based tooltips were not being updated properly in some cases.
- Labels of a zero-value slices on a `Venn` diagram will not be displayed anymore.
- `Sankey` links were ignoring `dx` and `dy` settings set on nodes.
- A JS error could occur when loading on-demand data in some specific cases.
- Series range affected by an axis range was not using settings from its `tempalteField`.
- When data grouping was enabled on `DateAxis`, calling `zoomToDates()` (and `zoomToValues()`) could result zooming to slightly different dates.


[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
