### ISSUE TITLE
LineSeries Mask

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts5#144]
I'm seeing some issues with the LineSeries where objects can display beyond the series area, i.e. they are not being clipped. I'm only seeing this on the right hand side and the bottom though.

Here it's the labels on the right, they are part of the bullets:
<img width="1157" alt="Screen Shot 2021-12-14 at 7 09 58 PM" src="https://user-images.githubusercontent.com/5614099/145980642-60bd7167-3865-4dc7-8c4b-ed5965e463b2.png">

Here it's the bullets going off the bottom and the right:
<img width="1156" alt="Screen Shot 2021-12-14 at 7 12 26 PM" src="https://user-images.githubusercontent.com/5614099/145981695-5ae451c7-5102-46a5-a614-68930dd9d762.png">

Note that this is inconsistent behavior. It always works on first page load but subsequent in-page reloadings of the chart with new data or a different scale can cause it to go beyond borders but not always. Top and left side always work, no issues there. I also make sure to clean up the chart unloads with:
```javascript
chart.dispose();
chart.root.dispose();
```

I thought maybe the series mask had incorrect dimensions but there doesn't seem to be a mask at all when I check with `series.get("mask")`. Where is the actual mask and what issue could this be? Is there something that does not get cleaned up on unload?

**Comment by zeroin** [comment]
Series itself is not masked, it has a mainContainer which is masked. But I am not sure how this could help. I am afraid I need a reproducible case in order to help. Do the bullets outside the plot area move when you zoom in or they are just some left over from some previous data?

**Comment by sassomedia** [comment]
Ok, let me check if I can find anything on the mainContainer mask. I wonder if it is changing between loads. I will try if I can recreate a simpler example. As for the bullets, they do move in and out on zoom. Here is a screen recording:
https://user-images.githubusercontent.com/5614099/146166288-3281aba6-d978-450f-a914-57714a1f0342.mp4

**Comment by sassomedia** [comment]
@zeroin I didn't find a "mainContainer" on the chart but a number of others. Checked all of them for a mask but didn't see any. On which object would I be able to find the "mainContainer"?

I also tried to create an example that is similar in this [pen](https://codepen.io/sassomedia/pen/WNZpYqB?editors=0010) but I can't seem to recreate the issue. Although, on line 156 of that example I tried to call `chart.root.dispose();` but it throws a type error: `TypeError: undefined is not an object (evaluating 'chart.root.dispose')`. It seems to indicate that the CDN version is not up-to-date as the `root` prop was introduced in v5.0.6. Could you please verify whether that's the case?

**Comment by sassomedia** [comment]
Eh, never mind. I just went all the way back to 5.0.0-beta10 and `chart.root.dispose();` still works. I guess the chart one is always there, just for other elements it was introduced later. Not sure why the pen example throws an error there.

However, I finally figured out the issue of the overlap and was able to reproduce it. I updated the pen. The issue is the delay that's causing it `series.appear(800, 500);`. If I use a shorter delay like `series.appear(800, 100);`, it still works fine. 🤔

**Comment by zeroin** [comment]
The clipping issue will be fixed in next release - thanks!

**Comment by sassomedia** [comment]
Great, thanks!

**Comment by martynasma** [comment]
Fixed in [5.0.18](https://github.com/amcharts/amcharts5/releases/tag/5.0.18).

## [5.0.18] - 2021-12-19

### Changed
- When auto-wrapping labels, text will no longer break on dots to prevent fractional numbers from wrapping.
- Scrollable `Container`'s scrollbar will auto-hide if contents fit in it without scrolling.

### Fixed
- Disabling click-toggling of legend, was disabling hover events, too.
- `ResponsiveTheme`'s custom rules were not working properly.
- `Exporting` was not applying proper background color to exported images.
- `CategoryDateAxis` grid and labels placing algorithm improved.
- Sometimes bullets of XYChart were not being properly clipped by the bounds of the plot area.
- Memory leak related to: https://bugs.chromium.org/p/chromium/issues/detail?id=1279394 was fixed.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
