### ISSUE TITLE
AmCharts is being flagged for CVE-2024-22363

### ISSUE THREAD

**Issue by SteveCorbett** [amcharts/amcharts5#1450]
AmCharts is being flagged by code scanning since it contains xlsx version 0.19.3.

Updating the bundled hard copy of xlsx to version 0.20.2 or higher will resolve this.

**Comment by martynasma** [comment]
Thanks for the heads up! Working on a fix.

**Comment by martynasma** [comment]
Fixed in [5.9.1](https://github.com/amcharts/amcharts5/releases/tag/5.9.1).

## [5.9.1] - 2024-04-10

## Added
- New control in `StockChart`'s drawing toolbar: "Select". Allows toggling "selection" mode on and off. When it's on, clicking on any existing drawing will select it. Otherwise drawing will be initiated using currently selected tool. This allows drawing over existing drawings. Default: off.
- New `StockChart` setting: `drawingSelectionEnabled` (default: `false`). If set to `true`, all drawings will be selectable by clicking on them.

### Changed
- Bundled `xlsx` library code updated to `0.20.2`.
- All drawings are not selectable by default (they were selectable since 5.9.0). To enable selection, use the newly introduced "Select" control, or via `StockChart`'s `drawingSelectionEnabled` setting.

###
- Revisited fix to `tabindexOrder` with a safer approach.
- Arrow-navigating between grouped focusable items were not "jumping over" hidden items.
- `LineSeries`' axis ranges were not properly using `stroke`/`fill` templates from data.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by willpoorman** [comment]
Any chance this update to xlsx could be backported to amcharts4 to clear this vulnerability for that package as well?

**Comment by martynasma** [comment]
> Any chance this update to xlsx could be backported to amcharts4 to clear this vulnerability for that package as well?

It will.
