### ISSUE TITLE
5.9.0 stock chart drawing related issue

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1452]
I have a feature where a lot of drawings are un-serialized by the user, so after un-serializeDrawings if user try to draw then any other drawing is selected.  Because of this user is not able to draw.

A basic example  : 
- I have firstly un-serialize the Drawings.
- Then I clicked to the new drawing tool, and tried to use NEAR the  un-serialize drawings.
- So Instead of creating a triangle, line tool got selected.
- And now I am unable to draw the triangle near line.

https://github.com/amcharts/amcharts5/assets/137867461/6306f360-e121-40d9-b386-ad4cf0c003b1

And consider I have this much un-serialize drawings so it would be way too hard to draw new drawings.
![image](https://github.com/amcharts/amcharts5/assets/137867461/a86c5bf7-b309-4d55-8e3e-3bd7a452a6c2)

Ideally on-click of the drawing it should get active.

**Comment by martynasma** [comment]
We're introducing something to address this in the next version.

**Comment by martynasma** [comment]
Fixed in [5.9.1](https://github.com/amcharts/amcharts5/releases/tag/5.9.1).

## [5.9.1] - 2024-04-10

## Added
- New control in `StockChart`'s drawing toolbar: "Select". Allows toggling "selection" mode on and off. When it's on, clicking on any existing drawing will select it. Otherwise drawing will be initiated using currently selected tool. This allows drawing over existing drawings. Default: off.
- New `StockChart` setting: `drawingSelectionEnabled` (default: `false`). If set to `true`, all drawings will be selectable by clicking on them.

### Changed
- Bundled `xlsx` library code updated to `0.20.2`.
- All drawings are not selectable by default (they were selectable since 5.9.0). To enable selection, use the newly introduced "Select" control, or via `StockChart`'s `drawingSelectionEnabled` setting.

###
- Revisited fix to `tabindexOrder` with a safer approach.
- Arrow-navigating between grouped focusable items were not "jumping over" hidden items.
- `LineSeries`' axis ranges were not properly using `stroke`/`fill` templates from data.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
