### ISSUE TITLE
Initial `visible` series property not reflected on tooltip

### ISSUE THREAD

**Issue by mskocik** [amcharts/amcharts5#1470]
**Bug description**

When adding series with `visible: false` its tooltip is visible, ie. not respecting visibility status. When hidden series is show/hidden again, tooltip behaves as it should - hides as well.

Related code snippet from [related jsfiddle](https://jsfiddle.net/mskocik/bag2hq14/9/).
```js
chart.series.push(am5xy.LineSeries.new(root, {
    name: name,
    xAxis: xAxis,
    yAxis: yAxis,
    valueYField: "value",
    valueXField: "date",
    tooltip: tooltip,
    visible: false
  }));
```

Results in:
![image](https://github.com/amcharts/amcharts5/assets/25513620/a5961659-306f-4bb2-b423-b31638574315)

**Environment (if applicable)**

amCharts version: 5.9.1 (in production), jsfiddle (latest)

**Comment by martynasma** [comment]
Fixed in [5.9.3](https://github.com/amcharts/amcharts5/releases/tag/5.9.3).

## [5.9.3] - 2024-04-23

### Added
- Added possibility to add bullets to links in a linked hierarchy charts, like Force-directed and Tree. [More info](https://www.amcharts.com/docs/v5/charts/hierarchy/hierarchy-link-bullets/).
- New `IndicatorControl` method: `clearIndicators()`. Allows clearing all indicators from the chart at once.

### Changed
- `StockChart` will now automatically disable select mode when exitting drawing mode.
- `XYChart` background fill color and opacity have been moved to a default theme, so that it can be overridden by custom themes.

### Fixed
- Resize bubbles on `StockChart`'s drawings were sometimes disabled when switching and drawing with another drawing tool.
- Resize bubbles on `StockChart`'s were not shown after Eraser was turned on and off.
- Resize bubbles on `StockChart`'s were not shown when drawing mode was toggled off and then back on.
- `PieChart` was not updating radius if resized very quickly.
- If an `XYSeries` was initially hidden, its tooltip was still visible on an `XYChart` with cursor.
- Clicking on a selected icon drawing in a `SockChart` would not unselect it.
- A perfectly vertical or horizontal line with `strokeGradient` set was invisible.
- Removing an indicator from `StockChart` could cause Y-axis to be auto-zoomed incorrectly.
- The centering of a scaled HTML content was not taking `centerX`/`centerY` into account.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
