### ISSUE TITLE
how to ignore minbulletdistance options?

### ISSUE THREAD

**Issue by bossbelle** [amcharts/amcharts5#1471]
I use two bullet points in the chart.
'A' bullet must be marked
'B' bullets only want to be displayed when zoomed in.
However, if you use the minbulletdistance option
Both A and B are not displayed.
Is there a way for 'A' bullet to ignore the minbulletdistance option?
As shown in the image, 'A' bullet shows only one per chart.
![스크린샷 2024-04-18 095104](https://github.com/amcharts/amcharts5/assets/122963338/5c29e3ef-4672-418a-92cb-cdf0df0cd368)

**Comment by bossbelle** [comment]
As you advised in the comments, I added a series that shows only the data that the Bullet needs and added an image Bullet.
However, there is a problem that even though each series has the same value as the attached image, it is not displayed in the same location.
Is there a way to solve it?
![Uploading 스크린샷 2024-04-24 095909.png…]()

**Comment by zeroin** [comment]
It shouldn't be like this, something is not right here. If you could create a codepen where this is reproduced, I could take a look.

**Comment by bossbelle** [comment]
Here's my CodePen.
[codepen](https://codepen.io/-bossbelle/pen/KKYJgjJ)

**Comment by zeroin** [comment]
The problem is that you have stacked series, I didn't thought about that when suggesting. Try setting stacked:false for the bullet series. Of course, if you need the bullets to be on one of the stacked series, then you should calculate the values for the bullet series by adding all the values of previous series to the original value.

**Comment by bossbelle** [comment]
It works! Thank you so much.
