### ISSUE TITLE
Drawing Tool issue in 5.9.2 when using unserializeDrawings

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1474]
I am unable to move the drawings after I use unserializeDrawings.

In the below video :
- Firstly I tried to make new line. And I am able to move it using the point.
- Then I unserialized the Drawings.
- And made a new drawing.
- **Now I am unable to move  the drawing which I made before unserializeDrawings.** 
- I was able to do this thing in prior versions.
- NOTE : I am asking to move the drawings not selecting.

https://github.com/amcharts/amcharts5/assets/137867461/3fc120ee-41c4-4489-8adf-959680fba22a

codepen : https://codepen.io/team/amcharts/pen/gOyOEKy/b91d5db28e2e2336ab92dc71665c501f?editors=0010

**Comment by martynasma** [comment]
In my tests it's enough just to draw a line, switch to rectangle, draw a rectangle, to lose lines drag bubbles.

**Comment by martynasma** [comment]
Fixed in [5.9.3](https://github.com/amcharts/amcharts5/releases/tag/5.9.3).

## [5.9.3] - 2024-04-23

### Added
- Added possibility to add bullets to links in a linked hierarchy charts, like Force-directed and Tree. [More info](https://www.amcharts.com/docs/v5/charts/hierarchy/hierarchy-link-bullets/).
- New `IndicatorControl` method: `clearIndicators()`. Allows clearing all indicators from the chart at once.

### Changed
- `StockChart` will now automatically disable select mode when exitting drawing mode.
- `XYChart` background fill color and opacity have been moved to a default theme, so that it can be overridden by custom themes.

### Fixed
- Resize bubbles on `StockChart`'s drawings were sometimes disabled when switching and drawing with another drawing tool.
- Resize bubbles on `StockChart`'s were not shown after Eraser was turned on and off.
- Resize bubbles on `StockChart`'s were not shown when drawing mode was toggled off and then back on.
- `PieChart` was not updating radius if resized very quickly.
- If an `XYSeries` was initially hidden, its tooltip was still visible on an `XYChart` with cursor.
- Clicking on a selected icon drawing in a `SockChart` would not unselect it.
- A perfectly vertical or horizontal line with `strokeGradient` set was invisible.
- Removing an indicator from `StockChart` could cause Y-axis to be auto-zoomed incorrectly.
- The centering of a scaled HTML content was not taking `centerX`/`centerY` into account.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
