### ISSUE TITLE
Logarithmic scale fails for very low values

### ISSUE THREAD

**Issue by montalbano** [amcharts/amcharts5#1483]
Hi,
in my code when I put very low values as 0.0000001 the Log scale is not correctly displayed, but it display 0 as value from some point on:
https://codepen.io/dmnr-infn/pen/bGJOOVo
So, below a certain value the log scale fails and also the tooltip in the Y axis show 0 as value.
I use the 5.9.2 amcharts version.

**Comment by zeroin** [comment]
To solve series tooltip, value, you should format number:

`labelText: "{valueX}: {valueY.formatNumber('#.########')}"`

to solve axis tooltip value, set:

`extraTooltipPrecision:2` for your value axis.

**Comment by montalbano** [comment]
> To solve series tooltip, value, you should format number:
> 
> `labelText: "{valueX}: {valueY.formatNumber('#.########')}"`
> 
> to solve axis tooltip value, set:
> 
> `extraTooltipPrecision:2` for your value axis.

Thanks for your helpful reply.
I have another 2 questions:

With amCharts3 I was able to show tooltip on mouse hover and the value scale (Y) is evenly divided between e+0 and e-7

![Schermata del 2024-04-24 16-04-20](https://github.com/amcharts/amcharts5/assets/3714710/15187dbe-e28b-4ddc-a745-2025ab610f89)

Instead in amCharts5 I don't have tooltip on series (just in some sporadic value) and the value axis is compressed on top:

![Schermata del 2024-04-24 16-04-36](https://github.com/amcharts/amcharts5/assets/3714710/a81138ce-acd4-493b-adc1-4f82da4157a7)

How can solve? Thank you

**Comment by zeroin** [comment]
Could you create a codepen with this data?

**Comment by montalbano** [comment]
> Could you create a codepen with this data?

https://codepen.io/dmnr-infn/pen/bGJOOVo

they are not the same data, but it is the same behaviour

**Comment by martynasma** [comment]
Fixed in [5.9.4](https://github.com/amcharts/amcharts5/releases/tag/5.9.4).

## [5.9.4] - 2024-04-26

### Fixed
- `StockChart` with `VolumeProfile` indicator was snapping scrollbar's left grip to the start.
- Logarithmic axis was not showing labels less than 10e-5.
- `Treemap`'s labels would sometimes not adjust its size (usually with a lot of data).

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
