### ISSUE TITLE
Labels in Treemap sometimes blink or get stuck at a small size

### ISSUE THREAD

**Issue by c-ody** [amcharts/amcharts5#1484]
**Bug description**

After clicking one of the Treemap's nodes, causing it to transition to the next level, *rarely* Label text in the Treemap Rectangles will do one of these things:

1. As its Rectangle is getting bigger, and so is its font size, it "blinks" back to a smaller font size, but then back to the larger font size. Or it stays small and eventually jumps to the larger font size.
2. Sometimes, the labels that "blink" do not go to their proper larger size, and remain at the smaller size.

For an example, I took your demo Treemap (https://www.amcharts.com/demos/drill-down-treemap/), set the font size larger, set `minScale` to something small (seems to happen more often with this set, but I've seen it happen without this being set too), and added extra junk data to hopefully create lag (not sure if lag is necessary for bug to appear, or if it's something else). In my case, with the treemap at 1200x500px, 100% page zoom, and a Chrome browser, if I click on Toyota the label for Tacoma gets large (expanding to fill its Rectangle) as expected but then it jumps to a smaller size and stays that way. If I click on Hyundai, the label for Elantra is small and suddenly jumps to its larger font size. It doesn't seem to happen in the same place consistently, so it may take several attempts or randomly clicking back and forth between makes / models before you spot one. Getting one to remain at the smaller size takes many attempts of random clicking around for me, it doesn't happen often. https://jsfiddle.net/2xo95yq0/

**Comment by martynasma** [comment]
Fixed in [5.9.4](https://github.com/amcharts/amcharts5/releases/tag/5.9.4).

## [5.9.4] - 2024-04-26

### Fixed
- `StockChart` with `VolumeProfile` indicator was snapping scrollbar's left grip to the start.
- Logarithmic axis was not showing labels less than 10e-5.
- `Treemap`'s labels would sometimes not adjust its size (usually with a lot of data).

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
