### ISSUE TITLE
Logarithmic scale not showed completely

### ISSUE THREAD

**Issue by montalbano** [amcharts/amcharts5#1487]
With amCharts3 I was able to show tooltip on mouse hover and the value scale (Y) is evenly divided between e+0 and e-7:

![Schermata del 2024-04-24 16-04-20](https://github.com/amcharts/amcharts5/assets/3714710/108b6b01-6b38-4ac3-9f96-f8ab2d982571)

Instead in amCharts5 I don't have tooltip on series (just in some sporadic value) and the value axis is compressed on top:

![Schermata del 2024-04-24 16-04-36](https://github.com/amcharts/amcharts5/assets/3714710/417ee75d-479d-4615-8770-700ef9682331)

How can solve? Thank you

**Comment by zeroin** [comment]
Could you create a codepen with this config and data?

**Comment by montalbano** [comment]
> Could you create a codepen with this config and data?

yes, this is the codepen:

https://codepen.io/dmnr-infn/pen/bGJOOVo

I was able to view the labels in the Y axis up to 10e-5. Why does it stop at that value and not go down?

**Comment by martynasma** [comment]
Fixed in [5.9.4](https://github.com/amcharts/amcharts5/releases/tag/5.9.4).

## [5.9.4] - 2024-04-26

### Fixed
- `StockChart` with `VolumeProfile` indicator was snapping scrollbar's left grip to the start.
- Logarithmic axis was not showing labels less than 10e-5.
- `Treemap`'s labels would sometimes not adjust its size (usually with a lot of data).

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
