### ISSUE TITLE
yAxis doesn't show values below 1e-5 on logarithmic scale

### ISSUE THREAD

**Issue by montalbano** [amcharts/amcharts5#1490]
With logarithmic scale the yAxis doesn't show values below 1e-5:

![image](https://github.com/amcharts/amcharts5/assets/3714710/dc6990bb-4054-4f66-b90b-ab63cc8ef0c1)

Codepen:
https://codepen.io/dmnr-infn/pen/bGJOOVo

**Comment by martynasma** [comment]
Fixed in [5.9.4](https://github.com/amcharts/amcharts5/releases/tag/5.9.4).

## [5.9.4] - 2024-04-26

### Fixed
- `StockChart` with `VolumeProfile` indicator was snapping scrollbar's left grip to the start.
- Logarithmic axis was not showing labels less than 10e-5.
- `Treemap`'s labels would sometimes not adjust its size (usually with a lot of data).

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
