### ISSUE TITLE
Compressed grid lines on logarithmic yAxis 

### ISSUE THREAD

**Issue by montalbano** [amcharts/amcharts5#1492]
Hi,
in my logarithmic chart if I don't set the maximum value the horizontal lines of yAxis are compressed.

![image](https://github.com/amcharts/amcharts5/assets/3714710/6ea30bf1-320e-4e26-b97c-f3e8929e99b3)

If I set the max value on yAxis the grid lines are equally spaced:

![image](https://github.com/amcharts/amcharts5/assets/3714710/74eb76cb-3e73-4a70-91e2-c28ce842b6cf)

This happens for values less than 1 and to display it correctly I must set the maximum value to at least 100. 

https://codepen.io/dmnr-infn/pen/bGJOOVo

**Comment by martynasma** [comment]
Fixed in [5.9.5](https://github.com/amcharts/amcharts5/releases/tag/5.9.5).

## [5.9.5] - 2024-05-02

### Added
- New `DrawingControl` setting: `scrollable` (default: `false`). If set to `true` will restrict tool list to the height of the target chart.
- New `Sprite` method: `compositeRotation()`. Returns element's rotation in degrees, taking into account all of its ancestors.
- New element `EditableLabel`.

### Changed
- The drawing tool dropdown will now be fixed to the height of the target chart by default. You can disable it using `scrollable: false` on the `DrawingControl`.
- HTML content will now take `rotation` setting into account.
- Label and Callout drawing tools in `StockChart` will now use new `EditableLabel` element for smoother editing experience. The text is now editable.

### Fixed
- A `ValueAxis` with logarightmic scale and very small numbers was sometimes displaying cluttered grid lines and overlapping labels.
- Volume Profile indicator could show previous data if user quickly scrolled to the range where no volume data was available.
- Switching type of `RadialLabels` from radial to circular was resulting in those labels positioned incorrectly.
- If a mouse pointer was over the chart when TAB key was used to focus an `XYCursor` line, series/axis' tooltip would disappear.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
