### ISSUE TITLE
Draw tools cut off / do not show scrollbar when longer than div

### ISSUE THREAD

**Issue by theoturner** [amcharts/amcharts5#1499]
**Bug description**

Drawing tools dropdown cuts off items and does not display a scroll bar when the chart div is too short to display all tools.

The indicator control works fine and displays a scroll bar. It would be great if the drawing controls had the same behaviour.

![img](https://github.com/amcharts/amcharts5/assets/10600558/ce326ad4-e290-4967-9256-feb649ec392d)

**Environment**

Amcharts 5.9.4
Reproducible in Windows, MacOS, Ubuntu and Android in Chrome, Brave, Firefox, and Edge, as well as Safari on MacOS.

**Comment by martynasma** [comment]
We're adding `scrollable` setting to `DrawingControl` in the next version.

Still figuring out whether it'd be cool to change the default.

**Comment by martynasma** [comment]
Fixed in [5.9.5](https://github.com/amcharts/amcharts5/releases/tag/5.9.5).

## [5.9.5] - 2024-05-02

### Added
- New `DrawingControl` setting: `scrollable` (default: `false`). If set to `true` will restrict tool list to the height of the target chart.
- New `Sprite` method: `compositeRotation()`. Returns element's rotation in degrees, taking into account all of its ancestors.
- New element `EditableLabel`.

### Changed
- The drawing tool dropdown will now be fixed to the height of the target chart by default. You can disable it using `scrollable: false` on the `DrawingControl`.
- HTML content will now take `rotation` setting into account.
- Label and Callout drawing tools in `StockChart` will now use new `EditableLabel` element for smoother editing experience. The text is now editable.

### Fixed
- A `ValueAxis` with logarightmic scale and very small numbers was sometimes displaying cluttered grid lines and overlapping labels.
- Volume Profile indicator could show previous data if user quickly scrolled to the range where no volume data was available.
- Switching type of `RadialLabels` from radial to circular was resulting in those labels positioned incorrectly.
- If a mouse pointer was over the chart when TAB key was used to focus an `XYCursor` line, series/axis' tooltip would disappear.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
