### ISSUE TITLE
Series hidden by default

### ISSUE THREAD

**Issue by tobias-berg** [amcharts/amcharts5#15]
What is the preferred way of hiding a series from start, before rendering the chart? After that, the user should be able to show/hide it manually.

Currently I call series.hide() during creation. This indeed hides the series, but it makes the legend go inverted. So the series is hidden but the legend shows the visible state. Clicking on the legend shows the series but now the legend shows the hidden state. Hope that makes sense.

**Comment by martynasma** [comment]
`hide()` should be enough. The legend item not being switched off is a bug, which we'll need to fix.

Will keep you posted.

**Comment by martynasma** [comment]
Fixed in [5.0.0-beta.20](https://github.com/amcharts/amcharts5/releases/tag/5.0.0-beta.20).

## [5.0.0-beta.20] - 2021-09-21

### Added
- `toFront()` and `toBack()` methods added to `Sprite`.
- `"above"` setting added to `AxisDataItem`. Allows putting `AxisRange` grid and fill elements above the series.
- New setting `ignoreFormatting` for `Label` added. If set to `true`, it will ignore square-bracketed style blocks and will display text as it is.

### Fixed
- Elements in chart will not generate hover events if they are obstructed by some other DOM element anymore.
- `XYSeries` with a vertical axis range was fully visible, even the part covered by an axis range.
- Axis bullets were not being hidden when axis data item was hidden.
- Labels in `BreadcrumbBar` were sometimes misaligned in Safari browser.
- Legend item of an initially-hidden series/slices/columns was being shown as enabled.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download-v5/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
