### ISSUE TITLE
PieChart: When using a SliceGrouper, zooming or breaking slice displays group slice again + the actual grouped slices

### ISSUE THREAD

**Issue by chirmac** [amcharts/amcharts5#1525]
**Bug description**

When I create a Pie Chart, and wish to update its data from a server, in this case, using am5.load utility, the SliceGrouper stops working correctly. However I try it, I can't get it to work. If I simply create a new one on the root, it will create a new "other" slice inside the actual grouped slice. If I dispose the previous grouper and create a new one, same thing happens.

I made a simple example using await Promise below to show what is happening:
https://codepen.io/axglxieg-the-scripter/pen/pomJYEb

https://github.com/amcharts/amcharts5/assets/19695011/4e39fbb1-d01d-491e-8966-ddd750c57047

**Environment (if applicable)**

I'm using amCharts 5.9.7, in the latest version of Edge, in a .Net 8 MVC project, with WebPack and TypeScript.

**Additional context**

Creating a new object, setting the old one, removing the old one and create a new one, all of them create a glitch, either a missing slice or another wrong slice inside the grouped one

**Comment by martynasma** [comment]
It seems SliceGrouper does not register data update on the target series. We'll need to figure this out.

Thanks for the heads up!

**Comment by martynasma** [comment]
Fixed in [5.9.9](https://github.com/amcharts/amcharts5/releases/tag/5.9.9).

## [5.9.9] - 2024-05-21

### Added
- "Average True Range" indicator added to `StockChart`.

### Fixed
- Some recent versions of Chrome would sometimes clear canvas of a chart in an inactive tab after some time.
- Some events were not being disposed together with related object.
- Disposing an `XYChart` immediately after it was created would not dispose its `XYCursor` and related event handlers.
- `StockChart` method `unselectDrawings()` was not hiding resizer brackets.
- `SliceGrouper` would not update properly when series data was updated.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
