### ISSUE TITLE
Exporting chart as image under dark mode does not export associated background color

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#153]
If I add dark mode to any chart, not change the color of the axis and set the css of background image to any color, when exporting as png say, it would not export the background so the chart's background will still be white and the axis would not show up as its white text on white background.

**Comment by martynasma** [comment]
Do you mean you are using dark theme?

Would you be able to post your whole chart setup, including CSS you have goin on on CodePen or jsFiddle so that we can test exactly what you are using?

**Comment by dez1729** [comment]
https://stackblitz.com/edit/js-pqa5uv?file=index.js

**Comment by jcgithub9** [comment]
Related question/comment - have found with v5 charts/maps with a white background, PNG and PDF exports properly show white background, but JPG export has a black background.  Not sure if intentional behavior or not.

**Comment by martynasma** [comment]
Thanks for reporting this!

Both issues should be fixed in the next version. Will notify here when it's out.

**Comment by martynasma** [comment]
Fixed in [5.0.18](https://github.com/amcharts/amcharts5/releases/tag/5.0.18).

## [5.0.18] - 2021-12-19

### Changed
- When auto-wrapping labels, text will no longer break on dots to prevent fractional numbers from wrapping.
- Scrollable `Container`'s scrollbar will auto-hide if contents fit in it without scrolling.

### Fixed
- Disabling click-toggling of legend, was disabling hover events, too.
- `ResponsiveTheme`'s custom rules were not working properly.
- `Exporting` was not applying proper background color to exported images.
- `CategoryDateAxis` grid and labels placing algorithm improved.
- Sometimes bullets of XYChart were not being properly clipped by the bounds of the plot area.
- Memory leak related to: https://bugs.chromium.org/p/chromium/issues/detail?id=1279394 was fixed.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
