### ISSUE TITLE
Venn diagram crashes when quickly turning off more then one series in the legend

### ISSUE THREAD

**Issue by AlexSarva** [amcharts/amcharts5#1538]
If you quickly turn off A and B, the diagram will break with an error

check your [demo](https://www.amcharts.com/demos/venn-diagram) 

error: 

layout.js:286 Uncaught 
TypeError: Cannot read properties of undefined (reading 'size')
    at layout.js:286:60
    at L (layout.js:181:19)
    at layout.js:18:19
    at V._prepareChildren (Venn.ts:275:20)
    at index.js?ver=20240426-8e1:1:18442
    at Array.forEach (<anonymous>)
    at B._runDirties (index.js?ver=20240426-8e1:1:18340)
    at B._renderFrame (index.js?ver=20240426-8e1:1:19416)
    at B._runTicker (index.js?ver=20240426-8e1:1:19763)
    at _ticker._ticker (index.js?ver=20240426-8e1:1:20187)

**Comment by martynasma** [comment]
Fixed in [5.9.11](https://github.com/amcharts/amcharts5/releases/tag/5.9.11).

## [5.9.11] - 2024-05-30

### Added
- `clusterDelay` setting added to `ClusteredPointSeries`. Setting it to non-zero number will automatically debounce re-clustering of points, helping with performance when there are a lot of data items.

### Changed
- `ZoomControl` buttons will now be automatically disabled whem max or min zoom level is reached.

### Fixed
- "Zoom out" button was visible even the chart was not zoomed when `selectionStrictMinMax` was set to `true` (you still need to set `strictMinMax: true` for it to go away).
- `Venn` chart could produce JS error when slices were being hidden in rapid succession.
- Charts added to clustered point series bullets were not being rendered.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
