### ISSUE TITLE
MapChart with 3000 clustered points is slow

### ISSUE THREAD

**Issue by pvougny** [amcharts/amcharts5#1544]
**Question**

I'm using `am5map.MapChart` with `am5map.ClusteredPointSeries`.

Here is a sample in CodePen:
https://codepen.io/pvougny/pen/rNRYmab

- After rendering 2,800 very simple sprites on the map (circles with label), zooming and dragging is very slow. Is there any way to have it faster?
- Plus, when I try to render 3,000 points by changing variable `var n = 3000` at line 2, I get an error: `RangeError: Maximum call stack size exceeded`; then the map can't be rendered. Should I configure my sample differently to avoid that?

**Environment**

- amCharts latest
- Angular 15

<img width="509" alt="map-chart-3000" src="https://github.com/amcharts/amcharts5/assets/34480075/dc9878cb-8cab-4ae0-8dae-57664b564432">

**Comment by martynasma** [comment]
Fixed in [5.9.11](https://github.com/amcharts/amcharts5/releases/tag/5.9.11).

## [5.9.11] - 2024-05-30

### Added
- `clusterDelay` setting added to `ClusteredPointSeries`. Setting it to non-zero number will automatically debounce re-clustering of points, helping with performance when there are a lot of data items.

### Changed
- `ZoomControl` buttons will now be automatically disabled whem max or min zoom level is reached.

### Fixed
- "Zoom out" button was visible even the chart was not zoomed when `selectionStrictMinMax` was set to `true` (you still need to set `strictMinMax: true` for it to go away).
- `Venn` chart could produce JS error when slices were being hidden in rapid succession.
- Charts added to clustered point series bullets were not being rendered.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
