### ISSUE TITLE
MapChart with 3,000 bullets is still slow

### ISSUE THREAD

**Issue by pvougny** [amcharts/amcharts5#1553]
**Question**

I'm using `am5map.MapChart` with `am5map.ClusteredPointSeries`.

I opened the issue https://github.com/amcharts/amcharts5/issues/1544 regarding the rendering performance.

Here is a sample in CodePen:
https://codepen.io/pvougny/pen/rNRYmab

Zooming can be smoother thanks to the new property `clusterDelay`.
But still, dragging the map with 3,000 bullets is very slow. In my example I'm drawing only circles with labels, but if want to draw pieCharts instead, it becomes even slower. What's the strategy of rendering? Do you plan to kill this latency? Or reduce it considerably at least?

I have a lisense for **amCharts Map**. Can this request be considered as a support?

**Environment**

- amCharts latest (5.9.11 when asking this question)

**Comment by martynasma** [comment]
We'll give it another go. Will keep you posted.

**Comment by zeroin** [comment]
The only idea which comes to my mind is not to do clustering when panning/rotating the map, only while zooming. In some cases that would be a problem but in many cases it won't will probably need a setting for that. But I don't think we can improve the performance significantly while zooming.

**Comment by martynasma** [comment]
Fixed in [5.9.12](https://github.com/amcharts/amcharts5/releases/tag/5.9.12).

## [5.9.12] - 2024-06-12

### Changed
- `ClusteredPointSeries` now re-clusters points only when zoom level changes. This improves performance when paning/rotating the map.

### Fixed
- `NumberFormatter` would incorrectly round numbers smaller than 0 due to floating point issue in some cases.
- An error could occur when enabling drawing mode if there were previously disposed chart indicators.
- Truncated or wrapped labels were not properly sizing underline and line-through decorations.
- While wheel-zooming both X and Y axes simultaneously, the chart could fully zoom out in some cases.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
