### ISSUE TITLE
Add explicit d3 dependencies?

### ISSUE THREAD

**Issue by JackRobards** [amcharts/amcharts5#1567]
**Question**
Would it be possible to add explicit `d3-shape`, `d3-force`, and `d3-hierarchy` dependencies to the package.json file for amCharts5? 

From what I can tell, all of these are already used in the repository and pulled in via other d3 dependencies. These 3 packages are directly imported and used in a few places in the codebase (e.g. [here](https://github.com/amcharts/amcharts5/blob/87761ccbeece294d6bcc0c6217609e5bda00055b/src/.internal/charts/xy/series/SmoothedXYLineSeries.ts#L2)). Also, `d3-shape` and `d3-hierarchy` are already including `@types` packages in the package.json as well, just not the packages themselves.

I ran into an issue with a bundler where it complains that these packages aren't directly included. I can ignore it or patch the package.json on my side, but it would be nice if it could be updated in the root project unless you all have a strong reason you'd prefer not to.

**Environment (if applicable)**

Latest amCharts@5 version.

Also using TypeScript, Vite, and ESM.

**Additional context**

I believe the error is related to #1265 (and some of the other related issues) but adding these 3 explicit dependencies should help in my case and would be simpler than fully implementing ESM for the project. Since the dependencies are directly used, adding them to the package.json would be a good idea in opinion at least!

**Comment by martynasma** [comment]
That makes sense. We'll add it in the next version.

**Comment by martynasma** [comment]
Fixed in [5.9.13](https://github.com/amcharts/amcharts5/releases/tag/5.9.13).

## [5.9.13] - 2024-07-03

### Fixed
- If start and end values of a `HeatLegend` were the same, the tooltip was shown in the top/left corner of the chart.
- If a linked hierarchy had bullets on links, they remained visible when nodes and links were hidden.
- Zoom-out button could be visible initially with some specific setups.
- `ZoomableContainer` would not react to pans in some of its sections if its contents was panned outside the its bounds.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by JackRobards** [comment]
Hi @martynasma! I'm not seeing these packages in the 5.9.13 package.json on main:
https://github.com/amcharts/amcharts5/blob/master/package.json

Am I missing something? It doesn't seem like this would fix the issue without that change.

**Comment by Pauan** [comment]
@JackRobards Sorry about that, we forgot to include the changes in 5.9.13, so they'll be in 5.9.14 instead.

**Comment by martynasma** [comment]
Fixed in [5.10.0](https://github.com/amcharts/amcharts5/releases/tag/5.10.0).

## [5.10.0] - 2024-07-22

### Added
- A second parameter (`dataContext`) added to `Component`'s methods `pushDataItem` and `makeDataItem`, allowing to pass in a data context object related to the data item.
- New class `PatternSet` added. Allows serving patterns similarly to `ColorSet`. [More info](https://www.amcharts.com/docs/v5/concepts/colors-gradients-and-patterns/patterns/#Pattern_sets).
- New setting `patterns` added to `Hierarchy`, `PercentSeries`, `Venn`, `SerialChart`, `FlowNodes`. [More info](https://www.amcharts.com/docs/v5/concepts/colors-gradients-and-patterns/patterns/#Pattern_sets).
- New setting `fillPattern` added to `IFlowNodesDataItem`, `IHierarchyDataItem`, `IPercentSeriesDataItem`, `IVennDataItem`, `ISeriesSettings`.

### Fixed
- `LinkedHierarchy` nodes were not clickable when children were added using `addChildData()` method.
- If there were no nodes at `topLevel` in `Hierarchy` chart, it would show nodes from upper levels.
- Not all event listeners were disposed when disposing a `ChartIndicator`. This could cause a memory leak.
- `Sprite`'s `hover()`/`unhover()` methods now check if the `Sprite` is not disposed. This fixes some potential errors when disposed items are being referenced.
- Adding in explicit d3 dependencies ([Issue 1567](https://github.com/amcharts/amcharts5/issues/1567))
- `DurationFormatter` was not rounding fractional numbers properly in some cases.


[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
