### ISSUE TITLE
heatlegend in Heatmap chart

### ISSUE THREAD

**Issue by pratham3164** [amcharts/amcharts5#1571]
I'm building a heatmap chart with heatLegend. If the max and min value for the heatlegend is the same for eg: Min = Max = 60, when hovered over the value in the heatmap grid, pop up on heatlegend doesn't appear on the bar but appears on the left top corner of the chart

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by pratham3164** [comment]
code-pen for reference  https://codepen.io/ErPratham/pen/vYwZwZZ

**Comment by martynasma** [comment]
Fixed in [5.9.13](https://github.com/amcharts/amcharts5/releases/tag/5.9.13).

## [5.9.13] - 2024-07-03

### Fixed
- If start and end values of a `HeatLegend` were the same, the tooltip was shown in the top/left corner of the chart.
- If a linked hierarchy had bullets on links, they remained visible when nodes and links were hidden.
- Zoom-out button could be visible initially with some specific setups.
- `ZoomableContainer` would not react to pans in some of its sections if its contents was panned outside the its bounds.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
