### ISSUE TITLE
heatmap with huge dataset

### ISSUE THREAD

**Issue by pratham3164** [amcharts/amcharts5#1584]
Hi there, 
 I'm working on heatmap chart with DateAxis .
 pasting codepen url for reference: https://codepen.io/ErPratham/pen/vYwZwZZ
 
 if the data set is huge then the heatmap chart does not render prorperly. It entirely becomes white

**Comment by martynasma** [comment]
Well, you have white border added to each column. What happens when you cram 8K columns with 2px white outlines into a chart? That's right - the white border of each subsequent column covers the whole of the column next to it, rendering the whole chart white 😉

Just remove the outlines: `strokeOpacity: 0`.

**Comment by pratham3164** [comment]
@martynasma Thanks it's working, I was checking if there is something wrt to grouping

**Comment by pratham3164** [comment]
Hi, @martynasma,
Have one query with respect to the above shared codepen implmentation. If the data set is huge i dont get the tooltips for values on hover and neither the pinch drag to zoom  functionality seems to work. Any workaround on that ?

**Comment by martynasma** [comment]
If there's a lot of columns and they are very small, e.g. 1px or smaller, their outlines get anti-aliased breaking pixel-color-coding. I suggest using `XYCursor` both to snap tooltips to the nearest column and for zooming.
