### ISSUE TITLE
Line graph does not display correctly in Firefox

### ISSUE THREAD

**Issue by jegelstaff** [amcharts/amcharts5#1633]
**Bug description**

See this codepen: https://codepen.io/jegelstaff/pen/poXERvo

Works in Chrome, Edge. Does not work in Firefox on Windows. Does not work in Firefox on Android.

**Environment (if applicable)**

**Additional context**

I have opened a bug with Firefox, since it may be a browser issue? See: https://bugzilla.mozilla.org/show_bug.cgi?id=1909718

**Comment by zeroin** [comment]
It seems this happens because your rangeDataItem has such a high endValue that the object is bigger than firefox allows it to be.

If I delete one 0 from the end value, it works fine. If you don't know what is expected max of your value axis, then you could monitor max and set endValue to the max value:

```
        yAxis.onPrivate("max", (max)=>{
          rangeDataItem.set("endValue",max * 2)
        })    
```

**Comment by jegelstaff** [comment]
Excellent! This is a dynamically generated graph, so it would be extra work to figure out the max when generating the dataset, and the extra big value seemed to do the trick, until it was opened in Firefox. Thank you very much for the tip. I will adjust that and alert the Firefox folks. It still seems to be a bug on their end, since the other browsers are able to render this OK, but this really narrows things down.
