### ISSUE TITLE
when the pie chart slices are even like 50%, the pointer line got disappears.

### ISSUE THREAD

**Issue by ajithkumarseenivasan** [amcharts/amcharts5#1637]
Example code:

```JavaScript
var chartData: any = {
"1995": [
{ sector: "Agriculture", size: 6.6 },
{ sector: "Mining and Quarrying", size: 6.6 } ],
"1996": [
{ sector: "Agriculture", size: 6.4 },
{ sector: "Mining and Quarrying", size: 6.4 } ],
"1997": [
{ sector: "Agriculture", size: 6.1 },
{ sector: "Mining and Quarrying", size: 6.1 } ],
};
var root = am5.Root.new("chartdiv");

root.setThemes([
am5themes_Animated.new(root)
]);

var chart = root.container.children.push(am5percent.PieChart.new(root, {
innerRadius: 100,
layout: root.verticalLayout
}));

var series = chart.series.push(am5percent.PieSeries.new(root, {
valueField: "size",
categoryField: "sector"
}));

series.data.setAll([
{ sector: "Agriculture", size: 6.6 },
{ sector: "Mining and Quarrying", size: 6.6 }
]);

series.appear(1000, 100);

var label = root.tooltipContainer.children.push(am5.Label.new(root, {
x: am5.p50,
y: am5.p50,
centerX: am5.p50,
centerY: am5.p50,
fill: am5.color(0x000000),
fontSize: 50
}));


var currentYear = 1995;
function getCurrentData() {
var data = chartData[currentYear];
currentYear++;
if (currentYear > 2014)
currentYear = 1995;
return data;
}

function loop() {
label.set("text", currentYear.toString());
var data = getCurrentData();
for(var i = 0; i < data.length; i++) {
series.data.setIndex(i, data[i]);
}
chart.setTimeout( loop, 4000 );
}

loop();
```

<img width="1221" alt="image" src="https://github.com/user-attachments/assets/37f5ba46-2891-4973-935e-5b4bd442082b">

**Comment by martynasma** [comment]
Fixed in [5.10.1](https://github.com/amcharts/amcharts5/releases/tag/5.10.1).

## [5.10.1] - 2024-08-09

### Added
- `fillGradient` setting added to `Label`.

### Changed
- Exporting a PDF will now check image size and will not scale it up to fit page size if it's smaller. It will still scale dowwn the image to fit in the page.

### Fixed
- Memory leak with axis ranges on `LineSeries` fixed.
- `PieSeries` tick was not visible if pie had two equal slices.
- `root.nonce` was not being added to all dynamically-loaded stylesheets.
- A stack overflow could occur when auto-zooming a `ValueAxis` in some very rare cases.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
