### ISSUE TITLE
TreeMap - restrict ZoomableContainer bounds to visible rectangles

### ISSUE THREAD

**Issue by efitzkiwi** [amcharts/amcharts5#1641]
As can be seen, in one of the official demos, you can zoom and pan freely on the tree map:
https://www.amcharts.com/demos/multilevel-tree-map/

I believe it would be user-friendly if the view was restricted only to visible rectangles, AKA prevent the whitespace from showing.

For reference, as you can see on this Tree Map used by another site, it is unable to be panned when whitespace is about to appear.
https://finviz.com/map.ashx?

Any ideas very welcome, thank you for a great product.

**Comment by martynasma** [comment]
There's currently no way to do that.

I'm marking this as a enhancement request. We might consider implementing the feature in the future.

Thanks for the suggestion!

**Comment by martynasma** [comment]
Fixed in [5.10.2](https://github.com/amcharts/amcharts5/releases/tag/5.10.2).

## [5.10.2] - 2024-08-23

### Added
- `panSensitivity` added to `AxisRenderer` (default: `1`).
- `maxPanOut` added to `ZoomableContainer` (default: `0.4`).
- Method `addLine(tool, panel, point)` added `DrawingControl`. Allows adding line drawings via API. Supports (`"Horizontal Line"`, `"Horizontal Ray"`, `"Vertical Line"` tools). [More info](https://www.amcharts.com/docs/v5/charts/stock/toolbar/drawing-control/#Adding_line_drawings).

### Fixed
- Fast mouse wheel zooming of stock chart could cause browser to hang in some cases.
- `minBulletDistance` of a `XYSeries` was ignored when base axis was `CategoryAxis` and other axis was `DateAxis`.
- RTL labels with text-wrapping enabled were not being positioned properly.
- 
[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
