### ISSUE TITLE
adding connect : false results in the grouped series disappearing upon zooming.

### ISSUE THREAD

**Issue by d2Evil** [amcharts/amcharts5#1656]
**Bug description**

I'm trying to add two grouped series to the same chart. However, setting connect: false for one series causes that series to disappear when zooming in. The tooltips remain visible, but the line series vanishes.

![amcharts series](https://github.com/user-attachments/assets/cbc1c8dc-861a-49bf-b486-7e92ad25bf82)

CodePen : https://codepen.io/catto22/pen/WNqjWRm

**Comment by martynasma** [comment]
This is a correct behavior.

You have set your data granularity to 1 hour, whereas data comes at 4-hour intervals for the second series.

This means that when you zoom in significantly enough so that grouping is turned off, you now have data items at 4 hour intervals, whereas your "break" period is 1 hour, hence all data items have a break between them.

You can fix that by setting `autoGapCount: 4` for the second series:
https://www.amcharts.com/docs/v5/charts/xy-chart/series/line-series/#Auto_gaps_with_dates

**Comment by d2Evil** [comment]
Setting autoGapCount seems to fix the isssue. Thanks for the info.
