### ISSUE TITLE
Tooltip, Zoom functionalities are not working under shadow root in Amcharts5

### ISSUE THREAD

**Issue by DeepKarmakar** [amcharts/amcharts5#166]
I'm using Angular 12 with Amcharts 5 and I implemented the map in one of the component. Here I'm encapsulating the component by using `encapsulation: ViewEncapsulation.ShadowDom`, after that Map tooltip and zoom functionalities are not working. 

I have created angular stackblitz project and replicated the same. Here is the link
[](https://stackblitz.com/edit/angular-ivy-rapc2j?file=src%2Fapp%2Fapp.component.ts)

As this component is coming under shadow root so I changed the document selector method in Line 26 and commented out 23.

**Comment by Pauan** [comment]
I can reproduce this, I'm working on fixing it.

**Comment by martynasma** [comment]
Fixed in [5.0.20](https://github.com/amcharts/amcharts5/releases/tag/5.0.20).

## [5.0.20] - 2021-12-30

### Fixed
- `SliceGrouper` with `clickBehavior = "zoom"` was not zooming out properly.
- `GridLayout` could leave empty gaps if some of the items in it were hidden.
- dragging sprites within rotated containers was not working properly.
- Null value was breaking stacking of columns in some cases.
- Fixing tooltips being broken inside of shadow DOM. ([Issue 166](https://github.com/amcharts/amcharts5/issues/166))

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by DeepKarmakar** [comment]
Now It's working perfectly. Thank you so much.
