### ISSUE TITLE
minBulletDistance not working for a Gantt chart with CategoryAxis and DateAxis

### ISSUE THREAD

**Issue by xiandew** [amcharts/amcharts5#1671]
minBulletDistance does not work as expected for a Gantt chart with CategoryAxis as the y-axis and DateAxis as the x-axis.

It works when changing the DateAxis to ValueAxis, with the same data and the same settings.
 
Codepen: https://codepen.io/yagwanggaeguli/pen/gONXPZx?editors=0010

**Environment (if applicable)**
amCharts version: 5.10.0
react: 16.13.1

**Comment by xiandew** [comment]
I expected it to work vertically, which doesn't work currently I suppose?

In the codepen I provided, when I vertically zoom in/out the chart with a category axis and a date axis, the bullets won't show/hide  accordingly as it would with a category axis and a value axis.

**Comment by martynasma** [comment]
Yup. That's what I was wondering about.

Indeed, it does not work. Looking into it.

**Comment by martynasma** [comment]
Fixed in [5.10.2](https://github.com/amcharts/amcharts5/releases/tag/5.10.2).

## [5.10.2] - 2024-08-23

### Added
- `panSensitivity` added to `AxisRenderer` (default: `1`).
- `maxPanOut` added to `ZoomableContainer` (default: `0.4`).
- Method `addLine(tool, panel, point)` added `DrawingControl`. Allows adding line drawings via API. Supports (`"Line"`, `"Horizontal Line"`, `"Horizontal Ray"`, `"Vertical Line"` tools). [More info](https://www.amcharts.com/docs/v5/charts/stock/toolbar/drawing-control/#Adding_line_drawings).

### Fixed
- Fast mouse wheel zooming of stock chart could cause browser to hang in some cases.
- `minBulletDistance` of a `XYSeries` was ignored when base axis was `CategoryAxis` and other axis was `DateAxis`.
- RTL labels with text-wrapping enabled were not being positioned properly.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
