### ISSUE TITLE
Enhancement : Drawing should get extend on lazy loading.

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1674]
Like Stock Indicators, drawings should also extend when we load more data via lazy loading.

- So if I draw a horizontal ray, and then load more it the line doesn't extend/apply to the new data. It remains on the old data only.
- See in the below image, horizontal line cover the full width. But in the below it doesn't because I have loaded more data points after drawing the line.
![image](https://github.com/user-attachments/assets/04086e18-da88-4b3a-92fb-f15de1c7ece7)

codepen to test and try it is an **official** link: https://codepen.io/team/amcharts/pen/ZENawbv
- Draw horizontal line first.
- Then scroll/load more data. The line doesn't extends. Ideally it should.

**Comment by martynasma** [comment]
Fixed in [5.10.2](https://github.com/amcharts/amcharts5/releases/tag/5.10.2).

## [5.10.2] - 2024-08-23

### Added
- `panSensitivity` added to `AxisRenderer` (default: `1`).
- `maxPanOut` added to `ZoomableContainer` (default: `0.4`).
- Method `addLine(tool, panel, point)` added `DrawingControl`. Allows adding line drawings via API. Supports (`"Line"`, `"Horizontal Line"`, `"Horizontal Ray"`, `"Vertical Line"` tools). [More info](https://www.amcharts.com/docs/v5/charts/stock/toolbar/drawing-control/#Adding_line_drawings).

### Fixed
- Fast mouse wheel zooming of stock chart could cause browser to hang in some cases.
- `minBulletDistance` of a `XYSeries` was ignored when base axis was `CategoryAxis` and other axis was `DateAxis`.
- RTL labels with text-wrapping enabled were not being positioned properly.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by workingbuddy10** [comment]
@martynasma  The Lazy loading codepen is not working in the new update!

**Comment by martynasma** [comment]
It is working for me. Can you explain what is not working for you?

**Comment by workingbuddy10** [comment]
It is not scrolling only @martynasma

**Comment by workingbuddy10** [comment]
Creating the bug in your  repo 😄 
@martynasma 

Is it possible to fix this today? Like then only I'll update the version.
