### ISSUE TITLE
Chart gets stuck when hovered on the indicator lines

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1678]
When I try to scroll on the chart, and the cursor is pointed on the line of the indicators. Then scroll doesn't works. While if I scroll on the empty space of the chart then it works fine.
 - So neither you can scroll nor you can pan when pointed on the indicator lines.

https://github.com/user-attachments/assets/e37c0f73-20f2-4af2-ae75-451a9b3b89d4

I have also added this in my theme :
```
      this.rule("Graphics", ["series", "fill", "drawing"]).setAll({
        forceInactive: true,
      });
```
you can test it here, try applying Bollinger band indicator  & place the cursor on the lines of the bollinger band then scroll : 
Try it after increasing the width/stroke of the indicator lines it will be easy to catch it.
https://codepen.io/Ansh-m-the-reactor/pen/ZEPrbrb?editors=0010

Note : Its not limited to the Bollinger band indicator.

**Comment by workingbuddy10** [comment]
True @martynasma , I know removing `interactive: true` solves in codepen. But it isn't working in the local machine.

**Comment by martynasma** [comment]
You know the drill: we need a way to reproduce it.

**Comment by workingbuddy10** [comment]
Got the imposter @martynasma ,  😵 
One of the stock chart event is causing the issue. 
You can checkout the same codepen, I have added this event you can see again the same problem came.
```
    stockChart.events.on("middleclick", () => {
       console.log("h")
    })
```

But I want this event.

**Comment by workingbuddy10** [comment]
Okay @martynasma !!
So mainly I am doing some operations in the below events only.
And let's say when the user used the middle click of the mouse anywhere in the whole chart (in my case its stockchart) only I want to print a hello world. 
currenlty I am doing this, what should I replace with as` panel.plotContainer.events `is not present :
```
   stockChart.events.on("middleclick", () => {
       console.log("hello world")
    })
```

These are the events I am using :

 ```
stockChart.events.on("drawingadded", () =>{
      console.log("h1")
    });
    stockChart.events.on("drawingremoved", () => {
       console.log("h2")
    })
    stockChart.events.on("indicatorsupdated", () => {
       console.log("h3")
    })
    stockChart.events.on("middleclick", () => {
       console.log("h4")
    })
```

**Comment by martynasma** [comment]
```JavaScript
document.getElementById("chartdiv").addEventListener('contextmenu', (event) => {
  event.preventDefault()
  // do your stuff
})
```

**Comment by workingbuddy10** [comment]
I got your point @martynasma , this would be the best practice!! Thanks for these suggestions 🙌  !!

But on the contrary side, just asking then why these events like ( [middleclick](https://www.amcharts.com/docs/v5/reference/sprite/#middleclick_event:~:text=%23-,middleclick,-Param) ) given in the doc to use on the stockChart ?
I was using this middle click event to zoom-in to the recent 50 points (as a reset initial view).

**Comment by martynasma** [comment]
It's due to how amCharts 5 interactivity works.

When you make some element interactive, everything in it (its sub-elements) become interactive, too).

This is why setting interactivity to a high level element like chart which literally holds all of the elements (hundreds if not thousands of those) is a no-go.

It's not only highly inefficient (because hit point registration canvas has to draw all the elements of the chart), but also may create anomalies like the one you found.

This particular one is because of how antialiasing works in canvas. When you make that indicator line interactive (by making all of the chart interactive), the line which normally would be ignored, gets drawn in hit canvas, and its antialiasing gets in the way of properly detecting pixel color.

I hope that makes sense.

**Comment by workingbuddy10** [comment]
Ohh genius @martynasma !! A very precise info!
