### ISSUE TITLE
Drawing is not getting extended on Lazy Loading in the new version [5.10.3]

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1684]
Using the same provided example of amcharts, it though extends till a certain point after that it breaks.

https://github.com/user-attachments/assets/11c0d878-60ab-41fe-8a1a-7dae399da339

https://codepen.io/Ansh-m-the-reactor/pen/wvLXWpm?editors=0010

**Comment by workingbuddy10** [comment]
@martynasma any issue found in this?
And does changing the multiplication number ( i.e more than 10) can fix the problem?
https://github.com/amcharts/amcharts5/blob/79ac14203e4e1ebaef455b57ab1d14f6edad5be3/src/.internal/charts/stock/drawing/HorizontalLineSeries.ts#L58

**Comment by martynasma** [comment]
Fixed in [5.10.4](https://github.com/amcharts/amcharts5/releases/tag/5.10.4).

## [5.10.4] - 2024-08-30

### Changed
- Multiple clicks (or ENTER presses when focused) on an `showTooltipOn: "click"` elements will toggle tooltip, rather than keep it open.

### Fixed
- Accessibility: A focusable element would display tooltip only once on ENTER press with NVDA reader.
- `"Horizontal Line"` and `"Horizontal Ray"` lines are now allow for longer overzoom / X-axis scope.
- Candles on a `GaplessDateAxis` could some time become too wide.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
