### ISSUE TITLE
A tooltip bug was found in the mobile environment.

### ISSUE THREAD

**Issue by skulter** [amcharts/amcharts5#169]
that bug is
Also available at https://www.amcharts.com/demos/data-grouping-50k-points/

After accessing the address in the mobile environment
After zooming in by dragging the chart, click the '-' button to view the entire chart again.
Clicking on another area reproduces the tooltip not displaying properly and out of focus.

I want to upload a video file, but I don't know how to deliver it, so I left it as text.

Please check the bug.

**Comment by martynasma** [comment]
Fixed in [5.0.19](https://github.com/amcharts/amcharts5/releases/tag/5.0.19).

## [5.0.19] - 2021-12-27

### Added
- `groupDataDisabled` setting added to XYSeries. If set to `false` will exclude series from data grouping mechanism, even if it is enabled on related `DateSeries`.
- New plugin `SliceGrouper`. Can be used to automatically group small slices on percent charts like Pie, Funnel, etc. [More info](https://www.amcharts.com/docs/v5/charts/percent-charts/grouping-slices/).

### Fixed
- If data was added to percent series after initial data was already processed, the bew slices would get colors from the start of the color set.
- Multiple square bracket and apostrophe escaping was not working properly.
- A JS error could occur when changing `XYSeries` data with less data items then there were before.
- `PieSeries` were not arranging its labels properly in some cases.
- `XYCursor` taps were not working properly after chart zoom on touch devices.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
