### ISSUE TITLE
Erase the rounded ends of the shapes after drawing.

### ISSUE THREAD

**Issue by tranmanhhungdn1201** [amcharts/amcharts5#1691]
![image](https://github.com/user-attachments/assets/ab69d967-1bf0-4ef2-9539-32c2ede2ec13)

I would like the red circle button to remain hidden by default. It should only become visible when the drawing is initiated by clicking on it. How can I achieve this using your code?

Thank you

**Comment by zeroin** [comment]
You have to loop through all the series, check if series is a drawing and then hide or show bulletsContainer:

```
  stockChart.panels.each((panel) => {
    panel.series.each((series) => {
      if (series.isType("DrawingSeries")) {
        series.bulletsContainer.set("forceHidden", true);
      }
    })
  })
```

**Comment by workingbuddy10** [comment]
@zeroin I don't think this work properly as it will also remove the label. Correct me please if I wrong!
Though it removes the bullets, but it will also remove the labels.

https://github.com/user-attachments/assets/3d9dd9bf-5c4e-48d4-bbc5-54dc9c2b21de

Is there anything, like it ignores the labels ore labels won't get removed because of this.
