### ISSUE TITLE
Bug Drawing Label don't appear letters

### ISSUE THREAD

**Issue by shishima123** [amcharts/amcharts5#1701]
I found that when I type text using the Label tool, the letters don't appear while drawing
It only appears when focus is out

https://github.com/user-attachments/assets/09a8e2de-85ab-46f5-8496-159aa0d9058f

**Comment by martynasma** [comment]
Fixed in [5.10.5](https://github.com/amcharts/amcharts5/releases/tag/5.10.5).

## [5.10.5] - 2024-09-06

### Added
- `scrollToChild()` method added to `Container`. Scrolls the container to the target child element if the container is scrollable and the element is currently outside of view.
- New `StockChart` drawing tool added: "Line Arrow".

### Changed
- When a selected drawing in a `StockChart` is inselected by clicking on a chart's plot area the new drawing will not be added anymore.

### Fixed
- Keyboard-dragging of focusable elements was not working correctly in some cases.
- Sometimes label/callout drawing text was cut temporarily while editing them on `StockChart`.
- Editable labels/callouts would go into edit mode when unserialized.
- If auto-saving of drawings was enabled, editing text would not always save the latest version of the label/callout text.
- Dragging a `StockChart` drawing while other drawing was selected, would drag the selected drawing as well.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
