### ISSUE TITLE
Duplicated chart data when remove a series range using series.axisRanges.removeValue(range)

### ISSUE THREAD

**Issue by gsi-chao** [amcharts/amcharts5#172]
I try to eliminate ranges attached to a series using amcharts 5, but in the chart the data is duplicated, I am using the function series.axisRanges.removeValue (range);

`
var rangeDataItem = xAxis.makeDataItem({ value: value, endValue: endValue, }) var range = lineSerie.value.createAxisRange(rangeDataItem)
`

Enviroment
VueJS 3
Amchart 5

![image](https://user-images.githubusercontent.com/32143683/147290628-d60d2f0d-930d-4a96-957e-e4c1db3f9a73.png)

**Comment by martynasma** [comment]
Which version of amCharts 5 are you using? We have fixed removal of axis ranges in 5.0.14. If you are using older version, you might want to try upgrading.

If that still persist, maybe you could post your chart code and data on CodePen or jsFiddle so that we can test?

**Comment by martynasma** [comment]
Thanks. This is weird. We're having trouble reproducing it outside of Vue:
https://codepen.io/team/amcharts/pen/f783d0ccac5974aa1933b39a5a8410f7?editors=0010

Besides, you're not creating actual ranges. You're just creating a data item, which should not do anything.

Is there perhaps some "hidden" code that I can't see? :)

**Comment by gsi-chao** [comment]
I updated the example and create the range, but the same issue continues.
Maybe this only happens in VUE?
Any idea how to fix it?

I am attaching a video with the behavior in my project, as you can see the range is being created but the charts are being duplicated.
https://nimb.ws/SqHZVD

**Comment by Pauan** [comment]
@gsi-chao You're returning the amCharts objects from the `setup` method, like this:

```js
    return {
      chartRoot,
      xChart,
      xRoot,
      xSeries,
      xAxisX,
      generateRamdomRange
    };
```

That won't work, it will cause all sorts of problems because Vue does special things with the `data`. So try removing those:

```js
    return {
      generateRamdomRange
    };
```

**Comment by gsi-chao** [comment]
Hello @Pauan 
The elements that I am returning are Ref of Vue, this should not generate any kind of problems.
I remove these elements from the return and it keeps giving the same problem.

**Comment by robheymann** [comment]
Hi, I think I am having the same issue. I keep an array of ranges, which I then loop through to clean up each time the data changes, using xAxis.axisRanges.removeValue and it just duplicates the items. Screengrab attached.

Vue3.2.26
amcharts5: 5.0.21

![image](https://user-images.githubusercontent.com/4670309/149297767-2e79bc24-f986-447f-841a-c9a46a3eb2fc.png)

**Comment by sassomedia** [comment]
Not sure about the Vue issue but why not re-render the component with new data/ranges? This was a bit of a concern with am4 since there could potentially be hundreds or thousands of chart DOM nodes and that could cause a lot of thrashing when re-rendering the chart. - With am5 however, it's a just few canvas elements and the performance is really fast.

**Comment by robheymann** [comment]
So I tried to dispose of the initial chart ('root' element) when the data changes, and then on the nextTick recreate it, but it throws Uncaught Error: You cannot have multiple Roots on the same DOM node. 

` if (this.rootChart) {
          this.rootChart.dispose()
          this.rootChart = null
        }

        this.$nextTick(() => {
          this.renderChart()
        })`

In RenderChart function, I set rootChart from this....

`const root = am5.Root.new('chartdiv')
this.rootChart = root
`

Any ideas why this might be happening? I suppose first prize is to fix the problem as stated in the OP

**Comment by gsi-chao** [comment]
Hi, @robheymann
I tried to do the same removing the root and got the same error, my temporary solution was to re-render the component using the v-if directive.

**Comment by robheymann** [comment]
@gsi-chao Thanks very much, I implemented something similar with a few chained NextTicks and a v-if on the element, that seems to have worked as a temp solution.

**Comment by Pauan** [comment]
@gsi-chao We are looking into this issue, it seems to be some sort of bug with the interaction of Vue and amCharts.

----

> @sassomedia I initially got the "multiple Roots" warning when I just disposed the chart but once I added chart.root.dispose(), I have not had the issue since.

That is correct, [you must dispose the Root](https://www.amcharts.com/docs/v5/getting-started/root-element/#Disposing), not the chart. Unlike in V4, you can have multiple charts per Root, so the Root is the top-most element.

**Comment by Pauan** [comment]
@gsi-chao After doing a lot of investigation, I found that using `ref` *at all* causes issues. This is because `ref` internally calls [`reactive`](https://v3.vuejs.org/api/basic-reactivity.html#reactive), which screws things up because it replaces the amCharts object with a Proxy.

This is not a bug in either amCharts or Vue. The problem is that `ref` expects the value to be a simple data object, but you are passing it a complex class.

So the solution is to not store the amCharts objects inside of `ref`:

https://codepen.io/team/amcharts/pen/a2917a590f131ef9969f07d7bb62169e

Alternatively, you can use [`shallowRef`](https://v3.vuejs.org/api/refs-api.html#shallowref), which does *not* use `reactive`, so the amCharts objects are not replaced with a Proxy:

https://codepen.io/team/amcharts/pen/e72f0ad7e97930e75195e4539c1931ea

**Comment by martynasma** [comment]
FYI, our [Vue.js tutorial](https://www.amcharts.com/docs/v5/getting-started/integrations/vue/) was updated as per above @Pauan findings.

**Comment by gsi-chao** [comment]
Thank you very much @Pauan  and @martynasma
