### ISSUE TITLE
[Request] Modify amCharts XYChart to Allow Page Scrolling When Inner Scroll Reaches Limit

### ISSUE THREAD

**Issue by denniscalazans** [amcharts/amcharts5#1776]
#### Description
Currently, the amCharts XYChart does not allow the page to continue scrolling when the inner scroll reaches its limit. 
I'm not sure if that is a bug or a feature.

The desired behavior is to ensure that the page continues scrolling when the inner scroll of the XYChart reaches its limit.
Would that be possible?

#### Steps to Reproduce
0. Create page which document generates a scroll bar, for example 3000px tall
1. Create an XYChart with horizontal and-or vertical scrollbars.
2. Scroll the chart to its limit using the mouse wheel.
3. Observe that the page does not continue scrolling when the inner scroll reaches its limit.

#### Relevant Code
The relevant code can be found in `src/.internal/charts/xy/XYChart.ts`, specifically lines 626-701. 
The `handleWheel` method needs to be modified to detect when the inner scroll is over and allow the page to continue scrolling.

#### Additional Context
To detect when the inner scroll is over, the `rangechanged` event of the `Scrollbar` can be used. 
This event is triggered whenever the scroll range changes. 
The `start` and `end` properties of the `Scrollbar` can be checked to determine if the scroll is at the beginning or end of the range. 
Implement logic to handle the scroll behavior when the inner scroll is over.

I believe that the following lines should be run conditionally
https://github.com/amcharts/amcharts5/blob/c32fbe30eff51b7f0174b11e70bbfc89ba3eec40/src/.internal/charts/xy/XYChart.ts#L510-L517

Perhaps they should only be applied in those situations:
https://github.com/amcharts/amcharts5/blob/c32fbe30eff51b7f0174b11e70bbfc89ba3eec40/src/.internal/charts/xy/XYChart.ts#L577-L700

But I'm not sure if that's the right way to do it.

> "@amcharts/amcharts5-fonts": "^5.0.1",
> Chrome - Version 130.0.6723.70 (Official Build) (arm64)

### Considerations

[Control + scroll](https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Control_scroll) is not what is needed. 

Listening for "wheel" events on xyChart.plotContainer is possible, 
Checking if the inner scroll has reached its limit can be done. 

However, setting "wheelX" back to "none" does not resolve the issue of the event trap.

**Comment by denniscalazans** [comment]
I opened a Draft PR pointing to where I believe the improvement could be done.  
[https://github.dev/amcharts/amcharts5/pull/1775/](https://github.dev/amcharts/amcharts5/pull/1775/files)

**Comment by martynasma** [comment]
Implemented in [5.10.8](https://github.com/amcharts/amcharts5/releases/tag/5.10.8).

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

## [5.10.8] - 2024-11-21

### Added
- New setting `lineCap` (default `"butt"`) added to `Graphics`. Allows specifying how line ends should be drawn. Possible values: `"butt"` (default), `"round"`, `"square"`.
- New setting `clickAnnounceText` added to `Sprite`. If set will announce the text when focused element is triggered with a press of ENTER or SPACE.

### Changed
- Pressing Shift-TAB while focus on non-first member of the focusabel group will now jump to a previous group or focusable element, rather than current group's first element.
- When an `XYChart` is zoomed using mouse wheel it will no longer stop page scroll when its fully zoomed out or zoomed in.

### Fixed
- HTML content was ignoring `dx`/`dy` position adjustment settings.
- Pressing the UP key was being ignored when navigating within a group of focusable objects.
- Last label of `GaplessDateAxis` was in wrong position when `baseInterval` was set to week and `minorGrid` was enabled.
- Setting data item's value to `null` (if previous was a valid number) did not remove the column of a `ColumnSeries`.
- The `maxWidth`/`maxHeight` recaculation of vertical labels was not correctly factoring in its padding.

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
