### ISSUE TITLE
Could not add stacked property to series due to TypeError(stacked area)

### ISSUE THREAD

**Issue by roszczypalam** [amcharts/amcharts5#178]
I would like to create chart based on this demo : https://www.amcharts.com/demos/stacked-area/ but when I add stacked property to series data it gives me error. 

Could someone help me with that ? Is something that I've missed from docs ? Are any specific conditions to be met to create such chart ? 

Here is jsfiddle example to reproduce issue (uncomment stacked: true to reproduce error) -> https://jsfiddle.net/2ue3k7co/1
<img width="541" alt="Screenshot 2021-12-29 at 15 29 52" src="https://user-images.githubusercontent.com/23001448/147673357-c07ad627-e154-46f5-8038-4575711b068a.png">
/

**Comment by martynasma** [comment]
We'll fix the error in the next version.

However, the stacking won't still work with data like that. I'm not entirely sure what would the end result you'd expect, but LineSeries needs to have equal number of data items to be stacked properly.

**Comment by martynasma** [comment]
Fixed in [5.0.20](https://github.com/amcharts/amcharts5/releases/tag/5.0.20).

## [5.0.20] - 2021-12-30

### Fixed
- `SliceGrouper` with `clickBehavior = "zoom"` was not zooming out properly.
- `GridLayout` could leave empty gaps if some of the items in it were hidden.
- dragging sprites within rotated containers was not working properly.
- Null value was breaking stacking of columns in some cases.
- Fixing tooltips being broken inside of shadow DOM. ([Issue 166](https://github.com/amcharts/amcharts5/issues/166))

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
