### ISSUE TITLE
Custom timezone request

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts5#180]
[https://www.amcharts.com/docs/v5/concepts/formatters/formatting-dates/](https://www.amcharts.com/docs/v5/concepts/formatters/formatting-dates/)

"amCharts 5 at this moment does not support setting custom time zones. This functionality might be introduced in the future."

Would like to request this feature be added to version 5 same as it was for version 4.  In my case I use this feature in virtually all my date/time charts.  I store date/time on my end as unix timestamps and prefer to display that data in the charts in specific timezones - not always the timezone of the device viewing the charts.  I could manipulate my timestamps/data going into the charts, but it was really convenient just setting `chart.dateFormatter.timezone = custom_timezone` in the chart code.

**Comment by morrow95** [comment]
Just wanted to share a 'workaround' that I was able to do for now for anyone that might be in the same situation with the new version 5.

I store date/time as unix timestamps in our database then convert them to whatever timezone I want to display them as.  In version 4 I was able to set the timezone in the dateformatter and the chart would show everything correctly in whatever timezone I wanted.  With version 5 you can no longer do this... the chart shows in the device timezone that is viewing the chart OR you have an option to show in UTC through a setting.

Here is an example of my workaround : 

You need to set your chart to use UTC with `chart.utc = true;`.

**1642050813** - unix timestamp from my database

**01/12/2022 9:13:33 PM** - This is the above timestamp converted to readable format in the 'America/Los_Angeles' timezone (you could use any timezone you want), but it is important the string does not include any timezone information in it - you just want the date and time.

**01/12/2022 9:13:33 PM +00:00** - I use the string above to create a new date/time (same date/time) just in UTC timezone.

**1642022013000** - I use the above to get a new timestamp to pass to the chart.  This timestamp is 01/12/2022 9:13:33 PM in UTC now.

The short version is I get the string of the date/time only in the timezone I want... then create a new timestamp with the same date/time just in UTC that the chart it set to use.  As long as I do not display any timezone information in my chart it will correctly show the date/time in whatever timezone I want.  In reality they are two totally different timestamps, but visually it is the correct date/time in whatever timezone I want.

This would need to be done for every timestamp you use in the chart.  With that said, it was MUCH easier just setting `chart.dateFormatter.timezone = 'America/Los_Angeles';` in version 4 to handle this.  It also allowed you to display the correct timezone when formatting timestamps like in your tooltips.  In this workaround you cannot do this as the chart is technically displaying everything in UTC - you are just translating the date/time from the timezone you want to same in UTC (which is really two totally different times).

For all of the date/time manipulation/calculation I used moment.js.  Pain in the butt to do it this way, but only way to display different timezones right now in version 5 that I can think of.

**Comment by martynasma** [comment]
Heads up, we're working on a built-in timezone solution. Will let you know here when it's out, and will also provide further info.

**Comment by morrow95** [comment]
@martynasma Fantastic!  I'll keep an eye out.

**Comment by martynasma** [comment]
Implemented in [5.1.0](https://github.com/amcharts/amcharts5/releases/tag/5.1.0).

## [5.1.0] - 2022-01-20

### Added
- New `Root` setting: `timezone`. E.g. `"America/Vancouver"`, `"Australia/Sydney"`, `"UTC"`.
- New export CSV option: `addBOM` (default: `true`). Indicates whether to add BOM characters at start of CSV output so that data viewer (e.g. Excel) knows we're exporting UTF-8 data.
- New methods for `Adapters`: `remove(key)`, `disable(key)`, and `enable(key)`.
- `GaplessDateAxis` added. It's a version of `DateAxis` that removes data-less intervals from its scale. `CategoryAxis` is being deprecated in favor of `GaplessDateAxis`. [More info](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/gapless-date-axis/).
- Timezone support added. [More info](https://www.amcharts.com/docs/v5/getting-started/root-element/#Time_zone).
- New `Component` method: `markDirtyValues()`. Will re-evaluate elements of the component that are data-reliant, such as axis labels.

### Fixed
- Clearing axis ranges from Axis and Series was not working properly.
- Slice with negative arc was ignoring `cornerRadius` property.
- `groupDataDisabled` on `XYSeries` was not working if set to `true`.
- Axis header was not updating its position if axes were stacked and size of an axis was updated.
- Disposing of charts with a lot of elements was quite slow.
- Series stacks with all-zero values could cause all stacks to disappear on zoom.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
