### ISSUE TITLE
Date axis grid scaling with non-English browser locale

### ISSUE THREAD

**Issue by phlundblom** [amcharts/amcharts5#1803]
I finally sat dawn and tried to understand a bug that has troubled us for quite some time. It seems like the automagic grid scaling on a DateAxis fails when resizing the canvas. This results in grid being calculated too tight and overlapping X axis labels.

The above happens when Amcharts jumps from the internally defined interval `{ timeUnit: "day", count: 5 }` to `{ timeUnit: "week", count: 1 }`. My understanding is that this is due to some hardcoded weekdays in `core/util/Timezone.js:34`. These weekdays are localized and don't match up when using a non-English browser.

![Screenshot from 2024-12-11 14-59-24](https://github.com/user-attachments/assets/01af09bc-249e-48f0-b859-3283d4181a3f)

![Screenshot from 2024-12-11 14-59-35](https://github.com/user-attachments/assets/fe5faccc-fd08-4433-9e40-4a894d09d04f)

The problem can be replicated in this Codepen: https://codepen.io/phlundblom/pen/QwLKyXp

Just adjust the width of the window to get grid lines every 5 days, then shrink it a little bit more and the internal calculations goes havoc.

(My interpretion is that the one-day gridlines are caused by the fact that `startDayOfWeek` is defaulted to 1 for timezones missing this property, and the weekday output from `parseDate()` is 0).

**Comment by martynasma** [comment]
I can't seem to be able to reproduce this on my "non-English" locale browser.

Is there something that needs to be added to CodePen to reproduce it?

When you mean "non-English browser" do you mean OS locale? Which particular locale are you using?

**Comment by phlundblom** [comment]
I'm using Swedish locale, for normal users this comes from the OS (Windoze in most cases) but the problem can be reproduced in Firefox on Linux with `LC_ALL=sv_SE firefox -no-remote`. This implies a Swedish locale for the browser is installed (menus/UI in Swedish).

In such case, the weekdays in the referred `Timezone.js` are localized (e.g. `Sun` is `sön` and so on). Based on this I assume the problem is the same for all browser locales having deviating weekday names.

**Comment by martynasma** [comment]
Thanks for the details.

A few notes for the team:

1) This can be reproduced by switching browser language to Swedish in both Chrome and Firefox via Settings > Language.
2) It only occurs when timezone is set on `Root` element.

**Comment by martynasma** [comment]
Fixed in [5.10.9](https://github.com/amcharts/amcharts5/releases/tag/5.10.9).

## [5.10.9] - 2024-12-20

### Added
- Added way to determine if text label was autotruncated (`label.text._display.trunacted`).
- Heikin Ashi indicator added to `StockChart`.

### Changed
- The following settings will carry over to `Label`'s HTML content if set: `fontFamily`, `fontSize`, `fontStyle`, `fontWeight`, `fontStyle`, `fontVariant`, `textDecoration`.
- When an `MapChart` is zoomed using mouse wheel it will no longer stop page scroll when its fully zoomed out.
- When arranging tooltips on an `XYChart`, will now pay attention to `tooltipContainerBounds.bottom` setting.

### Fixed
- `ZoomableContainer` was not zooming out properly if `minZoomLevel` was `< 1`.
- `PicturePattern` was ignoring `colorOpacity` setting.
- `PicturePattern` with `fit: "pattern"` set would sometimes not show actual image.
- "Measure" drawing tool of `StockChart` was not including one volume bar value.
- If a timezone was set on a chart and browser's locale was set to some non-English language, weekly grid was shown incorrecly on a `DateAxis`.
- Changing `text` on a `Label` with `oversizedBehavior="fit"` would sometimes not revert to original scale even if the new text would fit into max width.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
