### ISSUE TITLE
"animate()" needs default value

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts5#181]
I was refactoring my chart and all of a sudden saw weird behavior when testing it again. Some animation wasn't properly working anymore and whenever that animation executed, the processor went all haywire. Seemed to run in some kind of endless loop and used 150% CPU. 

After some troubleshooting, found that it was related to the `.animate` API. If no `duration` is passed in the `AnimationOptions`, it goes crazy. Adding a default value there would prevent such bugs.
https://github.com/amcharts/amcharts5/blob/e9e325270a37ea070e562ce6d6075f8679f0f591/src/.internal/core/util/Entity.ts#L752-L764

**Comment by Pauan** [comment]
Thanks for the report! We fixed this and it will be in the next release.

However, if the animation has no duration then it will behave the same as `set`. If you use TypeScript it will give you an error if you forget to use duration.

**Comment by sassomedia** [comment]
Fair enough, TypeScript would indeed help. Unfortunately, I'm not using that in my project at the moment. But yes, that makes sense that when there is no duration that it would use `set`. Works for me. 👍

**Comment by martynasma** [comment]
Fixed in [5.0.21](https://github.com/amcharts/amcharts5/releases/tag/5.0.21).

## [5.0.21] - 2022-01-11

### Added
- New `Sprite` setting: `forceInactive`. If set to `true`, it will override `interactive` setting as well as ignore any interaction events set on the element.
- `cursorhidden` event added to `XYCursor`. Dispatched when user rolls-out of the chart plot area and cursor is hidden.
- New `Component` method: `markDirtyValues()`. Forces a repaint of the element which relies on data.

### Changed
- Value (4th parameter of the Heat rule's `customFunction`) will now receive actual value of the target data item, not interpolated calculated setting value.

### Fixed
- Fixing bug when not passing the duration to the `animate` method ([Issue 181](https://github.com/amcharts/amcharts5/issues/181)).
- Horizontal and vertical layouts with `width`/`height` set in percents plus `minWidth`/`minHeight`/`maxWidth`/`maxHeight` set were arranging items incorrectly.
- Very small slices with `cornrerRadius > 0` were being drawn as a full circle.
- `SliceGrouper` with was not zooming out properly if there was no legend in chart.
- changing `groupData` from `false` to `true` on DateAxis was not working when doing so after the chart was built.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
