### ISSUE TITLE
Donut with center label - label becomes too small 

### ISSUE THREAD

**Issue by ArunPragadeeswar007** [amcharts/amcharts5#1812]
**Bug description**

I have created a half-donut chart and planned to have a center label with a count. When the pointer hovers over or moves out, the label becomes too small. If the shape changes to a rectangular one, and sometimes when there's a glitch or the slices shake, the center label also becomes too small.

Example : https://codepen.io/Arunpragadeeswar/pen/QwLpJjp?editors=0110

![donut-with-center-label](https://github.com/user-attachments/assets/ce45d4c8-e7a7-42b1-a828-246360e0df79)

**Environment (if applicable)**
 - amCharts version : 5
 - Browser and its version : chrome
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.] : Ember Js 

**Additional context**
 
I suspect that a computation might be causing this issue. The glitch is not reproducible in the attached GIF, but it appears in cases with size constraints and `overflow: hidden`

**Comment by martynasma** [comment]
Fixed in [5.10.9](https://github.com/amcharts/amcharts5/releases/tag/5.10.9).

## [5.10.9] - 2024-12-20

### Added
- Added way to determine if text label was autotruncated (`label.text._display.trunacted`).
- Heikin Ashi indicator added to `StockChart`.

### Changed
- The following settings will carry over to `Label`'s HTML content if set: `fontFamily`, `fontSize`, `fontStyle`, `fontWeight`, `fontStyle`, `fontVariant`, `textDecoration`.
- When an `MapChart` is zoomed using mouse wheel it will no longer stop page scroll when its fully zoomed out.
- When arranging tooltips on an `XYChart`, will now pay attention to `tooltipContainerBounds.bottom` setting.

### Fixed
- `ZoomableContainer` was not zooming out properly if `minZoomLevel` was `< 1`.
- `PicturePattern` was ignoring `colorOpacity` setting.
- `PicturePattern` with `fit: "pattern"` set would sometimes not show actual image.
- "Measure" drawing tool of `StockChart` was not including one volume bar value.
- If a timezone was set on a chart and browser's locale was set to some non-English language, weekly grid was shown incorrecly on a `DateAxis`.
- Changing `text` on a `Label` with `oversizedBehavior="fit"` would sometimes not revert to original scale even if the new text would fit into max width.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
