### ISSUE TITLE
Using templateField within SmoothedXLineSeries disables smoothing

### ISSUE THREAD

**Issue by sisao** [amcharts/amcharts5#182]
Is this a known behavior?

See example:

comment line 89 "templateField: 'foo'" re enables smoothing.

https://codepen.io/sisao/pen/bGoMvmz

**Comment by martynasma** [comment]
That is an expected behavior.

Smoothing algorithm relies on multiple data points, whereas each appearance of a `templateField` in data starts a new segment.

So essentially, your series consists of 2-point segments. Smoothing algo can't derive an actual curve out of two points, hence it consisting of straight lines.

If you need to apply different styling to sections of your smoothed line series, I suggest to consider using axis ranges instead:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/
