### ISSUE TITLE
Container minWidth/minHeight ignored when scaling

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts5#183]
If I specify `minWidth` on a container, I would expect the width of the container not to shrink beyond the `minWidth` value when the container size changes.

In this simplified example [here](https://codepen.io/sassomedia/pen/rNGvoKz?editors=0010), there is a top red and a yellow bar (container). The red bar has `minWidth` set to 200px, which is what the blue line above it visually represents since the bar is currently larger than the `minWidth`. Now, the green panel to the right can be toggled to expand its size, which simultaneously shrinks the chart. This naturally causes the red and yellow bars to shrink as well. However, the red bar shrinks below the length of the blue line, i.e. `minWidth`. Is this a bug or could this be achieved differently?

<img width="1427" alt="Screen Shot 2022-01-05 at 3 07 00 AM" src="https://user-images.githubusercontent.com/5614099/148104281-32f8fb61-1254-41f7-96fe-3aed35a0d3df.png">
<img width="1423" alt="Screen Shot 2022-01-05 at 3 08 14 AM" src="https://user-images.githubusercontent.com/5614099/148104300-e413dabf-0ab3-4df1-a4be-652826a3db9c.png">

**Comment by zeroin** [comment]
It's not exactly like that - the width of red rectangle is correct, but the yellow one is on top of it, so it covers some part of it. Based on your setup it's all correct. I've tried to achieve the desired thing with horizontal layout but I get a the same issue with current version, but I think I found a way to solve it and it should be fixed in next release.

**Comment by sassomedia** [comment]
Interesting, that indeed seems to be happening. Tried with both items on the same `layer` but it still keeps the graphics on different stacks. There's possibly `toFront()` or `toBack()`, although in my project, I deal with this on all four corners and minWidth could be happen randomly on any corner, so this would make it a bit difficult to apply these methods. If you found another solution, that's even better! 👍

**Comment by martynasma** [comment]
Fixed in [5.0.21](https://github.com/amcharts/amcharts5/releases/tag/5.0.21).

## [5.0.21] - 2022-01-11

### Added
- New `Sprite` setting: `forceInactive`. If set to `true`, it will override `interactive` setting as well as ignore any interaction events set on the element.
- `cursorhidden` event added to `XYCursor`. Dispatched when user rolls-out of the chart plot area and cursor is hidden.
- New `Component` method: `markDirtyValues()`. Forces a repaint of the element which relies on data.

### Changed
- Value (4th parameter of the Heat rule's `customFunction`) will now receive actual value of the target data item, not interpolated calculated setting value.

### Fixed
- Fixing bug when not passing the duration to the `animate` method ([Issue 181](https://github.com/amcharts/amcharts5/issues/181)).
- Horizontal and vertical layouts with `width`/`height` set in percents plus `minWidth`/`minHeight`/`maxWidth`/`maxHeight` set were arranging items incorrectly.
- Very small slices with `cornrerRadius > 0` were being drawn as a full circle.
- `SliceGrouper` with was not zooming out properly if there was no legend in chart.
- changing `groupData` from `false` to `true` on DateAxis was not working when doing so after the chart was built.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
