### ISSUE TITLE
Is there a way to change axis settings dynamically after chart was plotted without replotting?

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#197]
Say I have a chart that's already plotted. I would like to change some of the axes or line series settings without replotting. 

It seems like I can change the renderer.grid settings on the axes (opacity for instance) after the plot, but not say groupData or baseInterval (nothing seems to change).

**Comment by zeroin** [comment]
baseInterval can not be changed. If it is changed, a new data should be set, as it only does things when initially parsing data. 
As for the gorupData - setting to false from true works fine, but it seems we have a bug when setting from false to true. I am investigating it now.

**Comment by martynasma** [comment]
Fixed in [5.0.21](https://github.com/amcharts/amcharts5/releases/tag/5.0.21).

## [5.0.21] - 2022-01-11

### Added
- New `Sprite` setting: `forceInactive`. If set to `true`, it will override `interactive` setting as well as ignore any interaction events set on the element.
- `cursorhidden` event added to `XYCursor`. Dispatched when user rolls-out of the chart plot area and cursor is hidden.
- New `Component` method: `markDirtyValues()`. Forces a repaint of the element which relies on data.

### Changed
- Value (4th parameter of the Heat rule's `customFunction`) will now receive actual value of the target data item, not interpolated calculated setting value.

### Fixed
- Fixing bug when not passing the duration to the `animate` method ([Issue 181](https://github.com/amcharts/amcharts5/issues/181)).
- Horizontal and vertical layouts with `width`/`height` set in percents plus `minWidth`/`minHeight`/`maxWidth`/`maxHeight` set were arranging items incorrectly.
- Very small slices with `cornrerRadius > 0` were being drawn as a full circle.
- `SliceGrouper` with was not zooming out properly if there was no legend in chart.
- changing `groupData` from `false` to `true` on DateAxis was not working when doing so after the chart was built.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
