### ISSUE TITLE
RadarChart: setting AxisRendererCircular 'inversed: true' causes series' cornerRadius to not work

### ISSUE THREAD

**Issue by dsinger376** [amcharts/amcharts5#203]
Hello, I am switching from amcharts v4 to v5 and using the Radar Chart (https://www.amcharts.com/docs/v5/charts/radar-chart/).  
I am trying to achieve a rounded look to the RadarColumnSeries by setting the 'cornerRadius' property, however if I  reverse the direction in which the series' increment by setting the 'inversed' property of AxisRendererCircular to true, the cornerRadius suddenly stops working and the series appear squared instead of rounded.  I have included a screenshot from the following codepen for reference: https://codepen.io/dansinger456/pen/abLQbGQ. I have tried downgrading from v5.0.21 to lower version 5 releases, however the issue remains.  Looking forward to a solution, thanks!

<img width="1176" alt="corner radius" src="https://user-images.githubusercontent.com/88509443/149022260-e39d0b37-b47f-45e6-b691-b8eed66be56a.png">

**Comment by zeroin** [comment]
Indeed, thanks for pointing out. We will fix this in next release.

**Comment by dsinger376** [comment]
appreciate it, thanks!

**Comment by martynasma** [comment]
Fixed in [5.1.0](https://github.com/amcharts/amcharts5/releases/tag/5.1.0).

## [5.1.0] - 2022-01-20

### Added
- New `Root` setting: `timezone`. E.g. `"America/Vancouver"`, `"Australia/Sydney"`, `"UTC"`.
- New export CSV option: `addBOM` (default: `true`). Indicates whether to add BOM characters at start of CSV output so that data viewer (e.g. Excel) knows we're exporting UTF-8 data.
- New methods for `Adapters`: `remove(key)`, `disable(key)`, and `enable(key)`.
- `GaplessDateAxis` added. It's a version of `DateAxis` that removes data-less intervals from its scale. `CategoryAxis` is being deprecated in favor of `GaplessDateAxis`. [More info](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/gapless-date-axis/).
- Timezone support added. [More info](https://www.amcharts.com/docs/v5/getting-started/root-element/#Time_zone).
- New `Component` method: `markDirtyValues()`. Will re-evaluate elements of the component that are data-reliant, such as axis labels.

### Fixed
- Clearing axis ranges from Axis and Series was not working properly.
- Slice with negative arc was ignoring `cornerRadius` property.
- `groupDataDisabled` on `XYSeries` was not working if set to `true`.
- Axis header was not updating its position if axes were stacked and size of an axis was updated.
- Disposing of charts with a lot of elements was quite slow.
- Series stacks with all-zero values could cause all stacks to disappear on zoom.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
