### ISSUE TITLE
Disable/delete adapters

### ISSUE THREAD

**Issue by Scylanth** [amcharts/amcharts5#206]
Hello,

I am trying to migrate my usecases from amcharts 4 to amcharts 5, and I have some usecases that rely on adapters.
Is it possible to disable or delete some adapters with the latest version of amcharts 5 ? Checking the [documentation](https://www.amcharts.com/docs/v5/reference/adapters/), I can only find the add method but nothing to delete an adapter.

Best regards,

Scylanth

**Comment by martynasma** [comment]
There's currently no way to remove or disable added adapters.

I'm marking this as an enhancement request. We'll definitely add this functionality at some point.

Will notify you here once it's implemented.

**Comment by martynasma** [comment]
Implemented in [5.1.0](https://github.com/amcharts/amcharts5/releases/tag/5.1.0).

## [5.1.0] - 2022-01-20

### Added
- New `Root` setting: `timezone`. E.g. `"America/Vancouver"`, `"Australia/Sydney"`, `"UTC"`.
- New export CSV option: `addBOM` (default: `true`). Indicates whether to add BOM characters at start of CSV output so that data viewer (e.g. Excel) knows we're exporting UTF-8 data.
- New methods for `Adapters`: `remove(key)`, `disable(key)`, and `enable(key)`.
- `GaplessDateAxis` added. It's a version of `DateAxis` that removes data-less intervals from its scale. `CategoryAxis` is being deprecated in favor of `GaplessDateAxis`. [More info](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/gapless-date-axis/).
- Timezone support added. [More info](https://www.amcharts.com/docs/v5/getting-started/root-element/#Time_zone).
- New `Component` method: `markDirtyValues()`. Will re-evaluate elements of the component that are data-reliant, such as axis labels.

### Fixed
- Clearing axis ranges from Axis and Series was not working properly.
- Slice with negative arc was ignoring `cornerRadius` property.
- `groupDataDisabled` on `XYSeries` was not working if set to `true`.
- Axis header was not updating its position if axes were stacked and size of an axis was updated.
- Disposing of charts with a lot of elements was quite slow.
- Series stacks with all-zero values could cause all stacks to disappear on zoom.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by Scylanth** [comment]
Hello,
I can confirm that the remove and disable methods do now exist for adapters.
However, it seems that the adapters for templates do not have those methods.

// doesn't exist
yAxis.get('renderer').labels.template.adapters.remove('text');;

// exist
yAxis.get('renderer').labels.each((label) => label.adapters.remove('text'));

**Comment by martynasma** [comment]
You're right. The change does not affect templates.

We'll add `remove()` method in the next version.

That said, adding adapters on a template does not add them on previously created entities. Similarly removing adapter from template, would not remove it from entities that are already created.

**Comment by martynasma** [comment]
Fixed in [5.1.1](https://github.com/amcharts/amcharts5/releases/tag/5.1.1).

## [5.1.1] - 2022-01-31

## Added
- New method `remove(key)` on Template's adapaters.
- Each chart-type package now exports its default theme as `DefaultTheme`. E.g. `am5xy.DefaultTheme`, `am5flow.DefaultTheme`, etc.
- TypeScript: Settings interfaces for all objects are now being exposed via bundled re-export files like `index.ts`, `xy.ts`, etc.
- New class `am5.Modal`.
- New `Container` setting: `reverseChildren`. If set to `true`, will start rendering from the last child, effectively flipping the order in how children of the cotainer are laid out. Useful for [right-to-left setups](
https://www.amcharts.com/docs/v5/concepts/locales/right-to-left-support/).

## Changed
- Charts on iOS devices will now automatically use lesser resolution to work around canvas memory restriction introduced in iOS 15 Safari.
- Charts will now use less built-in layers, and thus less `<canvas>` elements by default, reducing memory consumption.
- All low/high-related settings and fields moved from `CandlestickSeries` to `XYSeries`. Sometimes it could be useful to have low/high on other series even if they are not shown visually.

## Fixed
- `XYCursor` was not being hidden when its `positionX` or `positionY` was changed to `undefined` and `alwaysShow` was set to `false`.
- Auto-wrapped right-aligned labels were being rendered in wrong position.
- Auto-wrapped labels were not being trimmed for whitespace on each line.
- `dropFromPrevious` and `riseFromPrevious` states on `ColumnSeries` were not working properly on a column after a gap in data in case previous data item was outside of selection.
- Emoji characters were not being displayed on circular labels.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
