### ISSUE TITLE
pointer in zoom plus and minus button

### ISSUE THREAD

**Issue by barrygwhite** [amcharts/amcharts5#212]
Is there a way to change cursorOverStyle property in zoom buttons? 
````
var zoomControl = chart.set("zoomControl", am5map.ZoomControl.new(root, {}));
	zoomControl.children._container.plusButton.set("icon", am5.Picture.new(root, {
		width: 15,
		height: 15,
		layer: 40,
		src: "/charts/amchart/img/plus.svg",
		cursorOverStyle: "pointer" // shows deafult cursor instead of pointer
	}));
	
		var customButton = zoomControl.children.moveValue(am5.Button.new(root, {
		layer: 40,
		x: -5,
		icon: am5.Picture.new(root, {
			width: 15,
			height: 15,
			interactive: true,
			src: "/charts/amchart/img/custom.svg",
			cursorOverStyle: "pointer" //works fine
		})
	}), 0)
	
	
````
It doesn't work with the default zoom buttons, but I was able to make it work with any custom buttons.

**Comment by sassomedia** [comment]
Seems odd that one would work but not the other. In any case, you probably would want to set the `cursorOverStyle` directly on the `Button`, instead of the `Picture`. Also, you get easy access to these buttons by directly accessing the `ZoomControl`'s properties. What you get is just a regular [`Button`](https://www.amcharts.com/docs/v5/reference/button) instance that you can modify:
```javascript
const zoomCtrl = am5map.ZoomControl.new(root, {});
const { minusButton, plusButton } = zoomCtrl;

plusButton.set("cursorOverStyle", "pointer");
minusButton.set("cursorOverStyle", "pointer");

chart.set("zoomControl", zoomCtrl);
```

You can see a working example [here](https://codepen.io/sassomedia/pen/vYevBrR).

**Comment by martynasma** [comment]
Just a bit of a context: icon of a button is not interactive (unless you set `interactive: true` on it explicitly). This means that it does not register any hovers, hence no changing of cursor.

@sassomedia is right. You need to set `cyrsorOverStyle` directly on a Button element, not its icon.
