### ISSUE TITLE
PieChart labels with wrapping and maxWidth

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#225]
https://codepen.io/buggedcom/pen/ZEXdopY

```js
series.labels.template.setAll({
  wrap: true,
  oversizedBehavior: 'wrap',
  textAlign: 'start',
  maxWidth: 150
})
```

![Screenshot 2022-01-21 at 12 17 44](https://user-images.githubusercontent.com/2810/150510026-6c57c700-b011-47c3-a8f5-96ff9c57cb3b.png)

When a label is forced to wrap, the alignment of the label is not as expected for the label is on the right hand side, is this a bug or am I missing something?

**Comment by martynasma** [comment]
Fixed in [5.1.1](https://github.com/amcharts/amcharts5/releases/tag/5.1.1).

## [5.1.1] - 2022-01-31

## Added
- New method `remove(key)` on Template's adapaters.
- Each chart-type package now exports its default theme as `DefaultTheme`. E.g. `am5xy.DefaultTheme`, `am5flow.DefaultTheme`, etc.
- TypeScript: Settings interfaces for all objects are now being exposed via bundled re-export files like `index.ts`, `xy.ts`, etc.
- New class `am5.Modal`.
- New `Container` setting: `reverseChildren`. If set to `true`, will start rendering from the last child, effectively flipping the order in how children of the cotainer are laid out. Useful for [right-to-left setups](
https://www.amcharts.com/docs/v5/concepts/locales/right-to-left-support/).

## Changed
- Charts on iOS devices will now automatically use lesser resolution to work around canvas memory restriction introduced in iOS 15 Safari.
- Charts will now use less built-in layers, and thus less `<canvas>` elements by default, reducing memory consumption.
- All low/high-related settings and fields moved from `CandlestickSeries` to `XYSeries`. Sometimes it could be useful to have low/high on other series even if they are not shown visually.

## Fixed
- `XYCursor` was not being hidden when its `positionX` or `positionY` was changed to `undefined` and `alwaysShow` was set to `false`.
- Auto-wrapped right-aligned labels were being rendered in wrong position.
- Auto-wrapped labels were not being trimmed for whitespace on each line.
- `dropFromPrevious` and `riseFromPrevious` states on `ColumnSeries` were not working properly on a column after a gap in data in case previous data item was outside of selection.
- Emoji characters were not being displayed on circular labels.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by buggedcom** [comment]
Assuming the CDN has been updated, this has not been fixed in 5.1.1 using the code pen in the original comment.

**Comment by buggedcom** [comment]
But in addition, we have updated to 5.1.1 in our app and that does not work either.

**Comment by martynasma** [comment]
How so? If I use `texAlign: "end"` or (`"right"`), the Austria label aligns fine now:

![image](https://user-images.githubusercontent.com/1458520/151925387-1debfa20-f13b-46fe-97ef-6c9d4161a65b.png)

**Comment by buggedcom** [comment]
![Screenshot 2022-02-01 at 09 29 21](https://user-images.githubusercontent.com/2810/151928679-6a26af77-101c-4a8c-ac3a-2ab75d9f064f.png)

That of course works for the labels on the left of the by, but not the ones on the right.

I guess this could be conditionally applied through an adapter however, but it seems that the pie should be handling this somehow automatically?

**Comment by martynasma** [comment]
That would need to be an adapter. We're trying to avoid precisely that kind of built-in fuzzy logic in amCharts 5.

**Comment by buggedcom** [comment]
Whats the best way to determine which side of the pie the label is on?

**Comment by martynasma** [comment]
I suppose you could use `target.get("labelAngle")` in label's adapter.

Right-side starts at 90 and ends at 270.

```JavaScript
series.labels.template.adapters.add("textAlign", function(align, target) {
  var angle = target.get("labelAngle");
  return angle >= 90 && angle <= 270 ? "right" : "left";
});
```
