### ISSUE TITLE
CanvasRenderer: null is not an object (evaluating 't._ghostContext.imageSmoothingEnabled=!1')

### ISSUE THREAD

**Issue by gguynn** [amcharts/amcharts5#235]
Hello dev,

Thank you for reviewing our second issue.

**issue**
- application crashes

**stack**
- React

**browser/os**
- Safari/iOS latest

**screenshot**
<img width="1792" alt="Screen Shot 2022-01-23 at 12 15 57 PM" src="https://user-images.githubusercontent.com/1015228/150691096-b2476def-a552-46db-bd66-08165c6ee9e5.png">

**Comment by martynasma** [comment]
It seems that Apple has [made life harder](https://developer.apple.com/forums/thread/689071) for everyone relying on Canvas by imposing severe handicaps on Canvas rendering in iOS Safari 15.* and up.

We're trying to figure out a workaround. It looks like we might need to downsample resolution of charts on iOS devices, unless we can find a better option. Thanks, Apple :/

**Comment by gguynn** [comment]
> It seems that Apple has [made life harder](https://developer.apple.com/forums/thread/689071) for everyone relying on Canvas by imposing severe handicaps on Canvas rendering in iOS Safari 15.* and up.
> 
> 
> 
> We're trying to figure out a workaround. It looks like we might need to downsample resolution of charts on iOS devices, unless we can find a better option. Thanks, Apple :/

That seems to be the case with the memory limit.  Thanks for looking into our issue.

I've reported the memory issue separately here:
https://github.com/amcharts/amcharts5/issues/234

This and the other issue seem related since our app doesn't crash from this JS error on desktop.  Maybe a try/catch will work.  Thanks again.

**Comment by martynasma** [comment]
> Maybe a try/catch will work.

Nah, Safari prevents canvas creation, so even if we weed out errors, we still don't get chart fully rendered, so it's a no go.

We'll need to figure out a workaround, or... wait for Apple to fix it. But seeing the issue drag out from 15 Betas (now it's 15.2), I doubt they consider it an issue.

**Comment by gguynn** [comment]
> > Maybe a try/catch will work.
> 
> 
> 
> Nah, Safari prevents canvas creation, so even if we weed out errors, we still don't get chart fully rendered, so it's a no go.
> 
> 
> 
> We'll need to figure out a workaround, or... wait for Apple to fix it. But seeing the issue drag out from 15 Betas (now it's 15.2), I doubt they consider it an issue.

Sorry, so.. the reason I created to issues was.

1. Charts not rendering issue #234
2. This issue.  Can you prevent my app from completely crashing when the charts fail to render?

Thanks

**Comment by gguynn** [comment]
> Chart crashing should not crash the whole app. I think. But you can wrap it in exception code just in case.
> 
> 
> 
> We're adding some fail-safes for iOS devices, too. Will roll them in the next version, and inform you here when it's out.

Awesome.  Thank you!

**Comment by martynasma** [comment]
Fixed in [5.1.1](https://github.com/amcharts/amcharts5/releases/tag/5.1.1).

## [5.1.1] - 2022-01-31

## Added
- New method `remove(key)` on Template's adapaters.
- Each chart-type package now exports its default theme as `DefaultTheme`. E.g. `am5xy.DefaultTheme`, `am5flow.DefaultTheme`, etc.
- TypeScript: Settings interfaces for all objects are now being exposed via bundled re-export files like `index.ts`, `xy.ts`, etc.
- New class `am5.Modal`.
- New `Container` setting: `reverseChildren`. If set to `true`, will start rendering from the last child, effectively flipping the order in how children of the cotainer are laid out. Useful for [right-to-left setups](
https://www.amcharts.com/docs/v5/concepts/locales/right-to-left-support/).

## Changed
- Charts on iOS devices will now automatically use lesser resolution to work around canvas memory restriction introduced in iOS 15 Safari.
- Charts will now use less built-in layers, and thus less `<canvas>` elements by default, reducing memory consumption.
- All low/high-related settings and fields moved from `CandlestickSeries` to `XYSeries`. Sometimes it could be useful to have low/high on other series even if they are not shown visually.

## Fixed
- `XYCursor` was not being hidden when its `positionX` or `positionY` was changed to `undefined` and `alwaysShow` was set to `false`.
- Auto-wrapped right-aligned labels were being rendered in wrong position.
- Auto-wrapped labels were not being trimmed for whitespace on each line.
- `dropFromPrevious` and `riseFromPrevious` states on `ColumnSeries` were not working properly on a column after a gap in data in case previous data item was outside of selection.
- Emoji characters were not being displayed on circular labels.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by gguynn** [comment]
> Fixed in [5.1.1](https://github.com/amcharts/amcharts5/releases/tag/5.1.1).

Thanks for the fix!
