### ISSUE TITLE
Preventing tooltip overlapping

### ISSUE THREAD

**Issue by roszczypalam** [amcharts/amcharts5#249]
Hi there, 

I am using this snippet to show only few tooltips on the series, but I've faced a problem of tooltip overlap.
How I can prevent that ?

```
    let maxTooltipsCounter = 0;
    currentDataSeries.bullets.push(function () {
      const properties = {
        fill: am5.color("#1E90FF"),
        tooltipText: "tooltip",
        showTooltipOn:
          maxTooltipsCounter < BUBBLE_PLOT_MAX_TOOLTIP_COUNT
            ? "always"
            : undefined,
        tooltip: am5.Tooltip.new(root, {}),
      };
      maxTooltipsCounter++;

      const graphics = am5.Circle.new(
        root,
        properties,
        currentDataCircleTemplate
      );

      return am5.Bullet.new(root, {
        sprite: graphics,
      });
```

Effect:
<img width="103" alt="Screenshot 2022-01-31 at 12 56 22" src="https://user-images.githubusercontent.com/23001448/151790036-5026cda2-6e21-44fe-bf68-307efe40d5d6.png">

**Comment by sassomedia** [comment]
This seems more like a manual check you would have to do. Rather than having a max tooltip count, create all the Bullets with Tooltip first (hidden), then loop through the Bullets and check whether the bounds are intersecting. If they don't intersect, show the tooltip. The crowdedness will determine how many tooltips can be displayed.
