### ISSUE TITLE
Hover position not working properly

### ISSUE THREAD

**Issue by DeepKarmakar** [amcharts/amcharts5#258]
I have a map with two points. There is a tooltip on hover of each point and country are name also coming up on hover map area. But somehow positions are not correct, I mean when I'm hovering exact on the point tooltip not coming but it's working bit down, same thing happening for map area as well. Do you have any suggestion for that?

**Comment by DeepKarmakar** [comment]
there was an zoom issue and for that it was happening, I got it.

**Comment by DeepKarmakar** [comment]
I got the reason, actually there a css that is "zoom: 90%;" in body for some reason and for that it is happening.

**Comment by sassomedia** [comment]
Do you have a screenshot of where that zoom 90% is?

**Comment by martynasma** [comment]
Better yet, a CodePen with a live map?

**Comment by DeepKarmakar** [comment]
Here is the [Stack blitz](https://stackblitz.com/edit/angular-ivy-yxxwd9?file=src%2Fstyles.css)

**Comment by sassomedia** [comment]
Ok thanks! I would remove that zoom style or override it to 100%. The tooltips still work as expected even if the user uses the browser zoom but if it's set in CSS, it breaks the scale functionality.

**Comment by DeepKarmakar** [comment]
yeah it's breaking in Am5 but I would like to tell you that it was good in Am4. Actually I'm upgrading from 4 to 5. So if you have any fixes for that that will be great.

**Comment by martynasma** [comment]
OK, so here's the deal: CSS' `zoom` directive is no-standard legacy IE stuff, and super wonky at that, which is not supported by some modern browsers, including Firefox. Don't use it! [More info](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom).

Instead use standard [`transform: scale()`](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale()) directive.

In current version of amCharts 5 it still breaks hovers, but we have it fixed in dev version, and will notify here when it's out.

**Comment by martynasma** [comment]
Fixed in [5.1.4](https://github.com/amcharts/amcharts5/releases/tag/5.1.4).

## [5.1.4] - 2022-02-11

## Added
- `affectsMinMax` added to value axis range.
- `segments` property added to `Line` class. Allows passing multiple segments instead of continous line.
- `tooltipIntervalOffset` setting added to `DateAxis`. If not set, axis' tooltip will use value of the `-tooltipLocation` (cell start timestamp by default), so that tooltip would should rounded value, like 06:00 instead of 06:30 when interval is hourly. [More info](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Axis_tooltip).
- `tooltipDateFormats` setting added to `DateAxis`. Allows specifying axis' tooltip date formats for time each time unit, different from `dateFormats`. NOTE: `tooltipDateFormat` will override the format if set. [More info](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Axis_tooltip).
- `syncWith` setting added to `XYCursor`. Set it to an array of other `XYCursor` objects to automatically position them as the cursor moves. [More info](https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#syncing-cursors).

## Changed
- Default tooltip date formats have changed slightly for `DateAxis`. Previously, it was using formats from `dateFormats`. Now it uses defaults/user values from newly-introduced `tooltipDateFormats` setting.

## Fixed
- In some cases `DurationAxis` with "second" as its base duration was going to stack overflow.
- Background on a `ValueAxis` was not showing.
- Improved performance for charts with lots of stacked series with null.
- Fixing mouse position when using `transform: scale` or `zoom` ([Issue 258](https://github.com/amcharts/amcharts5/issues/258)).
- Some touch interactions were not working in iOS 12.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
