### ISSUE TITLE
Treemap start on nested element

### ISSUE THREAD

**Issue by gitramro** [amcharts/amcharts5#259]
Im following this example

[https://codepen.io/team/amcharts/pen/GRmYymr](https://codepen.io/team/amcharts/pen/GRmYymr)

What if instead of rendering the treemap for the first time like this

![image](https://user-images.githubusercontent.com/17560424/152382786-a3092f56-36d1-4270-834f-b1dc337a9e2e.png)

 i want to render it like this

![image](https://user-images.githubusercontent.com/17560424/152382875-dbb8e06c-5781-489b-aed4-3c98b5c18aa4.png)

I was reading the docs and it talks about this, I guess thats the way

[https://www.amcharts.com/docs/v5/charts/hierarchy/#Pre_selected_branch](https://www.amcharts.com/docs/v5/charts/hierarchy/#Pre_selected_branch)

and it asks for a dataitem obj

I tried and took a look at series.dataItems[0] but it just gives me the root element as a dataitem, how can I get the element B0 as a dataitem so i can add it to series.set and render it with that value selected?

**Comment by sassomedia** [comment]
Maybe that example isn't ideal because the drill down you're seeing is actually due to the `initialDepth: 2`, not the `selectedDataItem` (you could even comment that out and you would still see the same thing). However, the root branch, which is a dataItem, also has an array of dataItem-children. And that's what you want:
```javascript
series.set("selectedDataItem", series.dataItems[0].get("children")[1]); // 1 being for the B-branch
```
Combine this with the `initialDepth` to get at different levels of that branch.

Example here: https://codepen.io/sassomedia/pen/ExbgPBX?editors=0010

**Comment by gitramro** [comment]
That totally worked, thanks!
