### ISSUE TITLE
Turning bullets on/off with "templateField"

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts5#26]
I'm trying to turn bullets on/off with the `templateField` in a LineSeries but this seems to work a bit differently than in am4. There are two issues that I'm encountering when setting properties in the data;
- the `disabled` property of a `Circle` does not seem to work, so I have to use `opacity` instead
- the `opacity` can only be turned off but not on

Example:
LineSeries with a number of data points where only one bullet should show. Previously, I used to be able to set the `opacity` to 0 when creating the bullet and then use the data binding to specify just one data point where I turn it on:
```javascript
const data = [
  { date: "2020-01-15", value: 234 },
  { date: "2020-01-16", value: 567 },
  { date: "2020-01-17", value: 012, opacity: 1 },
  { date: "2020-01-15", value: 345 },
  ...
]
```
In am5, this approach does not seem to work anymore ([CodePen](https://codepen.io/sassomedia/pen/WNOWwpa?editors=0010)). What does work however, is when I don't set `opacity` on bullet creation (all bullets show), then I have to set `opacity` in the data for all bullets except the one I want to see:
```javascript
const data = [
  { date: "2020-01-15", value: 234, bulletSettings: { opacity: 0 } },
  { date: "2020-01-16", value: 567, bulletSettings: { opacity: 0 } },
  { date: "2020-01-17", value: 012 },
  { date: "2020-01-15", value: 345, bulletSettings: { opacity: 0 } },
  ...
]
```
Is this the expected behavior?

**Comment by martynasma** [comment]
Thanks for the heads up!

There's more to it than just a bug. Once we release a version with a fix, I'll provide more details here.

This should happen within couple of days.

**Comment by sassomedia** [comment]
Ok cool, sounds good 👌 Thanks!

**Comment by martynasma** [comment]
Fixed in [5.0.0-beta.30](https://github.com/amcharts/amcharts5/releases/tag/5.0.0-beta.30).

## [5.0.0-beta.30] - 2021-10-05

### Added
- `shadow*` settings are now available on `Label` as well.
- `arrangeTooltips` (default: `true`) setting added to `XYChart`. If set to `false` will disable tooltip overlap check algo.

### Fixed
- Fixed type errors when importing maps (especially in Angular).
- Fixed `templateField` to override `template`.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download-v5/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
The following tutorial section describes what additional steps are needed in order to use `templateField` with bullets:
https://www.amcharts.com/docs/v5/concepts/common-elements/bullets/#Template_fields

**Comment by sassomedia** [comment]
Thanks for the update, works as expected. 👍
