### ISSUE TITLE
Taking axis ranges into account when calculating axis sxope

### ISSUE THREAD

**Issue by ghost** [amcharts/amcharts5#260]
Hi,
If axis ranges have values higher or lower than the values of displayed data series, then axis ranges are not visible in the chart. In amCharts 4, I could set includeRangesInMinMax = true on ValueAxis to adjust its scope. How to do this in amCharts 5?

Theoretically I could do it using this approach: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/value-axis/#Dynamic_min_max
But I'm afraid that calculating the min and max values of the data in displayed series (some might be not visible for example when hidden using legend) may be error prone.

**Comment by martynasma** [comment]
Implemented in [5.1.4](https://github.com/amcharts/amcharts5/releases/tag/5.1.4).

## [5.1.4] - 2022-02-11

## Added
- `affectsMinMax` added to value axis range.
- `segments` property added to `Line` class. Allows passing multiple segments instead of continous line.
- `tooltipIntervalOffset` setting added to `DateAxis`. If not set, axis' tooltip will use value of the `-tooltipLocation` (cell start timestamp by default), so that tooltip would should rounded value, like 06:00 instead of 06:30 when interval is hourly. [More info](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Axis_tooltip).
- `tooltipDateFormats` setting added to `DateAxis`. Allows specifying axis' tooltip date formats for time each time unit, different from `dateFormats`. NOTE: `tooltipDateFormat` will override the format if set. [More info](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Axis_tooltip).
- `syncWith` setting added to `XYCursor`. Set it to an array of other `XYCursor` objects to automatically position them as the cursor moves. [More info](https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#syncing-cursors).

## Changed
- Default tooltip date formats have changed slightly for `DateAxis`. Previously, it was using formats from `dateFormats`. Now it uses defaults/user values from newly-introduced `tooltipDateFormats` setting.

## Fixed
- In some cases `DurationAxis` with "second" as its base duration was going to stack overflow.
- Background on a `ValueAxis` was not showing.
- Improved performance for charts with lots of stacked series with null.
- Fixing mouse position when using `transform: scale` or `zoom` ([Issue 258](https://github.com/amcharts/amcharts5/issues/258)).
- Some touch interactions were not working in iOS 12.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
More info here:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/#including-in-min-max
