### ISSUE TITLE
GaplessDateAxis candlestick series tooltips displaying offset time

### ISSUE THREAD

**Issue by cwooldridge1** [amcharts/amcharts5#286]
I am using the new gapless date axis on a candlestick series chart. The issue that is occurring is that the tooltip date is being displayed as a slight offset. For example, say the base intervals time unit is a minute and the count is 5 (in other words each candle is 5 minutes). This displayed data on the tooltip for the point if say the data point was 14:00 the tooltip would display 14:02 and the data point of 13:55 would display 13:57. I am not sure how this weird offet is occuring. I have looked at this issue in amcharts 4 https://github.com/amcharts/amcharts4/issues/2919 and its related and nothing seems to be working in amcharts 5.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by cwooldridge1** [comment]
After I went to the efforts of making a code pen for it the code pen displayed it without the bug. I then figured I would try to NPM install it again and the bug was then fixed after updating. However, I still do have one issue. Arbitrarily the date axis will disappear when zooming in/out.
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/85259389/154342406-10c346df-7e1b-4b66-8d8e-bcb4469b8aa5.png">
You'll notice in the above photo that there is no date axis. However, if you zoom in or out a bit more it will appear again.
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/85259389/154342927-e6aeacfc-fe35-49e4-91b4-702ce0bd7e0e.png">
Here is the link to the code pen for it: https://codepen.io/cwooldridge1/pen/eYeexee?editors=1011. Youll notice this when you start to mess with zooming

**Comment by martynasma** [comment]
Yeah, somethings off. We'll need to look into it.

Will keep you posted.

**Comment by martynasma** [comment]
Fixed in [5.1.5](https://github.com/amcharts/amcharts5/releases/tag/5.1.5).

## [5.1.5] - 2022-02-22

### Added
- `minSize` setting added to `Flow` (`Chord` and `Sankey`) series. It's a relative value to the sum of all values in the series. If set, this relative value will be used for small-value nodes when calculating their size. For example, if it's set to `0.01`, small nodes will be sized like their value is 1% of the total sum of all values in series.

### Changed
- Direction of vertical panning with mouse wheel in an `XYChart` was inverted to make it consistent with OS native scrolling direction.

### Fixed
- Fixing ES6 module detection by BundlePhobia ([Issue 294](https://github.com/amcharts/amcharts5/issues/294)).
- Parsing of dates using `"i"` format was not working properly when no milliseconds were supplied.
- Using `minZoomCount` and `maxZoomCount` on a `GaplessDateAxis` was not working properly.
- Sometimes vertical `XYChart` scrollbar was not reacting to chart's pan via mouse drag or wheel.
- Using mouse wheel on a chart that was setup to pan was also zooming in/out in addition to pan.
- In some cases grid on `GaplessDateAxis` was not being placed properly. Grid and Label placement improved.
- `ForceDirectedTree` could freeze when used with Animated theme in some cases.
- Changing of baseInterval on DateAxis was not properly working in some cases.
- In some cases, when no animated theme was used, a state on a Sprite was not applied.
- Setting data on `MapSeries` after `geoJSON` was updated was not working properly which resulted heat rules not to be applied.
- It was difficult to make a selection close to the start/end of plot area on `RadarChart`.
- When `XYChart` was fully zoomed in, using mouse wheel would start panning the chart instead of zoom.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
