### ISSUE TITLE
Pan only, no zoom, on cursor scroll? 

### ISSUE THREAD

**Issue by cwooldridge1** [amcharts/amcharts5#291]
I've noticed on the pan setting on the chart that when you pan it doesn't just pan it also affects the zoom level of the x-axis. This trait is mainly apparent when panning towards the most recent data (scrolling in). What I am envisioning is when scrolling in the width of the zoom stays the same but the x-axis position of both the selectionMin and selectionMax get incremented the same amount instead of the current way of the selectionMin being incremented by more than the selectionMax. Does this make sense?

Also, I noticed that the zoomMinCount on the new GaplessDateAxis is very off. In my code pen the minZoomCount is 10 and I can zoom in up to to two increments. https://codepen.io/cwooldridge1/pen/eYeexee?editors=1011

Thanks

**Comment by martynasma** [comment]
I suppose this is because of over-zooming, which is enabled by default. You can turn it off by setting `maxDeviation: 0` in your axis settings:

https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Over_zooming

P.S. can you post the zoomMinCount thing as a separate issue? It's unrelated, and might be a bug. Thanks.

**Comment by martynasma** [comment]
Hm, yeah, that must be a bug. It should not zoom at all of `wheelY: "panX"` is set.

We'll need to fix this.

Thanks for thorough explanation!

**Comment by martynasma** [comment]
Fixed in [5.1.5](https://github.com/amcharts/amcharts5/releases/tag/5.1.5).

## [5.1.5] - 2022-02-22

### Added
- `minSize` setting added to `Flow` (`Chord` and `Sankey`) series. It's a relative value to the sum of all values in the series. If set, this relative value will be used for small-value nodes when calculating their size. For example, if it's set to `0.01`, small nodes will be sized like their value is 1% of the total sum of all values in series.

### Changed
- Direction of vertical panning with mouse wheel in an `XYChart` was inverted to make it consistent with OS native scrolling direction.

### Fixed
- Fixing ES6 module detection by BundlePhobia ([Issue 294](https://github.com/amcharts/amcharts5/issues/294)).
- Parsing of dates using `"i"` format was not working properly when no milliseconds were supplied.
- Using `minZoomCount` and `maxZoomCount` on a `GaplessDateAxis` was not working properly.
- Sometimes vertical `XYChart` scrollbar was not reacting to chart's pan via mouse drag or wheel.
- Using mouse wheel on a chart that was setup to pan was also zooming in/out in addition to pan.
- In some cases grid on `GaplessDateAxis` was not being placed properly. Grid and Label placement improved.
- `ForceDirectedTree` could freeze when used with Animated theme in some cases.
- Changing of baseInterval on DateAxis was not properly working in some cases.
- In some cases, when no animated theme was used, a state on a Sprite was not applied.
- Setting data on `MapSeries` after `geoJSON` was updated was not working properly which resulted heat rules not to be applied.
- It was difficult to make a selection close to the start/end of plot area on `RadarChart`.
- When `XYChart` was fully zoomed in, using mouse wheel would start panning the chart instead of zoom.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
