### ISSUE TITLE
Invert wheel direction for natural scrolling?

### ISSUE THREAD

**Issue by keegandonley** [amcharts/amcharts5#295]
On many Mac computers, the scroll direction is inverted from the standard on a Windows machine. Scrollable charts don't seem to respect this when scrolling vertically. Is it feasible to preserve the natural scrolling behavior inside a chart?

**Comment by martynasma** [comment]
Technically, this is not only Mac-related. It's how we treat wheel in panY situation. It's currently inversed on how OS wheel scroll works, even on Windows.

We will consider if we could just flip the direction of panY so it's consistent with the OS behavior.

**Comment by keegandonley** [comment]
Ah, I only develop on my mac so didn't realize the underlying reason. Thanks for the quick response, that would be a big help as I'm currently using the pan as a vertical overflow-style scrolling so it would feel much more natural

**Comment by martynasma** [comment]
Fixed in [5.1.5](https://github.com/amcharts/amcharts5/releases/tag/5.1.5).

## [5.1.5] - 2022-02-22

### Added
- `minSize` setting added to `Flow` (`Chord` and `Sankey`) series. It's a relative value to the sum of all values in the series. If set, this relative value will be used for small-value nodes when calculating their size. For example, if it's set to `0.01`, small nodes will be sized like their value is 1% of the total sum of all values in series.

### Changed
- Direction of vertical panning with mouse wheel in an `XYChart` was inverted to make it consistent with OS native scrolling direction.

### Fixed
- Fixing ES6 module detection by BundlePhobia ([Issue 294](https://github.com/amcharts/amcharts5/issues/294)).
- Parsing of dates using `"i"` format was not working properly when no milliseconds were supplied.
- Using `minZoomCount` and `maxZoomCount` on a `GaplessDateAxis` was not working properly.
- Sometimes vertical `XYChart` scrollbar was not reacting to chart's pan via mouse drag or wheel.
- Using mouse wheel on a chart that was setup to pan was also zooming in/out in addition to pan.
- In some cases grid on `GaplessDateAxis` was not being placed properly. Grid and Label placement improved.
- `ForceDirectedTree` could freeze when used with Animated theme in some cases.
- Changing of baseInterval on DateAxis was not properly working in some cases.
- In some cases, when no animated theme was used, a state on a Sprite was not applied.
- Setting data on `MapSeries` after `geoJSON` was updated was not working properly which resulted heat rules not to be applied.
- It was difficult to make a selection close to the start/end of plot area on `RadarChart`.
- When `XYChart` was fully zoomed in, using mouse wheel would start panning the chart instead of zoom.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
