### ISSUE TITLE
Performance issues when using LineSeries with fill

### ISSUE THREAD

**Issue by uniquexor** [amcharts/amcharts5#296]
I am trying to do a sort of elevation chart for a given route. My x axis is the distance, y axis - elevation and the area of the chart is colored to represent different types of gradient. I would like to be able to represent up to 10-20k points, using a scroll/zoom, however, even having ~900 points, the chart becomes too slow to use. 

I've created a demo here, with 966 data points:
https://jsfiddle.net/uniquexor/cdts4b51/1/

If I remove the coloring:
```js
        series.fills.template.setAll({
            visible: true,
            templateField: "fillSettings"
        });
```
the chart becomes quite responsive.

So my question is: can anything be done to achieve what I am aiming for or is it just not possible?

**Comment by martynasma** [comment]
OK, so when you use `templateField`, every time it is encountered in the data, a new line series segment is created. Since you have that in every single data item in your data, it means that for every data item, a new segment is started. It means separate calculation, drawing, etc, hence the diminishing performance.

What you should do, is to include `fillSettings` into those data points, that the change in fill occurs. Since templateField changes look for all subsequent data points, you don't need to define fillSettings for each and every one, just those the actual change occurs on.

Does that make sense?

**Comment by uniquexor** [comment]
Yup, it does! Thanks for the help I will try that out

**Comment by uniquexor** [comment]
I tried it out. Reducing the number of fillSettings, seemed to have improved the performance.
