### ISSUE TITLE
Sankey doesn't allow for async data?

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts5#318]
Hi again :) 

I'm attempting to setup a Sankey to take data asynchronously, but it doesn't seem to be supported.

Below is an example of the Sankey demo with the data set to load after 3 seconds: However, the `console.log`s are showing a `RangeError` when data is not defined for the Sankey. 
https://codepen.io/jonofoz/pen/Bamvggm?editors=0010

I added another, commented-out line that I'm using in the meantime as a hack to "allow" asynchronous data. The automatically created colors aren't the same, but it seems to work for all other intents and purposes with no other side effects.

I tested it with the v4 Sankey demo and did not encounter this issue; that may be comparing apples to oranges, though, as v5 is built on `canvas`. Not sure myself.  ¯\_(ツ)_/¯

Cheers as always!
Jon

**Comment by zeroin** [comment]
I confirm it's a bug, we will fix it in next release. Thanks for the heads up!

**Comment by jonofoz** [comment]
Thank _you_! :)

**Comment by martynasma** [comment]
Fixed in [5.1.8](https://github.com/amcharts/amcharts5/releases/tag/5.1.8).

## [5.1.8] - 2022-03-10

### Added
- Settings `pinchZoomX` and `pinchZoomY` (defaults: `false`) added to `XYChart`. If set to `true` will allow pinch-zooming of a chart on touch devices. NOTE: these settings are not supported on `RadarChart`.
- `topPlotContainer` added to `XYChart`. It's a `Container` that can be used to place element over plot area.

### Changed
- The types for adapters has been changed to be more intuitive and useful. ([Issue 312](https://github.com/amcharts/amcharts5/issues/312))
- Tapping an element on a touch device will now generate `pointerover` event in addition to `click`. When tapped somewhere else, `pointerout` event will be triggered.

### Fixed
- Fixing ES6 module detection by BundlePhobia again ([Issue 294](https://github.com/amcharts/amcharts5/issues/294)).
- Pinch-zooming of a `MapChart` was not working well in some cases.
- `maxHeight` setting in `Sprite` was not working.
- Change of `minWidth` was not being applied at once, only if some other changes triggered chart to be redrawn.
- Changing or not setting data on an existing `FlowChart` was resulting in a JS error.
- `maxPanOut` setting in `MapChart` was not working.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
