### ISSUE TITLE
Problem with MapChart's maxPanOut not limiting the panning

### ISSUE THREAD

**Issue by NXXR** [amcharts/amcharts5#321]
Hey,
I am using AmCharts in a React App.
The Root container and mapchart are set up during a useEffect hook and the geoJSON added to the polygon series. The geojson is fetched in a separate effect.

```typescript
const root = am5.Root.new('mapdiv');
const chart = root.container.children.push(
  am5map.MapChart.new(root, {
    projection: am5map.geoMercator(),
    maxPanOut: 0,
    zoomControl: am5map.ZoomControl.new(root, {
      paddingBottom: 25,
      opacity: 50,
    }),
  })
);
// Create polygon series
const polygonSeries = chart.series.push(
  am5map.MapPolygonSeries.new(root, {
    geoJSON: geodata ?? undefined,
    tooltipPosition: 'fixed',
  })
);
```

From what I read in the documentation the value for maxPanOut describes the percentage a map can be panned outside the viewport of its container.
However the map can still be panned out of the viewport and the maxPanOut does not seem to affect the map at all.
<details>
<summary>Screenshot of the map panned about halfway out of the viewport</summary>

![grafik](https://user-images.githubusercontent.com/25636783/157268113-dc7f27bf-732d-405f-aac2-e511aabe1f19.png)

</details>

- I checked if the geojson has any stray polgons that may expand the map area and throw the percantages off in that regard but the geojson appears clean.
- is it possible the panning breaks out of the box if/because the default container may be too small for the map at default zoom level?
  <details>
  <summary>Screenshot of the map in default position</summary>
  
  ![grafik](https://user-images.githubusercontent.com/25636783/157271265-de0a9abf-b9dc-4030-9060-76f64432f866.png)

  </details>

I appreciate any help.
If you need more infos or code I'll try to supply the relevant items.

**Comment by martynasma** [comment]
Fixed in [5.1.8](https://github.com/amcharts/amcharts5/releases/tag/5.1.8).

## [5.1.8] - 2022-03-10

### Added
- Settings `pinchZoomX` and `pinchZoomY` (defaults: `false`) added to `XYChart`. If set to `true` will allow pinch-zooming of a chart on touch devices. NOTE: these settings are not supported on `RadarChart`.
- `topPlotContainer` added to `XYChart`. It's a `Container` that can be used to place element over plot area.

### Changed
- The types for adapters has been changed to be more intuitive and useful. ([Issue 312](https://github.com/amcharts/amcharts5/issues/312))
- Tapping an element on a touch device will now generate `pointerover` event in addition to `click`. When tapped somewhere else, `pointerout` event will be triggered.

### Fixed
- Fixing ES6 module detection by BundlePhobia again ([Issue 294](https://github.com/amcharts/amcharts5/issues/294)).
- Pinch-zooming of a `MapChart` was not working well in some cases.
- `maxHeight` setting in `Sprite` was not working.
- Change of `minWidth` was not being applied at once, only if some other changes triggered chart to be redrawn.
- Changing or not setting data on an existing `FlowChart` was resulting in a JS error.
- `maxPanOut` setting in `MapChart` was not working.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
