### ISSUE TITLE
Errors raised when using exporting functionality on Google Chrome

### ISSUE THREAD

**Issue by koorizhizhi** [amcharts/amcharts5#329]
**Question**
I’m implementing a report-drawing functionality with Amcharts5.
I export each chart on a  canvas.
It begins to raise errors when I run the chart-generating function on an cloud-based embeded HTML env with Chrome( no error raised just 2 or 3 days before  ).  
<img width="198" alt="image" src="https://user-images.githubusercontent.com/83855880/158128438-ec8df42e-cca4-4029-b992-8019e82d594d.png">

But everything works properly when I access the same environment and run the function via Safari/MS Edge.
The exporting functions well in Codepen:
https://codepen.io/koorizhizhi/pen/jOGbGGV

I’m not sure whether the problem is with the browser itself or the embedded environment(which works on Safari but not on Chrome).

**Comment by koorizhizhi** [comment]
> @koorizhizhi What sort of environment are you running the code in? You say it's "cloud-based", but can you be more specific?

It’s a cloud-based LIM system where a HTML environment has been embedded allowing drawing and generating reports.

**Comment by Pauan** [comment]
I can't reproduce the error in Firefox or Brave, they both display the charts without any errors.

If you can reproduce it outside of your LIM system, then we'll take a look, but unfortunately if we can't reproduce it then we can't fix it.

Right now it sounds like it's probably a bug in your LIM system, or the embedded browser, but we can't know for sure.

Judging by the error message, it seems like it could be an async issue: maybe your code is running before the exporting plugin has finished loading. So make sure that all of the amCharts code is fully loaded (in the correct order) before running your app code.

**Comment by koorizhizhi** [comment]
Thanks for your support. I put all my codes in the ready function. 
But I've never seen this kind of error before, I'll keep testing on it.

**Comment by Pauan** [comment]
Even if your code is in the `ready` function it can still theoretically run before the scripts are finished loading. Also it's possible for the scripts to load out of order. But it depends on how you're loading the scripts.

**Comment by koorizhizhi** [comment]
Thanks! 
I'm new to Javascript 😔 and I will do a research on it.
It seems the promblem is with this certain environment itself cuz I run the same code in another environment of this system with no errors.

**Comment by jcquarto** [comment]
I had the problem described. It was working fine and then all of a sudden this week the same error message. What I realized was that I had to wrap all of my AM5 code in a ```am5.ready(function() {}``` block .   Almost none of the examples on the site have this (nor most of the CodePen examples).   As soon as I did this , the errors on Chrome went away and I was good to go.  

I'd also note that the documentation for am5 is substantially more of an understanding to understand compared to am4. The examples are mostly code, as are the tutorials, whereas for am4 there was a larger percentage of visual example (plus code).  Just try reading up on Axes and Cursors, hahaha :).  It'll really hurt your mind. I'm convinced that someone not involved with amCharts needs to be writing the documentation. This isn't an uncommon situation ; great coders are often awful explainers because they are too close to their excellent code.

**Comment by Pauan** [comment]
> @jcquarto What I realized was that I had to wrap all of my AM5 code in a `am5.ready(function() {}` block .

That shouldn't be necessary, we've changed V5 so that it should handle everything correctly without `ready`. Could you share your code which causes the error?

> I'd also note that the documentation for am5 is substantially more of an understanding to understand compared to am4.

Yes, V5 is a new product so we're still working on fleshing out the documentation for it. V4 has been out for years so it has a large headstart.

**Comment by jcquarto** [comment]
I was using the stock code from the site's example titled "XY chart with date-based axis" (https://www.amcharts.com/demos/xy-chart-date-based-axis/). But that I am convinced was NOT the problem,  because it started popping up on all my v5 charts the same day with no changes to our repo w.r.t. the charting portion for over a month.   What I think it IS related to is my environment, is Rails 7 serving up the JS for amCharts via a view partial with dynamic data provided from the backend at run-time (not a separate call to get the data).  This is nothing I'd expect amCharts to "support" for obvious reasons, and it's not something that would come up in a CodePen example, all of which work without the need for `ready` . However, it was an essential piece to put in since once i did so , it fixed the error everywhere (for me). 

I think my take-away is that  `ready` remains useful and probably should be put in the short list of things-to-try when one has a problem. Even if it's cost is tiny, and even if it's need is driven by a framework issue (which may well be the case here), it's inclusion as a potential quick fix should not be overlooked.   (what comes to mind is the old adage: There have more been sins committed in the name of efficiency than anything else in CS).   Give `ready` a bit more prominence in the docs; it almost certainly should be in the README.

p.s. do you realize it is non-trivial to find this github site with Issues-as-Dev-Portal from the main company site?  Yet another thing you might want to put on the main site under a "get help" link .

**Comment by Pauan** [comment]
@jcquarto The reason we don't mention `ready` in the docs isn't because of performance, it's because `ready` is almost never needed.

The only time when `ready` is needed is if the DOM node doesn't exist yet, because the DOM node is being created asynchronously, or because the JS code is being run way too early.

That's an exceptionally rare situation, which you happened to run into. In 99.9+% of situations, you don't need `ready`.

If you go to the [Support page](https://www.amcharts.com/support/) it has two options: paid support and free support. Paid support is done through ZenDesk, not GitHub. If you click on the link for free support, it has a link to the GitHub repo. Do you have any suggestions for how we can improve this?
