### ISSUE TITLE
Inconsistent x-axis zooming when cursor behavior is "zoomXY"

### ISSUE THREAD

**Issue by derekbking** [amcharts/amcharts5#33]
I have setup a [codepen](https://codepen.io/derekbking/pen/PojrQNG) copied from the amcharts5 demo. I have only added a cursor to the codepen with behavior set to "zoomXY". If all categories are not included in the zoom selection, the date axis will refuse to zoom.

**Selection that will cause the date axis to refuse to zoom**
![image](https://user-images.githubusercontent.com/3951143/136035541-0e7c742a-ca34-4329-9720-ac0d3e3c809a.png)

**Result** (notice the x scrollbar was unaffected)
![image](https://user-images.githubusercontent.com/3951143/136037556-cdd9eaeb-677c-4ec4-86d0-59e02b241cc6.png)
  
  

**Selection that the date axis will properly zoom**
![image](https://user-images.githubusercontent.com/3951143/136036016-d838a884-94b2-48b5-91ac-935992295f6c.png)

**Result** (notice the x scrollbar was properly updated)
![image](https://user-images.githubusercontent.com/3951143/136036129-e079e4f8-5895-492a-8dc5-e3d7c1275288.png)

The pattern I have noticed is that if any category is excluded from the zoom then the date axis will refuse zoom. When zooming it appears that the chart begins to animate the date axis zoom, but gets reset a fraction of a second later resulting in no zoom.

**Relevant Codepen**
https://codepen.io/derekbking/pen/PojrQNG

**Comment by martynasma** [comment]
Fixed in [5.0.0-beta.32](https://github.com/amcharts/amcharts5/releases/tag/5.0.0-beta.32).

## [5.0.0-beta.32] - 2021-10-08

### Changed
- `Exporting` plugin now imports minified version of `xlsx` library for XSLX data exports.
- Axis tooltips have now `animationDuration: 200` set automatically by Animated theme, so there's no need to set it in code anymore.

### Fixed
- Charts with `CategoryAxis` + `DateAxis` were zooming incorrectly in some cases.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download-v5/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
