### ISSUE TITLE
Gradient axis range does not display until scroll or resize

### ISSUE THREAD

**Issue by cabintech** [amcharts/amcharts5#333]
We have a chart with an x-axis range which has a gradient fill. The `axisFill `is setup with `visibility=false` so the gradient does not show when the graph is first displayed. 

Upon a user action (checkbox clicked), we make the range visible with:
`range.get("axisFill").set("visible", true);`

But the range gradient fill does not display. If the window is resized or the scroll bar moved slightly, then the gradient fill appears. It seems like a painting/refresh problem on the range's graphics object. When visibility is changed it does not repaint - although all subsequent changes to visibility work correctly even without any resizing or scrolling. It only fails to paint the first time.

I will also note that if we use a solid fill color, then it works as expected. This seems to be a problem only with a gradient fill.

The code is a bit lengthy so I have put it in a JSFiddle:
[https://jsfiddle.net/rkm8cv5y/1/](https://jsfiddle.net/rkm8cv5y/1/)

To see the problem, run the fiddle, which produces a page like:

![image](https://user-images.githubusercontent.com/31935300/158435790-0bc30246-d668-48de-84f4-c202e269a38b.png)

Click on the "Night shading" checkbox. This sets visible=true, but the shading does not appear:
![image](https://user-images.githubusercontent.com/31935300/158437459-fc5d0813-62ae-4b26-b4b4-4e4814cc6d3a.png)

Now grab the scroll bar handle and move it slightly... and then the gradient range appears.
![image](https://user-images.githubusercontent.com/31935300/158437547-af0d5ef0-187a-4878-ad9a-3cacec4416d8.png)

If you comment out line 139, and un-comment line 140, then a solid fill is used. Rerun the fiddle and observe that clicking on the "Night shading" checkbox immediately shows the range fill as it should.

I am seeing this problem on current Chrome and Edge browsers.

**Comment by martynasma** [comment]
Fixed in [5.1.9](https://github.com/amcharts/amcharts5/releases/tag/5.1.9).

## [5.1.9] - 2022-03-17

### Fixed
- Fixed the issue with resizing a chart inside of a flexbox. ([Issue 311](https://github.com/amcharts/amcharts5/issues/311))
- Fixed jumpy axis when panning an `XYChart` with mouse wheel.
- Panning XYChart with mouse wheel had incorrect direction if axis was inversed.
- If axis range had a gradient fill, gradient used to spread only through visible area, making it look icorrect.
- After pinch zooming and `XYChart` or zooming the chart with no animated theme used, CPU usage used to increase.
- `DateAxis` with `baseIntervals` `timeUnit` set to `"month"` could show incorrect month in the axis tooltip.
- If a `Graphics` had a gradient `fill`/`stroke` and initially was invisible, setting it to visible did not make the gradient to appear.
- While zooming `LineSeries`, a part of the line to the left of the first visible data point could disappear.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
