### ISSUE TITLE
Bug in range gradient

### ISSUE THREAD

**Issue by cabintech** [amcharts/amcharts5#335]
When a gradient is used to fill a range, and then the graph is zoomed, the gradient color points are calculated to the end of the visible graph instead of the end of the range. This results in incorrect drawing of the gradient near the edge of the graph. Here is a graph with an identical set of ranges filled with the same gradient. They all draw correctly when there is no gradient at the right edge: 
![image](https://user-images.githubusercontent.com/31935300/158593765-ec14f665-c233-4128-860c-24405fa367cb.png)

But when the graph is zoomed in and the range extends past the right edge of the display, the gradient gets compressed (observe the sharp edge of gray where it should fade in like the other ranges):
![image](https://user-images.githubusercontent.com/31935300/158594352-5bbd712b-3b32-415b-b390-e845843b0b1a.png)

The gradient color transition points should be calculated based on the full range, not on the visible display.

**Comment by martynasma** [comment]
Fixed in [5.1.9](https://github.com/amcharts/amcharts5/releases/tag/5.1.9).

## [5.1.9] - 2022-03-17

### Fixed
- Fixed the issue with resizing a chart inside of a flexbox. ([Issue 311](https://github.com/amcharts/amcharts5/issues/311))
- Fixed jumpy axis when panning an `XYChart` with mouse wheel.
- Panning XYChart with mouse wheel had incorrect direction if axis was inversed.
- If axis range had a gradient fill, gradient used to spread only through visible area, making it look icorrect.
- After pinch zooming and `XYChart` or zooming the chart with no animated theme used, CPU usage used to increase.
- `DateAxis` with `baseIntervals` `timeUnit` set to `"month"` could show incorrect month in the axis tooltip.
- If a `Graphics` had a gradient `fill`/`stroke` and initially was invisible, setting it to visible did not make the gradient to appear.
- While zooming `LineSeries`, a part of the line to the left of the first visible data point could disappear.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
