### ISSUE TITLE
Update D3 to 7.x

### ISSUE THREAD

**Issue by zamiang** [amcharts/amcharts5#344]
Are there any plans to update d3 to v7.x?

I am having trouble using this library in conjunction with others and my own code that uses d3 v7 (partly an issue with d3 where you cannot have multiple versions of d3 installed)

**Comment by Pauan** [comment]
@zamiang Thanks for the reminder, we're going to try upgrading d3 to version 7 in the next release.

**Comment by martynasma** [comment]
Fixed in [5.1.10](https://github.com/amcharts/amcharts5/releases/tag/5.1.10).

## [5.1.10] - 2022-03-30

### Added
- New in-line text formatting property `verticalAlign` added. Currently supports only `"super"` and `"sub"` values. E.g. `Copyright[fontSize: 8px; verticalAlign: super;]TM[\]`.

### Changed
- Logarithmic scale on `ValueAxis` was revamped with a different approach. No changes from the configration, but might influence appearance/scale.
- When calculating derivative values for series, `low`, `high`, and `open` used previous `low`, `high`, and `open` values. Now they all use `value` instead.
- Updated to D3 v7.

### Fixed
- In some cases, using a text placehodler, an empty string was shown insteaf of a zero.
- Some grid container masking issues fixed.
- Sometimes `valueAxis` was zoomed-in a bit on the first render of an `XYChart`.
- Axis ranges with `dRadius > 0` were not visible on `RadarChart`.
- Dynamic change of `value*Show` fields of an `XYSeries` was not working.
- Removing data from a legend could lead to JS errors in some particular cases.
- Ghost label was creating a gap in an `XYChartScrollbar` between scrollbar bottom an scrollbar series.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
