### ISSUE TITLE
Legend with standalone data with toggling based on templateField or value

### ISSUE THREAD

**Issue by rferreira98** [amcharts/amcharts5#359]
**Question**

I'm using standalone data for a columnSeries legend. Because I'm distinguishing values based on templateField condition.
The problem is that I cannnot toggle both ends of the series, only toggle whole series.
I've tried separating data in 2 columns series but for some reason it breaks.

https://codesandbox.io/s/column-charts-4hf8bh

**Environment**

amCharts version: "@amcharts/amcharts5": "^5.1.9"
React version: "react": "^17.0.2"

**Comment by martynasma** [comment]
Rather than using `templateField` on a single series to apply different coloration for certain columns, I would rather create two separate series: one for pink and one for black columns.

Then you can just add those two series to legend and let it take care of toggling.

Alternative would be to add click events on legend items, then iterating through series columns and hiding/showing them selectively, which sounds like more overhead than the two-series approach.

**Comment by rferreira98** [comment]
With two series I can't make them side by side, they stay stacked vertically on each other

**Comment by martynasma** [comment]
Why would the stack if you had values in data for only one of the series per day: either ping or black?

**Comment by rferreira98** [comment]
The stacked is for the brighter part, because I'm showing pink, black and blueish white to fill the rest of percentage
And when I had 3 series black becomes stacked with pink and blue out of picture.

**Comment by martynasma** [comment]
Well, if value of black for the day is zero, then it should not affect stack at all.

**Comment by rferreira98** [comment]
even with two series: they overlap each other with or without stacked: true.

**Comment by martynasma** [comment]
It seems your test data is wrong.

It contains values for both series each day, whereas you want to have only black value for "black days", and only orange value for "orange days".

Does that make sense?
