### ISSUE TITLE
Sunburst renders past defined startAngle and endAngle

### ISSUE THREAD

**Issue by dbishop-kcura** [amcharts/amcharts5#363]
**Bug description**

The Sunburst chart is rendering a portion of chart past the defined startAngle and endAngle settings. When using the defaults (full circle), this is causing sections to overlap, making portions of the chart inaccessible. Here is a jsFiddle that showcases the issue: https://jsfiddle.net/0h2sc6j7/1/.

![image](https://user-images.githubusercontent.com/25249726/161781376-b12e17a9-6114-459b-9fb1-50095d6121bd.png)

**Environment**
- amCharts5 version: latest (pulled from CDN in jsFiddle)
- Browser: latest version of Google Chrome (also seen with latest version of Microsoft Edge)

**Comment by zeroin** [comment]
The problem here is that you have values both in your parent nodes and in child nodes, and the sum of child nodes is not the same as the values of your parent nodes. For the sunburst to work properly you should only add values to the nodes which are the most deep in the structure, and all the other values will be calculated automatically.

**Comment by dbishop-kcura** [comment]
@zeroin Thank you for pointing that out, I missed that the count we were providing at the root level was actually not the full sum of all of its children (it was missing data from 17). After correcting that issue, things are rendering as we would expect. This issue can be closed. Thanks again!
