### ISSUE TITLE
Wrong initial zoom (positive value is limited to 10)

### ISSUE THREAD

**Issue by Otrozone** [amcharts/amcharts5#364]
Looks like the initial zoom of line series is limited to value 10. I believe, that one month ago it was working ok. Here is [an example](https://codepen.io/Otrozone/pen/YzYeVXm). To reproduce, enable and disable the line series in bottom. Only _Wifi strength_ (negative values) and _Wifi time_ (value < 10) works fine, other line series values are not visible.

**Comment by Otrozone** [comment]
The issue appears only when the chart combines line series and column series.  If the column series are removed, the zoom works correctly.

**Comment by zeroin** [comment]
I confirm it's a bug, thanks for helping to find it. We will fix it shortly.

**Comment by martynasma** [comment]
Fixed in [5.1.11](https://github.com/amcharts/amcharts5/releases/tag/5.1.11).

## [5.1.11] - 2022-04-06

### Added
- `groupDataWithOriginals` and `groupDataCallback` settings added to `XYSeries`. [More info](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Custom_aggregation_functions).
- `strictMinMaxSelection` setting added to `ValueAxis`. When set to `true`, the axis won't round `min` and `max` of a selection to the nearest round values, but will use actual min and max (`extraMin` and `extraMax` will still be added if set). This is a good feature when your series displays not actual but derivative values, like `valueYChangeSelection` as it helps to avoid frequent jumping of series to adjusted min and max of the axis.

### Changed
- Internal layout of `XYChart` containers was changed. `plotContainers` now goes to `yAxesAndPlotContainer`, and `plotContainer` and `topPlotContainer` goe into `plotContainers`.

### Fixed
- If `XYChart` was used without animated theme, and scrollbar's background was clicked to zoom to some specific spot, it resulted in scrollbar not being updated anymore when zoomed with wheel or zoom-out button.
- Fixed and issue where nodes of `ForceDirected` series were flickering to 0,0 point when div of a chart was resized.
- Fixed potential XSS injection issue with the accessibility of tooltips.
- `container` setting in `ExportingMenu` was being ignored.
- In some specific cases not all series were included in min/max calculation of a `ValueAxis` resulting not all series to be visible.
- When whole series was out of selected scope, its last or first value (depending on seleciton) was still included when calculating min and max.
- Layouts were allocating space for margins of hidden items.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
