### ISSUE TITLE
Problem with visualCentroid() logic in MapPolygon.ts when geometry.type in geoJSON is MultiPolygon

### ISSUE THREAD

**Issue by jackyleefu** [amcharts/amcharts5#365]
**Bug description**
When geometry.type in geoJSON is MultiPolygon, and there is only one item in geometry.coordinates, it will throw
Uncaught TypeError: Cannot read properties of undefined (reading 'length').

I used an external geoJSON data source.

**Environment (if applicable)**
 - amCharts 5.1.10

**Additional context**
visualCentroid() in MapPolygon.ts

if (geometry.coordinates.length > 1) {
  ...
}
=>
if (geometry.coordinates.length > 0) {
  ...
}

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by jackyleefu** [comment]
https://codesandbox.io/s/friendly-bush-9z9gdz?file=/src/App.js

hover some one province, tooltips throw error

**Comment by jackyleefu** [comment]
Is it possible for amchart5 map to provide the reverseGeodata property in amchart4, in the example I provided the external data source that uses non-ESRI order

**Comment by jackyleefu** [comment]
Can amchar5's map provide the reverseGeodata property, like amchart4? In the example I provided, the external data source that uses non-ESRI order

**Comment by martynasma** [comment]
Fixed in [5.1.13](https://github.com/amcharts/amcharts5/releases/tag/5.1.13).

## [5.1.13] - 2022-04-15

### Added
- `useLastColorForLegendMarker` setting added to `BaseColumnSeries` (applicable to all column-based series like `ColumnSeries`, `CandlestickSeries`)
- `geodataNames` setting added to `MapSeries`. Allows setting translations to map features, e.g. countries. [More info](https://www.amcharts.com/docs/v5/charts/map-chart/map-translations/).
- Read-only private setting `gridInterval` added to `DateAxis`.

### Fixed
- If geoJSON contained multipolygons with just one polygon, hovering over polygon was resulting in a JS error.
- `DateAxis` displayed wrong time when time was switching to DST, when a timezone was set on a `Root` element. 

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
