### ISSUE TITLE
Hidden Axis Ranges Come Back on Scroll

### ISSUE THREAD

**Issue by andrewfmbs** [amcharts/amcharts5#368]
**Bug description**

I am having an issue where if you call `axisRange.hide()` and then move the scroll bar around, the axis range will pop back on.

I have created a [jsFiddle](https://jsfiddle.net/fv14bkxr/4/) showing the bug. The range is hard to see (not sure why the strokeWidth and stroke aren't working here, but not important now) but if you press the Toggle Range button you will see it disappear. Hide the range, then shrink the scroll bar zoom as small as it will go, then drag the bar and scroll around >> the range will re-appear. 

It seems to happen when the chart auto adjust the viewport / scaling.

**Comment by martynasma** [comment]
This is due to how chart identifies what fills to show when. When fill needs to be hidden, it's hidden using `hide()` internally. When it needs to be shown, it is shown with a `show()` call.

It can't distinguish whether you have hidden it deliberately, or if it was hidden by chart itself to if it's out of view.

I suggest instead of using hiding the range itself, just hiding its grid:

```JavaScript
rangeDataItem.get("grid").hide();
```

**Comment by andrewfmbs** [comment]
Thanks! That works well.
