### ISSUE TITLE
Incorrect tooltip position

### ISSUE THREAD

**Issue by Mikanoshi** [amcharts/amcharts5#369]
A tooltip attached to an axis fill does not have a consistent positioning when panning/zooming the chart.
Positioning error becomes larger as more data is added to the chart (and it becomes slower).
In this demo moving mouse over chart fixes the position, but in my actual project only zoom/pan helps.
https://codepen.io/Mikanoshi/pen/bGammeM
Also if I do axisFill.hide() and then show() all the labels are bunched up in the top left corner until chart is panned/zoomed again.

**Comment by zeroin** [comment]
I would recommend using label of the axisRange instead of tooltip in your case. The trick is to move it to topPlotContainer, this will allow to position this label in the same way you do that in your example. Here is a demo:
https://codepen.io/team/amcharts/pen/RwxeOBr/408bea53b28fcdd7a332cbbfa6c2b714

**Comment by Mikanoshi** [comment]
Thanks, works perfectly.
