### ISSUE TITLE
Logarithmic scale bug

### ISSUE THREAD

**Issue by Mikanoshi** [amcharts/amcharts5#370]
Log scale is not always correctly auto adjusting min/max axis values to match currently displayed data:
https://codepen.io/Mikanoshi/pen/VwyEEbP
amcharts 5.1.9 does not have this problem, so probably a log fix in 5.1.10 is the cause.

**Comment by zeroin** [comment]
We changed the behavior so that the min and max would be close or equal (depending on situation) to the real min/max values, as otherwise you can get a lot of blank space at the bottom/top of the chart and a series which occupies only small part of the plot. But I see a bug that 0.1 and 0.01 labels are not displayed on the axis, I will fix this issue in next release.

**Comment by Mikanoshi** [comment]
But a lot of blank space is still a bug, all the values below 1000, including 0.1 and 0.01, are still being displayed even though visible data is between 1900 and 2000.

**Comment by zeroin** [comment]
Is it? I tried log scale with values as you described and I get no white space:
https://codepen.io/team/amcharts/pen/ZEvmymL/af84d53d79dbea4875754f483818d4ac?editors=1010

**Comment by Mikanoshi** [comment]
> Is it? I tried log scale with values as you described and I get no white space
It only happens sometimes, in my example just drag a left scrollbar limit and you will see that scale does not change until year 1983 goes your of the view, so almost half of all chart scale range stays wrong.

**Comment by zeroin** [comment]
This issue will also be fixed in next release, thanks for helping to find it.

**Comment by martynasma** [comment]
Fixed in [5.1.14](https://github.com/amcharts/amcharts5/releases/tag/5.1.14).

## [5.1.14] - 2022-04-22

### Fixed
- `ValueAxis` with a logarithmic scale was not showing some of the labels in some specific cases.
- Moved `zoomOutButton` of `XYChart` to `topPlotContainer` to solve unwanted zoom when cursor's `snapToSeries` was set.
- Initially-hidden series legend markers were not being dimmed out unless Animated theme was in use.
- When whole series was out of selected scope, its last or first value (depending on seleciton) was still included when calculating min and max, causing chart not to adjust min/max values to a visible series scope.
- `Annotator` was not disabling chart interactivity when activated in Firefox.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
