### ISSUE TITLE
Annotator does not block chart on Firefox

### ISSUE THREAD

**Issue by Mikanoshi** [amcharts/amcharts5#371]
Firefox 99. These examples:
https://www.amcharts.com/docs/v5/concepts/exporting/annotator/
If you move a mouse right after clicking on Annotate, interactions are disabled, but if you just click it and don't move the mouse then chart remains interactive.

**Comment by martynasma** [comment]
Fixed in [5.1.14](https://github.com/amcharts/amcharts5/releases/tag/5.1.14).

## [5.1.14] - 2022-04-22

### Fixed
- `ValueAxis` with a logarithmic scale was not showing some of the labels in some specific cases.
- Moved `zoomOutButton` of `XYChart` to `topPlotContainer` to solve unwanted zoom when cursor's `snapToSeries` was set.
- Initially-hidden series legend markers were not being dimmed out unless Animated theme was in use.
- When whole series was out of selected scope, its last or first value (depending on seleciton) was still included when calculating min and max, causing chart not to adjust min/max values to a visible series scope.
- `Annotator` was not disabling chart interactivity when activated in Firefox.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
