### ISSUE TITLE
XYChartScrollbar events

### ISSUE THREAD

**Issue by macthestack** [amcharts/amcharts5#39]
The events "rangechanged" and "propertychanged" don't seem as reliable to use in amcharts 5 as in 4.

These events no longer seem to capture changes that originate in the chart itself rather than in the scrollbar.

I'm using this to fetch new data based on date range.

Are there other options in amcharts5 that are preferable or is this a bug?

**Comment by martynasma** [comment]
No need for such events in v5 since you can attach events to be triggered on a change of setting or private setting.

Instead of monitoring scrollbar for events, I'd just set up events for axis' private properties `selectionMin` and `selectionMax`:

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Events

**Comment by macthestack** [comment]
Thanks, that's very helpful!

**Comment by martynasma** [comment]
Well, in that case probably the best approach is to debounce the execution of your data load a few milliseconds so that it triggers only when animation has settled.
