### ISSUE TITLE
Exporting plugin bug

### ISSUE THREAD

**Issue by Mikanoshi** [amcharts/amcharts5#399]
Hovering mouse over 3 dots disables chart completely, can only be enabled by clicking on that button.
https://www.amcharts.com/demos/exporting-chart-to-image/

**Comment by martynasma** [comment]
Fixed in [5.2.0](https://github.com/amcharts/amcharts5/releases/tag/5.2.0).

## [5.2.0] - 2022-04-29

### Added
- Initial (beta) version of `StockChart` added. Check [documentation](https://www.amcharts.com/docs/v5/charts/stock/) and [product info](https://www.amcharts.com/stock-chart/).

### Fixed
- Week numbers for "leap weeks" were not being formated properly.
- Removing an axis range with a bullet was not removing the bullet itself.
- If one of the series had less data than another and their date axis had data grouping enabled, data of a series with less values could be not grouped.
- `ColumnSeries` was not coloring its legend marker initially if `useLastColorForLegendMarker` was `true`.
- Hovering on `ExportingMenu` was permanently disabling chart interactivity.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
