### ISSUE TITLE
GeoMap gets out of center

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/amcharts5#400]
Take your demo WorldLow globe and rotate it. All fine. Now zoom in on country level and turn the globe towards north and zoom out again. Result is, the globe is no longer in the center.
https://www.amcharts.com/demos/rotate-globe-to-a-selected-country/

In my case the globe was larger and the off-center movement is even more pronounced.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/13607767/165893768-599c0fad-d975-4321-93ef-9a387de1aa02.png">

<img width="410" alt="image" src="https://user-images.githubusercontent.com/13607767/165893832-1d9c3d0b-9230-4c7c-8e85-a7515971242a.png">

scandinavia and further nord
<img width="379" alt="image" src="https://user-images.githubusercontent.com/13607767/165893915-f29ec0b8-661e-41bf-a04b-9a093e81d644.png">

The globe gets cropped at the top becaue it is no longer in the same position as before.
<img width="389" alt="image" src="https://user-images.githubusercontent.com/13607767/165894003-4cefe8ce-b4bb-4d9b-bf5f-a2bbd281983a.png">

**Comment by zeroin** [comment]
We added `centerMapOnZoomOut` feature like it was in v4, it will be available in next release. This will solve this problem. We don't count it as a bug, as the chart zooms to the position of the mouse, but we understand that this makes the map not usable in cases like this (when map is draggable, user can easily drag map to fix the position).

**Comment by martynasma** [comment]
Fixed in [5.2.1](https://github.com/amcharts/amcharts5/releases/tag/5.2.1).

## [5.2.1] - 2022-05-03

### Added
- `centerMapOnZoomOut` setting added to `MapChart` (default: `true`). Means the map will center itself (or go to `homeGeoPoint` if set) when fully zoomed out.
- `getGroupInterval(duration)` method added to `DateAxis`. Returns a time interval axis would group data to for a specified duration.
- `getIntervalMax(interval)` and `getIntervalMin(interval)` methods added to `DateAxis`. These methods return `min` and `max` of a specified time interval.

### Changed
- Axis fills on a `StockChart` are now not visible by default.
- All `Chart` elements now have `interactiveChildren: true` set by default, so that adding events on a chart does not automatically make all elements in it interactive.
- Zooming out `MapChart` using mouse wheel will now auto-center the map by default. Set `centerMapOnZoomOut: false` to bring back old behavior.

### Fixed
- Changing `inside` and `opposite` of `AxisRendererX` or `AxisRendererY` after the axis was already initialized was not working properly.
- `StockChart`'s' period selection buttons were not zooming to exact dates when data grouping of an X-axis was turned on.
- `StockChart`'s' series type switcher was not switching series properly when data grouping was enabled.
- `StockChart`'s' series type switcher was not switching series properly when comparing mode was on.
- If a `StockChart` was in percent scale mode, adding an indicator which was not on a separate panel was resulting in the indicator using wrong scale.
- Fixed week number calculation (again).
- Fixed CSS of `StockToolbar` for FireFox.
- Pinch-zoom of `MapChart` was ignoring `minZoomLevel` and `maxZoomLevel` settings.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
