### ISSUE TITLE
pdfkit is outdated

### ISSUE THREAD

**Issue by zdm** [amcharts/amcharts5#401]
Hi.
Original `pdfkit` is outdated and is not supported. It contains old dependencies, that will never be updated.
It is possible to use fork: https://github.com/foliojs-fork/pdfkit?

**Comment by Pauan** [comment]
Unfortunately there isn't anything we can do about that. We don't use `pdfkit`, we use `pdfmake`. So `pdfmake` has to change their dependencies, we can't do it for them.

**Comment by zdm** [comment]
Yes, you are using pdfmake, that is using pdfkit.

**Comment by martynasma** [comment]
Actually, we're experimenting with something. Let's keep this open for now.

**Comment by zdm** [comment]
I created issue https://github.com/alafr/SVG-to-PDFKit/issues/165

**Comment by Pauan** [comment]
@zdm We will upgrade pdfmake in the next release, that should fix this problem.

**Comment by curtdept** [comment]
This would be great, those old polyfill libs are crazy.

**Comment by martynasma** [comment]
Fixed in [5.2.3](https://github.com/amcharts/amcharts5/releases/tag/5.2.3).

## [5.2.3] - 2022-05-12

### Changed
- Upgraded versions of `pdfmake` and `xlsx` dependencies.
- Reseting `x` and `y` of the `ForceDirectedSeries` data item will make the node be not ifxed anymore.
- Tweaked styles of `StockToolbar` controls to work better with theme colors.

### Fixed
- Enclosing multi-word parameters in in-line styles were not working.
- `DateAxis` was producing an error if series had no initial data and timezone was set on a root element.
- Vertically-stacked Y-axes was incorrectly plotting related series with Y-axis set as base axis.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
