### ISSUE TITLE
minZoomLevel not respected when pinching to zoom on mobile device

### ISSUE THREAD

**Issue by ow77** [amcharts/amcharts5#407]
**Bug description**

When zooming on desktop minZoomLevel is respected and the user isn't permitted to zoom beyond the specified value. However, on mobile it appears pinch to zoom is disregarding minZoomLevel along with maxZoomLevel.

The same bug was reported on AMCharts 4, see https://github.com/amcharts/amcharts4/issues/2536. I believe the commit containing the fix is https://github.com/amcharts/amcharts4/blame/d542633d312b57484b3a45237e7486c265b6fe9c/src/.internal/charts/types/MapChart.ts#L691, please can this be applied accordingly to AMCharts 5?

**Environment (if applicable)**

Version: 5.2.0
Browser: Safari iOS 15.4.1

**Comment by martynasma** [comment]
Fixed in [5.2.1](https://github.com/amcharts/amcharts5/releases/tag/5.2.1).

## [5.2.1] - 2022-05-03

### Added
- `centerMapOnZoomOut` setting added to `MapChart` (default: `true`). Means the map will center itself (or go to `homeGeoPoint` if set) when fully zoomed out.
- `getGroupInterval(duration)` method added to `DateAxis`. Returns a time interval axis would group data to for a specified duration.
- `getIntervalMax(interval)` and `getIntervalMin(interval)` methods added to `DateAxis`. These methods return `min` and `max` of a specified time interval.

### Changed
- Axis fills on a `StockChart` are now not visible by default.
- All `Chart` elements now have `interactiveChildren: true` set by default, so that adding events on a chart does not automatically make all elements in it interactive.
- Zooming out `MapChart` using mouse wheel will now auto-center the map by default. Set `centerMapOnZoomOut: false` to bring back old behavior.

### Fixed
- Changing `inside` and `opposite` of `AxisRendererX` or `AxisRendererY` after the axis was already initialized was not working properly.
- `StockChart`'s' period selection buttons were not zooming to exact dates when data grouping of an X-axis was turned on.
- `StockChart`'s' series type switcher was not switching series properly when data grouping was enabled.
- `StockChart`'s' series type switcher was not switching series properly when comparing mode was on.
- If a `StockChart` was in percent scale mode, adding an indicator which was not on a separate panel was resulting in the indicator using wrong scale.
- Fixed week number calculation (again).
- Fixed CSS of `StockToolbar` for FireFox.
- Pinch-zoom of `MapChart` was ignoring `minZoomLevel` and `maxZoomLevel` settings.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by ow77** [comment]
@martynasma thanks for the quick turn around, can confirm this is now fixed! 👍
