### ISSUE TITLE
Overlapping charts with multiple y axes

### ISSUE THREAD

**Issue by 0viera** [amcharts/amcharts5#410]
**Overlapping charts with multiple y axes**

H, I'm trying to use a single graph with multiple yAxes with ColumnSeries,
The graph is being rendered overlapping instead of one after the other.

Example:
https://codepen.io/0viera/pen/VwQYGGN

In the example above there are 2 ColumnSeries with different yAxis: 
* Modules 1,2,4,5 (Axis title 1)
* Module 3 (Axis title 2, purple color)
I would expect that Module 3 would be shown in the same row as "Axis title 2", but instead it is shown in "Axis title 1" row.

Screenshot:
![image](https://user-images.githubusercontent.com/104842016/166468802-eb3ec7bd-15de-400c-880f-63216f1c92ef.png)

**Environment**
 - amCharts 5
 - Chrome

**Additional Information**
_I followed carefully the example below but couldn't get similar results
[Syncing axis widths across multiple charts](https://codepen.io/team/amcharts/pen/gOXjWVe)
_

**Comment by 0viera** [comment]
I think it's a bug, not a question

**Comment by martynasma** [comment]
Fixed in [5.2.3](https://github.com/amcharts/amcharts5/releases/tag/5.2.3).

## [5.2.3] - 2022-05-12

### Changed
- Upgraded versions of `pdfmake` and `xlsx` dependencies.
- Reseting `x` and `y` of the `ForceDirectedSeries` data item will make the node be not ifxed anymore.
- Tweaked styles of `StockToolbar` controls to work better with theme colors.

### Fixed
- Enclosing multi-word parameters in in-line styles were not working.
- `DateAxis` was producing an error if series had no initial data and timezone was set on a root element.
- Vertically-stacked Y-axes was incorrectly plotting related series with Y-axis set as base axis.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
