### ISSUE TITLE
Stock chart toolbar z-index bug

### ISSUE THREAD

**Issue by dnewkerk** [amcharts/amcharts5#420]
**Bug description**

I noticed there is a problem with the z-index for the stock chart toolbar buttons. The class `.am5stock-control-button` has a z-index of 100000, making it likely to appear on top of various UI elements of a site.

This can be observed on the official amCharts demo pages:
https://www.amcharts.com/demos/stock-chart/

To reproduce, scroll down a bit until the toolbar overlaps the site header.

It's unclear from what I can tell why the buttons have such a high z-index value. I would recommend setting it much lower if possible, as it will also currently appear above various things like modals (for instance Bootstrap modals have a z-index over 1000).

**Environment**

 - amCharts version: 5.2.3
 - Browser: Chrome 101.0.4951.64, Firefox 100
 
![amcharts-zindex-bug](https://user-images.githubusercontent.com/1725553/168403636-14ebccbf-82ce-4ccd-9191-0fde663c8b6d.png)

**Comment by martynasma** [comment]
Thanks for the heads up!

This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by martynasma** [comment]
Fixed in [5.2.4](https://github.com/amcharts/amcharts5/releases/tag/5.2.4).

## [5.2.4] - 2022-05-17

### Added
- `handleWheel()` method added to `XYChart`. Use it to mirror the same behavior as if the wheel was used on plot area.
- `useDefaultCSS` (default: `true`) setting added to `DateRangeSelector`.
- `inversed` added to `Tree` series. If set to `true`, will flip the direction of the tree.

### Fixed
- `StockToolbar` default CSS was using unnecessarily high `z-index` for its buttons.
- `StockToolbar` datepicker's style was off in some cases.
- `GaplessDateAxis` could display the same month name label two times in a row in some cases.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
