### ISSUE TITLE
Date range selector shows incorrect dates, does not sync with chart

### ISSUE THREAD

**Issue by dnewkerk** [amcharts/amcharts5#421]
**Bug description**

First, thank you for adding the stock chart and toolbar features. Very excited to start using them!

I noticed a bug with the Date range selector in the stock chart toolbar. After selecting a date range, the ".am5stock-control-label" text next to the date icon does not update to display the date values that were selected or entered in the date picker, and the label also does not update in response to changes made to the chart zoom level (e.g. using the scrollbar or mouse wheel).

For example:
https://www.amcharts.com/demos/stock-chart/

1) Click the date icon in the toolbar.
2) On the From side calendar, for month select July, and for day select 4. At this point the input and the calendar will show the correct/selected date. Click Apply.
3) Note that the chart has now correctly zoomed in to the July 4 start date. However the label next to the Date range selector icon now shows an incorrect date range: 2021-03-31 -- 2022-03-31 (still showing the full original chart date range, not the date range that was just selected).
4) Click the Date range selector icon/label again. Note that the From input now shows 2021-07-02, and the calendar has selected July 2, even though we selected July 4 above and haven't changed anything. I understand this might be due to there not being an actual data point on this specific date, however if it can be helped, this is possibly confusing to the user who just entered a specific value in, and is now seeing a different value.
5) Lastly, grab the right side of the scrollbar on the chart (which should still currently be at the far right side) and drag it left to an earlier date. Note that the date in the Date range selector label does not update to reflect the change. If you then click the date selector, you can see the correct date is shown on the To side. Only if you click Apply, then the label updates to the correct date.

There is also a small CSS issue with the date range selector (wasn't sure it warranted a separate issue)... the pair of date picker UIs are overflowing out of the container on the right side.

Thanks!

**Environment**

 - amCharts version: 5.2.3
 - Browser: Chrome 101.0.4951.64, Firefox 100

**Comment by martynasma** [comment]
We will have to discuss if/what we can do about it. Thanks.

I posted a new issue for the CSS thing: https://github.com/amcharts/amcharts5/issues/422

Make sure you follow it to get notified when the fix is available.

**Comment by martynasma** [comment]
We're rolling in the fix into the next version. Will notify here when the new version is out.

That being said: we won't be fixing the July 2/4 issue you described. If you would be using a regular `DateAxis`, which does have July 4 in its scale, the selection and labels would work as expected.

In this case, with `GaplessDateAxis`, which does not have July 4th (because there's no data for that day), zooming to July 4th, makes it zoom slightly outside July 6th (the first day with data), so it grabs July 2th, hence the discrepancy.

It's not a huge issue, I think, now that the labels will show correct dates.

**Comment by dnewkerk** [comment]
@martynasma that's fantastic, thank you so much for your hard work on amCharts! Understood about the secondary issue.

**Comment by martynasma** [comment]
Fixed in [5.2.9](https://github.com/amcharts/amcharts5/releases/tag/5.2.9).

## [5.2.9] - 2022-06-21

### Added
- New properties on `Root`: `tapToActivate` (default: `false`) - if enabled, requires to tap on chart pefore gesture-based functionality (zoom/pan) works, and `tapToActivateTimeout` (default: `3000`) - milliseconds of inactivity before chart becomes "inactive" for touch gestures. [More info](https://www.amcharts.com/docs/v5/getting-started/root-element/#Touch_related_options).

### Changed
- If there are no pan/zoom functionality set on charts, they should not prevent scrolling of the page by touch anymore.
- Bullets will no longer knock off user-set `maxWidth` on their `sprite` element.

### Fixed
- `DateRangeSelector` was not updating its label correctly when dates were picked.
- `LineSeries` with `templateField` and a lot of data items could cause chart to crash.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
