### ISSUE TITLE
Tooltip over the category/value axis labels instead of on series/columns

### ISSUE THREAD

**Issue by sridhargk-thoughtclan** [amcharts/amcharts5#424]
**Question**

Is there any way to provide a tooltip over the labels on the category/value axis of a bar chart / any XY charts instead of on the columns using XYCursor?

I tried out the same bar graph in order to achieve the tooltip over the label on the category axis along with the cursor method to find out the differentiation.

Please find the sample in Code Sandbox: https://codesandbox.io/s/amcharts-horizontal-bar-tooltip-6ooxqe?file=/src/BarChart.jsx

**Environment**

 - amCharts 5.2.2
 - ReactJS

**Comment by zeroin** [comment]
The easiest way to do this would be to create a setup method, which would add a background to a label, make it interactive and set tooltipText. You should also use a separate tooltip, as otherwise it will use axis tooltip (if created) which has bounds set by the cahrt and might be positioned in a wrong way. Here is a sample:

```
var tooltip = am5.Tooltip.new(root, {});

yAxis.get("renderer").labels.template.setup = function(label){
  label.set("tooltipText", "{category}");
  label.set("background", am5.Rectangle.new(root, {fillOpacity:0, fill:am5.color(0x00ff00)}))
  label.set("tooltip", tooltip);
  label.set("tooltipY", 5);
}
```

**Comment by sridhargk-thoughtclan** [comment]
Thanks @zeroin the fix is working fine.
