### ISSUE TITLE
axis.get('renderer').labels only include every n AxisLabels, accordingly to the data length?

### ISSUE THREAD

**Issue by sgarza-ksm** [amcharts/amcharts5#430]
in a theme, I am running an after-effect on a Category Y Axis's `dataValidated` event that wants to update the positions of all axis labels. while building this out with smaller data sets it seemed to work properly; however, as i load increasingly larger data sets, i find that only every `n` items are actually included in `.labels`, respective to the size of the data.

I switched to trying to iterate through the axis's `.dataItems` where all data is included, but again in the `_settings` only those axis labels in `.labels` have a `_settings.label` themselves to reference, all the non-referenced data items still have `_settings.category` populated with the label's text.

this feels like a bug, but if not, where could  i find all axisLabels included in an axis?

Below are examples of larger and smaller data sets, respectively, with the succesfully updated labels recolored as well as being in an exagerated position to where i would like them

<img width="987" alt="image" src="https://user-images.githubusercontent.com/57367214/169114743-f090d444-7e25-403a-8b46-167d29cf2c17.png">

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/57367214/169114872-6ec8825b-a932-4cf1-abaa-43e17e5c4dff.png">

 - amCharts version: 5.1.x, persisted after updating to 5.2.4
 - Browser and its version: Google Chrome Version 101.0.4951.54 (Official Build) (arm64)
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.]: Typescript, React

If my approach is correct and it may be my theme or further details are needed, id be happy to write up an example, thank you

**Comment by martynasma** [comment]
Labels are visual elements. It's not data. Axis decides to skip labels/grid dynamically, in order to make them not too crammed.

Details are here:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#grid-density

If there is no label associated with the data item, it means there is no label displayed, so it does not need to be modified in any way.

If you want all grid/labels to be displayed, you can set `minGridDistance: 1` in your axis renderer's settings.

It's not a bug, it's by design.

Hope it makes sense.
