### ISSUE TITLE
Leftover canvases when using export plugin

### ISSUE THREAD

**Issue by SDVII** [amcharts/amcharts5#437]
**Bug description**

When using the exporting plugin, a top level canvas is created and not disposed of every time an export is initiated.

_Steps:_

1. Create chart and export it to pdf or data URI
2. Cancel the export
3. Check the document's body. You'll find a canvas remaining there.
4. Export again and cancel
5. Check the document's body. You'll find a new canvas after the older one

_Reproduction:_
- https://codepen.io/team/amcharts/pen/jOwObzV
![export](https://user-images.githubusercontent.com/10416702/169987247-93a03672-bb93-4f88-8531-f4058c3f9371.gif)

**Environment**

- amCharts: v.5.1.14
- Edge: v.101.0.1210.47
- React: v.16.14.0,

**Comment by martynasma** [comment]
Fixed in [5.2.6](https://github.com/amcharts/amcharts5/releases/tag/5.2.6).

## [5.2.6] - 2022-05-25

### Added
- `nodePadding` added to `Pack`.
- `maxTooltipDistanceBy` with possible values `"x"`, `"y"`, and `"xy"` added. Indicates how distance from mouse pointer to the tooltip point should be measured when comparing with `maxTooltipDistance`.

### Fixed
- Exporting chart image was creating leftover canvas elements in the body of the document.
- Further improvements in `DateAxis` performance with grouping and timezone enabled.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
