### ISSUE TITLE
Updating PieChart series alignLabels performance

### ISSUE THREAD

**Issue by alenyu6** [amcharts/amcharts5#442]
Hi, I'm working on a React Typescript project that allows the user to toggle the Pie Chart settings and updates the chart on the fly. There are a few properties that don't update the Pie Chart without having to force some of re-rendering by updating either the data, or reconstructing a chart element. 

The example I am currently working with is setting the alignLabels setting by toggling a checkbox. In amCharts 4, I can easily update the the alignLabels property and have it re-render simply by setting the property. In amCharts 5, I've only been able to consistently update the alignLabels property by removing the series from the chart and creating a brand new one with the updated value. I have not been able to get this to work with other methods such as markDirtyValues/appear or updating the setting and re-setting the data on the series. The performance seems to suffer from this because of the need to reconstruct a brand new series (drawing and all) every time the value is changed. Admittedly, this is is probably a bit of an edge case regarding how this library should be used. I was wondering if there are any recommendations in completing the above or if this is a bug that needs to be caught? 

I've created some codepens that are based off the sample projects from the site, both were tested on Chrome Version 101.0.4951.67:

amCharts 4:
https://codepen.io/alyu5/pen/vYdWJaJ

amCharts 5:
https://codepen.io/alyu5/pen/wvyPqGp

Looking at the performance tool, amCharts 5 spends almost 5 times more time on scripting (which I'd expect with having to reconstruct the series every time), and gets worse when other settings (ticks, labels) need to be re-applied to the new series.

EDIT: On a side note, the amCharts 5 codepen above has the ticks flickering when toggling the setting, I was wondering if there was a to prevent that from happening without doing some odd hide/show of ticks.

**Comment by martynasma** [comment]
Fixed in [5.2.7](https://github.com/amcharts/amcharts5/releases/tag/5.2.7).

## [5.2.7] - 2022-06-07

### Added
- `minDistance` to `LineSeries` (default: 0). If set, it will skip line points closer than X pixels, resulting in a smoother, less cluttery line.
- `isVisibleDeep()` method to `Sprite`. Check not only if `Sprite` itself is visible, but also its all ascendants.

### Changed
- TAB press should now skip over focusable elements of hidden series.

### Fixed
- Toggling `PieSeries` `alignLabels` after the chart was initialized was not working.
- Fixing bug where the wheel event would sometimes not trigger.
- When setting `stockSeries` with a new series on `StockChart` it was not inheriting `stockPositiveColor`/`stockNegativeColor` values.
- Tweaked default `StockToolbar` CSS to act better on pages with larger font sizes.
- DOM elements for focusable series items (columns, bullets, etc.) were being left behind when data for series was updated.
- Exporting chart to image was not inheriting document styles properly.
- If stock series increase/decrease colors were changed and then a series type was changed, new series used to reset colors and not use the ones user set.
- Dynamically changing page-wide font-related CSS (e.g. via media queries) could cause visual anomalies on the chart, especially on axes.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
