### ISSUE TITLE
Stock Charts Color Settings isn't Reflected if Candle Type is Changed

### ISSUE THREAD

**Issue by cwooldridge1** [amcharts/amcharts5#445]
I have noticed that if you change the color of a 'main series' and then you change the candle type what happens is the previous color setting is forgotten about in terms of how it is plotted however in the legend settings the correct color that you changed it to previously is shown. 
For example say a change the color to pink:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/85259389/171051579-cf4aae60-4b1e-4e01-83f1-dbf75771e4a7.png">

Then I change the candle type:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/85259389/171051612-b3881816-24ce-4bbd-94cc-e2766f4dfb24.png">
As you can see it is now green instead of pink.
However the legend still says that it should be pink:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/85259389/171051655-d03167c0-3cc0-45c0-816b-08b180fac441.png">

Also, I have noticed that if you change it to a line, there are no options to change the line's color.

Ultimately what would be nice and is something to think about is creating some event listener for when the color changes/any inputs/settings change so the developer can somehow save the users' inputs to be remembered beyond the current session.

The above screenshots are captured from this demo on the site https://www.amcharts.com/demos/stock-chart-comparing-prices/

**Comment by martynasma** [comment]
Fixed in [5.2.7](https://github.com/amcharts/amcharts5/releases/tag/5.2.7).

## [5.2.7] - 2022-06-07

### Added
- `minDistance` to `LineSeries` (default: 0). If set, it will skip line points closer than X pixels, resulting in a smoother, less cluttery line.
- `isVisibleDeep()` method to `Sprite`. Check not only if `Sprite` itself is visible, but also its all ascendants.

### Changed
- TAB press should now skip over focusable elements of hidden series.

### Fixed
- Toggling `PieSeries` `alignLabels` after the chart was initialized was not working.
- Fixing bug where the wheel event would sometimes not trigger.
- When setting `stockSeries` with a new series on `StockChart` it was not inheriting `stockPositiveColor`/`stockNegativeColor` values.
- Tweaked default `StockToolbar` CSS to act better on pages with larger font sizes.
- DOM elements for focusable series items (columns, bullets, etc.) were being left behind when data for series was updated.
- Exporting chart to image was not inheriting document styles properly.
- If stock series increase/decrease colors were changed and then a series type was changed, new series used to reset colors and not use the ones user set.
- Dynamically changing page-wide font-related CSS (e.g. via media queries) could cause visual anomalies on the chart, especially on axes.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
