### ISSUE TITLE
data grouping not working if series is added in a second time

### ISSUE THREAD

**Issue by estradege** [amcharts/amcharts5#46]
Hello,
datagrouping is not working if the series is added in a second time (on a button click for example).
it works only if in the addSeries() function, I create also an other xAxis. Is it the right way ?

https://codepen.io/gestrade/pen/porPBBY

**Comment by martynasma** [comment]
Fixed in [5.0.0-beta.40](https://github.com/amcharts/amcharts5/releases/tag/5.0.0-beta.40).

## [5.0.0-beta.40] - 2021-10-30

### Fixed
- `Label` setting `oversizedBehavior` was not working properly when heigh/with was 0.
- `XYSeries` was not calculating `maxWidth`/`maxHeight` properly on data items with negative values.
- Data grouping was not being applied when data was being updated after chart init.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download-v5/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
