### ISSUE TITLE
Map disappears after setting series data

### ISSUE THREAD

**Issue by matissb77** [amcharts/amcharts5#464]
Hi, 
I have I have initialized a Map, set heatRules and then set the data on the polygonSeries by calling polygonSeries.data.setAll( countryData ).
Everything works fine until I try to set new data on the polygonSeries. When I call polygonSeries.data.setAll( newData ) from a separate function with the help of a button the whole map just disappears.

`countryData = [{value: 6, id: 'BY'}, {value: 20, id: 'LV'}]
newData = []
`

**Comment by martynasma** [comment]
The `newData` in your snippet is just an empty array, hence the empty map.

Or am I missing something here?

**Comment by matissb77** [comment]
Yes, it is.  
After reading your comment maybe I do not understand the whole process completely.
The map also disappears when I call setMapData() without an empty array.
`const setMapData = () => {
    mapPolygonSeries.data.setAll([{
            value: 100,
            id: 'LV'
        },
        {
            value: 60,
            id: 'BY'
        }
    ]);
}`
My final question then would be - 
How do I update the map data so that the heatRules also update and the map does not disappear?

**Comment by martynasma** [comment]
Gotcha. Thanks.

Yeah, we'll need some nice way to trigger re-application of GeoJSON of data, when it is updated.

Will keep you posted.

**Comment by matissb77** [comment]
Okay. Thanks for responding!

**Comment by matissb77** [comment]
What I did for now was dispose the polygonSeries by calling `polygonSeries.dispose()` and then setting everything else that was necessary again (`chartMap.series.push(), polygonSeries.mapPolygons.template.setAll(), ... `).

Now after including that into `setMapData()` before the `polygonSeries.data.setAll()` everything works as needed.

**Comment by martynasma** [comment]
Yeah, that should work. But after next update, you won't have to do it. Doing `setAll()` on data will automatically update heatmaps without destroying the map.

I'll ping you here when the new version is out. Possibly within a day or two.

**Comment by martynasma** [comment]
Fixed in [5.2.10](https://github.com/amcharts/amcharts5/releases/tag/5.2.10).

## [5.2.10] - 2022-06-28

### Added
- `lineJoin` setting added to `Graphics` (default: `"miter"`). Possible values: `"miter"`, `"round"`, and `"bevel"`. [More info](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin).

### Fixed
- `GaplessDateAxis` with one data item was not showing date label at all.
- Setting `colors` on a `ColorSet` will now properly reset all iterators, so that new color generation is consistent.
- If `data.setAll()` was called on a `MapSeries` with `geoJSON` set previously, objects from geoJSON would disappear.
- `PieSeries` was not keeping active slice pulled out when it was hidden and then shown up again.
- PDF export was not taking page orientation into account when auto-fitting an image.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by matissb77** [comment]
Thanks a lot!
