### ISSUE TITLE
RadialGradient not centered on series (V5)

### ISSUE THREAD

**Issue by dsinger376** [amcharts/amcharts5#468]
Hello,

My team is using a licensed version of Amcharts v5.2.10, and I am **having trouble centering the radial gradient used for a series fill gradient**.  Using combinations of centerX, centerY, width, height, x, y, dx, dy, and other properties applied to different elements (the chart, x and y axes, and series) didn't help.  **I have included a screenshot and codepen link** for reference.  Any insight you can share to help resolve this issue would be greatly appreciated.  Thanks!

https://codepen.io/dansinger456/pen/abYbYWR?editors=1010

**Environment **
React app running v18.1.0
Amcharts Version: 5.2.10

<img width="711" alt="radialGradient issue" src="https://user-images.githubusercontent.com/88509443/176335032-524ebdfb-741c-47ef-9361-b70e5b39a1da.png">

**Comment by zeroin** [comment]
Hi,

It's a bug on our side, we will fix it in next release and will let you know. 
When the fix is available, you'll have to set x:0 and y:0 for your RadialGradient in order the gradient to be positioned correctly.

**Comment by dsinger376** [comment]
Sounds good, thanks for letting me know.  Looking forward to next release 👌

**Comment by martynasma** [comment]
Fixed in [5.2.11](https://github.com/amcharts/amcharts5/releases/tag/5.2.11).

## [5.2.11] - 2022-07-18

### Added
- A new setting `deactivateRoot` (default: `true`) added to `Modal`. Indicates if any interactivity on the underlying chart should be disabled when modal is open.
- A new setting `html` added to `Container`. Set it to a string with HTML to be used as container's content. Will work on any element inheriting from `Container`, e.g. `Label`. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/html-content/).
- A new setting `labelHTML` added to `Tooltip`. If set, will ne used as HTML content for the tooltip. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/html-content/).
- A new setting `tooltipHTML` added to `Sprite`. If set, will ne used as HTML content for the tooltip when element is hovered. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/html-content/).
- `wheelZoomPositionX` and `wheelZoomPositionY` added to `XYChart`. This value is not set by default, but you can use it to fix wheel zooming, to the end (if you set it to 1) or to the start (0) or middle (0.5). In `StockChart`, it is set to 1 by default, as this is common practice in financial charts.
- "Volume-Weighted Average Price (VWAP)" indicator added to `StockChart`.

### Changed
- Setting `id` setting when creating an object will not register it in `am5.registry.entitiesById` immediatelly, without waiting for the next frame.

### Fixed
- `RadialGradient`'s `x` and `y` settings were being ignored.
- Labels as bullets with `oversizedBehavior` set were not being displayed properly in some cases.
- `DateAxis` with `startLocation = 0.5` and `endLocation = 0.5` and single value only was showing a really big date range.
- Resizing `PieChart` to a very small size with a legend positioned on the left or right could cause some anomaly in layout.
- Updating `CategoryAxis` data with less items than there was originally was causing old columns/bullets to be shown.
- Setting `verticalScrollbar` on `Container` to `undefined` to remove a previously set scrollbar was not working.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
