### ISSUE TITLE
Windows with 150% scaling calculate wrong chart size by 1/2px

### ISSUE THREAD

**Issue by dnmsk** [amcharts/amcharts5#471]
Windows with Chrome browser, select system scaling 150%.
For example, reproduce on [demo](https://www.amcharts.com/demos/candlestick-chart/) . Set `padding: 0` to element div.content-demos for full-width chart. Page will appear with scrolling. Expected: no scrolling.

**Comment by martynasma** [comment]
I'm not sure I follow. Why would a page appear without scrolling?

Also, is this about our website, or amCharts 5? This is a repo for amCharts 5 lib.

**Comment by dnmsk** [comment]
@martynasma 
Amcharts5 lib. Chart with width 100% of page, when no one element has margin or padding, adds 0.5 additional width to canvas when windows display has scaling 150%. It appear bottom scrolling on page, but it no needed. When I have 2 displays , one with scaling 150%, another with 100% - I see bottom scroll on one with scaling and don't see scroll after move browser to display without scaling.
That issue can be reproduced on any amcharts demo with small manipulation.

I'm sorry for short description.

**Comment by sassomedia** [comment]
@dnmsk Not sure what your goal is but I would generally not recommend scaling any website. If you need to in order to be able to better read text, sure, but I would not expect the layout to work properly. Designing and developing for browser scaling is a nightmare, hence why most sites will not bother to check for that.

Instead, what you could do is turn on viewport scaling in your OS' accessibility settings. This will scale the whole viewport and keeps the browser scale intact at 100%. Similar to pinch-to-zoom on a phone.

**Comment by dnmsk** [comment]
@sassomedia I'm wrote about viewport scaling (=windows display scaling or system scaling 150%) in OS' accessibility settings.

**Comment by martynasma** [comment]
@sassomedia I think what @dnmsk says is that he is using OS-based zoom, which is very common with Retina-like displays.

I was able to reproduce this on Windows with 150% OS zoom. It seems there's something off with the rounding of scaled canvas we're using.

We're looking into it.

**Comment by sassomedia** [comment]
Ok, so he's talking about Windows, not windows. Got it.

**Comment by martynasma** [comment]
Fixed in [5.2.15](https://github.com/amcharts/amcharts5/releases/tag/5.2.15).

## [5.2.15] - 2022-08-06

### Added
- Added `PicturePattern` that allows using external images as patterns. [More info](https://www.amcharts.com/docs/v5/concepts/colors-gradients-and-patterns/patterns/#Image_patterns).

### Fixed
- Fixing issue where chart scrollbar would break when zooming.
- Fixing chart being too large and overflowing when zooming in ([Issue 471](https://github.com/amcharts/amcharts5/issues/471)).
- `pan:"zoom"` was not working on left-side Y Axis.
- Removing a panel from a `StockChart` was not removing indicator from charts `indicators` list.
- Zooming chart with custom timezone was resulting in errors in some cases.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
