### ISSUE TITLE
tooltip :similar to keeptargethover property of amcharts 4 not able to find in amcharts 5.

### ISSUE THREAD

**Issue by shanqq** [amcharts/amcharts5#489]
i am tryingto keep the hover on in sunburst chart. last depth which is of size three.

**Comment by martynasma** [comment]
There's currently no such feature available. I'm marking this as an enhancement request. Will let you know here if/when we implement it.

Thanks!

**Comment by martynasma** [comment]
Added in [5.2.14](https://github.com/amcharts/amcharts5/releases/tag/5.2.14).

## [5.2.14] - 2022-07-23

### Added
- New setting `keepTargetHover` added to `Tooltip` (default: `false`). If set to `true`, hovering the tooltip will be treated like hovering its target element itself.

### Fixed
- Removing `verticalScrollbar` from a `Container` was causing some issues.
- Labels with HTML content and horizontal padding were not being sized/centered properly.
- Date formatting code "EEEE" was producing weekday's short version ("Tue") instead of full one ("Tuesday").
- `Scrollbar` was not working after it was zoomed and clicked on a background to change position, if no animated theme was used.
- Paused animations will no longer obstruct chart export.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
