### ISSUE TITLE
exporting.download() on Radar chart freezes the browser tab

### ISSUE THREAD

**Issue by mayurhotwani** [amcharts/amcharts5#498]
**Bug description**

- I have a dropdown menu item "Export chart as Png", on click of it I use the exporting.download('png') to download the chart snapshot as image.
- While clicking the menu item for the Radar chart freezes the browser tab completely and i cannot interact with it anymore, only way is to force close the tab and relaunch again
- after investigation I found that there is some issue with the exporting.download() function

**Environment (if applicable)**
- Angular 12
- @amcharts/amcharts5": ^5.1.7
- typescript: ~4.3.2

**Additional context**
- download() works fine for my other chart types - Donut, Bar, funnel

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

I just tested export with a RadarChart, and it works fine:
https://codepen.io/team/amcharts/pen/GRxmPyj/a23943497c36939ae11bf8b73334e6df?editors=0010

**Comment by mayurhotwani** [comment]
u are using the "menu" from epxorting
can u try on exporting.download('png)
this is my code: 
  public downloadChartImage(root, filePrefix: string): void {
    const exporting = Exporting.new(root, {
      filePrefix: filePrefix || 'chart',
      backgroundColor: am5.color('#FFFFFF'),
    });
    exporting.download('png');
  }
  
  Also I see that this is working on safari browser, but not working on chrome latest version - Version 103.0.5060.134 (Official Build) (arm64) - can u replicate this env and code?

**Comment by martynasma** [comment]
Fixed in [5.2.14](https://github.com/amcharts/amcharts5/releases/tag/5.2.14).

## [5.2.14] - 2022-07-23

### Added
- New setting `keepTargetHover` added to `Tooltip` (default: `false`). If set to `true`, hovering the tooltip will be treated like hovering its target element itself.

### Fixed
- Removing `verticalScrollbar` from a `Container` was causing some issues.
- Labels with HTML content and horizontal padding were not being sized/centered properly.
- Date formatting code "EEEE" was producing weekday's short version ("Tue") instead of full one ("Tuesday").
- `Scrollbar` was not working after it was zoomed and clicked on a background to change position, if no animated theme was used.
- Paused animations will no longer obstruct chart export.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
