### ISSUE TITLE
@amcharts/amcharts5 doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module

### ISSUE THREAD

**Issue by dorklein** [amcharts/amcharts5#499]
**Bug description**

I'm running amcharts5 in a nuxtjs 3 application. When building the app it gives me this message:
```@amcharts/amcharts5 doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.```

**Environment (if applicable)**
@amcharts/amcharts5: "^5.2.13"
nuxt: "3.0.0-rc.4"

**Additional context**
I have a workaround for the development server, but it fails again when trying to build the app.
```typescript
//nuxt.config.ts
// This only works for the dev environment
export default defineNuxtConfig({
   build: {
        transpile: ['@amcharts/amcharts5'],
    }
})
```

**Comment by Pauan** [comment]
I can't reproduce that error.

I [installed Nuxt 3](https://v3.nuxtjs.org/getting-started/installation) and followed [our Vue tutorial](https://www.amcharts.com/docs/v5/getting-started/integrations/vue/). I got the following error: `Cannot use import statement outside a module`

I fixed the error by [wrapping the component in `<ClientOnly>`](https://v3.nuxtjs.org/guide/directory-structure/components/#clientonly-component), like this:

```ts
<ClientOnly>
  <Chart />
</ClientOnly>
```

Alternatively, you can fix it by [naming your component](https://v3.nuxtjs.org/guide/directory-structure/components/#client-components) `Chart.client.vue` instead of `Chart.vue`

**Comment by OwsOwies** [comment]
I have the same issue with

"@sveltejs/kit": "1.0.0-next.539"
"vite": "3.2.3"

This warning was present in previous versions too, but now it also breaks in runtime:
`Unexpected token 'export'
export { Root } from "./.internal/core/Root";`

**Comment by Pauan** [comment]
@OwsOwies Since you're using SvelteKit / Vite I think that's a different issue.

That looks like a bug with Vite or SvelteKit. They claim to support ES6 modules, and amCharts uses ES6 modules, so it should work.
