### ISSUE TITLE
Legend label dynamically ajust width 

### ISSUE THREAD

**Issue by justine-mlss** [amcharts/amcharts5#506]
Hello,

I've got many issues with my area legend labels. 

**A)** I want to optimize space and so delete unused space between labels.
My legend can be very long and I notice that the labels are aligned line to line and so, so much space are wasted (wasted spaces are  surrounded) => 

![legend_wasted](https://user-images.githubusercontent.com/66368359/180828264-a9bcbba4-849d-48cd-82ac-7f19bac93f98.png)

1) Is there a solution to avoid line to line alignment ? 
2) Is there a way to ajust dynamically label width depending of the length of the label ?

```
  const legend = chart.children.push(
    am5.Legend.new(root, {
      centerX: am5.p50,
      x: am5.p50,
      y: am5.percent(98),
    }),
  );

  legend.labels.template.setAll({
    fontSize: areaFontSize,
  });

  legend.valueLabels.template.setAll({
    width: 0,
  });

  legend.markers.template.setAll({
    width: 5,
    height: 5,
  });
  legend.data.setAll(chart.series.values);
```

**B)** Always with the aim of saving space, I want to reduce spaces between legend lignes. But when I set an height to label, markers are no longer aligned with label =>

![legend_alignement](https://user-images.githubusercontent.com/66368359/180816107-2fb1350a-6972-42ce-b3ba-9a3164ffed65.png)

```
  const legend = chart.children.push(
    am5.Legend.new(root, {
      centerX: am5.p50,
      x: am5.p50,
      y: am5.percent(98),
      paddingTop: 10,
    }),
  );

  legend.labels.template.setAll({
    fontSize: areaFontSize,
    height: 1,
  });

  legend.valueLabels.template.setAll({
    fontSize: areaFontSize,
    width: 0,
  });

  legend.markers.template.setAll({
    width: 5,
    height: 1,
  });
  legend.data.setAll(chart.series.values);
```

Thank you !!

**Comment by martynasma** [comment]
> Is there a solution to avoid line to line alignment ?

I'm afraid there's no way to make multi-line layout to not arrange items in columns.

Besides that would probably look quite confusing to user, not to mention that color-coded legend loses its actual usefulness to the user once the count of the items goes above 10.

Just look at these colors:
![image](https://user-images.githubusercontent.com/1458520/180985422-53ab5320-4278-4bbf-b4f5-6da7e0a44b7c.png)

Do you expect user to make a connection between these shades of purple in legend and in chart itself?

Just mentioning it, since you might want to reconsider your chart setup for a better UX.

> Always with the aim of saving space, I want to reduce spaces between legend lignes. But when I set an height to label, markers are no longer aligned with label =>

That can be best achieved by reducing item padding:

```JavaScript
legend.itemContainers.template.setAll({
  paddingTop: 2,
  paddingBottom: 2
});
```

**Comment by justine-mlss** [comment]
Ok thank you ! So useful the _legend.itemContainers.template_ !
