### ISSUE TITLE
Zooming by panning axis not working on Y

### ISSUE THREAD

**Issue by olimexsmart** [amcharts/amcharts5#513]
Zooming by panning ([docs](https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Zooming_by_panning_axis), [provided example](https://codepen.io/team/amcharts/pen/abyMJmZ)) does not work on Y axis. 

I don't know if it's the example that is broken or the library itself. I tried implementing it on another plot and I obtain the same result.

On X axis it works fine.

**Comment by martynasma** [comment]
It looks like it's working if Y axis is put to the right.

We will look into it, why `pan: "zoom"` does not work for left Y axis.

Thanks.

**Comment by martynasma** [comment]
Fixed in [5.2.15](https://github.com/amcharts/amcharts5/releases/tag/5.2.15).

## [5.2.15] - 2022-08-06

### Added
- Added `PicturePattern` that allows using external images as patterns. [More info](https://www.amcharts.com/docs/v5/concepts/colors-gradients-and-patterns/patterns/#Image_patterns).

### Fixed
- Fixing issue where chart scrollbar would break when zooming.
- Fixing chart being too large and overflowing when zooming in ([Issue 471](https://github.com/amcharts/amcharts5/issues/471)).
- `pan:"zoom"` was not working on left-side Y Axis.
- Removing a panel from a `StockChart` was not removing indicator from charts `indicators` list.
- Zooming chart with custom timezone was resulting in errors in some cases.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
