### ISSUE TITLE
StockChart get Freeze on some closing operations in Panel

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#537]
**Bug description**
StockChart get Freeze on closing operations in Panel

Click on link to see code:
https://jsfiddle.net/9tyur0ch/

Steps to create issue:
1. Click on Close button of Volume Panel
2. add any indicator from indicator list
3. you will see chart is freeze.....

**Environment (if applicable)**
 - amCharts version: updated CDN
 - Browser and its version: Chrome Updated
 - Related frameworks and their versions : JS

**Comment by martynasma** [comment]
Fixed in [5.2.16](https://github.com/amcharts/amcharts5/releases/tag/5.2.16).

## [5.2.16] - 2022-08-16

### Changed
- A clicked `PeriodSelector` button will now stay highlighted until other button is clicked, or chart is zoomed in any other way.
- `SpriteResizer` class moved to main package. It's now accessible via `am5.SpriteResize`.

### Fixed
- Better initial sizing of HTML-content tooltips.
- `MapChart` pan bounds were incorrect after size of a chart's div changed significantly.
- If a panel with a volume series of `StockChart` or volume series itself was removed, adding indicators after this was resulting in an error.
- On a chart with a `CategoryAxis` and series with non-consistent data, some data items might become invisible in some cases.
- Removing a point from `MapPointSeries` was not affecting the `MapLineSeries` with lines that had this point in their `pointsToConnect` setting.
- A `Label` rotated at `-90` angle was not being properly hidden as per `oversizedBehavior: "hide"`.
- Opening a settings modal from `StockLegend` would cause chart to be panned/zoomed when modal was claused.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
