### ISSUE TITLE
Can't see tooltips on truncated labels of Y axis

### ISSUE THREAD

**Issue by jdim** [amcharts/amcharts5#539]
**Bug description**

Hello. There are truncated long labels on my chart's Y axis. I need a way to show a tooltip with the full text of the label.

Currently, trying to implement this via `axisRendererY.labels.template`, but it doesn't work:

```
axisRendererY.labels.template.setAll({
    maxWidth: 150,
    oversizedBehavior: 'truncate',
    tooltipText: 'Item: {valueY}',
})
```

Code example here:
https://codepen.io/dm-khabarov/pen/zYWLjye

**Environment (if applicable)**

 - amCharts 5
 - Browser Chrome
 - Related frameworks: React, but the example from demos

**Additional context**

As a bonus, how can I show a pointer cursor on label hover?

Thanks.

**Comment by martynasma** [comment]
Labels themselves cannot be interactive in amCharts 5. To add any kind of interactivity, you need to add a background to them.

For axis labels, it means setting up template setup function.

More info and examples here:
https://www.amcharts.com/docs/v5/concepts/common-elements/labels/#interactive-axis-labels

**Comment by ankit-mercer** [comment]
Hello,

In my case, I am trying to show a very long text on hovering axis label but due to the length of the tooltip label text it goes outside the chart, I tried applying width to the tooltip but it does not work. I have also tried the method in which we fix width for the series tooltip but that too did not worked in axes label case.

Is there any way through which we can fix the width and apply oversizedBehavior: "wrap" to the tooltip of axis labels, so that  long text breaks to the new line if it goes beyond the given width of tooltip.
