### ISSUE TITLE
Typings in amCharts 5 for example - dataContext: unknow

### ISSUE THREAD

**Issue by tscislo** [amcharts/amcharts5#541]
In general I observed that amCharts 5 is poorly typed. In many cases props are typed as unknown which causes issues with TypeScript based projects.
I think that the most prominent example is dataContext being typed as unknown in many cases.

**Comment by martynasma** [comment]
We use `unkown` in a a very few places. In those places where we cannot enforce any kind of structure, like `dataContext` that you mentioned, which is a raw user data. We cannot possibly know what kind of mumbo-jumbo users could have in their data, and we can't possibly restrict that.

Hope that makes sense.

**Comment by tscislo** [comment]
You could use generic types for this. With current version of AmCharts in our TS code we need to use @ts-ignore a lot

**Comment by Pauan** [comment]
@tscislo Originally we did try using generics, but it caused a lot of extra complexity and problems, because the generic has to be used all over the place.

In most cases TypeScript can't infer the correct type anyways, and the data is often retrieved with JSON (which has no static types), so it wasn't worth it.

If you know the static type of the data, you can easily use `as` to convert it:

```ts
interface IFoo {
    foo: string;
    bar: number;
}

data.dataContext as IFoo
```

**Comment by daniel-ricado** [comment]
have it accept a type <T> or just use a generic type. 

It's completely weird to being throwing ts-ignore all over that place when using amcharts
