### ISSUE TITLE
Rotated label bullet and incorrect oversizedBehavior

### ISSUE THREAD

**Issue by DanielScholte** [amcharts/amcharts5#543]
**Bug description**

When using `oversizedBehavior` on a rotated label bullet, it seems like the oversized calculation doesn't account for the rotation of the label.  

**Example**
Take the following codepen: https://codepen.io/danielscholte/pen/zYWJyGE  
The chart contains two columns with labels, but the label in one of the columns is rotated 90 degrees.  
Furthermore, both labels have their `padding` set to `0` and have their `oversizedBehavior` set to `hide`.  
When you change the width of the chart (change the css or the width of your browser window), you can see that both labels get hidden at the same time.  
I would expect the rotated label to stay visible for longer, as there is more horizontal space available because it's rotated.  
It seems like the `oversizedBehavior` calculation does not account for the rotation of the label.

**Environment (if applicable)**

- AmCharts version 5.2.15

**Comment by martynasma** [comment]
Fixed in [5.2.16](https://github.com/amcharts/amcharts5/releases/tag/5.2.16).

## [5.2.16] - 2022-08-16

### Changed
- A clicked `PeriodSelector` button will now stay highlighted until other button is clicked, or chart is zoomed in any other way.
- `SpriteResizer` class moved to main package. It's now accessible via `am5.SpriteResize`.

### Fixed
- Better initial sizing of HTML-content tooltips.
- `MapChart` pan bounds were incorrect after size of a chart's div changed significantly.
- If a panel with a volume series of `StockChart` or volume series itself was removed, adding indicators after this was resulting in an error.
- On a chart with a `CategoryAxis` and series with non-consistent data, some data items might become invisible in some cases.
- Removing a point from `MapPointSeries` was not affecting the `MapLineSeries` with lines that had this point in their `pointsToConnect` setting.
- A `Label` rotated at `-90` angle was not being properly hidden as per `oversizedBehavior: "hide"`.
- Opening a settings modal from `StockLegend` would cause chart to be panned/zoomed when modal was claused.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
