### ISSUE TITLE
Amchart5 Stock chart

### ISSUE THREAD

**Issue by ankit-mercer** [amcharts/amcharts5#551]
How can we remove the increase/decrease option from the popup of first in stock chart.

**Comment by martynasma** [comment]
Are you referring to some specific demo? Can you provide a link? I'm not sure about the context of this question.

**Comment by ankit-mercer** [comment]
I am sharing demo link from amchart site - https://www.amcharts.com/demos/stock-chart-comparing-prices
I want to remove the increase/decrease popup which appears while user click the gear icon of first series only.

**Comment by martynasma** [comment]
Gotcha. Thanks.

Please refer to this tutorial on how to disable certain legend icons:
https://www.amcharts.com/docs/v5/charts/stock/stock-legend/#Settings_and_close_buttons

**Comment by ankit-mercer** [comment]
We want to keep color palate option for all legends except the first but wants to remove specific "Increase and Decrease" option from the popup of first legend as shown in the attached screenshot.
![image](https://user-images.githubusercontent.com/96469108/185628810-88ba58c0-061b-4238-b59c-34e3b012c57e.png)

**Comment by martynasma** [comment]
You want to remove Increase/Decrease but leave empty popup?

I'm not entirely sure I follow :)

**Comment by ankit-mercer** [comment]
I don't want the increase/decrease popup here. It should be as follow:

1. Popup should have features similar to other popup of comparing series. Screenshot attached:
<img width="148" alt="Capture" src="https://user-images.githubusercontent.com/96469108/185868249-0764fd55-89f1-4ff7-9f0e-c21bfe26a71d.PNG">
2. If the above is not possible, the gear icon which triggers this popup should be hidden.

Thanks!

**Comment by martynasma** [comment]
Well, for the CandlestickSeries automatic popup shows two options: Increase and Decrease colors.

For LineSeries, it shows line color and thickness selection.

There's currently no easy way to add above settings to a CandlestickSeries.

You can disable settings dialog for that series altogether, as per the tutorials I linked to earlier.

**Comment by ankit-mercer** [comment]
We are not using candlestick series at all, even then the first line series are showing the increase/decrease popup. This should be not the case as per our methodology. 
Can you suggest how can we disable this.

**Comment by martynasma** [comment]
Can you share your chart setup in a CodePen? You shared a link to an amCharts demo, which does use CandlestickSeries.

**Comment by ankit-mercer** [comment]
Sharing the codepen for reference: https://codepen.io/gurkirat_turna/pen/wvmLZzG?editors=0010.

**Comment by martynasma** [comment]
Thanks!

This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by ankit-mercer** [comment]
Thanks! Kindly also add feature where user can close the first option.

**Comment by martynasma** [comment]
Fixed in [5.2.20](https://github.com/amcharts/amcharts5/releases/tag/5.2.20).

## [5.2.20] - 2022-09-05

### Added
- All indicator series will now have `"indicator"` theme tag set. Detect indicator series via `series.hasTag("indicator")`.
- `autoZoom` added to `ValueAxis` (default: `true`). If set to `false`, the axis won't be auto-zoomed to a selection (this works only if the other axis is a `DateAxis` or a `CategoryAxis`). This setting will be ignored if both X and Y axes are a `ValueAxis`.
- `StandardDeviation` indicator added.

### Changed
- Series edit modal on a `StockChart` would show incorrect controls if the main chart series was a `LineSeries`.

### Fixed
- Initial sizing of HTML tooltips fixed (again).
- Exporting a chart in a `<div>` with `height: auto` was not working properly.
- If a point in a `LineSeries` was way out of bounds (million times further than the bounds of plot area), the line could disappear.
- In some cases, if chart was using loadable fonts, it could go into non-stop flickering mode.
- `StockChart` with drawing mode disabled could start drawing new objects if clicked on points of an old drawing.
- `PointedRectangle`, mostly used by a `Tooltip` was drawn incorrectly if its stem size was bigger than height. 
- Removing a `QuadrantLineSeries` drawing from a `StockChart` resulted an error.
- It was impossible to delete `Fibonacci` or `FibonacciTimezone` drawings one by one after switching to another drawing tool.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
