### ISSUE TITLE
Incremental on-demand data loading for StockCharts with Comparing Series

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#560]
I have Implemented Incremental on-demand data loading for StockCharts, with the reference
https://www.amcharts.com/docs/v5/tutorials/incremental-on-demand-data-loading/

I know you have implemented above on XYChart. but i needed it in StockChart

but, when it comes with the add comparing series, it having issues like,
1. sometimes, the main chart is stick at back, and just newly added series is moving.
2. Incremental on-demand data loading for newly added series.
3. and if zoom out, the main chart series is hidden, and just data is incremented.

Check My Code:
https://jsfiddle.net/mukeshbadgujar/y6hanbuz/32/

let me know, from your side, what is the development about the Incremental on-demand data loading for StockCharts with Comparing Series.

**Comment by martynasma** [comment]
In StockChart all series (including compared ones) are regular XY series, so incremental updates would work exactly the same way as in XYChart.

Since your CodePen does not seem to have any incremental loading going on, I'm not sure what to suggest. Can you update your test case with actual code you are using to update series' data incrementally?

**Comment by mukeshbadgujar** [comment]
please check link : https://jsfiddle.net/mukeshbadgujar/y6hanbuz/34/

**Comment by martynasma** [comment]
I don't see any incremental loads going on there. Can you point me to a specific line that does incremental updates?

**Comment by mukeshbadgujar** [comment]
the increment load is working on scroll event, 

but my problem is solved.

thanks for looking out my issue.
