### ISSUE TITLE
Limit number of selection in comparison control dropdown

### ISSUE THREAD

**Issue by ankit-mercer** [amcharts/amcharts5#561]
Hi Team,
I'm using a comparison control dropdown, currently we can select all the available options but I want to limit the user selection, like user can select only up to 5 options from the comparison control dropdown i.e. only 5 markets data can be shown on chart at a time. If a user try to select more than 5 options it will not allow to do so.  
Adding to this, one option which has been already selected should not be selected twice, for example, if Canada is already selected then on clicking Canada from dropdown it should not allowed to add the data for same option again, it makes the data redundant.

**Comment by martynasma** [comment]
Those two are excellent suggestions. We will consider adding them soon. Thanks!

Will keep you posted.

**Comment by martynasma** [comment]
I've updated this demo:
https://www.amcharts.com/demos/stock-chart-comparing-prices/

It will now not allow selecting more than five comparisons.

It also has a code to disable item of an already added comparison, but will require a new release of amCharts 5 to work properly.

I'll ping you here when the new version is out later this week.

**Comment by ankit-mercer** [comment]
Thanks! Will wait for new version.

**Comment by martynasma** [comment]
Fixed in [5.2.18](https://github.com/amcharts/amcharts5/releases/tag/5.2.18).

## [5.2.18] - 2022-08-24

### Added
- `disabled` key support added to `DropdownList` item interface.

### Fixed
- Removed leftover debug code in `IndicatorControl`.
- `selected` event in `IndicatorControl` was not firing.
- Adding an adapter on Y-axis' labels could cause flickers on the chart.
- `maxWidth`/`maxHeight` of a `Container` was ignored when arranging objects by Horizontal or Vertical layout.
- `maxWidth`/`maxHeight` of a `Container` was ignored when drawing background.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by ankit-mercer** [comment]
I am afraid the issue that I mentioned above is still open regarding same market select. Could you please share any link if it is already resolved.

**Comment by martynasma** [comment]
Does [this demo](https://www.amcharts.com/demos/stock-chart-comparing-prices/) allow you select multiple items?

If it does, try clearing your browser cache and reloading.

**Comment by ankit-mercer** [comment]
Thanks! It worked after clearing the cache.
