### ISSUE TITLE
Adding Tooltip to Picture or Container

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts5#57]
I can't seem to get a Tooltip added to a Picture or a Container. The only way I get it to show is when setting `tooltipText`. Creating a separate Tooltip instance and adding it on instantiation or afterwards does not seem to work: https://codepen.io/sassomedia/pen/yLojOGX?editors=0010

Any idea what I'm missing here?

**Comment by martynasma** [comment]
Adding `tooltip` setting to an element does not make it "interactive" or create hover events required for displaying tooltip.

Adding `tooltipText` does it.

So you should use this, directly on the element (not on tooltip):

```JavaScript
chart.children.push(am5.Picture.new(root, {
  // ...
  tooltipText: "This is a Tooltip"
}));
```

You don't need to create tooltip object for an element at all, unless you want to configure tooltip for it specifically.

**Comment by sassomedia** [comment]
Right, this is a bit of an odd behavior because it seems inconsistent with how other elements are instantiated.

If I set the `tooltip` with `tooltipText` on instantiation, it does not work:
```javascript
chart.children.push(am5.Picture.new(root, {
  width: 100,
  height: 100,
  x: am5.percent(60),
  y: am5.percent(30),
  centerX: am5.percent(50),
  centerY: am5.percent(50),
  src: "https://assets.codepen.io/t-160/icon_btc.svg",
  tooltip: am5.Tooltip.new(root, {
    tooltipText: "This is a Tooltip", // gets ignored, doesn't display tooltip
    fill: am5.color(0xff0000),
  }),
}));
```
If I set both `tooltip` and `tooltipText`, it activates it but ignores any properties added to `am5.Tooltip.new`.
```javascript
chart.children.push(am5.Picture.new(root, {
  width: 100,
  height: 100,
  x: am5.percent(60),
  y: am5.percent(30),
  centerX: am5.percent(50),
  centerY: am5.percent(50),
  src: "https://assets.codepen.io/t-160/icon_btc.svg",
  tooltip: am5.Tooltip.new(root, {
    tooltipText: "This is a Tooltip", // gets ignored, displays "Activate" instead
    fill: am5.color(0xff0000), // gets ignored
  }),
  tooltipText: "Activate",
}));
```
If I add a separate Tooltip instance and change the properties, it takes the background setting but not the tooltip text:
```javascript
const ttip = am5.Tooltip.new(root, {});
ttip.get("background").set("fill", am5.color(0xff0000)); // displays red bg
ttip.label.set("text", "This is a Tooltip"); // gets ignored, displays "Activate" instead

chart.children.push(am5.Picture.new(root, {
  width: 100,
  height: 100,
  x: am5.percent(30),
  y: am5.percent(60),
  centerX: am5.percent(50),
  centerY: am5.percent(50),
  src: "https://assets.codepen.io/t-160/icon_btc.svg",
  tooltip: ttip,
  tooltipText: "Activate",
}));
```
If I create a separate instance and define the object as a separate item, only then can I set the `tooltipText`:
```javascript
const ttip = am5.Tooltip.new(root, {});
ttip.get("background").set("fill", am5.color(0xff0000)); // displays red bg

const picture = am5.Picture.new(root, {
  width: 100,
  height: 100,
  x: am5.percent(30),
  y: am5.percent(60),
  centerX: am5.percent(50),
  centerY: am5.percent(50),
  src: "https://assets.codepen.io/t-160/icon_btc.svg",
  tooltip: ttip,
  tooltipText: "Activate",
});

picture.set("tooltipText", "This is a Tooltip"); // gets accepted, displays "This is a Tooltip"
chart.children.push(picture);
```

Since `tooltipText` is a property on `Tooltip`, I would expect it to be set on instantiation, as well as get the tooltip activated. Would that not be possible?

**Comment by martynasma** [comment]
`tooltipText` is a property of a `Sprite` which is basically any element in the chart, not of `Tooltip`.

`tooltipText` means "display this text in a tooltip when I hover over this element. So, if you set `tooltipText` on a `Tooltip` you mean "display this text in another tooltip when I hover over this tooltip". It just does not make any sense.

`Tooltip` has a dedicated property: `labelText` which is a shortcut as setting `text` on tooltip's label.

So the following two are identical:

```JavaScript
const tooltip = am5.Tooltip.new(root, {});
tooltip.label.set("text", "Blah");
picture.set("tooltip", tooltip);
```

and

```JavaScript
picture.set("tooltip", am5.Tooltip.new(root, {
  labelText: "Blah"
});
```

And again: setting `tooltip` for an element does not make it hoverable or make it display tooltip when hovered.

It just sets a "personal" tooltip instance for the element IF hovering is enabled for the tooltip.

And hovering is enabled by setting `tooltipText` on an element (not on tooltip).

Normally, you don't need to create individual `Tooltip` instances for elements, unless you want to configure them in some unique way that is not applicable to other elements on the chart.

Elements share tooltip instances. For example, when you set `tooltipText` on standalone objects like Pictures in your example, a chart's global `Tooltip` object is used.

Series elements like bullets, columns, etc, use series' `Tooltip` instance. So if you need to configure tooltip in some way for all series elements, you configure it rather than create own tooltip for each individual element.

**Comment by sassomedia** [comment]
Ok, I guess I got confused by the docs as `Tooltip` has a `tooltipText` property. I figured that could be set in one go. But it makes sense now, thanks!
