### ISSUE TITLE
html tooltip element available in DOM even when tooltip is hidden

### ISSUE THREAD

**Issue by tscislo** [amcharts/amcharts5#576]
With latest AmCharts 5.2.17 using labelTooltip, like in here: https://codepen.io/tscislo/pen/XWEBYzW
when tooltip is hidden it is still in the DOM with opacity: 0. This is problematic especially if tooltip is presented beyond char area as it hides some other parts of the page when not visible.
Ideally tooltip should be removed from DOM when hidden

![image](https://user-images.githubusercontent.com/2109390/186704460-d18548e2-ca67-4d21-aefc-8a3cfe9eb2ec.png)

**Comment by martynasma** [comment]
Good catch. Thanks!

It will be fixed in the next version.

**Comment by martynasma** [comment]
Fixed in [5.2.19](https://github.com/amcharts/amcharts5/releases/tag/5.2.19).

## [5.2.19] - 2022-08-26

### Added
- `geoPoint()` method added to `MapChart`. Returns a geoPoint of the current the center of the map viewport.
- `pancancelled` event added to `XYChart`. It will kick in if pointer is pressed down and released without moving. `panended` event will still kick in.
- `originalEvent` added to `panstarted`, `panended`, and `pancancelled` events.

### Fixed
- Tooltips were not working properly on an `XYChart` if they were placed in a separate root element.
- If an `XYChart` with a `CategoryAxis` had series with missing values, zooming to the part of a series with no data caused value axis not to zoom according to the selection.
- HTML-based tooltips were leaving a visible (albeit transparent) DOM element after tooltip was hidden.
- Clear and erase buttons were not clearing/erasing all the drawings of StockChart properly.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by tscislo** [comment]
@martynasma unfortunately while this is fixed with 5.2.19 unfortunately this problem has returned: https://github.com/amcharts/amcharts5/issues/523

**Comment by martynasma** [comment]
Arrrrrrgh... OK next version :)

**Comment by martynasma** [comment]
Fixed in [5.2.20](https://github.com/amcharts/amcharts5/releases/tag/5.2.20).

## [5.2.20] - 2022-09-05

### Added
- All indicator series will now have `"indicator"` theme tag set. Detect indicator series via `series.hasTag("indicator")`.
- `autoZoom` added to `ValueAxis` (default: `true`). If set to `false`, the axis won't be auto-zoomed to a selection (this works only if the other axis is a `DateAxis` or a `CategoryAxis`). This setting will be ignored if both X and Y axes are a `ValueAxis`.
- `StandardDeviation` indicator added.

### Changed
- Series edit modal on a `StockChart` would show incorrect controls if the main chart series was a `LineSeries`.

### Fixed
- Initial sizing of HTML tooltips fixed (again).
- Exporting a chart in a `<div>` with `height: auto` was not working properly.
- If a point in a `LineSeries` was way out of bounds (million times further than the bounds of plot area), the line could disappear.
- In some cases, if chart was using loadable fonts, it could go into non-stop flickering mode.
- `StockChart` with drawing mode disabled could start drawing new objects if clicked on points of an old drawing.
- `PointedRectangle`, mostly used by a `Tooltip` was drawn incorrectly if its stem size was bigger than height. 
- Removing a `QuadrantLineSeries` drawing from a `StockChart` resulted an error.
- It was impossible to delete `Fibonacci` or `FibonacciTimezone` drawings one by one after switching to another drawing tool.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by tscislo** [comment]
@martynasma works fine thx!
