### ISSUE TITLE
Bug: Some Drawing Controls are not working Properly (Cant Remove any Drawing eg. Line, Doodle etc.)

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#581]
Please Solve this in Emergency,

Selected Remove is not working
also Clear Button not working

I tested it on Line, Doodle.

Please Check all.

https://jsfiddle.net/mukeshbadgujar/0uz5c9kt/8/

Edit:
I tested it on Line, Doodle, Rectangle

**Comment by martynasma** [comment]
Fixed in [5.2.19](https://github.com/amcharts/amcharts5/releases/tag/5.2.19).

## [5.2.19] - 2022-08-26

### Added
- `geoPoint()` method added to `MapChart`. Returns a geoPoint of the current the center of the map viewport.
- `pancancelled` event added to `XYChart`. It will kick in if pointer is pressed down and released without moving. `panended` event will still kick in.
- `originalEvent` added to `panstarted`, `panended`, and `pancancelled` events.

### Fixed
- Tooltips were not working properly on an `XYChart` if they were placed in a separate root element.
- If an `XYChart` with a `CategoryAxis` had series with missing values, zooming to the part of a series with no data caused value axis not to zoom according to the selection.
- HTML-based tooltips were leaving a visible (albeit transparent) DOM element after tooltip was hidden.
- Clear and erase buttons were not clearing/erasing all the drawings of StockChart properly.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
