### ISSUE TITLE
ValueAxis with max set results in hidden values

### ISSUE THREAD

**Issue by JacobDeuchert** [amcharts/amcharts5#585]
**Bug description**
When using a line chart and settings the max property on the ValueAxis the values in the chart are not displayed if some value exceeds a certain threshold.

I recreated the issue in this [codepen](https://codepen.io/jacobdeuchert/pen/MWVMMWY?editors=0010)

In the pen you will find a chart with 3 values and the max value set on the ValueAxis / Y-Axis. 
If the last value exceeds 174_000_000 the values in the chart won't get displayed.

**Comment by zeroin** [comment]
This happens because when line is really really big, canvas simply doesn't draw it. We will solve this issue in next release.

**Comment by JacobDeuchert** [comment]
Thanks! We usually don't have jumps this big in our values but some of the sensor devices we use send occasionally very high values if they encounter some error.

**Comment by martynasma** [comment]
Fixed in [5.2.20](https://github.com/amcharts/amcharts5/releases/tag/5.2.20).

## [5.2.20] - 2022-09-05

### Added
- All indicator series will now have `"indicator"` theme tag set. Detect indicator series via `series.hasTag("indicator")`.
- `autoZoom` added to `ValueAxis` (default: `true`). If set to `false`, the axis won't be auto-zoomed to a selection (this works only if the other axis is a `DateAxis` or a `CategoryAxis`). This setting will be ignored if both X and Y axes are a `ValueAxis`.
- `StandardDeviation` indicator added.

### Changed
- Series edit modal on a `StockChart` would show incorrect controls if the main chart series was a `LineSeries`.

### Fixed
- Initial sizing of HTML tooltips fixed (again).
- Exporting a chart in a `<div>` with `height: auto` was not working properly.
- If a point in a `LineSeries` was way out of bounds (million times further than the bounds of plot area), the line could disappear.
- In some cases, if chart was using loadable fonts, it could go into non-stop flickering mode.
- `StockChart` with drawing mode disabled could start drawing new objects if clicked on points of an old drawing.
- `PointedRectangle`, mostly used by a `Tooltip` was drawn incorrectly if its stem size was bigger than height. 
- Removing a `QuadrantLineSeries` drawing from a `StockChart` resulted an error.
- It was impossible to delete `Fibonacci` or `FibonacciTimezone` drawings one by one after switching to another drawing tool.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
