### ISSUE TITLE
Data dissapear when chaging timeUnit from "day" to "minute"/"hour"

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts5#590]
I have this DateAxis:

```
            var xAxis = chart.xAxes.push(am5xy.DateAxis.new(root, {
                maxDeviation: 0.1,
                groupData: false,
                baseInterval: {
                    timeUnit: "day",
                    count: 1
                },
                renderer: am5xy.AxisRendererX.new(root, {

                }),
                tooltip: am5.Tooltip.new(root, {})
            }));
```

Series Data is:
```
data = [
            {
                "time": "2012-07-27",
                "profit": 13,
                "dd": 0,
            }, {
                "time": "2012-07-28",
                "profit": 11,
                "dd": 1,
            }, { ...
```

It works fine with "day" in timeUnit but if I change it to "minute"/"hour" it does not show the data.
Any clue why is that? I don't fully understand how "count" in baseInterval works, what is that number and when is useful?

Here is a codepen:
https://codepen.io/enriqu3/pen/oNqKROY

**Comment by martynasma** [comment]
You have `connect: false` set in your series settings.

It means that when there's a gap bigger than `baseInterval` between two data points, it breaks the line.

Since you have data coming in at daily intervals, all data points are 24 hours apart, which means there's a "break" between every data point.

If you absolutely need to have `baseInterval` set to hours while using daily data, you should set `autoGapCount: 24` on your series.

https://www.amcharts.com/docs/v5/charts/xy-chart/series/line-series/#Auto_gaps_with_dates

**Comment by enriquepiatti** [comment]
connect: true did the trick to show the data, but now the labels are really difficult to find, is there any way to have some "magnetic" pointer to show data near? not exactly the XY pixel?    
My data is at minute level, I need to show the minute, but it's not every minute, could be days, or even months without data.

**Comment by martynasma** [comment]
Do you mean the tooltips?

Turning on cursor snapping should help:
https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#snapping-to-series

**Comment by enriquepiatti** [comment]
Perfect, thanks !!
