### ISSUE TITLE
HTML tooltip blinks when hovering the mouse over different categories in the stacked column

### ISSUE THREAD

**Issue by vanvt** [amcharts/amcharts5#608]
Hi Supporter

Currently, I am developing a stacked column like the below gif.
![182331922-b1f1004b-7e3d-4826-971e-879b6d23119e](https://user-images.githubusercontent.com/12226958/189273005-52728a05-930d-4724-a37d-89a50353fbc7.gif)

My client doesn't want the tooltip blinks when hovering the mouse over the categories on a column, 
=> Tooltip should be shown 1 time and not appear again when hovering the mouse on any other parts of the same column
Is there any way to do that?
Thanks

VanVT

**Comment by vanvt** [comment]
I've updated the latest version, but the issue is still happening now.
plz help to check the code.
https://codepen.io/vanvt6/pen/LYmNpKo

**Comment by martynasma** [comment]
Thanks. We're making a few improvements. It should better with the next release. I'll let you know when it's out later this week.

**Comment by martynasma** [comment]
Fixed in [5.2.22](https://github.com/amcharts/amcharts5/releases/tag/5.2.22).

## [5.2.22] - 2022-09-15

### Added
- ZigZag indicator added to `StockChart`.

### Changed
- `"%"` number formatting modifier will now consider locale when choosing whether percent sign goes before or after the number. At this moment only `tr_TR` (Turkish) locale is placing percent sign before number.
- `StockChart` indicators, that were using black (`0x000000`) color as a default series color now use `alternativeBackground` color of a theme (they'll now be white if "Dark" theme is used).

### Fixed
- Stock toolbar dropdown items will now display proper `title` attribute.
- HTML tooltips were flashing an unpositioned content briefly.
- The `"Z"` date formatting option was not taking into account Root element's `timezone` setting.
- If a timezone was set on a chart and data grouping was on, the grouping was not paying attention to the timezone.
- If a timezone which was not using DST was set on a chart, and user was in a timezone which used DST, the axis labels were shifted by 1 hour in some setups.
- `GaplessDateAxis` was not working properly with a timezone set.
- `DateAxis` fills that should have been visible were hidden in some cases.
- `StockChart` was incorrectly switching to percent mode when last of the compared series was removed.
- `"p"` number formatting modifier added. Works the same way as `"%"` except it treats numbers as absolute values and does not multiply them by 100.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
