### ISSUE TITLE
Export data uses local timezone instead of the provided timezone

### ISSUE THREAD

**Issue by nothing-personal-gh** [amcharts/amcharts5#612]
**Bug description**

Steps to reproduce:

1. Set your computer's timezone to Indian Standard Time
2. Open https://codepen.io/trooper-isa/pen/NWMroVo?editors=1000 and click on the Export menu -> CSV to download the CSV file.
3. Notice that the exported file has IST (05:30) instead of the provided timezone `Australia/Sydney` (10:00) (from line 93)

This would be the content of the exported file:

```
value,time
682.64,2022-08-11 03:00:00 GMT+05:30
90.16,2022-08-11 03:05:00 GMT+05:30
189.5,2022-08-11 03:10:00 GMT+05:30
837.16,2022-08-11 03:15:00 GMT+05:30
864.91,2022-08-11 03:20:00 GMT+05:30
75.69,2022-08-11 03:25:00 GMT+05:30
```

What's even more wrong is that the timezone is applied incorrectly. The first data point `1660150800000` is Wednesday, 10 August 2022 22:30:00 [GMT+05:30] or Thursday, 11 August 2022 03:00:00 [GMT+10:00].

The export is taking the time value from the correct timezone but the actual timezone component is from the local timezone. This makes the content in the export file invalid.

 - amCharts version - 5
 - Browser and its version - Chrome latest
 - Related frameworks and their versions - N/A

**Comment by martynasma** [comment]
Fixed in [5.2.22](https://github.com/amcharts/amcharts5/releases/tag/5.2.22).

## [5.2.22] - 2022-09-15

### Added
- ZigZag indicator added to `StockChart`.

### Changed
- `"%"` number formatting modifier will now consider locale when choosing whether percent sign goes before or after the number. At this moment only `tr_TR` (Turkish) locale is placing percent sign before number.
- `StockChart` indicators, that were using black (`0x000000`) color as a default series color now use `alternativeBackground` color of a theme (they'll now be white if "Dark" theme is used).

### Fixed
- Stock toolbar dropdown items will now display proper `title` attribute.
- HTML tooltips were flashing an unpositioned content briefly.
- The `"Z"` date formatting option was not taking into account Root element's `timezone` setting.
- If a timezone was set on a chart and data grouping was on, the grouping was not paying attention to the timezone.
- If a timezone which was not using DST was set on a chart, and user was in a timezone which used DST, the axis labels were shifted by 1 hour in some setups.
- `GaplessDateAxis` was not working properly with a timezone set.
- `DateAxis` fills that should have been visible were hidden in some cases.
- `StockChart` was incorrectly switching to percent mode when last of the compared series was removed.
- `"p"` number formatting modifier added. Works the same way as `"%"` except it treats numbers as absolute values and does not multiply them by 100.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
