### ISSUE TITLE
Export menu makes html form select menu options inoperable with mouse

### ISSUE THREAD

**Issue by jcgithub9** [amcharts/amcharts5#62]
If an html page containing an amcharts5 chart also has html form(s) with selectable options in pull-down menu(s), those selection menus do not function properly when an export menu is included with the amcharts5 chart.  Those same html form menus work fine when export menu is not on the chart.
Can reproduce a simple example using the gauge example files – simply added the following html to the index.html file, and the noted javasciprt in the index.js file to add the export menu.  Without the export menu, the html select menu functions and options can be selected with the mouse.  When the export menu is included, the html select menu drop down options appear when menu clicked but the options cannot be selected.

HTML snippet to add to an example index.html file to show that menu selections via mouse work without export menu present, and do NOT work when export menu present:
<FORM><SELECT NAME="var" style="width:50%"><OPTION VALUE="V1">Option 1</OPTION><OPTION VALUE="V2">Option 2</OPTION><OPTION VALUE="V3">Option 3</OPTION></SELECT></FORM>

Javascript snippet to add to index.js:
<script src="../../plugins/exporting.js"></script> 
var exporting = am5plugins_exporting.Exporting.new(root, {
  menu: am5plugins_exporting.ExportingMenu.new(root, {})
});

**Comment by jcgithub9** [comment]
UPDATE to html example (neglected to insert as code in original post so html tags got stripped out):
`<FORM><SELECT NAME="var" style="width:50%"><OPTION VALUE="V1">Option 1</OPTION><OPTION VALUE="V2">Option 2</OPTION><OPTION VALUE="V3">Option 3</OPTION></SELECT></FORM>`

**Comment by martynasma** [comment]
Thanks for the heads up!

This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by martynasma** [comment]
Fixed in [5.0.5](https://github.com/amcharts/amcharts5/releases/tag/5.0.5).

## [5.0.5] - 2021-11-15

### Added
- New root element method: `moveDOM()` (accepts element id or reference as a parameter). Can be used to move whole chart to some other container within DOM.

### Fixed
- `ExportingMenu` was interfering with functionality of form elements on the same page (e.g. select).
- Fixed issues with text kerning with styling blocks mid-word.
- Animating values of `width`/`height` settings using percent values was not working properly.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download-v5/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
