### ISSUE TITLE
How to add a constant line in a bar chart

### ISSUE THREAD

**Issue by carinezhang** [amcharts/amcharts5#634]
Hello,
I want to add a threshold line on my bar chart that goes straight from the start to the end and put the label at the right side. 

Something similar to "Goal" and "2 x Goal" in this example is what i want [https://www.amcharts.com/demos/step-count-chart/](https://www.amcharts.com/demos/step-count-chart/)
but the problem is that the axis labels at the left is inside the graph.
I've tried changing `inside` to `false` in the `yRenderer` but it doesn't work (result here: [https://codepen.io/carinezhang/pen/yLjzvoB](https://codepen.io/carinezhang/pen/yLjzvoB))

How can I fix that ?
Or is there any other way to create a constant line ?

Thank you

**Comment by xorspark** [comment]
You need to set the axis ranges' `inside` property to true so that they don't auto-adjust (preventing the infinite drawing your code has). From there, you can just set `centerX` to 0 to move it to the right outside of the graph if you want, or keep your existing values. 

Demo which also adds some padding and shifts the labels on the right outside of the chart: https://codepen.io/team/amcharts/pen/mdLBvEq/3b10835a39bf3fade8b34bbfde1339a9?editors=0010

This is explained more in depth here: https://www.amcharts.com/docs/v5/tutorials/aligning-axis-range-labels/

**Comment by carinezhang** [comment]
Thank you
