### ISSUE TITLE
Text styling issue - incorrect letters spacing (kerning) when styles applied

### ISSUE THREAD

**Issue by DmitryOganezov** [amcharts/amcharts5#65]
![image](https://user-images.githubusercontent.com/12894670/141517602-fcb27a74-398e-4544-a314-e2fcfe55bf40.png)

It seems like there are some problems with styled text rendering.
(https://www.amcharts.com/docs/v5/concepts/formatters/text-styling/)

Impact: styled text looks sloppy, in some cases even unreadable.
Example: https://codepen.io/DmitryO/pen/eYELKmo

- amCharts version
5.0.4 (although the issue was discovered in early beta).

 - Browser and its version
Chrome Version 95.0.4638.69 (Windows)
Microsoft Edge 44.18362.449.0 (Windows)
Chrome Version 95.0.4638.64 (Android)

Note: text kerning on Android looks better, but it's not ideal.

**Additional context**

The same text styling patterns worked just fine in amCharts 4.

Regards,
--DO

**Comment by martynasma** [comment]
Fixed in [5.0.5](https://github.com/amcharts/amcharts5/releases/tag/5.0.5).

## [5.0.5] - 2021-11-15

### Added
- New root element method: `moveDOM()` (accepts element id or reference as a parameter). Can be used to move whole chart to some other container within DOM.

### Fixed
- `ExportingMenu` was interfering with functionality of form elements on the same page (e.g. select).
- Fixed issues with text kerning with styling blocks mid-word.
- Animating values of `width`/`height` settings using percent values was not working properly.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download-v5/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
