### ISSUE TITLE
SliceGrouper uses first color from palette instead of next from the list

### ISSUE THREAD

**Issue by JayesNS** [amcharts/amcharts5#653]
**Bug description**

I am trying to use `SliceGrouper` plugin for `PieChart` and I found problem with color of "Other" slice. Instead of choosing next color available in palette, it uses first from the list. I can not even change color of slice manually because plugin does not provide proper options to change it. You can see it in amChart 5 docs [here](https://www.amcharts.com/docs/v5/charts/percent-charts/grouping-slices). On GIFs colors are all right, but on [CodePen](https://codepen.io/team/amcharts/pen/WNZdpxO) in Example section on the same wiki page, "Other" slice is blended with first one. It is confusing what is on PieChart and someone may think it is one big slice.

Expected:
![image](https://user-images.githubusercontent.com/7165170/193784597-23ea5378-0652-43b2-aa46-b4a096cdcae3.png)

Current:
![image](https://user-images.githubusercontent.com/7165170/193784992-4ae2fcdf-d269-4adb-b5c9-a8eecd42df75.png)

**Comment by martynasma** [comment]
This is a bug, albeit nor related to SliceGroupe. A fix is coming. Will notify you here.

Thanks for the the report!

**Comment by JayesNS** [comment]
Thank you for your prompt reply! Have you considered adding more options of customizing "Other" slice directly when adding new instance of plugin? I guess there is some workaround to get slice object add modify it after initialization.

**Comment by martynasma** [comment]
Yes, you can use `sliceGrouper.getPrivate("groupDataItem").get("slice")`.

**Comment by martynasma** [comment]
Fixed in [5.2.28](https://github.com/amcharts/amcharts5/releases/tag/5.2.28).

## [5.2.28] - 2022-10-06

### Added
- `stacked` setting added to `AxisBullet`. If set to `true` and multiple data items (axis ranges) were added to the same date/category, bullets will be stacked on top of each other.

### Fixed
- If a timezone was set and `baseInterval` was a `"month"`, tooltip could show incorrect date value on a month when DLS happened.
- If a new slice was added to `PercentChart` after the initial data was set, the new slice was using first color from colorset instead of the next one.
- Some sprites were not dispatching `boundschanged` event when their settings affecting the bounds were being changed.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
