### ISSUE TITLE
Pie resizing issues in combination with react-grid-layout

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#658]
**Question**

Please see the attached video. I am unable to setup an example of this as there are many layers affecting this and I believe it to be rootly caused by some combination of https://github.com/react-grid-layout/react-grid-layout, amcharts and our react stack.

The problem at hand appears to be that if a card in our dashboard that contains an amchart is resized quickly the pie chart does not correctly resize, but rather, when it is resized again quickly it uses the dimensions of the first resize to calculate the size of the pie. This is shown in the second half of the attached screen recording.

However, if resized, slowly, and the user waits for the resizing of the card to "catch-up" with the resize ghost, it the resizing works as expected. This is shown in the first half of the attached screen recording.

This problem only appears to exist with the `PieSeries` from what we can tell.

Now, I know this is particular to our setup as I have tried to setup an example in codepen using CSS `resize`, but it works fine.

I have tried to band-aid fix this, by calling `root.resize()`, and even putting it in a `setInterval` calling every second, but it does not correctly resize the pie. The root canvas itself is the correct dimensions according to the resize, but just not the pie series or labels.

I have also tried "reflowing" the pie by calling `series.appear()`, however that does not work either.

My question is, is this possibly a bug somehow in `PieSeries`? I assume not and rather there is some timing issues between our stack and amcharts events, but I would have expected the `resize()` or `appear()` calls to fix the issue? What can I try next?

https://user-images.githubusercontent.com/2810/194261780-108a8e6f-45ac-41dd-9d1a-0a6fe8109400.mov

**Comment by martynasma** [comment]
We are going to investigate this further.

In the interim, as a temporary solution, could you please check if there are any React Grid events you can tap into that kick in when resize happens.

You could do `root.resize()` when those kick in.

**Comment by martynasma** [comment]
Fixed in [5.2.30](https://github.com/amcharts/amcharts5/releases/tag/5.2.30).

## [5.2.30] - 2022-10-14

### Added
- `"click"` option added to `showTooltipOn` setting. If set, tooltip will appear when clicking/tapping the element, rather than on hover.
- `ExportMenu` has two new private settings: `menuElement` and `listElement`. Holds actual DOM elements of the menu items.

### Changed
- Disposing `Exporting` object, will now dispose related `ExportingMenu`, if set.
- `Legend`'s item containers will now have `role="checkbox"` set by default.
- Setting `focusable: true` on `XYCursor`'s `lineX` and/or `lineY` will enable moving them with keyboard's arrow keys.
- Better arrangement of tooltips on an `XYChart` with multiple tooltips on the same data point and an `XYCursor` (less chances tooltips going off-screen).

### Fixed
- In some situations chart was not resizing correctly.
- If `sequencedAnimation` was set to `true` on a `LineSeries`, it was drawing line to 0 while animating series.
- `ExportMenu` was using a non-existent "aria" attribute.
- When `snapToSeries` was set on an `XYChart`, zooming to a selection with the cursor produced wrong zoom.
- `XYChart` with `DurationAxis` could freeze the browser in certain configurations and chart sizes.
- `LineSeries` used to draw a line to null values while series was animating (if `sequencedAnimation` was set to `true`).
- Eliminating warnings about `getImageData()` on the new Chrome.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
