### ISSUE TITLE
Radar Timeline Graph Issue

### ISSUE THREAD

**Issue by KasimMahroof** [amcharts/amcharts5#66]
Hi,

I'm building a graph using the demo for the Radar Timeline Graph: https://www.amcharts.com/demos/radar-timeline/

Would it be possible to make the top-level categories (Continents) width be reflected not by the the number of sub-categories (Countries) it has, but by the actual value of its sub-categories (temperature).

e.g. In the demo above, say the temperature change of all the countries in Oceania was 50°C, but in Europe it was only 30°C. I would expect the width of Oceania to be larger, but since it has fewer countries it will be smaller.

Let me know if what I said is even possible/doesn't make sense.

**Comment by martynasma** [comment]
That sounds doable. While we don't have a ready-made example like that, here are a few guidelines you can follow to make the necessary changes:

1. Create separate `ColumnSeries` and `CategoryAxis` for each continent.
2. On each X axis' renderer use `startAngle` and `endAngle` values to make them start and stop to form as large "slices" as you need. You will need to calculate those yourself as per your requirements, and make sure axes do not overlap.
3. Zooming into continent would need to be implementing by animating `startAngle`/`endAngle` of "active" continent to -90/270 respectively, whereas hidden series can either be hidden by calling their `hide()` method, or by animating both of their angle settings to -90.
4. Scrollbars won't work as expected, naturally. If you need zooming with a scrollbar, you'll need to add standalone `Scrollbar` elements and calculate `startAngle`/`endAngle` for all axes based on scrollbar's position. This might get complicated.
5. Naturally, for timeline animation, you will need to update data for each series individually, rather than one series as it is in the original demo.

Hope this makes sense.

**Comment by KasimMahroof** [comment]
Hi, thanks for your help.

Unfortunately, the company I work for is under a time constraint.

Do you guys offer expert developer help to build the graph like the one I described above?

**Comment by martynasma** [comment]
No, I'm afraid. Sorry :(
