### ISSUE TITLE
Chart freezes the browser

### ISSUE THREAD

**Issue by cramsc** [amcharts/amcharts5#665]
Hello, this example with that data freezes the browser. 

It is curious because changing the width and height makes it work fine. For example that values will work:
`  width: 100%;
  height: 750px;`

But not the full next example:

```
<html>
<style>
  #chartdiv {
  width: 1785px;
  height: 500px;
}
</style>


<script src="//cdn.amcharts.com/lib/5/index.js"></script>
<script src="//cdn.amcharts.com/lib/5/xy.js"></script>
<script src="//cdn.amcharts.com/lib/5/themes/Animated.js"></script>
<script src="//cdn.amcharts.com/lib/5/percent.js"></script>
<div id="chartdiv"></div>

<script>	
		
	var root = am5.Root.new("chartdiv");
	
	root.setThemes([am5themes_Animated.new(root)]);
	var chart = root.container.children.push(am5xy.XYChart.new(root, {
	  panX: false,
	  panY: false,
	  layout: root.verticalLayout,
	}));
	
	

	var data = [{"category":"example","aa":56103.43,"bb":35674.67,"cc":3384.4,"dd":32357.43,"ee":17942.8,"ff":12222.3,"gg":16752.76,"hh":3723.17,"ii":17188.47,"jj":10315.43,"kk":79605.41,"ll":7519,"mm":16703.15,"nn":17.22}];
	
	
	var xAxis = chart.xAxes.push(am5xy.CategoryAxis.new(root, {
	  categoryField: "category",
	  renderer: am5xy.AxisRendererX.new(root, {}),	  
	}));
	
	
	xAxis.data.setAll(data);
	
	var yAxis = chart.yAxes.push(am5xy.DurationAxis.new(root, {
	  baseUnit:"second",
	  renderer: am5xy.AxisRendererY.new(root, {}),
	}));

	function createSeries(name, field) {			
	  var series = chart.series.push(am5xy.ColumnSeries.new(root, {
		name: name,
		xAxis: xAxis,
		yAxis: yAxis,
		valueYField: field,
		categoryXField: "category"
	  }));
	  
	  series.columns.template.setAll({
		tooltipText: "{name}, {valueY.formatDuration('hh:mm:ss')}" ,
		width: am5.percent(90),
		tooltipY: 0,

	  });
		  
		  
	  series.data.setAll(data);	
	  series.appear();
	  
	}
	
	createSeries("aa", "aa");
	createSeries("bb", "bb");
	createSeries("cc", "cc");
	createSeries("dd", "dd");
	createSeries("ee", "ee");
	createSeries("ff", "ff");
	createSeries("gg", "gg");
	createSeries("hh", "hh");
	createSeries("ii", "ii");
	createSeries("jj", "jj");
	createSeries("kk", "kk");
	createSeries("ll", "ll");
	createSeries("mm", "mm");
	createSeries("nn", "nn");	
		

</script>
</html>

```

**Comment by martynasma** [comment]
Fixed in [5.2.30](https://github.com/amcharts/amcharts5/releases/tag/5.2.30).

## [5.2.30] - 2022-10-14

### Added
- `"click"` option added to `showTooltipOn` setting. If set, tooltip will appear when clicking/tapping the element, rather than on hover.
- `ExportMenu` has two new private settings: `menuElement` and `listElement`. Holds actual DOM elements of the menu items.

### Changed
- Disposing `Exporting` object, will now dispose related `ExportingMenu`, if set.
- `Legend`'s item containers will now have `role="checkbox"` set by default.
- Setting `focusable: true` on `XYCursor`'s `lineX` and/or `lineY` will enable moving them with keyboard's arrow keys.
- Better arrangement of tooltips on an `XYChart` with multiple tooltips on the same data point and an `XYCursor` (less chances tooltips going off-screen).

### Fixed
- In some situations chart was not resizing correctly.
- If `sequencedAnimation` was set to `true` on a `LineSeries`, it was drawing line to 0 while animating series.
- `ExportMenu` was using a non-existent "aria" attribute.
- When `snapToSeries` was set on an `XYChart`, zooming to a selection with the cursor produced wrong zoom.
- `XYChart` with `DurationAxis` could freeze the browser in certain configurations and chart sizes.
- `LineSeries` used to draw a line to null values while series was animating (if `sequencedAnimation` was set to `true`).
- Eliminating warnings about `getImageData()` on the new Chrome.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
