### ISSUE TITLE
Bugs with stacked property - LineSeries and Column Series

### ISSUE THREAD

**Issue by nothing-personal-gh** [amcharts/amcharts5#690]
**Bug description**

These 2 bugs might be related as they both happen only when enabling the `stacked` property.

Codepen link - https://codepen.io/trooper-isa/pen/GRGWYdM?editors=0010 (change lines 1 and 2 to reproduce the bugs)

### Bug 1 - Random horizontal lines appear when enabling `stacked` property on ColumnSeries.

See the lines on Oct 25 to 31.

<img width="999" alt="image" src="https://user-images.githubusercontent.com/111722528/201293072-9e6b1c2b-a12e-418e-a646-61b8c146d27c.png">

When `stacked` is set to false, it appears normally:

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/111722528/201293156-51a531c0-8993-4c71-8ab8-92585d8b2f5f.png">

### Bug 2 - Line chart renders lines where there is no data when `stacked` is true:

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/111722528/201293782-77f53d47-8bc6-4fa3-9da7-17ac06f251a4.png">

When `stacked` is set to false, it appears normally:

<img width="990" alt="image" src="https://user-images.githubusercontent.com/111722528/201293415-2288602f-1ca4-4d78-b5ed-cadef47e19a2.png">

 - amCharts version - 5.x latest
 - Browser and its version - Chrome latest
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.] - N/A

**Comment by martynasma** [comment]
For series to stack properly they need to have the same number of data points with matching tiemstamps.

Otherwise the stacks will have unpredictable results.

Since your both series are using different data sets, for them to stack you will need to "equalize" both datasets. I.e. so they have the same number of data points, and their timestamps match.

If there's no measurement/value for specific timestamp, you can have a value-less data point, but it needs to be there.

Hope it makes sense.

**Comment by nothing-personal-gh** [comment]
Thanks @martynasma 

Issue is resolved after having the set of timestamps for both series.
