### ISSUE TITLE
Changing width of map container

### ISSUE THREAD

**Issue by nizhnikovskiy** [amcharts/amcharts5#7]
When container of chart change width, positioning is buggy.
The bug is reproduced if you try to scroll the chart left-right, zoom, resize the container and try to do it again.

Demo: https://codepen.io/nizhnikovskiy/pen/ExXoxLM?editors=1010

**Comment by martynasma** [comment]
Fixed in [5.0.0-beta.18](https://github.com/amcharts/amcharts5/releases/tag/5.0.0-beta.18).

## [5.0.0-beta.18] - 2021-09-17

### Added
- `areLinked()` method added to `LinkedHierarchy`.
- `unlinkDataItems()` method added to `LinkedHierarchy`.
- Global function `am5.disposeAllRootElements()` added. Disposes all charts.
- `am5.registry.rootElements` added which holds an array with instances of all active `Root` elements.
- `seriesGraphics` property added to `PictorialStackedSeries`. It's a `Graphics` which shows `svgPath` shape under all slices. Useful when `startLocation`/`endLocation` is used to make slices not occupy whole shape area.

### Changed
- `maxPanOut` of `MapChart` is temporarily disabled until we figure out proper behavior for it.

### Fixed
- Linking nodes with `linkDataItems` of `LinkedHierarchy` was not working if called after the data was set.
- `Micro` theme was not removing padding from charts.
- Adding in `@types/geojson` as a dependency.
- Map could jump to unpredictable position after the chart's container size changed and user zoomed or panned the map.
- In some cases `Label` with `oversizedBehavior = "fit"` could be incorrectly positioned.
- Removing series and axes from a serial chart was not working properly.

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
