### ISSUE TITLE
Range Selector plugin for version 5?

### ISSUE THREAD

**Issue by dnewkerk** [amcharts/amcharts5#70]
First, thank you for the exceptional library! For a licensed amCharts customer I've been using the [version 4 stock chart](https://www.amcharts.com/demos-v4/stock-chart-v4/), which included a plugin called [Range Selector](https://www.amcharts.com/docs/v4/tutorials/plugin-range-selector/), which adds form inputs for a date range, and zoom presets. I noticed that the [version 5 stock chart](https://www.amcharts.com/demos/stock-chart/) does not include this behavior, and after searching the code, docs, and issues, it appears the functionality is not (yet?) in version 5. I just wanted to check, is this feature expected to be on the future roadmap?

Again thank you for your terrific work on this library!

**Comment by martynasma** [comment]
At this moment we do not plan on implementing Range Selector plugin for amCharts 5.

In amCharts 4, it served a purpose of somewhat plugging the functionality hole due to lack of Stock chart. We do plan full-fledged Stock chart for amCharts 5, so having this functionality in a separate plugin would be kinda redundant.

Before you ask, there's no ETA for Stock chart, yet. But it gets a priority. I'm hoping it hits the light soon(ish).
