### ISSUE TITLE
MapSeries include/exclude functionality does not respect idField

### ISSUE THREAD

**Issue by b8** [amcharts/amcharts5#704]
**Bug description**

The MapSeries' `include`/`exclude` functionality does not work if I don't have an `id` field in my raw data and try to map it with the `idField` functionality.

`id` seems to be hard coded, see https://github.com/amcharts/amcharts5/blob/60f627a62437bacfc2bd59217e2c1f374961ac1b/src/.internal/charts/map/MapSeries.ts#L175

Therefore, I cannot include/exclude any countries when I use raw data with a field `code` (instead of `id`) and I set `idField: code`.

**Environment**

amCharts: 5.2.35
Angular: 14.2.0
Browser: Firefox 107.0

**Comment by martynasma** [comment]
Fixed in [5.2.39](https://github.com/amcharts/amcharts5/releases/tag/5.2.39).

## [5.2.39] - 2022-12-07

### Added
- `fillOpacity` setting added to `Label`.

### Changed
- The whole under-the-hood implementation of the `Root`'s setting `tooltipContainerBounds`. The change should be transparent, but please inform us if the functionality broke in some way.

### Fixed
- `GraticuleSeries` was not being redrawn if its `clipExtent` was being set after series was already rendered.
- `idField` was not being respected in some cases in a `MapSeries`.
- `MapPointSeries` was not setting map bounds properly if it did not contain any geometries (just points with lat/long).
- `keepTargetHover` on a `Tooltip` was not working when `tooltipContainerBounds` was used in `Root`.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
