### ISSUE TITLE
Adding themes to Map don't work

### ISSUE THREAD

**Issue by abishekrsrikaanth** [amcharts/amcharts5#708]
The map control has been quite great, but for some reason, I can seem to set the theme for it. I tried to set different themes, but it still seems to render the same colors again.

here is a test https://codepen.io/abishekrsrikaanth/pen/xxzmYBW

**Comment by martynasma** [comment]
Themes like Frozen define only [color sets](https://www.amcharts.com/docs/v5/concepts/colors-gradients-and-patterns/#Color_sets) (used when colors are assigned to series on an XYChart, or to slices on a PieChart). They do not define [interface colors](https://www.amcharts.com/docs/v5/concepts/colors-gradients-and-patterns/#Interface_colors).

Here's a code for the Frozen team:
https://github.com/amcharts/amcharts5/blob/master/src/.internal/themes/FrozenTheme.ts

MapChart does not use any color sets. It uses interface colors. I.e. for polygon coloring it uses interface's button background color.

That's why it seems that the theme is not working.

I suppose your best bet would be to apply colors to the required elements manually:

```JavaScript
polygonSeries.mapPolygons.template.setAll({
  tooltipText: "{name}",
  toggleKey: "active",
  interactive: true,
  fill: am5.color(0xbec4f8)
});

polygonSeries.mapPolygons.template.states.create("hover", {
  fill: am5.color(0xa5abee)
});
```

Or if you'd like to use it from theme, here's how you can do it:

```JavaScript
var colorset = am5.ColorSet.new(root, {});

polygonSeries.mapPolygons.template.setAll({
  tooltipText: "{name}",
  toggleKey: "active",
  interactive: true,
  fill: colorset.getIndex(0)
});

polygonSeries.mapPolygons.template.states.create("hover", {
  fill: colorset.getIndex(1)
});
```
