### ISSUE TITLE
setting topDepth to 2 or above doesnt hide the 2nd or higher nodes on the graph

### ISSUE THREAD

**Issue by JackNgis** [amcharts/amcharts5#712]
When setting the topDepth to 2 or more, in a tree chart, nodes of 2 or more are not hidden on the first display of the tree, they still appear with no links, clicking on them to show/hide links will hide the links on first click, then on 2nd click will display the links and hide the node correctly.

This is reproducible  in the docs by simply setting topDepth to 2 or more in the example code
 var series = container.children.push(
  am5hierarchy.Tree.new(root, {
    singleBranchOnly: false,
    downDepth: 1,
    initialDepth: 5,
    topDepth: 2, //set this to 2 or more
    valueField: "value",
    categoryField: "name",
    childDataField: "children",
    orientation: "horizontal"
  })
);
![image](https://user-images.githubusercontent.com/120081062/206369678-34179f5a-b2f1-4cdf-9f9f-5505f41fcdf3.png) 
(A0 double clicked to hide, but other can still be seen)

https://www.amcharts.com/docs/v5/charts/hierarchy/tree/

**Comment by zeroin** [comment]
Hi,

Which of the examples did you use? It would be a lot easier if you could simply send a link to a codepen where this is reproduced.

**Comment by JackNgis** [comment]
that specific example is on this code pen
https://codepen.io/team/amcharts/pen/OJmBxXo
just need to set the topDepth to 2

**Comment by martynasma** [comment]
Fixed in [5.2.42](https://github.com/amcharts/amcharts5/releases/tag/5.2.42).

## [5.2.42] - 2022-12-16

### Added
- `reverseGeodata` setting added to `MapPolygonSeries`. If set to `true`, will reverse direction of polygon corners in GeoJSON.
- `linechanged` event added to MapLine.

### Fixed
- If a chart had multiple vertically stacked Y axes and `snapToSeries` was set, moving mouse to series in the bottom could cause chart cursor to disappear.
- A legend label for a `ZigZag` indicator was showning "NaN" instead of its `depth` value.
- Hierarchy series' `topDepth` setting was not working properly if set to `>1`.
- If a `Sprite` was hidden, it hid it's tooltip even if the tooltip at the moment was used by other element. This caused some wrong behavior with Axis tooltips, as all axis elements share the same tooltip.
- If a `MapLine` was changed and some `MapPoint` was assigned to this line, `MapPoint` was not always updating its position.
- Map with `geoAlbersUsa` projection was not working if `GraticuleSeries` was added to it.
- `MapLine` was showing tooltips in a wrong position (in case lines were not straight).
- `PeriodSelector` was not properly zooming whe data grouping was enabled.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
