### ISSUE TITLE
Bug: ZigZag Shows NaN in Second Parameter on Legend

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#713]
https://www.amcharts.com/demos/stock-chart-with-bollinger-bands-indicator/

![image](https://user-images.githubusercontent.com/32473209/206403133-d48d7741-fd95-4bd2-91d9-c778d6df75c3.png)

**Comment by mukeshbadgujar** [comment]
@martynasma @amcharts Have you checked this for bug??

**Comment by martynasma** [comment]
Fixed in [5.2.42](https://github.com/amcharts/amcharts5/releases/tag/5.2.42).

## [5.2.42] - 2022-12-16

### Added
- `reverseGeodata` setting added to `MapPolygonSeries`. If set to `true`, will reverse direction of polygon corners in GeoJSON.
- `linechanged` event added to MapLine.

### Fixed
- If a chart had multiple vertically stacked Y axes and `snapToSeries` was set, moving mouse to series in the bottom could cause chart cursor to disappear.
- A legend label for a `ZigZag` indicator was showning "NaN" instead of its `depth` value.
- Hierarchy series' `topDepth` setting was not working properly if set to `>1`.
- If a `Sprite` was hidden, it hid it's tooltip even if the tooltip at the moment was used by other element. This caused some wrong behavior with Axis tooltips, as all axis elements share the same tooltip.
- If a `MapLine` was changed and some `MapPoint` was assigned to this line, `MapPoint` was not always updating its position.
- Map with `geoAlbersUsa` projection was not working if `GraticuleSeries` was added to it.
- `MapLine` was showing tooltips in a wrong position (in case lines were not straight).
- `PeriodSelector` was not properly zooming whe data grouping was enabled.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
