### ISSUE TITLE
Funnel series doesn't show slices if all values equals zero

### ISSUE THREAD

**Issue by okadev** [amcharts/amcharts5#718]
actual result:
![image](https://user-images.githubusercontent.com/31209923/207606744-e64cc9b3-f868-4398-8f56-11ca85ccdfe0.png)

expected result: 
![image](https://user-images.githubusercontent.com/31209923/207606338-567d48de-7348-4bae-a56c-398dab6fc831.png)

example:
https://jsfiddle.net/adn3106k/1/

**Comment by martynasma** [comment]
We don't believe that this would be the right behavior.

Funnel is a chart meant to display gradual progress of the data. There's no way to calculate 0 percent of 0.

Having a zero as a starting point is a "no data" scenario, and should be handled as such, e.g. show a message to the user notifying them there is no data, rather than chart.

I hope that makes sense.

**Comment by okadev** [comment]
@martynasma Thank you for your reply. amcharts 4 has this behavior so I thought it was wrong. But it is a cool empty state, if you can add some option for this it would be great

**Comment by martynasma** [comment]
I don't think this is something we should handle with an option.

It's quite easy to do. E.g.:
https://www.amcharts.com/docs/v5/tutorials/show-no-data-warning-on-a-chart/
