### ISSUE TITLE
AM5 Force Directed Charts updated and now children nodes are not linked

### ISSUE THREAD

**Issue by KrautGTI** [amcharts/amcharts5#726]
https://codepen.io/krautgti/pen/xxWgMKR/f9aadce0a0f48a789ab5d8a0511a216a

These charts were 100% working, this morning all of my charts using AM5 Force directed network have the same problem.
<img width="430" alt="Screenshot 2022-12-19 at 11 42 08 AM" src="https://user-images.githubusercontent.com/94489438/208497239-1d868201-a872-40e3-8bab-e1d8423290ac.png">
<img width="1136" alt="Screenshot 2022-12-19 at 11 44 37 AM" src="https://user-images.githubusercontent.com/94489438/208497378-6c4588c7-4ce7-456b-b2eb-07e4442a0648.png">

**Comment by martynasma** [comment]
Fixed in [5.2.44](https://github.com/amcharts/amcharts5/releases/tag/5.2.44).

## [5.2.44] - 2022-12-20

### Fixed
- If a `ForceDirected` node with `topDepth` set to `1` was clicked to hide children and then clicked again to reveal them, the clicked node was hidden. (since 5.2.42)
- `ValueAxis` with `min` and `max` set could result in an empty chart. (since 5.2.43)

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by KrautGTI** [comment]
Im sorry, I am using the cdn links, not local copies- the charts were working as is until just yesterday.

**Comment by KrautGTI** [comment]
I see what you mean, Ill let you know if it persists! Thanks!
