### ISSUE TITLE
X axis ticks and labels appear below scrollbar

### ISSUE THREAD

**Issue by jcgithub9** [amcharts/amcharts5#75]
Question - When a scrollbar is added to X-axis of an xy chart via a push or unshift to the chart's bottomAxesContainer, the X-axis ticks and labels then appear below the scrollbar.  Is there a way to get scrollbar to appear below the ticks and labels?  Keeping ticks and labels close to the X-axis is more visually appealing than having them offset from the axis by a scrollbar.
Note in amcharts4 with analogous action of making the scrollbar's parent the bottomAxesContainer, the scrollbar does appear below ticks/labels.

**Comment by martynasma** [comment]
Fixed in [5.0.6](https://github.com/amcharts/amcharts5/releases/tag/5.0.6).

## [5.0.6] - 2021-11-18

### Added
- Accessibility: new setting on `Sprite`: `focusableGroup`. If set, TAB key will iterate through first elements of each focusable group, allowing user to select within group using arrow keys. [More info](https://www.amcharts.com/docs/v5/concepts/accessibility/#Grouping_focusable_elements).
- New `Root` setting: `autoResize` (default: `true`). If set to `false`, the chart will not automtically resize itself when width/height of its container change. Use `resize()` method to resize manually.
- New `Root` method: `resize()`. Resizes chart to fit container dimensions, if automatic resizing is disabled (`root.autoResize = false`).
- Global `am5.p0` shortcut function added which returns `Percent(0)`.
- All element will now have a read-only property `root` which holds their `Root` object.
- New `Sprite` events: `rightclick` and `middleclick`. Please note that adding `rightclick` event will not disable possible contextual menu on right-mouse click.
- New `XYCursor` setting: `snapToSeriesBy` (default: `"xy"`). Defines in which direction to look when searching for the nearest data item to snap to. Possible values: `"xy"` (default), `"x"`, and `"y"`.

### Changed
- If set `wheel` event will now fire even if `wheelable = false`. This allows capturing wheel events on elements without interfering with scroll of the document.

### Fixed
- `oversizedBehavior` on `Label` (still) was not handling `maxWidth` and `maxHeight` values properly (since `5.0.2`).
- Dynamically updating `geoJSON` on a `MapPolygonSeries` was not working properly in some cases.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download-v5/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
