### ISSUE TITLE
Pie Charts- slices are not centered

### ISSUE THREAD

**Issue by Alsaf** [amcharts/amcharts5#750]
The pie slices doesn't originate from the center of the circle. Its clearly noticable when there are thinner pie slices in the chart
https://codepen.io/alsaf/pen/VwBmZgw

**Comment by martynasma** [comment]
They do, but borders of some slices can be drawn on top of other slices, so it might seem that way.

Try reducing slice border width:

```JavaScript
series.slices.template.setAll({
  strokeWidth: 0.5
})
```

**Comment by Alsaf** [comment]
@martynasma That didn't fix the issue. Its not just the borders, the slices are drawn off the center of the circle.

**Comment by martynasma** [comment]
If you need a slice to perfectly start at the middle (or seem like it), you need to completely eliminate the border by setting `strokeWidth: 0`. That will eliminate gaps between slices, though.

**Comment by Alsaf** [comment]
![image](https://user-images.githubusercontent.com/10709445/212887909-b5341ee5-48bc-4188-b1fe-be30c6dd3ad5.png)
Border doesn't make much difference. slices are way off center.

![image](https://user-images.githubusercontent.com/10709445/212888147-6dfe5f58-0b97-40cc-9c2d-e75efd3999c2.png)

**Comment by martynasma** [comment]
The first screenshot seems to be using borders.

The second one is blown up significantly, so any visual discrepancies are exaggerated. They are not as prominent in regular view.

<img width="419" alt="chrome_2023-01-17_14-01-55" src="https://user-images.githubusercontent.com/1458520/212894752-a804dc82-e9e3-4fd4-9ce4-f50a01ac4648.png">

Those result from slices being only slightly enlarged so that they fit well together, and do not seem to be disjointed (tiny white hairlines between them).

Hope it makes sense.
