### ISSUE TITLE
XY chart shows disjointed intervals at closer zoom despite baseInterval

### ISSUE THREAD

**Issue by binaryartifex** [amcharts/amcharts5#752]
**Bug description**

EDIT [FIXED IN LATEST SANDBOX]: and ive just discovered that after following the "Location of items on date axis and date-based series" guide on the AMCharts 5 website, the chart provided in the code sandbox, the X axis labels and data points no longer line up at all as can be seen in the codesandbox (ie. if I hover around the 6AM label, the tooltip for 9AM pops up). This is the last thing i expected to waste all night on trying to figure out. the data points are all in order, ive followed the docs to the letter as far as I can see. what am i doing wrong?!?

I have created a very basic time series XY Line Chart with a dataset (see codesandbox) that increments every 30 minutes for a whole day (12AM till 11:30PM). Ive set the baseInterval to `baseInterval: { timeUnit: "minute", count: 30}` as its my understanding this is required for a dataset such as mine. I thought id fixed an issue with axis/label/tooltip alignment being out of whack however upon zooming closer into the dataset, it will show clean hourly distribution however the next zoom level, instead of showing clean 30 minute intervals, the labels have been computed strangely (7:02 to 7:33, etc). As a result the data points themselves no longer align with the computed labels. Ive been at this for hours now and for the life of me i can't figure out what im doing wrong...the 30 minute interval is a common use case at my place of work it would be great if someone could determine if this is a bug or if ive just missed something and need to either go to bed or crawl under my desk with a bottle of whiskey...

In this demo, as you begin zooming into the dataset, when it should cleanly distribute the data in 30 minute increments, it becomes a mess. 

[https://codesandbox.io/s/hungry-easley-eycsmb?file=/src/XY-Chart.tsx](url)

**Environment (if applicable)**

@amcharts/amcharts5 5.2.47
Windows 11
VSCode 1.74.2
Typescript 4.9.4
Node 18.12.1

**Comment by martynasma** [comment]
> In this demo, as you begin zooming into the dataset, when it should cleanly distribute the data in 30 minute increments, it becomes a mess.

I tried zooming in and out for a while. The labels, the series itself, and axis seems good to me.

Can you perhaps post a screenshot of what you mean by the "mess"?

**Comment by martynasma** [comment]
Gotcha. Thanks!

Seems like a bug. We'll fix it in the next version, and will let you know.

**Comment by martynasma** [comment]
Fixed in [5.2.48](https://github.com/amcharts/amcharts5/releases/tag/5.2.48).

## [5.2.48] - 2023-01-17

### Added
- Slovak (sk_SK) locale added.

### Fixed
- Grid was not being placed in correct place on a `DateAxis` with grid or grid interval in 30 minutes.
- Cursor tooltip was not being snapped to an `XYSeries` with `snapTooltip: true` when it was left of the first available data item.
- `PeriodSelector` was not properly zooming the X axis with a non-standard value in `firstDayOfWeek` locale.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
