### ISSUE TITLE
RegressionSeries  on CommonJS, building with angular 15.1.1 with nx 15.5.2 

### ISSUE THREAD

**Issue by muratbeser** [amcharts/amcharts5#762]
Build at: 2023-01-19T11:31:41.741Z - Hash: 5bbd5b6d764eece9 - Time: 19785ms

Warning: /node_modules/@amcharts/amcharts5/.internal/charts/stock/drawing/RegressionSeries.js depends on 'regression'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: bundle initial exceeded maximum budget. Budget 500.00 kB was not met by 190.27 kB with a total of 690.27 kB.

**Comment by Pauan** [comment]
That is not an error, it is just a warning.

It is telling you that the [`regression` npm package](https://www.npmjs.com/package/regression) is using CommonJS modules, not ES6 modules. This means that the `regression` code will be slightly less optimized. This does not hurt anything, you can ignore that warning.

Because this is happening in the `regression` package (not amCharts), there is nothing we can do about it. You should [file a bug report with `regression`](https://github.com/tom-alexander/regression-js) politely asking them to switch to ES6 modules.

The second warning is simply saying that your compiled code is larger than 500 kB. You can also ignore that as well, unless you really care about having a very small file size.

**Comment by muratbeser** [comment]
Hi Puan, I know what the warning means and I put it in here because am5Charts **chose to use** this particular library. I did not put it in here to request a fix.

I was kindly saying "hey guys there is this warning with this particular library, and it may cause some problems with angular users" 

as for your answer I already pulled clone the regression do a custom package and used it but this would not help other Angular users.  I hope this clarify intentions of this issue and how it could be easily solved.

**Comment by Pauan** [comment]
There is no concern, most of the npm packages use CommonJS, it does not cause any problems.

If you want to disable the warning, you can add the `"regression"` package into your `allowedCommonJsDependencies` configuration:

https://angular.io/guide/build#configuring-commonjs-dependencies

You might need to do this with other dependencies as well, such as `"xlsx"` or `"pdfmake"`. CommonJS packages are very common.

**Comment by muratbeser** [comment]
Yet those libraries often used on backend like arent they?  but as I understand you don't see CommonJS as package method used for backend. So we have approach difference in here. (and yes I know that even angular it self gives out the warning)

so have a nice day thank you for your time.
