### ISSUE TITLE
Error when grouping data - undefined .bullets[0]

### ISSUE THREAD

**Issue by bye7** [amcharts/amcharts5#774]
**Bug description**
I'm listening to an event that's fired every second, where I call and pass arguments to addData(), when I enable grouping the graph will freeze when it attempts to group data. To reproduce, open "Line Chart Adding Data Every Second" demo in CodePen and make the following changes to the lines:

**#&#8203;34** - Increased loop iteration from `50` to `1000` (generating more data)
**#&#8203;69** - Changed `groupData` setting to `true`
**#&#8203;166** - Commented out the removal of the first data element from a series.

The error is produced in this [CodePen](https://codepen.io/bye7/pen/JjBBZoG) at line:
**#&#8203;183** - `lastDataItem.bullets[0]` returns "undefined", the next line cannot `newDataItem.bullets[0].get()`.
Which throws error: `Uncaught TypeError: Cannot read properties of undefined (reading 'get')`.

**Environment (if applicable)**
AmCharts 5.3.0 library

**Comment by zeroin** [comment]
With grouping enabled things get complicated here. You need to add data to the mainDataSet, not to currently selected one. Bullet is never not created for the grouped data set, because bullet:true is not passed to the grouped data item. I tried to do it with grouped data:

https://codepen.io/team/amcharts/pen/poZZQjg

I used different approach - instead of creating actual Bullet I create a simple sprite and udpate it's position to the last data items point. Note, I get lastDataItem from _mainDataSet. And I must admit I couldn't think of a proper way to do the animations of the last data point when data is grouped, so it's not as smooth as in the original demo, but it's the best I could do.
