### ISSUE TITLE
Mouse display tooltip problem.

### ISSUE THREAD

**Issue by mbdmt** [amcharts/amcharts5#775]
When setting maxTooltipDistance: 0 in v5, just display a tooltip. When the mouse hover the column chart of 2020, the "income" data should be displayed, but the "expenses" data should be displayed, and the income data must be moved to the top to appear, v3 There is no such problem.

**demo
https://codepen.io/chinolin/pen/MWBqdbZ

**Environment 
amCharts5
chrome
Loading script files (script src ...amcharts5/index.js)

**Comment by martynasma** [comment]
When `maxTooltipDistance: 0` is used, the cursor determines closest data item to show tooltip for.

The "location" of a dataitem is the bullet/joing for LineSeries, and top of the column for the ColumnSeries.

So the chart will show tooltip whichever is closer to mouse cursor.

This is by design.

If you need to show Income tooltip whenever cursor is over the column, and Expenses whenever cursor over the bullet of a LineSeries, you will need to remove tooltip information from series, and place `tooltipText` on column and bullet templates.

**Comment by mbdmt** [comment]
> 

The documentation says it's the closest distance, but it's actually the farthest...

**Comment by martynasma** [comment]
Not really. Watch how tooltip switches to the column when it gets closer to the top of the column.

https://user-images.githubusercontent.com/1458520/215711139-222c1a4a-e60d-42af-b779-a1e6885b6133.mp4

When the cursor is at the bottom of the column, column's top is farther away from the cursor than the bullet of the line series.

I hope that makes sense.

**Comment by mbdmt** [comment]
> 

The method written in the template is fine, thank you!

original way:
`var series = chart.series.push(am5xy.LineSeries.new(root, {
   ....
  tooltip: am5.Tooltip.new(root, {
  ....
  })
}));
`

change to :
`
series.columns.template.setAll({
  tooltipText: "{name}, {categoryX}: {valueY}"
  ....
});
`
