### ISSUE TITLE
Stock chart with axis bullet

### ISSUE THREAD

**Issue by chandru21** [amcharts/amcharts5#778]
I want axis bullet like this https://codepen.io/Chandru228/pen/mdjQeBL. In this I adjusted dy value to place bullet on line. but it will not workout when we have multiple data.

Can you provide me a solution for this?

**Comment by zeroin** [comment]
Just delete dy: -100 from here:

```
  var bullet = am5.Container.new(root, {
    dy: -100
  });
```

**Comment by chandru21** [comment]
No. I think you didn't get me clearly. Check the same link. I want place the bullets on curve of the line series dynamically like how placed on for Apr 21, 2021 data

**Comment by zeroin** [comment]
Oh, then you should add bullets to the stockSeries, not to the axis:
https://www.amcharts.com/docs/v5/concepts/common-elements/bullets/

**Comment by chandru21** [comment]
![image](https://user-images.githubusercontent.com/27004276/216515766-e00e1caa-4c84-47f7-8ae5-6648b5986621.png)

The image is implemented with amcharts 4. Is this possible to implement the same in amcharts 5 by using axis bullets/ series bullets? If yes, kindly provide me some link

**Comment by zeroin** [comment]
Yes, you can do this with series bullets. We don't have exact bullet in v5 though, but you can of course use svgPath for it. So just take any demo with bullets:

https://www.amcharts.com/demos/trend-lines/

Instead of a Circle, use Graphics, set svg path which would draw shape like in your picture and set centerY for the Graphics to am5.p100 so that the center would be at the bottom of the Graphics.
