### ISSUE TITLE
stock chart freezes/crashes entire page when height is reduced to a certain threshold

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#780]
When using stock chart, reducing the height of the panel beyond a certain threshold will free/crash the entire page, forcing a hard exit. This was still okay with normal XYCharts.

Minimal reproducible example:
- open https://codepen.io/team/amcharts/pen/MWrmBoV
- change height of chartdiv to 10vh

**Comment by martynasma** [comment]
Fixed in [5.3.2](https://github.com/amcharts/amcharts5/releases/tag/5.3.2).

## [5.3.2] - 2023-02-03

### Changed
- Panning/zooming with a right mouse button was disabled.

### Fixed
- `StockChart`'s panels date axes could go out of sync if data range was different. Now all X-axes will sync their `min` and `max`  to the axis of the main panel (one that contains `stockSeries`).
- `StockChart` could crash if the height of div was really small.
- Private settings `selectionMinFinal` and `selectionMaxFinal` were not being set on a `DateAxis`.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
