### ISSUE TITLE
Display labels on a treemap when the rectangles are small

### ISSUE THREAD

**Issue by birkasbence** [amcharts/amcharts5#787]
Hello,

I have a problem. After a certain size, the labels disappear from the treemap and I'm not sure how to solve this.
The `oversizedBehavior` is set to `"wrap"`.

Without the labels:
<img width="204" alt="Screenshot 2023-02-06 at 16 38 24" src="https://user-images.githubusercontent.com/53494862/217015551-4539db77-618f-4baa-9132-1dff830cee15.png">

With the labels:
<img width="447" alt="Screenshot 2023-02-06 at 16 39 14" src="https://user-images.githubusercontent.com/53494862/217015772-84ff4e02-7f19-48f8-90c7-7bcae8b680b7.png">

**Comment by xorspark** [comment]
That's strange, `wrap` should work in this case. I'm not able to reproduce this in [my codepen](https://codepen.io/team/amcharts/pen/LYBvjWZ/7593e9d2efa51ebd15bff9a26f0d5cbf?editors=0010). Can you confirm you're on the latest release? Can you also provide a codepen of your setup that reproduces the issue?

**Comment by birkasbence** [comment]
Yes I'm on the latest release. I can't really show you the code, but I found out that the labels become invisible after either the width or the height becomes less then 201px. Is there a way to force them to be visible all the time?

**Comment by xorspark** [comment]
Generally speaking as long as the `oversizedBehavior` is not set to `fit`, it should be visible no matter the size. Do you happen to have a responsive theme enabled? The [default rules](https://github.com/amcharts/amcharts5/blob/master/src/.internal/themes/ResponsiveTheme.ts#L764-L777) set `forceHidden` to true on the labels when the width is around 200px. Since there is only one rule for Hierarchy charts, you can simply remove the theme in this case or create your own theme without any default rules instead: https://www.amcharts.com/docs/v5/concepts/responsive/#Applying.

**Comment by birkasbence** [comment]
Yes, this is exactly what my problem was. Thank you very much!
