### ISSUE TITLE
The `reset` button in stock charts > toolbar crashes the chart

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#788]
Under stock charts, when the `draw` button is enabled, after making a few drawings, pressing `reset` (instead of `clear` which is on the same row as the draw button) would no longer enable you to draw any more and would subsequently crash the chart completely.

**Comment by martynasma** [comment]
Fixed in [5.3.3](https://github.com/amcharts/amcharts5/releases/tag/5.3.3).

## [5.3.3] - 2023-02-08

### Added
- New method on `Language`: `addTranslationsAny()`. Allows adding custom translations to locale. [More info](https://www.amcharts.com/docs/v5/concepts/locales/creating-translations/#Extending_locale_with_custom_prompts).

### Fixed
- In `StockChart` if "Reset" button was pressed when there were drawings present on the chart, it could freeze.
- Calling `dispose()` on a `StockToolbar` was not properly removing all DOM elements.
- `getCellWidthPosition()` method on a `CategoryAxis` was returning a wrong result.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
