### ISSUE TITLE
Bug: Unexpected tooltip animation on bar charts

### ISSUE THREAD

**Issue by sutkovoy** [amcharts/amcharts5#796]
Amcharts 5. When the chart has an item with a small amount of % at the end and the user hovers on the last thing from the right, tooltips appear with some animation: 

Working demo to reproduce the bug:
https://stackblitz.com/edit/angular-ivy-tc7ecr?file=src%2Fapp%2Fapp.component.ts,package.json

Video: https://www.youtube.com/embed/kbG_8LcmjBQ

**Comment by martynasma** [comment]
That is a weird bug. We're looking into it. Thanks!

**Comment by martynasma** [comment]
Fixed in [5.3.4](https://github.com/amcharts/amcharts5/releases/tag/5.3.4).

## [5.3.4] - 2023-02-20

### Added
- `cellWidth` read-only private setting added to `Axis`. Holds a distance in pixels between two grid lines. It might not be accurate as grid on `DateAxis` might not be at equal intervals.
- `getCellWidthPosition()` added to all axis types. Returns relative distance between two grid lines of the axis.

### Fixed
- HTML-based tooltip might produce a funky animation if it was displayed very close to the edge of the chart.
- `StockChart`'s X-axes from all panels not always were syncing properly between data updates.
- Fixing bug where click event was not dispatched on tooltips outside of the chart boundaries.
- Changing a color for a `LineSeries` in with a `StockChart` control was not changing its tooltip color.
- `GaplessDateAxis` was not taking into account missing dates when using `zoomToDates()` or `zoomToValues()` methods.
- When data grouping was on and data was changed, `ValueAxis` was zooming to incorrect position.
- Radial labels sometimes could get reversed when updating their settings.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
