### ISSUE TITLE
Tooltips that approach the edge of the chart don't always correctly position themselves to be inside the chart.

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#80]
Hi,

I have an issue with tooltips not correctly displaying inside the chart bounds.

Take this screen recording as an example.

There are a bunch of series near the top edge of the chart, Most of the time if there are multiple tooltips they don't correctly position themselves inside the chart, but rather overflow the canvas container and cannot be seen.

Is this expected behaviour or a bug? Seems to me to be a possible bug?

https://user-images.githubusercontent.com/2810/142384556-20de2e98-0726-4d86-9d2c-61ac422b8569.mov

**Comment by martynasma** [comment]
Normally, tooltips should arrange themselves to be within plot area:

![image](https://user-images.githubusercontent.com/1458520/142436725-76f0cc52-2471-447a-9c72-100aa86dca3a.png)

I can't quite reproduce the issue from your video. Would you be able to post your chart on CodePen or jsFiddle?

**Comment by jcgithub9** [comment]
Related question/observation - in amcharts4 tooltips will 'overflow' outside the bounds of the chart if there are a lot of them, whereas in amcharts5 they get truncated by chart/plot area.  Seems to be a change in default behavior between v4 and v5; not necessarily improper, just not sure if intentional.  Also curious if there is a way to allow the tooltips to not be truncated and overflow the chart bounds as in amcharts4?

**Comment by sassomedia** [comment]
I'm seeing that issue as well with items that display a tooltip and are placed close to the top. It does cut off and doesn't invert the positioning. Maybe something with the edge detection is not quite working:
<img width="553" alt="Screen Shot 2021-11-19 at 1 33 58 PM" src="https://user-images.githubusercontent.com/5614099/142565568-d472e72b-d36d-42ca-b3e6-d412d9b9976f.png">

It's not a big issue in my case because I need the tooltip to point upwards or even sideways may be acceptable. When pointing upwards, I can just extend the chart area to get the full tooltip.

@jcgithub9, the main difference between the chart versions is that am4 is SVG and am5 is Canvas based. The advantage of Canvas is that it is much faster but everything drawn on Canvas is restricted by the bounds of it. That's the limitation unfortunately but maybe the automatic tooltip positioning can be improved.

**Comment by martynasma** [comment]
Folks, you'd make our life much more easier, and speed up fixes, if you could provide a CodePen that demonstrates the issue. Thanks :)

**Comment by jcgithub9** [comment]
Code Pen example, showing amcharts4 XY chart where tooltips extend beyond chart, and same XY chart in amcharts5 where tooltips are clipped.  
[https://codepen.io/jcgithub9/pen/wvqOrrK](url)
Understand the clipping in amcharts5, and just noting the difference between versions.  Am planning to use maxTooltipDistance setting to reduce number of displayed tooltips, and possibly the option to only ever display one tooltip at a time.  Only concern with the clipping as compared to amcharts4 is it may be unclear to users that tooltips are being clipped and that not all are being displayed as they were previously in amcharts4.

**Comment by martynasma** [comment]
> Code Pen example, showing amcharts4 XY chart where tooltips extend beyond chart, and same XY chart in amcharts5 where tooltips are clipped. [https://codepen.io/jcgithub9/pen/wvqOrrK](url) Understand the clipping in amcharts5, and just noting the difference between versions. Am planning to use maxTooltipDistance setting to reduce number of displayed tooltips, and possibly the option to only ever display one tooltip at a time. Only concern with the clipping as compared to amcharts4 is it may be unclear to users that tooltips are being clipped and that not all are being displayed as they were previously in amcharts4.

OK, so this is a different issue. amCharts 5 is canvas, which means that all that is drawn on it is restricted to its limits, whereas, in amCharts 4 SVG, individual elements go outside bounds.

That said, I strongly recommend using `maxTooltipDistance` to limit number of tooltips, like you suggested yourself, as displaying so many is just bad UX.

That said, tooltips should never be clipped in amCharts 5, unless they physically cannot fit. If there's a situation where tooltips should fit, but do not, it must be a bug, and I would very much like to see such demo, so that we can attempt to fix it.

**Comment by buggedcom** [comment]
For my original demo it's going to be quite hard to extract a codepen as we have embedded amCharts inside some highly complex React logic. I'll try to get an example but not sure when I will be able to.

**Comment by jcgithub9** [comment]
I may have reproduced the original issue in updated codepen:   https://codepen.io/jcgithub9/pen/wvqOrrK
Shows a case where tooltips near top of chart do not auto-arrange into chart when they should fit and get clipped at top, whereas tooltips near bottom of chart do re-arrange into chart.  In codepen example, there are 6 points near top of chart for year 1970, and only two tooltips will appear and can see that there are more tooltip arrows leading to above clipped tooltips.  Had this occur when setting maxTooltipDistance - set it large so that all six points near top of chart in example would be active by hover.  In second chart in example, maxTooltipDistance is not set, and tooltips at both top and bottom of chart auto-arrange properly for same set of points.  Not sure if originator of problem is using maxTooltipDistance or not, and not sure if that property is related to original problem.

**Comment by sassomedia** [comment]
> Folks, you'd make our life much more easier, and speed up fixes, if you could provide a CodePen that demonstrates the issue. Thanks :)

Yup, sometimes that may take a bit of time to get a simplified version ready. Here's the [pen](https://codepen.io/sassomedia/pen/YzxoyBK?editors=0010) from my screenshot. It appears that it's caused by the `dy` offset. If applied, it will not align itself. If `dy` is commented out, it will show within bounds.

**Comment by martynasma** [comment]
@sassomedia Well, `dy` is a low-level setting. It causes element to move by a number of pixels vertically. No questions asked. I'm afraid it would be wrong to adjust tooltip fitting mechanism to account for custom dy/dx.

If you absolutely need to use it on a tooltip, I suggest adding a bit extra padding on top of the chart.

**Comment by martynasma** [comment]
Fixed in [5.0.12](https://github.com/amcharts/amcharts5/releases/tag/5.0.12).

## [5.0.12] - 2021-11-24

### Added
- `latitudeField` and `longitudeField` added to `MapPointSeries` for an easier way to add data.

### Changed
- Tooltip arrangement algorithm with many XY series was improved.

### Fixed
- Axis fill rule of `DateAxis` sometimes skipped an interval or was drawn two fills in a row. Also, with months as interval between grids, the end of the fill was not at exact position where it should have been.
- When setting new data for a series, if new data has less items than series had before, a JS error could occur.


[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by sassomedia** [comment]
@martynasma sorry, missed this notification. But yeah, reason for using `dy` is that the tooltip is over a button with an icon that changes when clicked. The tooltip would be blocking the visible change of the icon, so I have to offset it a bit. To get around the cutoff issue, I have instead flipped the tooltip orientation the other way to display it inside the chart.

**Comment by luktom** [comment]
> @sassomedia Well, `dy` is a low-level setting. It causes element to move by a number of pixels vertically. No questions asked. I'm afraid it would be wrong to adjust tooltip fitting mechanism to account for custom dy/dx.
> 
> If you absolutely need to use it on a tooltip, I suggest adding a bit extra padding on top of the chart.

@martynasma I have similar problem with `dy` setting. I am using it to show the tooltip above the line series bullet, not in a center of it. Adding extra padding is not a solution for me. It seems that `dy` value is still applied by the positioning algorithm when tooltip overflows. Would't be better to ignore `dx` and `dy` settings when tooltip overflows? 

Please see you modified demo: https://jsfiddle.net/tbdo4xvr/21/

Additional question: why tooltips are not being flip when `pointerOrientation` is set to `vertical` but they are when `horizontal` is set, that would also solve the problem.

**Comment by morrow95** [comment]
Got here looking for a solution as well.  In my case I am also using the dy setting.  I am setting dy: -30 so the series tooltip is never 'behind' the xaxis tooltip and hidden from view... it seems the xaxis tooltip is layered over the series tooltip in some cases when the y value is low.  dy solves that problem, but the side effect is when the tooltip is high in the chart the top of it can be cutoff.
