### ISSUE TITLE
Tooltip color change

### ISSUE THREAD

**Issue by chandru21** [amcharts/amcharts5#807]
![image](https://user-images.githubusercontent.com/27004276/219306960-4c19f929-41f1-4b29-9c2a-df61ee63e4f1.png)

I want to change tooltip background color while change the line series color by using 
![image](https://user-images.githubusercontent.com/27004276/219307195-5d31bae9-adf9-42a1-b5d0-83199707d4b3.png)
this popup.

**Comment by martynasma** [comment]
Fixed in [5.3.4](https://github.com/amcharts/amcharts5/releases/tag/5.3.4).

## [5.3.4] - 2023-02-20

### Added
- `cellWidth` read-only private setting added to `Axis`. Holds a distance in pixels between two grid lines. It might not be accurate as grid on `DateAxis` might not be at equal intervals.
- `getCellWidthPosition()` added to all axis types. Returns relative distance between two grid lines of the axis.

### Fixed
- HTML-based tooltip might produce a funky animation if it was displayed very close to the edge of the chart.
- `StockChart`'s X-axes from all panels not always were syncing properly between data updates.
- Fixing bug where click event was not dispatched on tooltips outside of the chart boundaries.
- Changing a color for a `LineSeries` in with a `StockChart` control was not changing its tooltip color.
- `GaplessDateAxis` was not taking into account missing dates when using `zoomToDates()` or `zoomToValues()` methods.
- When data grouping was on and data was changed, `ValueAxis` was zooming to incorrect position.
- Radial labels sometimes could get reversed when updating their settings.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by chandru21** [comment]
Let me know if there is any event that will get triggered when a user clicks on the "Save" button of the modal.

**Comment by martynasma** [comment]
```JavaScript
stockChart.getPrivate("settingsModal").events.on("done", function(ev) {
  if (ev.settings === null) {
    // Cancelled
  }
  else {
    // Saved
    console.log(ev.settings);
  }
});
```
