### ISSUE TITLE
Hovering on legend item for a pie chart does not show slice's tooltip as done in amcharts4

### ISSUE THREAD

**Issue by jcgithub9** [amcharts/amcharts5#81]
With amcharts4, with a pie chart legend, hovering over a legend item will show the tooltip on the corresponding pie slice.  This behavior does not seem to occur with amcharts5 (at least not by default).  Not sure if an intentional change with amcharts5?  If so, could use some guidance on how to replicate this behavior, presumably by adding an event/adapter to show the slice's tooltip upon legend item hover-over.

**Comment by martynasma** [comment]
Fixed in [5.0.7](https://github.com/amcharts/amcharts5/releases/tag/5.0.7).

## [5.0.7] - 2021-11-19

### Added
- New setting `pan` (default: `"none"`) added to `AxisRendererX` and `AxisRendererY`. If set to `"zoom"` will enable zoom of axis scale by dragging in axis label area.

### Changed
- Heat rules will not longer apply setting value if target data item does not have any numeric value.
- Hovering legend item will now simulate hover on related item on some charts (e.g. `PieSeries`, `Hierarchy`, `Venn`).

###
- `HeatLegend` was acting out when its `showValue()` method was called with non-numeric parameter.
- If series was pre-hidden before chart init, its status was not being correctly reflected in related legend item.
- Locales in script version were not working properly.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
