### ISSUE TITLE
How to clear a line drawed on a stock chart programaticaly?

### ISSUE THREAD

**Issue by renatonmag** [amcharts/amcharts5#816]
Hi. I'd like to clear the candlestick chart off all drawed lines. But I want to call clear from a function. For exemple, to clear this line. Is it possible?

![image](https://user-images.githubusercontent.com/123212911/220532025-9823fdd8-a757-4663-af92-858ab1eeb225.png)

**Comment by zeroin** [comment]
All the drawing series are added to `drawings` list. So you get the series and call clearDrawings() method:

`mainPanel.drawings.getIndex(0).clearDrawings()`

**Comment by dez1729** [comment]
I've just encountered the same problem but I think `clearDrawings()` does not seem to exist (or not exposed in typescript).
This call seemed to work for me:
`mainPanel.drawings.clear()`

**Comment by dez1729** [comment]
I noticed the problem with using clear is that I cannot reuse the `drawings` variable to load another annotations. Is there another way to load new annotations after using `clear()`?

**Comment by martynasma** [comment]
We're adding `clearDrawings()` method on `DrawingControl` in the next version. Will notify here, when it's out.

**Comment by martynasma** [comment]
Implemented in [5.3.9](https://github.com/amcharts/amcharts5/releases/tag/5.3.9).

## [5.3.9] - 2023-03-31

### Added
- New `PeriodSelector` setting: `hideLongPeriods`. Indicates whether to hide buttons for periods that are longer than the actual data on chart.
- New `DrawingControl` methods: `clearDrawings()` and `setEraser(true | false)`.
- Methods `hide()` and `show()` will now properly hide and show any indicator.
- `MapChart` methods `zoomToGeoPoint()` and `zoomToGeoBounds()` now accepts `rotationX` and `rotationY` parameters. If provided, the map not only zoom to the provided point/bounds but will rotate so that this point/bounds would be in the center. Mostly usefull with `geoOrthographic` projection.
- `MapChart`'s `convert()` method now accepts `rotationX` and `rotationY` optional parameters. If provided, the calculations will be done as if map is rotated by provided values.
- `MapPolygonSeries` / `MapPointSeries` method `zoomToDataItem()` now accepts an optional boolean `rotate` parameter. If it's `true`, the map will rotate so that this point/polygon would be in the center. Mostly useful with `geoOrthographic` projection.

### Changed
- Hiding a `StockPanel` via its `hide()` method will now animate it to size 0 before hiding completely.

### Fixed
- The scale of the `StockChart` could become incorrect if there were compared series and the scale was switched back and forth between logarithmic and regular.
- HTML-based tooltips were sized incorrectly in some cases.
- Setting `pointerOrientation` on a `Tooltip` was not updating an already visible tooltip.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
