### ISSUE TITLE
Stock Chart: Annotation labels not applying when close to the graph

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#817]
For stock chart, trying to apply an annotation label when close to the graph will not apply, but when far enough away it will.
![image](https://user-images.githubusercontent.com/20635596/220786748-bbda4e85-1946-4915-bbcb-55560e015c4b.png)

**Comment by martynasma** [comment]
Fixed in [5.3.5](https://github.com/amcharts/amcharts5/releases/tag/5.3.5).

## [5.3.5] - 2023-02-24

### Changed
- Reverting "Fixing bug where click event was not dispatched on tooltips outside of the chart boundaries" introduced in `5.3.4` as it was causing other issues.

### Fixed
- Down state was changed to a default state if a draggable object was unhovered while dragging.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
