### ISSUE TITLE
Unwanted chart 'pointerover' event fires when moving over columns in XYChart.

### ISSUE THREAD

**Issue by CodeCabbie** [amcharts/amcharts5#828]
I'm using the chart "pointerover" event to detect the user mousing over an XYChart. I'm also using chart 'pointerout' to detect them leaving it.

Unfortunately both events also fire unwantedly when the mouse pointer moves over any of the columns of the ColumnSeries being displayed *in* the chart.

I can't find a way to stop these additional firings, neither can I distinguish them from the real ones that occur correctly at the edge of the XYChart.

It's as though the column is treated as 'outside' the chart.

Is this a know issue? How can I ignore the events occurring inside the chart?

**Comment by zeroin** [comment]
If you want a reliable solution to register mouse over and out over the chart div, my recommendation would be to add listeners to chart's div:
```
document.getElementById("chartdiv").addEventListener("pointerover", ()=>{
  console.log("over");
})

document.getElementById("chartdiv").addEventListener("pointerout", ()=>{
  console.log("out");
})
```
As canvas does not support true interactivity, it is simulated using a ghost canvas and detecting what color is under the mouse. And on the edges of sprites, because of anti-aliasing the colors are changing so the pointer out event is fired while you move the mouse over the chart.
