### ISSUE TITLE
Heat Rules - behavior when valueField not populated

### ISSUE THREAD

**Issue by jcgithub9** [amcharts/amcharts5#84]
In amcharts4 for a map chart, if a map polygon series is defined along with a heat rules legend, if a given polygon id does not have its value field populated in the data, that polygon is not filled with a heat-range color, as with no value it is not in the heat rules min/max range, and it remains with default or background fill.  Have benefited from this behavior as have data for some but not all countries specified in worldLow set of polygons, and having a non-heat-range color fill on countries with no values helps indicate they have unspecified values (e.g., are not in the denoted heat rules min/max range).
In amcharts5, if a map polygon series is defined along with a heat map, if a given polygon id does not have its value specified, the polygon will be filled with the color associated with the min property of the heatRules.  This then depicts polygons (e.g., countries) with no values as being at the minimum end of the heat range, rather than not in the range at all.
Not sure if this different behavior between amcharts4 and amcharts5 is intentional; if intentional am seeking to replicate the amcharts4 behavior in this situation.
Did notice the customFunction option in amcharts5 heatRules and considered it as a possibility for replicating the amcharts4 behavior; while a customFunction could likely handle the case of a non-specified value and set fill to a specific color in this case, believe the customFunction would also have to determine appropriate fill when value is specified and therefore would not be leveraging the automatic determination of the fill color within the heat range (unless there is some function that could be called to return the appropriate fill color within a min/max color range for a value).

**Comment by martynasma** [comment]
We'll need to discuss this which way makes more sense. Will keep you posted.

Adding a demo case for reference (Texas does not have a value):
https://codepen.io/team/amcharts/pen/707e173e905f3e21c97382f13d988547?editors=0010

**Comment by martynasma** [comment]
We'll change the behavior of how it was in v4 starting with the next version.

We'll inform you here when it's out.

**Comment by martynasma** [comment]
Fixed in [5.0.7](https://github.com/amcharts/amcharts5/releases/tag/5.0.7).

## [5.0.7] - 2021-11-19

### Added
- New setting `pan` (default: `"none"`) added to `AxisRendererX` and `AxisRendererY`. If set to `"zoom"` will enable zoom of axis scale by dragging in axis label area.

### Changed
- Heat rules will not longer apply setting value if target data item does not have any numeric value.
- Hovering legend item will now simulate hover on related item on some charts (e.g. `PieSeries`, `Hierarchy`, `Venn`).

###
- `HeatLegend` was acting out when its `showValue()` method was called with non-numeric parameter.
- If series was pre-hidden before chart init, its status was not being correctly reflected in related legend item.
- Locales in script version were not working properly.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
