### ISSUE TITLE
Tooltips positioning broken on export when using tooptipContainerBounds on the root

### ISSUE THREAD

**Issue by andrewfmbs** [amcharts/amcharts5#849]
**Bug description**

When exporting a chart to png with static tooltips and while using `tooltipContainerBounds` on the root, all the tooltips anchor to the bottom left corner of the chart in the image. Issue is not reproducible when tooltipContainerBounds is removed.

Here is a link to a jsfiddle where I have recreated the bug: [https://jsfiddle.net/4d72gcqr/](https://jsfiddle.net/4d72gcqr/)

**Comment by martynasma** [comment]
Fixed in [5.3.8](https://github.com/amcharts/amcharts5/releases/tag/5.3.8).

## [5.3.8] - 2023-03-24

### Changed
- Auto-hidden (as per `oversizedBehavior: "hide"` setting) `Label` elements will now trigger `boundschanged` events.
- Defaults of `marginTop` and `marginBottom` set to `1` on all `ZoomControl` buttons.

### Fixed
- HTML-based tooltips were not being properly sized on first show unless Animated theme was enabled
- HTML-based tooltips were sometimes ignoring `keepTargetHover: true`.
- Tooltip positions were off when exporting a chart with `tooltipContainerBounds` set.
- `DrawingControl` can now be used completely standalone. [More info](https://www.amcharts.com/docs/v5/charts/stock/toolbar/drawing-control/#Standalone_usage_API).
- Internal tweaks that were occasionally interfering with some drag-and-drop libs.
- Horizontal columns were not being properly highlighted when gaining focus.
- Old bullets of data item were not being cleared if `series.data.setIndex` was used to update old data (since 5.3.7).
- `zoomToValues()` (and `zoomToDates()` by extension) method on `GaplessDateAxis` was not working correctly with a date range outside of actual data range.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
