### ISSUE TITLE
No click event when clicking on edge of axis range with tooltip

### ISSUE THREAD

**Issue by tonyhignett** [amcharts/amcharts5#850]
**Bug description**

In a particular case, if you click just at the edge of an axis range which has a tooltip, a click handler on the chart container receives no click event.

Here is a demo: https://codesandbox.io/s/stoic-julien-7hl0bc. To reproduce the problem:
- open the demo window itself in a new window (Open In New Window icon at top right)
- ~~use this answer to see the exact cursor coordinates: https://stackoverflow.com/a/54375312~~
- ~~position the cursor with x-coordinate 601, i.e. just to the left of the red block (y-coordinate anywhere on the graph)~~
- position the cursor just to the left of the red block, on the rightmost column of pixels which does not have the Error tooltip
- click

You won't get a "chart clicked" alert, but you get it anywhere else on the graph.

**Environment (if applicable)**

 - amCharts version: 5.3.7
 - Browser and its version: Chrome 110
 - Related frameworks and their versions: React 18

**Additional context**

If I tweak anything, e.g. the graph width, the axis range, remove the tooltip, it stops happening.

**Comment by zeroin** [comment]
I guess it depends on a width of the chart, but as the div is not fixed, we are getting different results (I could not reproduce this).
However I believe it might happen and I know the reasons why. as Canvas is a single object and does not support interactivity by default, we simulate it by drawing an invisible canvas with a different color for each interactive object. When a mouse moves, we check which color is under the mouse and find out which object is currently hovered (this is default way to do this in most of Canvas applications). However on the edges, because of antialiasing the colors are not exact. We tried different approaches to solve this, but it still fails at some situations. I am afraid at this moment we can not offer a solution.

**Comment by martynasma** [comment]
@tonyhignett Thanks for additional details.

As @zeroin mentioned, we're using pixelmatching on separate canvas to register interactivity.

The problem is that canvas drawings do not support turning off of the antialiasing, which means that in some rare cases edges of the shapes can produce a slightly different color than the shape itself, throwing off interactivity.

Unfortunately, despite our best efforts, we were not able to find a workaround for that.

I hope it's not a huge issue.

**Comment by JonathanWylie** [comment]
@martynasma Have you considered doing something like this to remove antialiasing? https://stackoverflow.com/a/49357655
It looks like it filters out the faded pixels. It would mean there are no "dead" pixels, so interactive events would work better.

**Comment by martynasma** [comment]
Safari does not support SVG filter in canvas. No go :(

**Comment by JonathanWylie** [comment]
Let's try again :-) .
When comparing the colour of the interactive pixel, could you just ignore the opacity of the pixel. Or does antialiasing change the colour as well?

**Comment by martynasma** [comment]
Canvas does not work that way. A pixel has one color. It does not have layers of pixels.
