### ISSUE TITLE
Motion chart leaves residue of the previous points on the chart during animation

### ISSUE THREAD

**Issue by EmineTopcu** [amcharts/amcharts5#864]
**Bug description**
I am creating an animation based on a demo on your website. Since the version 5.3.7, the animation does not clear any of the points previously drawn.

The demo on your website has the same issue when you run the animation:
https://www.amcharts.com/demos/motion-chart/

Version 5.3.6 works without any problems.

**Environment (if applicable)**
I have tried on Google Chrome (Version 111.0.5563.66), Firefox (111.0.1), and Edge (111.0.1661.44).

Version: amCharts 5.3.7

**Comment by martynasma** [comment]
Fixed in [5.3.8](https://github.com/amcharts/amcharts5/releases/tag/5.3.8).

## [5.3.8] - 2023-03-24

### Changed
- Auto-hidden (as per `oversizedBehavior: "hide"` setting) `Label` elements will now trigger `boundschanged` events.
- Defaults of `marginTop` and `marginBottom` set to `1` on all `ZoomControl` buttons.

### Fixed
- HTML-based tooltips were not being properly sized on first show unless Animated theme was enabled
- HTML-based tooltips were sometimes ignoring `keepTargetHover: true`.
- Tooltip positions were off when exporting a chart with `tooltipContainerBounds` set.
- `DrawingControl` can now be used completely standalone. [More info](https://www.amcharts.com/docs/v5/charts/stock/toolbar/drawing-control/#Standalone_usage_API).
- Internal tweaks that were occasionally interfering with some drag-and-drop libs.
- Horizontal columns were not being properly highlighted when gaining focus.
- Old bullets of data item were not being cleared if `series.data.setIndex` was used to update old data (since 5.3.7).
- `zoomToValues()` (and `zoomToDates()` by extension) method on `GaplessDateAxis` was not working correctly with a date range outside of actual data range.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
