### ISSUE TITLE
Tooltips don't seem to work on category y-axis labels without backgrounds

### ISSUE THREAD

**Issue by cbryan-risklens** [amcharts/amcharts5#87]
Hey AMCharts team!

Thank you for your amazing product.

I just upgrade to v5 and, unless I'm missing something, it doesn't seem that tool-tips work on the labels on a category y-axis: https://codepen.io/cbryan-risklens/pen/KKvYVJP
(There's a second weird thing described in a comment on line 28 of this pen, but it's not what I'm worried about here.)

They seem to work fine in v4: https://codepen.io/cbryan-risklens/pen/YzxMqPv

**Comment by martynasma** [comment]
Labels as interactive elements in amCharts 5 are tricky. Basically, it's super hard to determine hover/click over just text because it's impossible to completely eradicate antialising, and the actual colored area is super tiny.

For this to work, you need to add a background to the labels. It does not need to visible, so you can set `fillOpacity: 0`.

```JavaScript
yAxis.get("renderer").labels.template.setup = function(target) {
  target.set("background", am5.Rectangle.new(root, {
    fill: am5.color(0x000000),
    fillOpacity: 0
  }));
}
```

More about template setup functions:
https://www.amcharts.com/docs/v5/concepts/settings/list-templates/#Setup_handler

Here's updated CodePen:
https://codepen.io/team/amcharts/pen/0a1cb2c69a5b93bc72655b291144d272?editors=0010

P.S. the second issue is fixed there as well, but we have a one question per issue policy, so if you need an explanation, post another issue ;)

**Comment by cbryan-risklens** [comment]
Excellent, that worked great. :)

Was there a reason you put `maxWidth` in an adapter (first snippet) instead of on the template (second snippet)?  Is there some benefit to doing it that way?

You wrote this:
```
yAxis.get("renderer").labels.template.setAll({
  tooltipText: "TEST TEST TEST {categoryY}",
  oversizedBehavior: "truncate"
});

yAxis.get("renderer").labels.template.adapters.add("maxWidth", function() {
  return 100;
});
```
As opposed to this:
```
yAxis.get("renderer").labels.template.setAll({
  tooltipText: "TEST TEST TEST {categoryY}",
  oversizedBehavior: "truncate",
  maxWidth: 100
});
```

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by cbryan-risklens** [comment]
Sorry, I wasn't trying to nitpick.  Thanks again for the help!

**Comment by martynasma** [comment]
> Sorry, I wasn't trying to nitpick. Thanks again for the help!

No worries. We're just trying to avoid multi-issue threads. Those make finding required info for users much harder. So better to post it as separate ticket.
