### ISSUE TITLE
Custom Pie Chart Tooltip with HTML Content

### ISSUE THREAD

**Issue by jeinhorn787** [amcharts/amcharts5#878]
**Question**
I am trying to render custom tooltip content on a Pie Chart. Using the `tooltip` and `tooltipHTML` settings on the `slices.template`, I am able to render what I need.  I need to set the shadows on the background so I definitely need to define a `tooltip` where I can alter those settings.

However, this seems to come riddled with visual issues including inconsistent tooltip backgrounds.  I took a screen recording of some of the visual issues I am running into:

https://user-images.githubusercontent.com/29580247/229899784-3fe59eea-2cf7-478b-a0a3-2555bb494f4c.mov

I don't know if there are bugs here or not but ultimately my question is, is there a more elegant way to handle custom tooltip content on a Pie Chart?  Thank you in advanced!

Codepen: https://codepen.io/jeinhorn787/pen/abRoWpW

**Comment by martynasma** [comment]
Fixed in [5.3.10](https://github.com/amcharts/amcharts5/releases/tag/5.3.10).

## [5.3.10] - 2023-04-06

### Added
- `homeRotationX` and `homeRotationY` settings added to `MapChart`. Allows setting home x and y rotations. The chart will rotate to provided values when `goHome()` method is called.

### Fixed
- Accessibility: Legend item's ARIA labels will not contain "Press ENTER to toggle" message if the `clickTarget = "none"` is set.
- Further improvements in rendering/sizing of the HTML-based tooltips.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
