### ISSUE TITLE
Flickering Tooltip using `tooltipHTML` (Post 5.3.10 release)

### ISSUE THREAD

**Issue by jeinhorn787** [amcharts/amcharts5#881]
**Bug description**

**This is a follow up from my previous [issue](https://github.com/amcharts/amcharts5/issues/878) that was addressed in release 5.3.10**

After updating to amCharts 5.3.10, rendering `tooltipHTML` in a Pie chart or Bar chart results in the tooltip flickering when the mouse is moving over the tooltip. This may affect other charts as well but that has not been tested here.  The tooltip looks and behaves correctly if the mouse is moving over the target but is NOT on the tooltip.  I am using an am5 `Tooltip` as the `tooltip` setting on the `series.columns` and `series.slices` templates. I am then setting `tooltipHTML` via the `adapters` on both templates as well.

Below in a screen recording of the issue:

https://user-images.githubusercontent.com/29580247/230422634-48daf295-197b-4bac-aae7-38056ad6d057.mov

And here is the codesandbox used: https://codesandbox.io/s/withered-https-g5mxik

**Comment by martynasma** [comment]
Fixed in [5.3.11](https://github.com/amcharts/amcharts5/releases/tag/5.3.11).

## [5.3.11] - 2023-04-07

### Changed
- Possibly a breaking change! All HTML content in tooltips now has interactivity disabled. If you have buttons/links or other interactive elements, you need to explicitly set `tooltip.label.set("interactive", true)`.

### Fixed
- HTML tooltips were flickering when moving pointer over them.
- Hierarchy drill-downs were broken in some cases (since 5.3.10).
- TAB-focusing of elements on the page might get stuck in a chart if tabbing started outside the document.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
