### ISSUE TITLE
Removing the yAxes (opposite: true), Removes two Axes configuration

### ISSUE THREAD

**Issue by mkdudeja** [amcharts/amcharts5#9]
Hi Team,

I had a requirement of dynamically adding and removing multiple series with their own independent axes (Y1 & Y2) and I have implemented the same. However, when I am removing the series, I am removing the bound yAxes as well. But that action tends to remove the two yAxes from the List.

Below is the codepen forked from the demos to replicate the behavior:
https://codepen.io/mkdudeja/pen/NWgyKgZ

Try clicking on `Delete Series 1`, you'll notice two axes will be removed, and so on. And, at some point, you'll have some series with no underlying yAxes, and then removing that series will throw `Index out of bound error.`

Worth mentioning that the remove axes feature works fine if all the axes are on the left(default) side. The issue only comes when it's of mixed type (some on left, some on right), or all axes are on right.

Looking forward to your response on this.

Thanks,
Manish Kumar

**Comment by martynasma** [comment]
Fixed in [5.0.0-beta.18](https://github.com/amcharts/amcharts5/releases/tag/5.0.0-beta.18).

## [5.0.0-beta.18] - 2021-09-17

### Added
- `areLinked()` method added to `LinkedHierarchy`.
- `unlinkDataItems()` method added to `LinkedHierarchy`.
- Global function `am5.disposeAllRootElements()` added. Disposes all charts.
- `am5.registry.rootElements` added which holds an array with instances of all active `Root` elements.
- `seriesGraphics` property added to `PictorialStackedSeries`. It's a `Graphics` which shows `svgPath` shape under all slices. Useful when `startLocation`/`endLocation` is used to make slices not occupy whole shape area.

### Changed
- `maxPanOut` of `MapChart` is temporarily disabled until we figure out proper behavior for it.

### Fixed
- Linking nodes with `linkDataItems` of `LinkedHierarchy` was not working if called after the data was set.
- `Micro` theme was not removing padding from charts.
- Adding in `@types/geojson` as a dependency.
- Map could jump to unpredictable position after the chart's container size changed and user zoomed or panned the map.
- In some cases `Label` with `oversizedBehavior = "fit"` could be incorrectly positioned.
- Removing series and axes from a serial chart was not working properly.

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by mkdudeja** [comment]
@martynasma Thanks for the quick fixes.

However, I don't think the issue is fixed.

Codepen still has the issue. It still deletes the two yAxis series, but now two consecutive series are getting deleted.
(I have hard refreshed the page and ensured the new version is there.)

https://codepen.io/mkdudeja/pen/NWgyKgZ

Thanks,
Manish Kumar

**Comment by zeroin** [comment]
Indeed, our mistake. we were removing axis by index, not by value from the axis parent. This will be fixed in next release, thanks for the heads up.

**Comment by martynasma** [comment]
Fixed in [5.0.0-beta.19](https://github.com/amcharts/amcharts5/releases/tag/5.0.0-beta.19).

## [5.0.0-beta.19] - 2021-09-18

### Fixed
- Eemoving an axis from `xAxes` or `yAxes` was not working properly in some cases.
- If a `templateField` was set on some child of a bullet's `sprite`, it was being ignored.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download-v5/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
