### ISSUE TITLE
Inline formatNumber doesn't support negative format with parentheses

### ISSUE THREAD

**Issue by Mozzarella123** [amcharts/amcharts5#906]
**Bug description**
Inline formatting with `formatNumber` function doesn't work.

From docs: 
[positive format] | [negative format] | [zero format]
`#,###\|(#,###s)\|'-'`

if we pass this string to inline formatting
`formatNumber('#,###|(#,###s)|"-"'` 
it won't work.

**Environment**

 - "@amcharts/amcharts5": "^5.2.23",
 - Chrome Version 112.0.5615.137
 - React TypeScript

**Additional context**

The main problem is located in [PopulateString](https://github.com/amcharts/amcharts5/blob/a44c61501f705da6f4d7a94d08e6b75794ce2c08/src/.internal/core/util/PopulateString.ts#L48) file
Regex is broken when there is more than one parenthesis in format string
<img width="738" alt="image" src="https://user-images.githubusercontent.com/22841455/236138248-599fe861-2f79-459c-be75-d3de8b7366bb.png">

**Comment by martynasma** [comment]
Fixed in [5.3.12](https://github.com/amcharts/amcharts5/releases/tag/5.3.12).

## [5.3.12] - 2023-05-05

### Added
- New locale: Faroese (fo_FO). Thanks Martin Puge.

### Changed
- The `min` and `max` settings are now optional for `IHeatRule` ([Issue 883](https://github.com/amcharts/amcharts5/issues/883)).
- Removed `xlsx` package (with vulnerability) from dependencies in favor of a bundled hard copy (version 0.19.3) due to their decision not to publish to NPM. ([Issue 897](https://github.com/amcharts/amcharts5/issues/897)).

### Fixed
- Events now work properly with open shadow DOM (but not closed shadow DOM).
- Fixed export of data freezing in some cases where there are visual elements on the chart that are constantly being updated.
- Using parentheses in the in-line number formatting function was not working as needed.
- Tapping on a touch display outside chart was applying default state to elements that weren't being "touch-hovered".
- `getDataItemById()` method was not working properly on `Hierarchy` series.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
