### ISSUE TITLE
External Legend Item not updating directly

### ISSUE THREAD

**Issue by aniznik1** [amcharts/amcharts5#91]
When showing/hiding series by clicking on a legend item, the item will not update its state to `active` until the mouse leaves the legend container.

Reproduce: https://jsfiddle.net/t03y5Ldm/5/
1. Click on the "Series" legend item twice and don't move mouse outside the legend container
2. Series will be visible, yet legend item's status will be `inactive`
3. Move mouse outside of container - legend item status will change to`active`

**Comment by martynasma** [comment]
Fixed in [5.0.11](https://github.com/amcharts/amcharts5/releases/tag/5.0.11).

## [5.0.11] - 2021-11-23

### Added
- New `fps` property on `Root` which defines the maximum FPS that it will run at. Set it 30 or lower if performance is an issue.
- `"range"` theme tag is now added to all axis range elements (axisFill, grid, tick and label) so you could target specific theme rules.
- `"range"` and `"series"` theme tag is now added to all series axis range elements (axisFill, grid, tick and label) so you could target specific theme rules. 

### Changed
- A `axisFill` of an axis range will not be shown unless its `visible: true` setting is set.

### Fixed
- Adapter for `text` of a `Label` was not kicking in when data item of its `Tooltip` (or other parent of a Label) was changed.
- Legend marker/label was not returning to a default state when clicked on a disabled item in some cases when Animated theme was not used.
- Axis range fill tooltip was being shown in a wrong position.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
