### ISSUE TITLE
In Drawing Tools How to Change Fibonacci Value to Percentage 

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#911]
See the values outside () .

![image](https://user-images.githubusercontent.com/32473209/236826225-7e92a414-2ec7-4029-bbea-35603b458929.png)

To Like Below:

![image](https://user-images.githubusercontent.com/32473209/236826927-8a0444aa-0a54-4d20-823f-93017296cab1.png)

**Comment by martynasma** [comment]
Our implementation of Fibonacci is implemented according to industry-standard logic. There's no option to use some other calculations, I'm afraid.

**Comment by mukeshbadgujar** [comment]
can i change the values or can i get or set the values? and how?

**Comment by martynasma** [comment]
No, I'm afraid. The values are calculated from the map series of the StockChart.

**Comment by mukeshbadgujar** [comment]
stockChart.indicators.values[0].series.dataItems[0].dataContext

**Comment by martynasma** [comment]
@mukeshbadgujar I'm not entirely sure I follow. If you do have a support subscription, can you contact us at contact@amcharts.com directly to work this out?

**Comment by nanimesh** [comment]
Still facing this issue. I want specific percentages to show up for example: 61.8% instead of 0.62. @martynasma 
@mukeshbadgujar How did you go about it, were you able to solve this issue of yours? @zeroin 


![image](https://github.com/amcharts/amcharts5/assets/122960174/721d2ac7-011b-401a-9179-d70063b5cdf9)
