### ISSUE TITLE
what is the best format for datetime  

### ISSUE THREAD

**Issue by rareaqil** [amcharts/amcharts5#916]
![image](https://github.com/amcharts/amcharts5/assets/64183077/ddf89e56-26af-4011-86ea-32ffa96f8eb7)

**Comment by rareaqil** [comment]
![image](https://github.com/amcharts/amcharts5/assets/64183077/35328f85-8505-44d8-80d1-e4c21261c0c6)
trying this data and i got this 
![image](https://github.com/amcharts/amcharts5/assets/64183077/0a87b4d0-c7c6-4ba7-979d-11b632004cf7)
and i use hour time unit
![image](https://github.com/amcharts/amcharts5/assets/64183077/ac7607ff-e3a7-4b50-bbee-2bb8247cec34)

**Comment by martynasma** [comment]
If you must use string-based date/time in your data, you will need to use data parser to parse those into timestmaps:
https://www.amcharts.com/docs/v5/concepts/data/#Parsing_dates

But, if you can modify your data source to provide timestamps right from the start, it would be best, since you'd be eliminating a pre-processing overhead.

**Comment by rareaqil** [comment]
i will modify data source first, but what string timestamps format that i can use? cause in last code i use "yyyy/MM/dd hh:mm" its didnt work any suggestion ?

**Comment by martynasma** [comment]
Timestamps are numbers. You don't need to use any format.
