### ISSUE TITLE
Is amCharts and its Axis module still ES module only?

### ISSUE THREAD

**Issue by rowild** [amcharts/amcharts5#919]
**Bug description**

When importing Axis as described in the documentation and in the tutorials with `import * as am5xy from "@amcharts/amcharts5/xy"` errors are thrown saying that a ES modules has to be imported differently:

```sh
[08:48:54] (node:18) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use node --trace-warnings ... to show where the warning was created)
[nuxt] [request error] [unhandled] [500] Cannot use import statement outside a module 
```

Here is a mega simple reproducable code (see app.vue and console):
https://stackblitz.com/edit/nuxt-starter-2z9xbs?file=app.vue

As soon as I add `{ "type": "module", ...}` to package.json, I get
`equestAnimationFrame is not defined`

**Environment (if applicable)**

Node 18.15
npm 9.6.5
nuxt 3.4.3

**Comment by Pauan** [comment]
@rowild We have a [tutorial for Nuxt](https://www.amcharts.com/docs/v5/getting-started/integrations/nuxt/). Because Nuxt has SSR, you must put your amCharts code [inside of `<ClientOnly>`](https://nuxt.com/docs/api/components/client-only):

https://stackblitz.com/edit/nuxt-starter-uoi1wh?file=components%2FChart.vue,app.vue
