### ISSUE TITLE
Unable to execute Jest esm tests with amcharts5 lib

### ISSUE THREAD

**Issue by tidou44** [amcharts/amcharts5#920]
I'm trying to migrate the execution of Jest unit tests in ESM isolated mode in my angular 15 project. 

Execution goes well (and much faster than in normal mode), but using the @amcharts/amcharts5 graph library execution fails.
The execution in non ESM mode is OK.

**Question**

The error :

```
FAIL  src/app/app.component.router.spec.ts
  ● Test suite failed to run

    Must use import to load ES Module: /vif/tmp/jest-preset-angular-main/examples/example-app-v15/node_modules/d3-shape/src/index.js

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:841:21)
```

I tried to add transformIgnorePattern in jest config file but it's the same.

` transformIgnorePatterns: [`/node_modules/(?!d3-|@amcharts|tslib)`]`

It's possible to reproduce in https://github.com/tidou44/jest-preset-angular /examples/example-app-v15 I just add @amcharts/amcharts5 dependency and use it in app.component.ts

when i run npm run test-esm-isolated , i have the error

Does anyone knows what is wrong ?

Thank you in advance

**Comment by martynasma** [comment]
Before we look into this deeper, did you follow our official Jest guide?

https://www.amcharts.com/docs/v5/getting-started/integrations/jest/

**Comment by tidou44** [comment]
I use [jest-angular-preset](https://github.com/thymikee/jest-preset-angular) and it's ok in non ESM mode.
The problem is when using [ESM mode](https://thymikee.github.io/jest-preset-angular/docs/guides/esm-support)

**Comment by Pauan** [comment]
@tidou44 Jest ESM support is still experimental, it's not ready for production use yet, so we can't officially support it:

https://jestjs.io/docs/ecmascript-modules

I tried creating an Angular app by following [our documentation](https://www.amcharts.com/docs/v5/getting-started/integrations/angular/), and then I added `jest-preset-angular` by following [their directions](https://thymikee.github.io/jest-preset-angular/docs/getting-started/installation). I also followed [our documentation for configuring Jest](https://www.amcharts.com/docs/v5/getting-started/integrations/jest/).

I had to make a minor change to the `transformIgnorePatterns` inside of `jest.config.js`:

```js
module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  globalSetup: 'jest-preset-angular/global-setup',
  transformIgnorePatterns: [
    "/node_modules/(?!.*\\.mjs$|@amcharts|d3-)"
  ],
};
```

Lastly I created this `chart.component.spec.ts` file:

```ts
import { ComponentFixture, TestBed } from '@angular/core/testing';

import { ChartComponent } from './chart.component';

describe('ChartComponent', () => {
  let component: ChartComponent;
  let fixture: ComponentFixture<ChartComponent>;

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [ChartComponent]
    });
    fixture = TestBed.createComponent(ChartComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should have chart', async () => {
    await fixture.whenRenderingDone();
    const compiled = fixture.nativeElement as HTMLElement;
    const child = compiled.querySelector('#chartdiv')?.children[0] as HTMLElement;
    expect(child.style["position"]).toContain('relative');
  });
});
```

With all of that setup, I was able to get it working.

I then had to make some changes to enable ESM mode:

* I renamed `jest-config.js` to `jest-config.mjs` and changed it:
   ```js
   export default {
     preset: 'jest-preset-angular/presets/defaults-esm',
     setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
     globalSetup: 'jest-preset-angular/global-setup.mjs',
     transformIgnorePatterns: [
       "/node_modules/(?!rxjs|tslib|@amcharts|d3-)"
     ],
   };
   ```
* I had to change the `package.json`:
   ```json
   "scripts": {
     "test": "node --experimental-vm-modules --no-warnings node_modules/jest/bin/jest.js -c=jest-config.mjs --no-cache"
   },
   ```
* I had to change the `setup-jest.ts` file:
   ```ts
   import 'jest-preset-angular/setup-jest.mjs';
   ```
* I had to change the `tsconfig.spec.json` file:
   ```json
   {
     "extends": "./tsconfig.json",
     "compilerOptions": {
       "esModuleInterop": true,
       "module": "ES2020"
     },
     "include": [
       "src/**/*.spec.ts",
       "src/**/*.d.ts"
     ]
   }
   ```

However, after making those changes the tests now hang forever. That seems to be a bug with Jest, which makes sense since ESM support is still experimental.
