### ISSUE TITLE
Location-Sensitive Map disappearing and reappearing

### ISSUE THREAD

**Issue by xSinTx** [amcharts/amcharts5#940]
**Bug description**

Today i have encountered a bug in which location-sensitive map's disappearing. In my application after trying 4-5 times to go to another page and back to the Location-Sensitive Map page..the map surprisingly reappears. This bug may be specific to a country (I used Hungary in my application). When I go to https://www.amcharts.com/demos/location-sensitive-map/ site no map is shown so maybe you can take a look at that. I haven't changed anything in my application and it worked fine until today.

**Environment**

 - amCharts version: 5
 - Browser and its version: edge with version 113.0.1774.57

**Additional context**

When i go to https://www.amcharts.com/demos/location-sensitive-map/ site this is what i see:
![image](https://github.com/amcharts/amcharts5/assets/86297448/b4943578-a420-4439-b312-6485a3e3492d)

In my application this is what i see (as i said there was a map before)
![image](https://github.com/amcharts/amcharts5/assets/86297448/4005af1f-de67-4476-bfc6-182f3176fed7)

When I force by going back to home page and to the map page (at least 5 times) I see the map
![image](https://github.com/amcharts/amcharts5/assets/86297448/167cd9cb-4cee-43f4-88ef-aed1e4e01415)

Thanks in advance!

**Comment by xorspark** [comment]
The page loads correctly for me. There may have been some sort of timeout with the API we're using behind the scenes. Traditionally we've recommended using your own GeoIP service for this particular demo on prior versions instead of just copying the code verbatim, though that notice isn't present in this iteration. If you're not already doing so, you may want to leverage a GeoIP API provider that works best for you and integrate your map implementation with that instead.
