### ISSUE TITLE
Amcharts5 selection issue in scatter.

### ISSUE THREAD

**Issue by tech-dev-vin** [amcharts/amcharts5#941]
**Question**

While selecting items within scatter graph, it marks few items as selected while selection moves over all items.
I found, If my selection leave graph canvas, items are not marked as selected if selection drag ends outside canvas. But selection area shown as selected for drag selection.
Is this the normal behavior or an issue? 
If it's an issue how we can fix.

https://github.com/amcharts/amcharts5/assets/92369879/2d0b0944-2480-4e7f-b577-862ee3449693

**Comment by martynasma** [comment]
This looks like custom behavior. Do you have a working example?

**Comment by tech-dev-vin** [comment]
Please check the working example here https://codepen.io/vineetechosquare/pen/bGmXpzv

**Comment by tech-dev-vin** [comment]
I did the same but still the selection doesn't select markers if my drag leaves or overlap x axis.

**Comment by martynasma** [comment]
Gotcha.

OK, so it seems that private settings `positionX` and `positionY` stop being updated when cursor moves outside of the plot area, hence selection inconsistencies.

We'll fix it in the next version, due to be released next week.

I'll ping you here when it happens.

**Comment by tech-dev-vin** [comment]
Thanks

**Comment by martynasma** [comment]
Fixed in [5.3.16](https://github.com/amcharts/amcharts5/releases/tag/5.3.16).

## [5.3.16] - 2023-06-13

### Fixed
- Legend label's were losing their disabled state if labels were updated by moving cursor.
- `XYCursor` will no longre freeze when selecting and pointer moves out of plot area.
- `Treemap`'s focus navigation using arrow keys and `focusableGroup` was not working properly.
- `Annotator` plugin was sometimes retaining drawings after drawing was cancelled.


[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
