### ISSUE TITLE
Legend element not always becomming gray when using series.hide() with dynamic legend text

### ISSUE THREAD

**Issue by SirBouBou** [amcharts/amcharts5#947]
Hello, I'm opening a new issue since the last one was closed and I don't know if I can reopen it.

We have found a bug which prevent legend items from being grayed out when using series.hide() if dynamic legend text is activated for this item and the mouse has hovered the chart.

By using this codepen : https://codepen.io/SirBouBou/pen/KKGMvPE you can see that if you do nothing for 3 seconds, 6 legend buttons are desactivated (Normal behavior) but if you put the mouse over the chart during this time to display the cursor, only 3 of the 6 legend are disabled (The one not using dynamic legend label).

If you disable the cursor (which is needed to show dynamically data in the legend), the issue disappear.

**Comment by martynasma** [comment]
Fixed in [5.3.16](https://github.com/amcharts/amcharts5/releases/tag/5.3.16).

## [5.3.16] - 2023-06-13

### Fixed
- Legend label's were losing their disabled state if labels were updated by moving cursor.
- `XYCursor` will no longre freeze when selecting and pointer moves out of plot area.
- `Treemap`'s focus navigation using arrow keys and `focusableGroup` was not working properly.
- `Annotator` plugin was sometimes retaining drawings after drawing was cancelled.


[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
