### ISSUE TITLE
Bug Annotator, discarded changes appears after deleting something

### ISSUE THREAD

**Issue by SirBouBou** [amcharts/amcharts5#954]
Hello there seems to be a bug on the Annotator tool, directly reproductible in the documentation page (https://www.amcharts.com/docs/v5/concepts/exporting/annotator/#Example).
The step to reproduce on the first exemple (line chart):

- Open the annotation system, draw anything, then presse the cross to discard the changes
- Open it back, draw anything then delete it with the bin and press the check button to validate
- The first drawing that should have been discarded reappear.

**Comment by martynasma** [comment]
Fixed in [5.3.16](https://github.com/amcharts/amcharts5/releases/tag/5.3.16).

## [5.3.16] - 2023-06-13

### Fixed
- Legend label's were losing their disabled state if labels were updated by moving cursor.
- `XYCursor` will no longre freeze when selecting and pointer moves out of plot area.
- `Treemap`'s focus navigation using arrow keys and `focusableGroup` was not working properly.
- `Annotator` plugin was sometimes retaining drawings after drawing was cancelled.


[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
