### ISSUE TITLE
Issue with series.setAll after first load

### ISSUE THREAD

**Issue by robheymann** [amcharts/amcharts5#97]
Hi,

After having upgrated to amcharts 5.0.12, the following error is thrown when trying to update the series data on subsequent calls to series.setAll()

Chart:

` const root = am5.Root.new('skillschart')

          root.setThemes([am5themes_Animated.new(root)])

          // Create wrapper container
          const container = root.container.children.push(
            am5.Container.new(root, {
              width: am5.percent(100),
              height: am5.percent(100),
              layout: root.verticalLayout,
            }),
          )

const series = container.children.push(
            am5hierarchy.ForceDirected.new(root, {
              singleBranchOnly: false,
              // downDepth: 2,
              topDepth: 1,
              // initialDepth: 1,
              maxRadius: 100,
              minRadius: 30,
              valueField: 'skillLevel',
              categoryField: 'name',
              childDataField: 'children',
              idField: 'name',
              linkWithField: 'linkWith',
              // tooltip: am5.Tooltip.new(root, {}),
              // tooltipText: 'asdadsdasdasd',
              manyBodyStrength: -12,
              centerStrength: 0.8,
            }),
          )

...

series.data.setAll([{ value: 0, children: [...this.chartData] }])
series.set('selectedDataItem', series.dataItems[0])
series.appear(1500, 500)
`

The chart loads and displays correctly, but when trying to re set the series data, I call: 
`
this.series.data.setAll([{ value: 0, children: [...this.chartData] }])
`

Output error:

Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at ForceDirected.ts:329
    at initialize (collide.js:78)
    at Function.force.initialize (collide.js:84)
    at initializeForce (simulation.js:80)
    at Map.forEach (<anonymous>)
    at Object.nodes (simulation.js:98)
    at ForceDirected2.value (ForceDirected.ts:247)
    at Component.ts:213
    at Proxy.<anonymous> (EventDispatcher.ts:382)
    at EventDispatcher.ts:304

Uncaught TypeError: Cannot read properties of undefined (reading 'set')
    at ForceDirected2.value (Hierarchy.ts:467)
    at ForceDirected2.value (ForceDirected.ts:275)
    at ForceDirected2.value (Hierarchy.ts:292)
    at ForceDirected2.value (ForceDirected.ts:207)
    at Root.ts:686
    at Array.forEach (<anonymous>)
    at Root2.value (Root.ts:679)
    at Root2.value (Root.ts:776)
    at _ticker (Root.ts:806)

Any help would be much appreciated.
Thanks,
Rob

**Comment by martynasma** [comment]
Fixed in [5.0.13](https://github.com/amcharts/amcharts5/releases/tag/5.0.13).


## [5.0.13] - 2021-11-25

### Added
- `clickTarget` (possible vales: `"itemContainer"` (default), `"marker"`, and `"none"`) added to `Legend`. Use `clickTarget: "none"` to disable toggling of legend items.

### Changed
- Setting `wheelX`/`wheelY` on `XYChart` or `MapChart` no longer marks their plot areas as `wheelable`.

### Fixed
- In some cases using `oversizedBehavior = "wrap"` on labels in super small spaces the chart would hang.
- Updating data on a `ForcedDirectedTree` may cause JS errors.
- Hovering legend item of a hidden slice no longer tries to show the tooltip for it.
- Drill-down maps were displaying country in a wrong position after drill-down.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
